"""Independent reference calculator -- stdlib only, no msa_backend imports.

This module re-derives the expected weighted column statistics for the
fixtures from first principles (plain Python loops + ``math.log2``). The
unit tests compare the core implementation against BOTH this independent
calculator and the static hand-written ``expected_*.json`` files, so the
reference answers are not generated by the code under test.

Spec implemented here (mirrors config/settings.yaml):
  * identity over positions where both rows are non-gap; cluster when
    identity >= 0.95; each cluster carries total weight 1 split equally;
  * gaps excluded from distributions; columns normalised by their own
    non-gap weight;
  * ambiguous symbols split their weight uniformly over concrete bases;
  * H = -sum p log2 p; IC = 2 - H; conserved iff top freq >= 0.6 and
    coverage >= 2.0; below the floor -> "insufficient_coverage".
"""

from __future__ import annotations

import math

IUPAC = {
    "A": ("A",), "C": ("C",), "G": ("G",), "T": ("T",),
    "R": ("A", "G"), "Y": ("C", "T"), "S": ("G", "C"), "W": ("A", "T"),
    "K": ("G", "T"), "M": ("A", "C"),
    "B": ("C", "G", "T"), "D": ("A", "G", "T"), "H": ("A", "C", "T"),
    "V": ("A", "C", "G"), "N": ("A", "C", "G", "T"),
}
ALPHABET = ("A", "C", "G", "T")
IDENTITY_THRESHOLD = 0.95
CONSERVATION_THRESHOLD = 0.6
MIN_COVERAGE = 2.0


def read_fasta(path: str) -> tuple[list[str], list[str]]:
    ids: list[str] = []
    rows: list[str] = []
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if not line:
            continue
        if line.startswith(">"):
            ids.append(line[1:].split()[0])
            rows.append("")
        else:
            rows[-1] += line.upper()
    return ids, rows


def _identity(a: str, b: str) -> float:
    compared = [(x, y) for x, y in zip(a, b) if x != "-" and y != "-"]
    if not compared:
        return 1.0
    return sum(1 for x, y in compared if x == y) / len(compared)


def _weights(rows: list[str]) -> list[float]:
    n = len(rows)
    parent = list(range(n))

    def find(x: int) -> int:
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    for i in range(n):
        for j in range(i + 1, n):
            if _identity(rows[i], rows[j]) >= IDENTITY_THRESHOLD:
                pi, pj = find(i), find(j)
                if pi != pj:
                    parent[pi] = pj

    groups: dict[int, list[int]] = {}
    for i in range(n):
        groups.setdefault(find(i), []).append(i)
    weights = [0.0] * n
    for members in groups.values():
        for m in members:
            weights[m] = 1.0 / len(members)
    return weights


def expected_columns(path: str) -> list[dict]:
    """Independent recomputation of every column's expected statistics."""
    _ids, rows = read_fasta(path)
    weights = _weights(rows)
    total_weight = sum(weights)
    results = []
    for col in range(len(rows[0])):
        counts = dict.fromkeys(ALPHABET, 0.0)
        non_gap = 0.0
        gap = 0.0
        for row, w in zip(rows, weights):
            ch = row[col]
            if ch == "-":
                gap += w
                continue
            non_gap += w
            for base in IUPAC[ch]:
                counts[base] += w / len(IUPAC[ch])
        if non_gap > 0:
            dist = {b: counts[b] / non_gap for b in ALPHABET}
        else:
            dist = dict.fromkeys(ALPHABET, 0.0)
        entropy = -sum(p * math.log2(p) for p in dist.values() if p > 0)
        top_base = max(ALPHABET, key=lambda b: dist[b])
        if non_gap < MIN_COVERAGE:
            consensus, status = "?", "insufficient_coverage"
        elif dist[top_base] >= CONSERVATION_THRESHOLD:
            consensus, status = top_base, "conserved"
        else:
            consensus, status = top_base.lower(), "variable"
        results.append(
            {
                "column_index": col + 1,
                "distribution": dist,
                "entropy_bits": entropy,
                "information_content_bits": 2.0 - entropy,
                "effective_coverage": non_gap,
                "gap_fraction": gap / total_weight,
                "consensus": consensus,
                "status": status,
            }
        )
    return results


def expected_weights(path: str) -> dict[str, float]:
    ids, rows = read_fasta(path)
    return dict(zip(ids, _weights(rows)))
