"""Orchestration: graph construction, planning, execution, verification.

The service wires the core pipeline to the independent reference oracle and
the structured run log.  Verification answers are never generated by the
code under test: they come from :mod:`app.reference`.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

import numpy as np

from ..api.schemas import (
    CreateSessionRequest,
    CustomGraphSchema,
    PlanRequest,
    RunRequest,
)
from ..core import ops as ops_mod
from ..core.errors import (
    ActivationRecomputeError,
    StateConflictError,
)
from ..core.executor import execute
from ..core.graph import Node, build_graph
from ..core.numeric import fingerprint, max_abs_diff
from ..core.planner import plan_checkpoints
from ..core.state import ParameterInit, TrainingState
from ..core.tensor import coerce_array
from ..fixtures.specs import ALL_SPECS
from ..fixtures.graphs import get_fixture
from ..reference.finite_diff import finite_difference_param_grads
from ..reference.liveness import LivenessSim
from ..reference.oracle import OracleGraph
from ..reference.seedspec import reference_masks
from .runlog import RunLogger, new_run_id
from .sessions import Session, SessionStore

GRAD_TOL = 1e-8
FD_TOL = 1e-5


class Orchestrator:
    def __init__(self, store: Optional[SessionStore] = None,
                 logger: Optional[RunLogger] = None) -> None:
        self.store = store or SessionStore()
        self.logger = logger or RunLogger()

    # ---------------------------------------------------------------- sessions

    def create_session(self, req: CreateSessionRequest) -> Session:
        if (req.fixture is None) == (req.graph is None):
            from ..core.errors import InvalidInputError

            raise InvalidInputError(
                "provide exactly one of 'fixture' or 'graph'",
                code="E_INPUT_XOR",
                context={"fixture": req.fixture, "has_graph": req.graph is not None},
            )
        if req.fixture is not None:
            fx = get_fixture(req.fixture)
            graph = fx.graph()
            training = fx.training_state()
            inputs = dict(fx.inputs)
            spec = ALL_SPECS[req.fixture]
            session = Session(
                session_id="sess-" + new_run_id("").split("-", 1)[1],
                graph=graph, training=training, inputs=inputs, spec=spec,
                fixture_name=req.fixture, master_seed=req.master_seed,
            )
        else:
            session = self._session_from_custom(req.graph, req.master_seed)
        self.store.create(session)
        self.logger.record({
            "event": "session_created",
            "session_id": session.session_id,
            "fixture": session.fixture_name,
            "target": session.graph.target,
            "nodes": list(session.graph.order),
            "master_seed": session.master_seed,
        })
        return session

    def _session_from_custom(self, schema: CustomGraphSchema,
                             master_seed: int) -> Session:
        nodes = [
            Node(id=n.id, op=n.op, inputs=tuple(n.inputs), params=dict(n.params))
            for n in schema.nodes
        ]
        graph = build_graph(nodes, [schema.target])
        inits = {
            pid: ParameterInit(shape=tuple(meta.shape), seed=meta.seed)
            for pid, meta in schema.parameters.items()
        }
        param_ids = {
            nid for nid, n in graph.nodes.items()
            if n.op == ops_mod.PARAMETER
        }
        if set(inits) != param_ids:
            from ..core.errors import InvalidInputError

            raise InvalidInputError(
                "'parameters' must list exactly the parameter nodes",
                code="E_INPUT_PARAM_SET",
                context={"expected": sorted(param_ids),
                         "provided": sorted(inits)},
            )
        input_ids = {
            nid for nid, n in graph.nodes.items() if n.op == ops_mod.INPUT
        }
        if set(schema.inputs) != input_ids:
            from ..core.errors import InvalidInputError

            raise InvalidInputError(
                "'inputs' must provide exactly the input nodes",
                code="E_INPUT_INPUT_SET",
                context={"expected": sorted(input_ids),
                         "provided": sorted(schema.inputs)},
            )
        inputs = {
            nid: coerce_array(value, name=nid)
            for nid, value in schema.inputs.items()
        }
        training = TrainingState(inits)
        spec = {
            "name": "custom",
            "target": schema.target,
            "inputs": {k: v.tolist() for k, v in inputs.items()},
            "parameters": {
                pid: {"shape": list(init.shape), "seed": init.seed}
                for pid, init in inits.items()
            },
            "nodes": [
                {"id": n.id, "op": n.op, "inputs": list(n.inputs),
                 "params": n.params}
                for n in schema.nodes
            ],
        }
        return Session(
            session_id="sess-" + new_run_id("").split("-", 1)[1],
            graph=graph, training=training, inputs=inputs, spec=spec,
            fixture_name=None, master_seed=master_seed,
        )

    # ---------------------------------------------------------------- planning

    def plan(self, session: Session, req: PlanRequest) -> Dict[str, Any]:
        run_id = new_run_id("plan")
        try:
            plan = plan_checkpoints(
                session.graph, req.memory_budget,
                rng_strategy=req.rng_strategy, force_search=req.force_search,
            )
        except ActivationRecomputeError as exc:
            exc.run_id = run_id
            self._log_failure(session, run_id, "planning", exc)
            raise
        session.plan = plan
        session.plan_run_id = run_id
        session.rng_strategy = req.rng_strategy
        independent = self._independent_memory_check(session, req.rng_strategy)
        summary = plan.summary()
        self.logger.record({
            "event": "planned",
            "session_id": session.session_id,
            "run_id": run_id,
            "memory_budget": req.memory_budget,
            "intermediate": {
                "retained": summary["retained"],
                "simulated_peak": summary["peak_memory"],
                "independent_peak": independent["peak_memory"],
                "recompute_flops": summary["recompute_flops"],
                "independent_recompute_flops": independent["recompute_flops"],
            },
            "judgement": "feasible" if (
                self._budget_ok(req.memory_budget, summary["peak_memory"])
            ) else "feasible-unconstrained",
            "search": plan.search,
            "candidates_evaluated": plan.candidates_evaluated,
        })
        return {
            "run_id": run_id,
            "plan": summary,
            "independent_check": independent,
        }

    @staticmethod
    def _budget_ok(budget: Optional[int], peak: int) -> bool:
        return budget is None or peak <= budget

    def _independent_memory_check(self, session: Session,
                                  rng_strategy: str) -> Dict[str, Any]:
        sim = LivenessSim(session.spec)
        retained = [n for n in session.plan.retained if n != session.graph.target]
        result = sim.simulate(retained, rng_strategy=rng_strategy)
        core = session.plan.simulation
        return {
            "peak_memory": result["peak_memory"],
            "recompute_flops": result["recompute_flops"],
            "forward_flops": result["forward_flops"],
            "backward_flops": result["backward_flops"],
            "recomputed_nodes": list(result["recomputed_nodes"]),
            "matches_core": (
                result["peak_memory"] == core.peak_memory
                and result["recompute_flops"] == core.recompute_flops
                and result["forward_flops"] == core.forward_flops
                and result["backward_flops"] == core.backward_flops
            ),
        }

    # ---------------------------------------------------------------- running

    def run(self, session: Session, req: RunRequest) -> Dict[str, Any]:
        if session.plan is None:
            raise StateConflictError(
                "session has no plan; call /plan first",
                code="E_STATE_NO_PLAN",
                context={"session_id": session.session_id},
            )
        run_id = new_run_id("run")
        try:
            run_state, replay_log = execute(
                session.graph, session.plan, session.training,
                session.inputs, run_id=run_id,
                master_seed=req.master_seed,
                rng_strategy=session.rng_strategy,
            )
            verification = self._verify(session, run_state, replay_log,
                                        req.master_seed, req.finite_difference,
                                        req.fd_eps)
        except ActivationRecomputeError as exc:
            exc.run_id = run_id
            self._log_failure(session, run_id, "execution", exc)
            raise
        session.runs.append(run_state)
        session.last_run_id = run_id
        self.logger.record({
            "event": "run_completed",
            "session_id": session.session_id,
            "run_id": run_id,
            "status": run_state.status.value,
            "intermediate": {
                "loss": run_state.loss,
                "peak_memory": run_state.peak_memory,
                "simulated_peak": session.plan.simulation.peak_memory,
                "forward_flops": run_state.forward_flops,
                "recompute_flops": run_state.recompute_flops,
                "backward_flops": run_state.backward_flops,
                "recomputed_nodes": list(run_state.recomputed_nodes),
                "replay_waves": replay_log["replay_waves"],
                "emitted_side_effects": run_state.emitted_side_effects,
                "grad_fingerprints": {
                    pid: fingerprint(g) for pid, g in run_state.grads.items()
                },
            },
            "verification": {
                "passed": verification["passed"],
                "oracle_source": verification["oracle_source"],
                "grad_max_abs_diff": verification["grad_max_abs_diff"],
            },
            "judgement": (
                "gradients match independent oracle and replay invariants hold"
                if verification["passed"] else "VERIFICATION FAILED"
            ),
        })
        return {
            "run_id": run_id,
            "run": run_state,
            "replay_log": replay_log,
            "verification": verification,
        }

    def _verify(self, session: Session, run_state, replay_log,
                master_seed: int, use_fd: bool, fd_eps: float) -> Dict[str, Any]:
        masks = reference_masks(
            session.rng_strategy, master_seed, session.spec
        )
        params = {
            pid: session.training.get(pid)
            for pid in session.training.parameter_ids()
        }
        oracle = OracleGraph(session.spec)
        oracle_pg, oracle_ig, oracle_loss = oracle.backward(
            params, session.inputs, masks
        )
        grad_diffs = {
            pid: max_abs_diff(run_state.grads[pid], oracle_pg[pid])
            for pid in oracle_pg
        }
        loss_diff = abs(run_state.loss - oracle_loss)
        grad_ok = loss_diff <= GRAD_TOL and all(
            d <= GRAD_TOL for d in grad_diffs.values()
        )
        # input gradients from the replay log are JSON lists
        input_diffs = {
            iid: max_abs_diff(np.asarray(replay_log["input_grads"].get(iid)),
                              oracle_ig[iid])
            for iid in oracle_ig
        }
        input_ok = all(d <= GRAD_TOL for d in input_diffs.values())

        fd_diffs: Optional[Dict[str, float]] = None
        fd_ok = True
        if use_fd:
            fd_grads = finite_difference_param_grads(
                session.spec, params, session.inputs, masks, eps=fd_eps
            )
            fd_diffs = {
                pid: max_abs_diff(run_state.grads[pid], fd_grads[pid])
                for pid in fd_grads
            }
            fd_ok = all(d <= FD_TOL for d in fd_diffs.values())

        invariants_ok = (
            run_state.rng_replay_ok
            and run_state.emitted_side_effects == self._expected_emits(session)
            and run_state.peak_memory == session.plan.simulation.peak_memory
        )
        passed = grad_ok and input_ok and fd_ok and invariants_ok
        reasons: List[str] = []
        if not grad_ok:
            reasons.append("parameter gradients differ from independent oracle")
        if not input_ok:
            reasons.append("input gradients differ from independent oracle")
        if not fd_ok:
            reasons.append("finite-difference check outside tolerance")
        if not invariants_ok:
            reasons.append("replay/side-effect/memory invariant violated")
        return {
            "passed": passed,
            "oracle_source": "app.reference.oracle+seedspec",
            "loss_abs_diff": loss_diff,
            "grad_max_abs_diff": grad_diffs,
            "input_grad_max_abs_diff": input_diffs,
            "finite_difference_max_abs_diff": fd_diffs,
            "tolerances": {"grad": GRAD_TOL, "finite_difference": FD_TOL},
            "reasons": reasons or ["all checks within tolerance"],
        }

    @staticmethod
    def _expected_emits(session: Session) -> int:
        return sum(
            1 for n in session.graph.nodes.values()
            if ops_mod.SPECS[n.op].side_effect
        )

    # ---------------------------------------------------------------- apply

    def apply(self, session: Session, lr: float) -> Dict[str, Any]:
        if not session.runs:
            raise StateConflictError(
                "no completed run to apply",
                code="E_STATE_NO_RUN",
                context={"session_id": session.session_id},
            )
        run_state = session.runs[-1]
        before = session.training.step
        try:
            session.training.apply_run(run_state, lr=lr)
        except ActivationRecomputeError as exc:
            exc.run_id = run_state.run_id
            self._log_failure(session, run_state.run_id, "apply_step", exc)
            raise
        self.logger.record({
            "event": "step_applied",
            "session_id": session.session_id,
            "run_id": run_state.run_id,
            "step_before": before,
            "step_after": session.training.step,
            "lr": lr,
        })
        return {"run_id": run_state.run_id, "training_step": session.training.step}

    # ---------------------------------------------------------------- logging

    def _log_failure(self, session: Session, run_id: str, phase: str,
                     exc: ActivationRecomputeError) -> None:
        self.logger.record({
            "event": "run_failed",
            "session_id": session.session_id,
            "run_id": run_id,
            "phase": phase,
            "error_category": exc.category,
            "error_code": exc.code,
            "message": exc.message,
            "context": exc.context,
            "judgement": f"rejected as {exc.category}",
        })
