// Package oracle_test runs the compatibility suite: every synthetic
// fixture is decoded BOTH by the restricted codec under test and by the
// mature, independent library github.com/go-asn1-ber.  For valid inputs
// the decoded values (including arbitrary-width integers) must agree;
// for invalid inputs the code under test must report the documented
// error category and exact byte offset, and the oracle's own verdict is
// asserted as well — including the precise set of known divergences
// (BER permits things the restricted profile/DER forbids).
//
// The expected answers come from fixtures/vectors.json, which is
// generated by cmd/genfixtures from hand-derived vectors and library
// vectors — never from the code under test.
package oracle_test

import (
	"encoding/hex"
	"encoding/json"
	"math/big"
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"berconf/internal/ber"
	"berconf/internal/oracle"
)

type fixture struct {
	ID           string         `json:"id"`
	Description  string         `json:"description"`
	Source       string         `json:"source"`
	InputHex     string         `json:"input_hex"`
	ExpectOK     bool           `json:"expect_ok"`
	ExpectKind   string         `json:"expect_kind"`
	ExpectOffset int64          `json:"expect_offset"`
	ExpectMode   string         `json:"expect_mode"`
	Notes        []string       `json:"notes"`
	ExpectValue  *expectedValue `json:"expect_value"`
}

type expectedValue struct {
	Class       string          `json:"class"`
	Tag         uint32          `json:"tag"`
	Constructed bool            `json:"constructed"`
	IntegerDec  string          `json:"integer_decimal"`
	ValueHex    string          `json:"value_hex"`
	Children    []expectedValue `json:"children"`
}

func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, _ := runtime.Caller(0)
	dir := filepath.Dir(file) // .../test/oracle
	root, err := filepath.Abs(filepath.Join(dir, "..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	return root
}

func loadFixtures(t *testing.T) []fixture {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(repoRoot(t), "fixtures", "vectors.json"))
	if err != nil {
		t.Fatalf("fixtures missing; run `go run ./cmd/genfixtures`: %v", err)
	}
	var fx []fixture
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatal(err)
	}
	return fx
}

// oracleVerdict states what the independent mature library does with an
// input the code under test rejects.  These are independently observed
// facts about go-asn1-ber v1.5.8, not expectations produced by the SUT.
type oracleVerdict string

const (
	ovError       oracleVerdict = "oracle_errors" // library rejects too
	ovAcceptsEOC  oracleVerdict = "oracle_accepts_eoc"
	ovAcceptsRest oracleVerdict = "oracle_accepts_with_rest"
	ovAccepts     oracleVerdict = "oracle_accepts" // BER leniency / no content rules
)

// rejectedBySUT states the mature library's behaviour for each rejected
// fixture.  Divergences (BER-legal-but-restricted) are explicitly
// enumerated so they cannot silently appear or disappear.
var rejectedBySUT = map[string]oracleVerdict{
	// framing errors: oracle also rejects
	"primitive-indefinite":  ovError,
	"reserved-length":       ovError,
	"missing-eoc":           ovError,
	"truncated-content":     ovError,
	"truncated-tag":         ovError,
	"truncated-long-length": ovError,
	"bad-eoc-in-definite":   ovError,

	// EOC semantics the library treats leniently
	"toplevel-eoc": ovAcceptsEOC,
	"extra-eoc":    ovAcceptsRest, // first packet parsed; the extra 00 00 remains
	"lone-zero":    ovAccepts,     // (Go-only fixture, not in JSON; kept for completeness)

	// single-value boundary the library does not enforce
	"trailing-bytes": ovAcceptsRest,

	// content rules the restricted profile adds on top of structural BER
	"int-empty":                 ovAccepts, // empty INTEGER tolerated by library
	"bits-trailing-one":         ovAccepts, // unused bits not checked
	"bits-unused-8":             ovAccepts,
	"bits-empty-nonzero-unused": ovAccepts,
	"bits-missing-unused":       ovAccepts,

	// DER-only canonical constraints; library is a BER decoder
	"int-nonminimal-der":    ovAccepts,
	"der-nonminimal-length": ovAccepts,
	"der-indefinite":        ovAccepts,
}

func TestFixturesAgainstSUT(t *testing.T) {
	fx := loadFixtures(t)
	if len(fx) < 30 {
		t.Fatalf("only %d fixtures loaded", len(fx))
	}
	sources := map[string]bool{}
	for _, f := range fx {
		f := f
		t.Run(f.ID, func(t *testing.T) {
			sources[f.Source] = true
			raw, err := hex.DecodeString(f.InputHex)
			if err != nil {
				t.Fatalf("fixture hex: %v", err)
			}
			mode := f.ExpectMode
			if mode == "" {
				mode = "BER"
			}
			node, derr := ber.DecodeAndValidate(raw, mode, ber.DefaultLimits())
			if f.ExpectOK {
				if derr != nil {
					t.Fatalf("expected accept in %s, got %v", mode, derr)
				}
				if f.ExpectValue != nil {
					assertValueTree(t, *f.ExpectValue, node)
				}
				return
			}
			if derr == nil {
				t.Fatalf("expected %s at offset %d, got success", f.ExpectKind, f.ExpectOffset)
			}
			de := asDecodeErr(t, derr)
			if string(de.Kind) != f.ExpectKind {
				t.Fatalf("kind = %s, want %s (%s)", de.Kind, f.ExpectKind, de.Msg)
			}
			if de.Offset != f.ExpectOffset {
				t.Fatalf("offset = %d, want %d", de.Offset, f.ExpectOffset)
			}
		})
	}
	if !sources["hand"] || !sources["go-asn1-ber"] {
		t.Fatalf("fixtures must come from both independent sources, got %v", sources)
	}
}

func TestOracleAgreesOnValidInputs(t *testing.T) {
	fx := loadFixtures(t)
	agreed := 0
	for _, f := range fx {
		if !f.ExpectOK {
			continue
		}
		f := f
		t.Run("oracle/"+f.ID, func(t *testing.T) {
			raw, _ := hex.DecodeString(f.InputHex)
			res := oracle.Decode(raw)
			if !res.OK {
				t.Fatalf("mature library rejected an SUT-valid input: %v", res.ParseError)
			}
			if res.Rest != 0 {
				t.Fatalf("library left %d trailing bytes on a complete input", res.Rest)
			}
			sut, err := ber.Decode(raw, ber.DefaultLimits())
			if err != nil {
				t.Fatalf("SUT decode: %v", err)
			}
			assertTreesAgree(t, res.Node, sut)
			agreed++
		})
	}
}

func TestOracleVerdictsOnRejectedInputs(t *testing.T) {
	fx := loadFixtures(t)
	covered := map[string]bool{}
	for _, f := range fx {
		if f.ExpectOK {
			continue
		}
		want, known := rejectedBySUT[f.ID]
		if !known {
			t.Fatalf("fixture %q has no documented oracle verdict; add its observed behaviour", f.ID)
		}
		covered[f.ID] = true
		raw, _ := hex.DecodeString(f.InputHex)
		res := oracle.Decode(raw)
		switch want {
		case ovError:
			if res.OK {
				t.Fatalf("fixture %s: expected oracle to reject, but it accepted", f.ID)
			}
		case ovAcceptsEOC:
			if !res.OK || !res.IsEOC {
				t.Fatalf("fixture %s: expected oracle to parse a bare EOC, got ok=%v eoc=%v err=%v",
					f.ID, res.OK, res.IsEOC, res.ParseError)
			}
		case ovAcceptsRest:
			if !res.OK || res.Rest == 0 {
				t.Fatalf("fixture %s: expected oracle accept + trailing bytes, got ok=%v rest=%d",
					f.ID, res.OK, res.Rest)
			}
		case ovAccepts:
			if !res.OK {
				t.Fatalf("fixture %s: expected BER-lenient acceptance by oracle, got %v",
					f.ID, res.ParseError)
			}
		}
	}
	// every documented divergence must map to an actual fixture
	for id := range rejectedBySUT {
		if id == "lone-zero" {
			continue // generated only inside the Go unit tests
		}
		if !covered[id] {
			t.Fatalf("documented oracle verdict %q has no matching fixture", id)
		}
	}
}

// TestOversizedIntegerVsOracle uses a 301-byte INTEGER produced by the
// mature library and checks value identity through arbitrary precision;
// then tightens the width bound and asserts a SIZE_EXCEEDED rejection.
func TestOversizedIntegerVsOracle(t *testing.T) {
	huge := new(big.Int).Sub(new(big.Int).Lsh(big.NewInt(1), 2400), big.NewInt(7))
	wire := oracle.IntegerBytesRaw(twosComplement(huge))
	// 301 content octets (leading 0x00 + 300-octet magnitude) plus the
	// 4-octet header (02 82 01 2d, length 301).
	if len(wire) != 305 {
		t.Fatalf("oracle integer TLV = %d bytes, want 305", len(wire))
	}
	res := oracle.Decode(wire)
	if !res.OK {
		t.Fatalf("oracle rejected huge integer: %v", res.ParseError)
	}
	node, err := ber.DecodeAndValidate(wire, "BER", ber.DefaultLimits())
	if err != nil {
		t.Fatalf("SUT rejected huge integer under default limits: %v", err)
	}
	got, err := ber.BigIntegerValue(node)
	if err != nil {
		t.Fatal(err)
	}
	if got.Cmp(huge) != 0 {
		t.Fatalf("huge integer mismatch")
	}
	// Same bytes must be rejected by a deployment profile with a 256-byte
	// INTEGER width cap, at the header-end offset.
	tight := ber.DefaultLimits()
	tight.MaxIntegerBytes = 256
	_, err = ber.DecodeAndValidate(wire, "BER", tight)
	de := asDecodeErr(t, err)
	if de.Kind != ber.KindSizeExceeded {
		t.Fatalf("tight profile: kind = %s, want SIZE_EXCEEDED", de.Kind)
	}
}

// ---- value tree assertions ----

func assertValueTree(t *testing.T, want expectedValue, got *ber.Node) {
	t.Helper()
	wantClass := map[string]ber.Class{
		"universal": ber.ClassUniversal,
		"context":   ber.ClassContext,
	}[want.Class]
	if got.Class != wantClass || got.Tag != want.Tag || got.Constructed != want.Constructed {
		t.Fatalf("node = (%s,%d,constructed=%t), want (%s,%d,%t)",
			got.Class, got.Tag, got.Constructed, want.Class, want.Tag, want.Constructed)
	}
	if want.IntegerDec != "" {
		v, err := ber.BigIntegerValue(got)
		if err != nil {
			t.Fatalf("integer value: %v", err)
		}
		if v.String() != want.IntegerDec {
			t.Fatalf("integer = %s, want %s", v.String(), want.IntegerDec)
		}
	}
	if want.ValueHex != "" {
		wantBytes, _ := hex.DecodeString(want.ValueHex)
		if got.Constructed {
			t.Fatalf("unexpected expected value on constructed node")
		}
		// INTEGER expected value hex compares to raw content; BIT STRING too
		if !bytesEqual(got.Value, wantBytes) {
			t.Fatalf("value = %x, want %x", got.Value, wantBytes)
		}
	}
	if len(want.Children) != len(got.Children) {
		t.Fatalf("children = %d, want %d", len(got.Children), len(want.Children))
	}
	for i := range want.Children {
		assertValueTree(t, want.Children[i], got.Children[i])
	}
}

// assertTreesAgree compares the mature library's neutral tree with the
// SUT tree.  Context-primitive payloads are skipped: go-asn1-ber v1.5.8
// discards non-universal primitive content after consuming it.
func assertTreesAgree(t *testing.T, want *oracle.ORNode, got *ber.Node) {
	t.Helper()
	if want == nil {
		t.Fatal("oracle node nil")
	}
	if uint32(want.Class) != uint32(got.Class) || want.Tag != got.Tag || want.Constructed != got.Constructed {
		t.Fatalf("tree node = (%d,%d,c=%t), oracle = (%d,%d,c=%t)",
			got.Class, got.Tag, got.Constructed, want.Class, want.Tag, want.Constructed)
	}
	if want.Constructed {
		if len(want.Children) != len(got.Children) {
			t.Fatalf("children = %d, oracle = %d", len(got.Children), len(want.Children))
		}
		for i := range want.Children {
			assertTreesAgree(t, want.Children[i], got.Children[i])
		}
		return
	}
	if got.Class == ber.ClassContext {
		return // library discards context-primitive content (documented)
	}
	if !bytesEqual(want.Value, got.Value) {
		t.Fatalf("primitive value = %x, oracle = %x", got.Value, want.Value)
	}
}

func asDecodeErr(t *testing.T, err error) *ber.DecodeError {
	t.Helper()
	var de *ber.DecodeError
	if err == nil {
		t.Fatal("expected a decode error")
	}
	if !errorAs(err, &de) {
		t.Fatalf("not a *DecodeError: %T %v", err, err)
	}
	return de
}

func errorAs(err error, target **ber.DecodeError) bool {
	if de, ok := err.(*ber.DecodeError); ok {
		*target = de
		return true
	}
	return false
}

func bytesEqual(a, b []byte) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func twosComplement(v *big.Int) []byte {
	if v.Sign() == 0 {
		return []byte{0}
	}
	if v.Sign() > 0 {
		b := v.Bytes()
		if b[0]&0x80 != 0 {
			return append([]byte{0x00}, b...)
		}
		return b
	}
	mag := new(big.Int).Neg(v)
	w := 1
	half := new(big.Int).Lsh(big.NewInt(1), 7)
	for mag.Cmp(half) > 0 {
		w++
		half.Lsh(half, 8)
	}
	mod := new(big.Int).Lsh(big.NewInt(1), uint(8*w))
	out := new(big.Int).Add(v, mod).Bytes()
	if len(out) < w {
		out = append(make([]byte, w-len(out)), out...)
	}
	return out
}
