/**
 * Oracle test runner (plain Node, no test framework dependency).
 *
 *   node test/oracle/run-oracle.mjs [fuzzIterations] [seed]
 *
 * Phase 1: hand-authored vectors with exact, human-computed winner / failure.
 * Phase 2: seeded differential fuzzing comparing the independent oracle with
 * the compiled production core. Every line carries a run id, the service
 * version and progress. A parse error, thrown exception, or disagreement is a
 * hard failure with process exit code 1 - never silently reported as success.
 */
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { negotiate } from '../../dist/src/core/negotiator.js';
import { oracleDecide } from './oracle.mjs';

const RUN_ID = process.env.ORACLE_RUN_ID ?? randomUUID();
const VERSION = JSON.parse(readFileSync(new URL('../../package.json', import.meta.url), 'utf8')).version;
const ITERATIONS = Number(process.argv[2] ?? 500);
const SEED = Number(process.argv[3] ?? 20260928);

const log = (phase, msg, extra = {}) =>
  console.log(JSON.stringify({ runId: RUN_ID, serviceVersion: VERSION, phase, msg, ...extra }));

function mt(type, subtype, params = {}) {
  return { type, subtype, parameters: new Map(Object.entries(params)) };
}
function rep(id, type, subtype, lang, params) {
  return { id, mediaType: mt(type, subtype, params), language: lang, charset: 'utf-8', body: id };
}
function resource(id, reps) {
  return { id, name: id, representations: reps };
}

/**
 * Hand-computed vectors. Expected answers are written by hand from the RFC
 * rules, NOT generated by the oracle or the core. Variants use a fixed
 * declaration order so ties are predictable.
 */
const VECTORS = [
  {
    name: 'exact match both axes',
    resource: resource('r', [rep('a', 'application', 'json', 'en'), rep('b', 'application', 'xml', 'en')]),
    accept: 'application/json',
    lang: 'en',
    expect: { winner: 'a' },
  },
  {
    name: 'quality differentiates media (xml preferred)',
    resource: resource('r', [rep('a', 'application', 'json', 'en'), rep('b', 'application', 'xml', 'en')]),
    accept: 'application/json;q=0.4, application/xml;q=0.9',
    lang: 'en',
    expect: { winner: 'b' },
  },
  {
    name: 'specific exact q=0 forbids html but wildcard admits json',
    resource: resource('r', [rep('a', 'application', 'json', 'en'), rep('h', 'text', 'html', 'en')]),
    accept: 'text/html;q=0, */*;q=1',
    lang: 'en',
    expect: { winner: 'a' },
  },
  {
    name: 'all media explicitly forbidden',
    resource: resource('r', [rep('a', 'application', 'json', 'en'), rep('h', 'text', 'html', 'en')]),
    accept: 'text/html;q=0, application/json;q=0, */*;q=0',
    lang: 'en',
    expect: { failure: 'UNACCEPTABLE_MEDIA_TYPE' },
  },
  {
    name: 'no media matches at all',
    resource: resource('r', [rep('a', 'application', 'json', 'en')]),
    accept: 'image/png',
    lang: 'en',
    expect: { failure: 'UNACCEPTABLE_MEDIA_TYPE' },
  },
  {
    name: 'language unsupported',
    resource: resource('r', [rep('a', 'application', 'json', 'en')]),
    accept: '*/*',
    lang: 'ja',
    expect: { failure: 'UNACCEPTABLE_LANGUAGE' },
  },
  {
    name: 'language q=0 bans the only language',
    resource: resource('r', [rep('a', 'application', 'json', 'en')]),
    accept: '*/*',
    lang: 'en;q=0',
    expect: { failure: 'UNACCEPTABLE_LANGUAGE' },
  },
  {
    name: 'language en prefix also forbids en-gb',
    resource: resource('r', [rep('a', 'application', 'json', 'en-gb')]),
    accept: '*/*',
    lang: 'en;q=0, fr;q=1',
    expect: { failure: 'UNACCEPTABLE_LANGUAGE' },
  },
  {
    name: 'truncation fallback en-us serves en',
    resource: resource('r', [rep('a', 'application', 'json', 'en')]),
    accept: '*/*',
    lang: 'en-us',
    expect: { winner: 'a' },
  },
  {
    name: 'media pin + missing language combo fails',
    resource: resource('r', [rep('a', 'application', 'json', 'en'), rep('b', 'application', 'xml', 'fr')]),
    accept: 'application/json',
    lang: 'fr',
    expect: { failure: 'NO_VARIANT_FOR_COMBINATION' },
  },
  {
    name: 'media version parameter constraint matches v1',
    resource: resource('r', [rep('a', 'application', 'json', 'en', { version: '1' }), rep('b', 'application', 'json', 'en', { version: '2' })]),
    accept: 'application/json;version=1',
    lang: 'en',
    expect: { winner: 'a' },
  },
  {
    name: 'missing parameter value means no match',
    resource: resource('r', [rep('a', 'application', 'json', 'en')]),
    accept: 'application/json;version=2',
    lang: 'en',
    expect: { failure: 'UNACCEPTABLE_MEDIA_TYPE' },
  },
  {
    name: 'absent headers pick first declared variant',
    resource: resource('r', [rep('a', 'application', 'json', 'en'), rep('b', 'text', 'html', 'fr')]),
    accept: null,
    lang: null,
    expect: { winner: 'a' },
  },
  {
    name: 'type wildcard with earliest declaration order',
    resource: resource('r', [rep('a', 'application', 'json', 'en'), rep('b', 'application', 'xml', 'en')]),
    accept: 'application/*',
    lang: 'en',
    expect: { winner: 'a' },
  },
  {
    name: 'language quality picks fr over en',
    resource: resource('r', [rep('a', 'application', 'json', 'en'), rep('b', 'application', 'json', 'fr')]),
    accept: 'application/json',
    lang: 'en;q=0.3, fr;q=0.8',
    expect: { winner: 'b' },
  },
];

// ---- Seeded PRNG (mulberry32) for reproducible fuzzing ------------------------
function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const MEDIA_POOL = [
  ['application', 'json'],
  ['application', 'xml'],
  ['application', 'vnd.shop.v2+json'],
  ['text', 'html'],
  ['text', 'plain'],
];
const LANG_POOL = ['en', 'en-gb', 'fr', 'fr-ca', 'de', 'zh', 'ja'];
const Q_POOL = ['1', '0.9', '0.5', '0.1', '0'];

function pick(rng, arr) {
  return arr[Math.floor(rng() * arr.length)];
}

function randomResource(rng) {
  const count = 1 + Math.floor(rng() * 6);
  const reps = [];
  for (let i = 0; i < count; i += 1) {
    const [type, subtype] = pick(rng, MEDIA_POOL);
    const lang = pick(rng, LANG_POOL);
    const params = rng() < 0.3 ? { version: pick(rng, ['1', '2']) } : {};
    reps.push(rep(`v${i}-${type}-${subtype}-${lang}`.replace(/[^a-z0-9-]/gi, ''), type, subtype, lang, params));
  }
  return resource('fuzz', reps);
}

function randomAccept(rng, res) {
  if (rng() < 0.12) return null; // absent header
  const n = 1 + Math.floor(rng() * 3);
  const ranges = [];
  for (let i = 0; i < n; i += 1) {
    const shape = rng();
    let range;
    if (shape < 0.18) range = '*/*';
    else if (shape < 0.36) range = `${pick(rng, MEDIA_POOL)[0]}/*`;
    else {
      const [type, subtype] = pick(rng, MEDIA_POOL);
      range = `${type}/${subtype}`;
      if (rng() < 0.25) range += `;version=${pick(rng, ['1', '2'])}`;
    }
    const q = pick(rng, Q_POOL);
    if (q !== '1' || rng() < 0.3) range += `;q=${q}`;
    ranges.push(range);
  }
  return ranges.join(', ');
}

function randomLanguages(rng) {
  if (rng() < 0.12) return null;
  const n = 1 + Math.floor(rng() * 3);
  const ranges = [];
  for (let i = 0; i < n; i += 1) {
    let range;
    if (rng() < 0.2) range = '*';
    else {
      const base = pick(rng, LANG_POOL);
      // Sometimes ask for a regional tag that may need truncation fallback.
      range = rng() < 0.3 && !base.includes('-') ? `${base}-us` : base;
    }
    const q = pick(rng, Q_POOL);
    if (q !== '1' || rng() < 0.3) range += `;q=${q}`;
    ranges.push(range);
  }
  return ranges.join(', ');
}

// ---- Run ----------------------------------------------------------------------
let failures = 0;

log('hand-vectors', `validating ${VECTORS.length} hand-computed vectors`);
VECTORS.forEach((v, i) => {
  const coreTrace = negotiate({ resource: v.resource, acceptHeader: v.accept, acceptLanguageHeader: v.lang });
  const coreResult = coreTrace.failure ? { failure: coreTrace.failure.code } : { winner: coreTrace.winner.representationId };
  const oracleResult = oracleDecide(v.resource, v.accept, v.lang);
  const coreOk = JSON.stringify(coreResult) === JSON.stringify(v.expect);
  const oracleOk = JSON.stringify(oracleResult) === JSON.stringify(v.expect);
  const agree = JSON.stringify(coreResult) === JSON.stringify(oracleResult);
  if (!coreOk || !oracleOk || !agree) {
    failures += 1;
    log('hand-vectors', 'MISMATCH', { i, name: v.name, accept: v.accept, lang: v.lang, expect: v.expect, core: coreResult, oracle: oracleResult });
  } else {
    log('hand-vectors', `vector ${i + 1}/${VECTORS.length} ok: ${v.name} -> ${JSON.stringify(coreResult)}`);
  }
});

log('fuzz', `starting differential fuzz`, { iterations: ITERATIONS, seed: SEED });
const rng = mulberry32(SEED);
let agreements = 0;
for (let i = 0; i < ITERATIONS; i += 1) {
  const res = randomResource(rng);
  const accept = randomAccept(rng, res);
  const lang = randomLanguages(rng);

  let coreResult;
  let coreThrew = null;
  try {
    const trace = negotiate({ resource: res, acceptHeader: accept, acceptLanguageHeader: lang });
    coreResult = trace.failure ? { failure: trace.failure.code } : { winner: trace.winner.representationId };
  } catch (err) {
    coreThrew = err instanceof Error ? err.message : String(err);
  }
  let oracleResult;
  let oracleThrew = null;
  try {
    oracleResult = oracleDecide(res, accept, lang);
  } catch (err) {
    oracleThrew = err instanceof Error ? err.message : String(err);
  }

  if (coreThrew || oracleThrew || JSON.stringify(coreResult) !== JSON.stringify(oracleResult)) {
    failures += 1;
    log('fuzz', 'DISAGREEMENT', {
      iteration: i + 1,
      accept,
      lang,
      variants: res.representations.map((r) => ({ id: r.id, media: `${r.mediaType.type}/${r.mediaType.subtype}`, params: Object.fromEntries(r.mediaType.parameters), lang: r.language })),
      core: coreResult ?? { threw: coreThrew },
      oracle: oracleResult ?? { threw: oracleThrew },
    });
    if (failagesGuard(i)) break;
  } else {
    agreements += 1;
    if ((i + 1) % 100 === 0) log('fuzz', `progress ${i + 1}/${ITERATIONS}`, { agreements });
  }
}
function failagesGuard() {
  return failures >= 10; // stop after a few concrete disagreements
}

log('summary', failures === 0 ? 'ALL ORACLE CHECKS PASSED' : 'ORACLE CHECKS FAILED', {
  handVectors: VECTORS.length,
  fuzzIterations: ITERATIONS,
  agreements,
  failures,
});
if (failures > 0) process.exit(1);
