package compat

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"hpacklab.local/hpack"
)

// storyCase is one case in the http2jp/hpack-test-case JSON format.
type storyCase struct {
	Seqno           int                 `json:"seqno"`
	HeaderTableSize *uint32             `json:"header_table_size"`
	Wire            string              `json:"wire"`
	Headers         []map[string]string `json:"headers"`
}

type story struct {
	Description string      `json:"description"`
	Cases       []storyCase `json:"cases"`
}

const defaultTableSize = 4096

// loadStory parses one vendored golden story file.
func loadStory(t *testing.T, path string) story {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var s story
	if err := json.Unmarshal(raw, &s); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	return s
}

// goldenFields flattens the JSON's ordered single-key header maps into the
// wire order our decoder is expected to emit.
func goldenFields(c storyCase) []hpack.HeaderField {
	out := make([]hpack.HeaderField, 0, len(c.Headers))
	for _, m := range c.Headers {
		for k, v := range m {
			out = append(out, hpack.HeaderField{Name: k, Value: v})
		}
	}
	return out
}

// decodeStory runs every case of one story through a SINGLE decoder, so the
// dynamic table carries across cases exactly as on one real connection.
func decodeStory(t *testing.T, s story) {
	t.Helper()
	d := hpack.NewDecoder(hpack.DecoderOptions{
		// The ceiling is raised per-case below as SETTINGS changes arrive.
		MaxTableSize: defaultTableSize,
		Limits:       hpack.DefaultLimits(),
	})
	for i, c := range s.Cases {
		allowed := uint32(defaultTableSize)
		if c.HeaderTableSize != nil {
			allowed = *c.HeaderTableSize
		}
		d.SetAllowedMaxTableSize(allowed)
		wire, err := hex.DecodeString(strings.TrimSpace(c.Wire))
		if err != nil {
			t.Fatalf("case %d: bad wire hex: %v", i, err)
		}
		got, derr := d.DecodeBlock(wire)
		if derr != nil {
			t.Fatalf("case %d (seqno %d): decode error: %v", i, c.Seqno, derr)
		}
		want := goldenFields(c)
		if len(got) != len(want) {
			t.Fatalf("case %d: %d fields, want %d; got=%v want=%v", i, len(got), len(want), got, want)
		}
		for j := range want {
			if got[j].Name != want[j].Name || got[j].Value != want[j].Value {
				t.Fatalf("case %d field %d = %q:%q, want %q:%q", i, j, got[j].Name, got[j].Value, want[j].Name, want[j].Value)
			}
		}
	}
}

// TestGoldenCorpus decodes every vendored story produced by every bundled
// third-party HPACK implementation (nghttp2, python-hpack, node-http2,
// swift-nio, go-hpack). None of the expected answers is generated by the
// core implementation under test: wires and headers both come from the
// public http2jp/hpack-test-case corpus.
func TestGoldenCorpus(t *testing.T) {
	root := filepath.Join("testdata", "corpus")
	dirs, err := os.ReadDir(root)
	if err != nil {
		t.Fatal(err)
	}
	var impls []string
	for _, de := range dirs {
		// "raw-data" holds only encoder INPUT (headers, no wire); it is used
		// by the encoder oracle test, not the decode corpus.
		if de.IsDir() && de.Name() != "raw-data" {
			impls = append(impls, de.Name())
		}
	}
	sort.Strings(impls)
	if len(impls) < 5 {
		t.Fatalf("expected golden output from at least 5 independent implementations, got %v", impls)
	}
	stories := 0
	for _, impl := range impls {
		impl := impl
		t.Run(impl, func(t *testing.T) {
			matches, _ := filepath.Glob(filepath.Join(root, impl, "story_*.json"))
			sort.Strings(matches)
			if len(matches) == 0 {
				t.Fatalf("no stories in %s", impl)
			}
			for _, m := range matches {
				s := loadStory(t, m)
				t.Run(filepath.Base(m), func(t *testing.T) {
					decodeStory(t, s)
				})
				stories++
			}
		})
	}
	t.Logf("decoded %d stories across %d independent encoder implementations", stories, len(impls))
}

// TestGoldenCorpusTableShrink focuses on the nghttp2 change-table-size
// series, asserting the live dynamic table actually shrank when the wire
// carried size updates (not merely that decoding succeeded).
func TestGoldenCorpusTableShrink(t *testing.T) {
	s := loadStory(t, filepath.Join("testdata", "corpus", "nghttp2-change-table-size", "story_00.json"))
	d := hpack.NewDecoder(hpack.DecoderOptions{MaxTableSize: 4096, Limits: hpack.DefaultLimits()})
	for i, c := range s.Cases {
		if c.HeaderTableSize != nil {
			d.SetAllowedMaxTableSize(*c.HeaderTableSize)
		}
		wire, _ := hex.DecodeString(strings.TrimSpace(c.Wire))
		if _, err := d.DecodeBlock(wire); err != nil {
			t.Fatalf("case %d: %v", i, err)
		}
		if c.HeaderTableSize != nil && d.DynamicTableMax() != *c.HeaderTableSize {
			t.Fatalf("case %d: table max = %d, want SETTINGS %d", i, d.DynamicTableMax(), *c.HeaderTableSize)
		}
	}
}
