"""Bounded in-memory registries for tensors and graphs.

Handles are stable string ids generated by the store. Every registry is
capacity-bounded by configuration so a client cannot grow it without limit.
The registries are deliberately simple and single-process; they hold the
synthetic fixtures used by the API and tests.
"""

from __future__ import annotations

import itertools
import threading

from ..errors import ConfigError, StateError, StorageLimitExceededError
from ..graph import Graph
from ..tensor import Tensor


class TensorStore:
    """Handle -> Tensor registry with an eviction/ownership boundary."""

    def __init__(self, capacity: int, max_elements: int = 100_000_000) -> None:
        if not isinstance(capacity, int) or capacity <= 0:
            raise ConfigError(f"capacity must be a positive int, got {capacity!r}")
        if not isinstance(max_elements, int) or max_elements <= 0:
            raise ConfigError(
                f"max_elements must be a positive int, got {max_elements!r}")
        self._capacity = capacity
        self._max_elements = max_elements
        self._tensors: dict[str, Tensor] = {}
        self._counter = itertools.count(1)
        self._lock = threading.Lock()

    @property
    def capacity(self) -> int:
        return self._capacity

    def put(self, tensor: Tensor, *, handle: str | None = None) -> str:
        if not isinstance(tensor, Tensor):
            raise TypeError("TensorStore only holds Tensor instances")
        if tensor.size > self._max_elements:
            raise StorageLimitExceededError(
                f"tensor has {tensor.size} elements, above the per-tensor "
                f"limit of {self._max_elements}",
                details={"size": tensor.size,
                         "limit": self._max_elements})
        with self._lock:
            if handle is not None:
                self._tensors[handle] = tensor
                return handle
            if len(self._tensors) >= self._capacity:
                raise StateError(
                    f"tensor store full ({self._capacity} handles); "
                    "delete handles before adding more",
                    details={"capacity": self._capacity})
            handle = f"t{next(self._counter)}"
            while handle in self._tensors:
                handle = f"t{next(self._counter)}"
            self._tensors[handle] = tensor
            return handle

    def get(self, handle: str) -> Tensor:
        try:
            return self._tensors[handle]
        except KeyError:
            raise StateError(
                f"unknown tensor handle {handle!r}",
                details={"handle": handle, "not_found": True,
                         "available": sorted(self._tensors)}) from None

    def has(self, handle: str) -> bool:
        return handle in self._tensors

    def delete(self, handle: str) -> None:
        if handle not in self._tensors:
            raise StateError(f"cannot delete unknown tensor handle {handle!r}",
                             details={"handle": handle})
        del self._tensors[handle]

    def list_handles(self) -> list[str]:
        return sorted(self._tensors,
                      key=lambda h: int(h[1:]) if h.startswith("t") and h[1:].isdigit() else 0)

    def __len__(self) -> int:
        return len(self._tensors)

    def __contains__(self, handle: object) -> bool:
        return handle in self._tensors


class GraphStore:
    def __init__(self, capacity: int) -> None:
        if not isinstance(capacity, int) or capacity <= 0:
            raise ConfigError(f"capacity must be a positive int, got {capacity!r}")
        self._capacity = capacity
        self._graphs: dict[str, Graph] = {}
        self._counter = itertools.count(1)
        self._lock = threading.Lock()

    def put(self, graph: Graph, *, handle: str | None = None) -> str:
        if not isinstance(graph, Graph):
            raise TypeError("GraphStore only holds Graph instances")
        with self._lock:
            if handle is not None:
                self._graphs[handle] = graph
                return handle
            if len(self._graphs) >= self._capacity:
                raise StateError(
                    f"graph store full ({self._capacity} handles)",
                    details={"capacity": self._capacity})
            handle = f"g{next(self._counter)}"
            while handle in self._graphs:
                handle = f"g{next(self._counter)}"
            self._graphs[handle] = graph
            return handle

    def get(self, handle: str) -> Graph:
        try:
            return self._graphs[handle]
        except KeyError:
            raise StateError(f"unknown graph handle {handle!r}",
                             details={"handle": handle,
                                      "not_found": True}) from None

    def has(self, handle: str) -> bool:
        return handle in self._graphs

    def delete(self, handle: str) -> None:
        if handle not in self._graphs:
            raise StateError(f"cannot delete unknown graph handle {handle!r}",
                             details={"handle": handle})
        del self._graphs[handle]

    def list_handles(self) -> list[str]:
        return sorted(self._graphs)

    def __len__(self) -> int:
        return len(self._graphs)
