//! End-to-end tests against a live server on an ephemeral port.
//!
//! Every expected number in this file is hand-computed from the fixture
//! files (see README "Hand-computed baselines"); none of it is generated by
//! the implementation under test. Test logs print the run id and the key
//! intermediate states so a failure can be replayed by hand.

use std::sync::Arc;

use serde_json::{json, Value};
use stackstats::api;
use stackstats::config::Limits;
use stackstats::store::RunStore;

fn test_limits() -> Limits {
    Limits {
        max_runs: 8,
        max_samples_per_run: 16,
        max_stack_depth: 8,
        max_samples_per_request: 16,
    }
}

async fn spawn_server(limits: Limits) -> (String, tempfile::TempDir) {
    let dir = tempfile::tempdir().unwrap();
    let store = Arc::new(RunStore::open(dir.path().to_path_buf(), limits).unwrap());
    let app = api::router(store);
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let addr = listener.local_addr().unwrap();
    tokio::spawn(async move { axum::serve(listener, app).await.unwrap() });
    (format!("http://{addr}"), dir)
}

fn load_fixture(name: &str) -> Value {
    let path = format!("{}/fixtures/{name}", env!("CARGO_MANIFEST_DIR"));
    let text = std::fs::read_to_string(&path).unwrap();
    serde_json::from_str(&text).unwrap()
}

/// Creates a run from a fixture, ingests its samples, seals it, and returns
/// the run id. Logs each step for replayability.
async fn run_fixture(client: &reqwest::Client, base: &str, fixture: Value) -> String {
    let created: Value = client
        .post(format!("{base}/runs"))
        .json(&fixture["run"])
        .send()
        .await
        .unwrap()
        .json()
        .await
        .unwrap();
    let run_id = created["run_id"].as_str().unwrap().to_string();
    eprintln!("[test_log] run_id={run_id} step=create state=open");

    let ingest: Value = client
        .post(format!("{base}/runs/{run_id}/samples"))
        .json(&json!({"samples": fixture["samples"]}))
        .send()
        .await
        .unwrap()
        .json()
        .await
        .unwrap();
    eprintln!("[test_log] run_id={run_id} step=ingest response={ingest}");
    assert_eq!(ingest["accepted"], fixture["samples"].as_array().unwrap().len());

    client
        .post(format!("{base}/runs/{run_id}/seal"))
        .send()
        .await
        .unwrap();
    eprintln!("[test_log] run_id={run_id} step=seal state=sealed");
    run_id
}

async fn get(client: &reqwest::Client, url: &str) -> Value {
    client.get(url).send().await.unwrap().json().await.unwrap()
}

/// Depth-first lookup of a tree node by following display names.
fn find_node<'a>(roots: &'a [Value], path: &[&str]) -> &'a Value {
    let mut level = roots;
    for (depth, name) in path.iter().enumerate() {
        let node = level
            .iter()
            .find(|n| n["name"] == *name)
            .unwrap_or_else(|| panic!("node {name} missing at depth {depth}"));
        if depth == path.len() - 1 {
            return node;
        }
        level = node["children"].as_array().unwrap();
    }
    unreachable!()
}

#[tokio::test]
async fn recursion_and_shared_leaf_match_hand_computation() {
    let (base, _dir) = spawn_server(test_limits()).await;
    let client = reqwest::Client::new();
    let run_id = run_fixture(&client, &base, load_fixture("recursion_shared_leaf.json")).await;

    // Hand-computed from the fixture:
    //   s1 main;rec;rec;leaf w2 | s2 main;rec;leaf w1 | s3 main;other;leaf w4
    let tree = get(&client, &format!("{base}/runs/{run_id}/tree")).await;
    eprintln!("[test_log] run_id={run_id} step=tree total_weight={}", tree["total_weight"]);
    assert_eq!(tree["total_weight"], 7.0);
    assert_eq!(tree["sample_count"], 3);

    let roots = tree["roots"].as_array().unwrap();
    let main = find_node(roots, &["main"]);
    assert_eq!(main["inclusive_weight"], 7.0);
    assert_eq!(main["self_weight"], 0.0);

    // Recursion kept by position: rec@depth1 (incl 3) has child rec@depth2 (incl 2).
    let rec1 = find_node(roots, &["main", "rec"]);
    assert_eq!(rec1["inclusive_weight"], 3.0);
    let rec2 = find_node(roots, &["main", "rec", "rec"]);
    assert_eq!(rec2["inclusive_weight"], 2.0);
    assert_eq!(rec2["self_weight"], 0.0);
    assert_eq!(find_node(roots, &["main", "rec", "rec", "leaf"])["self_weight"], 2.0);
    // Shared leaf: three distinct positions, self weights 2 / 1 / 4.
    assert_eq!(find_node(roots, &["main", "rec", "leaf"])["self_weight"], 1.0);
    assert_eq!(find_node(roots, &["main", "other", "leaf"])["self_weight"], 4.0);

    let folded = get(&client, &format!("{base}/runs/{run_id}/folded")).await;
    assert_eq!(
        folded["lines"],
        json!([
            {"stack": "main;other;leaf", "weight": 4.0},
            {"stack": "main;rec;leaf", "weight": 1.0},
            {"stack": "main;rec;rec;leaf", "weight": 2.0},
        ])
    );

    let summary = get(&client, &format!("{base}/runs/{run_id}/summary")).await;
    eprintln!("[test_log] run_id={run_id} step=summary hot={} cold={}", summary["hot_path"], summary["cold_path"]);
    assert_eq!(summary["hot_path"], json!({"frames": ["main", "other", "leaf"], "weight": 4.0}));
    assert_eq!(summary["cold_path"], json!({"frames": ["main", "rec", "leaf"], "weight": 1.0}));
    assert_eq!(summary["keep_ratio"], 1.0);
    // Flat profile merges recursion positions: leaf self = 2+1+4 = 7.
    assert_eq!(summary["top_self"][0]["name"], "leaf");
    assert_eq!(summary["top_self"][0]["self_weight"], 7.0);
}

#[tokio::test]
async fn async_fragments_stitch_only_with_token_evidence() {
    let (base, _dir) = spawn_server(test_limits()).await;
    let client = reqwest::Client::new();
    let run_id = run_fixture(&client, &base, load_fixture("async_fragments.json")).await;

    // Hand-computed: a2 attaches under a1 (token tokA); a3's parent token is
    // missing so it anchors under a synthetic detached root with w3.
    let folded = get(&client, &format!("{base}/runs/{run_id}/folded")).await;
    eprintln!("[test_log] run_id={run_id} step=folded lines={}", folded["lines"]);
    assert_eq!(
        folded["lines"],
        json!([
            {"stack": "async_detached(task=9);orphan", "weight": 3.0},
            {"stack": "main;spawn", "weight": 1.0},
            {"stack": "main;spawn;poll_worker;leaf", "weight": 1.0},
        ])
    );
    assert_eq!(folded["total_weight"], 5.0);

    let summary = get(&client, &format!("{base}/runs/{run_id}/summary")).await;
    assert_eq!(
        summary["hot_path"],
        json!({"frames": ["async_detached(task=9)", "orphan"], "weight": 3.0})
    );
    assert_eq!(
        summary["cold_path"],
        json!({"frames": ["main", "spawn", "poll_worker", "leaf"], "weight": 1.0})
    );

    // Audit: every path carries its stitching evidence and rationale.
    let audit = get(&client, &format!("{base}/runs/{run_id}/audit")).await;
    eprintln!("[test_log] run_id={run_id} step=audit entries={}", audit["entries"]);
    let entries = audit["entries"].as_array().unwrap();
    let by_id = |id: &str| entries.iter().find(|e| e["sample_id"] == id).unwrap();
    assert_eq!(by_id("a1")["evidence"], json!({"kind": "direct"}));
    assert_eq!(
        by_id("a2")["evidence"],
        json!({"kind": "stitched", "parent_sample_id": "a1", "token": "tokA"})
    );
    assert_eq!(by_id("a2")["path"], json!(["main", "spawn", "poll_worker", "leaf"]));
    assert_eq!(
        by_id("a3")["evidence"],
        json!({"kind": "detached", "task_id": 9, "parent_token": "tokMissing"})
    );
    assert_eq!(by_id("a3")["path"], json!(["async_detached(task=9)", "orphan"]));
}

#[tokio::test]
async fn weighted_samples_and_drop_ratio_are_explicit() {
    let (base, _dir) = spawn_server(test_limits()).await;
    let client = reqwest::Client::new();
    let run_id = run_fixture(&client, &base, load_fixture("weighted_dropped.json")).await;

    // Hand-computed: weights 1.5 + 3.5 + 1.0 = 6.0 kept; 5 dropped.
    let summary = get(&client, &format!("{base}/runs/{run_id}/summary")).await;
    eprintln!(
        "[test_log] run_id={run_id} step=summary total_weight={} keep_ratio={} explanation={}",
        summary["total_weight"], summary["keep_ratio"], summary["weight_explanation"]
    );
    assert_eq!(summary["total_weight"], 6.0);
    assert_eq!(summary["sample_count"], 3);
    assert_eq!(summary["dropped_samples"], 5);
    assert_eq!(summary["keep_ratio"], 3.0 / 8.0);
    assert!(summary["weight_explanation"].as_str().unwrap().contains("keep_ratio"));

    // emit (3.5) is hotter than parse (2.5).
    assert_eq!(summary["hot_path"], json!({"frames": ["main", "emit"], "weight": 3.5}));
    assert_eq!(summary["cold_path"], json!({"frames": ["main", "parse"], "weight": 2.5}));

    let folded = get(&client, &format!("{base}/runs/{run_id}/folded")).await;
    assert_eq!(
        folded["lines"],
        json!([
            {"stack": "main;emit", "weight": 3.5},
            {"stack": "main;parse", "weight": 2.5},
        ])
    );
}

#[tokio::test]
async fn missing_symbols_and_same_named_functions_never_merge() {
    let (base, _dir) = spawn_server(test_limits()).await;
    let client = reqwest::Client::new();
    let run_id = run_fixture(&client, &base, load_fixture("missing_symbols.json")).await;

    let tree = get(&client, &format!("{base}/runs/{run_id}/tree")).await;
    eprintln!("[test_log] run_id={run_id} step=tree roots={}", tree["roots"]);
    let roots = tree["roots"].as_array().unwrap();
    let main = find_node(roots, &["main"]);
    let children = main["children"].as_array().unwrap();
    assert_eq!(children.len(), 3, "two helpers + one unknown address stay distinct");

    // Display disambiguates, identity stays (module, addr).
    let folded = get(&client, &format!("{base}/runs/{run_id}/folded")).await;
    assert_eq!(
        folded["lines"],
        json!([
            {"stack": "main;0xdead", "weight": 1.0},
            {"stack": "main;helper@app", "weight": 1.0},
            {"stack": "main;helper@lib", "weight": 1.0},
        ])
    );

    // Flat profile: helper@app and helper@lib are separate entries.
    let summary = get(&client, &format!("{base}/runs/{run_id}/summary")).await;
    let top = summary["top_self"].as_array().unwrap();
    let helpers: Vec<&Value> = top.iter().filter(|e| e["name"].as_str().unwrap().starts_with("helper@")).collect();
    assert_eq!(helpers.len(), 2);
    assert!(helpers.iter().all(|h| h["self_weight"] == 1.0));
}

#[tokio::test]
async fn error_categories_are_distinguishable_over_http() {
    let (base, _dir) = spawn_server(test_limits()).await;
    let client = reqwest::Client::new();

    // Unknown run -> input / 404.
    let res = client
        .post(format!("{base}/runs/run-nope/samples"))
        .json(&json!({"samples": []}))
        .send()
        .await
        .unwrap();
    assert_eq!(res.status(), 404);
    let body: Value = res.json().await.unwrap();
    assert_eq!(body["error"]["category"], "input");
    assert_eq!(body["error"]["code"], "run_not_found");

    let run_id = run_fixture(&client, &base, load_fixture("recursion_shared_leaf.json")).await;

    // Ingest into sealed run -> state_conflict / 409.
    let res = client
        .post(format!("{base}/runs/{run_id}/samples"))
        .json(&json!({"samples": [{"sample_id": "x", "weight": 1.0, "frames": [{"addr": 1}]}]}))
        .send()
        .await
        .unwrap();
    assert_eq!(res.status(), 409);
    let body: Value = res.json().await.unwrap();
    assert_eq!(body["error"]["category"], "state_conflict");
    assert_eq!(body["error"]["code"], "run_sealed");
    eprintln!("[test_log] run_id={run_id} step=reject reason=run_sealed body={body}");

    // Invalid weight -> input / 400.
    let created: Value = client.post(format!("{base}/runs")).json(&json!({})).send().await.unwrap().json().await.unwrap();
    let run2 = created["run_id"].as_str().unwrap();
    let res = client
        .post(format!("{base}/runs/{run2}/samples"))
        .json(&json!({"samples": [{"sample_id": "bad", "weight": 0.0, "frames": [{"addr": 1}]}]}))
        .send()
        .await
        .unwrap();
    assert_eq!(res.status(), 400);
    let body: Value = res.json().await.unwrap();
    assert_eq!(body["error"]["category"], "input");
    assert_eq!(body["error"]["code"], "invalid_weight");

    // Stack deeper than max_stack_depth (8) -> resource_exhausted / 413.
    let deep_frames: Vec<Value> = (0..9).map(|i| json!({"addr": i})).collect();
    let res = client
        .post(format!("{base}/runs/{run2}/samples"))
        .json(&json!({"samples": [{"sample_id": "deep", "weight": 1.0, "frames": deep_frames}]}))
        .send()
        .await
        .unwrap();
    assert_eq!(res.status(), 413);
    let body: Value = res.json().await.unwrap();
    assert_eq!(body["error"]["category"], "resource_exhausted");
    assert_eq!(body["error"]["code"], "stack_too_deep");

    // Async cycle -> input / 400.
    let res = client
        .post(format!("{base}/runs/{run2}/samples"))
        .json(&json!({"samples": [
            {"sample_id": "c1", "weight": 1.0, "frames": [{"addr": 1}],
             "async_link": {"task_id": 1, "token": "ta", "parent_token": "tb"}},
            {"sample_id": "c2", "weight": 1.0, "frames": [{"addr": 2}],
             "async_link": {"task_id": 1, "token": "tb", "parent_token": "ta"}}
        ]}))
        .send()
        .await
        .unwrap();
    assert_eq!(res.status(), 400);
    let body: Value = res.json().await.unwrap();
    assert_eq!(body["error"]["code"], "async_cycle");
    eprintln!("[test_log] run_id={run2} step=reject reason=async_cycle body={body}");

    // Malformed JSON -> input / 400 (not axum's default 422).
    let res = client
        .post(format!("{base}/runs/{run2}/samples"))
        .header("content-type", "application/json")
        .body("{not json")
        .send()
        .await
        .unwrap();
    assert_eq!(res.status(), 400);
    let body: Value = res.json().await.unwrap();
    assert_eq!(body["error"]["category"], "input");
}

#[tokio::test]
async fn sample_limit_is_resource_exhausted() {
    let mut limits = test_limits();
    limits.max_samples_per_run = 2;
    let (base, _dir) = spawn_server(limits).await;
    let client = reqwest::Client::new();
    let created: Value = client.post(format!("{base}/runs")).json(&json!({})).send().await.unwrap().json().await.unwrap();
    let run_id = created["run_id"].as_str().unwrap();
    let samples: Vec<Value> = (0..3)
        .map(|i| json!({"sample_id": format!("s{i}"), "weight": 1.0, "frames": [{"addr": 1}]}))
        .collect();
    let res = client
        .post(format!("{base}/runs/{run_id}/samples"))
        .json(&json!({"samples": samples}))
        .send()
        .await
        .unwrap();
    assert_eq!(res.status(), 413);
    let body: Value = res.json().await.unwrap();
    assert_eq!(body["error"]["category"], "resource_exhausted");
    assert_eq!(body["error"]["code"], "sample_limit");
    eprintln!("[test_log] run_id={run_id} step=reject reason=sample_limit body={body}");
}
