"""Hand-authored synthetic problem scenarios shared by the test modules.

These are deliberately explicit (not generated by the kernel): each carries
the concrete question it is meant to answer.
"""

from __future__ import annotations

from typing import Any

# F runs [0,4) requiring x>=1 throughout; G's end effect at t=2 drops x to 0.
# The invariant must therefore fail at the *interior* point t=2, not at an end.
MIDPOINT_VIOLATION: dict[str, Any] = {
    "horizon": 5,
    "fluents": {"x": 1},
    "resources": [],
    "actions": [
        {"id": "F", "duration": 4, "start_condition": [], "invariant": [
            {"fluent": {"id": "x", "op": ">=", "value": 1}}], "effects": []},
        {"id": "G", "duration": 1, "start_condition": [], "invariant": [],
         "effects": [{"fluent": "x", "op": "-", "amount": 1}]},
    ],
    "goal": {"all": []},
}

# Capacity-1 renewable: back-to-back over a half-open boundary is legal;
# overlapping by one grid point is a resource conflict at t=2.
BOUNDARY_RELEASE: dict[str, Any] = {
    "horizon": 5,
    "fluents": {"x": 0, "y": 0},
    "resources": [{"id": "robot", "capacity": 1, "kind": "renewable"}],
    "actions": [
        {"id": "A", "duration": 3, "start_condition": [], "invariant": [],
         "effects": [{"fluent": "x", "op": "+", "amount": 1}],
         "resource_use": [{"resource": "robot", "amount": 1}]},
        {"id": "B", "duration": 2,
         "start_condition": [{"fluent": {"id": "x", "op": ">=", "value": 1}}],
         "invariant": [], "effects": [{"fluent": "y", "op": "+", "amount": 1}],
         "resource_use": [{"resource": "robot", "amount": 1}]},
    ],
    "goal": {"fluent": {"id": "y", "op": ">=", "value": 1}},
}

# A zero-duration pulse applies its effect at exactly one instant.
ZERO_DURATION: dict[str, Any] = {
    "horizon": 3,
    "fluents": {"x": 0},
    "resources": [],
    "actions": [
        {"id": "Z", "duration": 0,
         "start_condition": [{"fluent": {"id": "x", "op": "==", "value": 0}}],
         "invariant": [{"fluent": {"id": "x", "op": "==", "value": 5}}],
         "effects": [{"fluent": "x", "op": "+", "amount": 5}]},
    ],
    "goal": {"fluent": {"id": "x", "op": ">=", "value": 5}},
}

# Start condition must hold in the pre-effect state at the start instant.
START_CONDITION: dict[str, Any] = {
    "horizon": 4,
    "fluents": {"ready": 0},
    "resources": [],
    "actions": [
        {"id": "arm", "duration": 1, "start_condition": [], "invariant": [],
         "effects": [{"fluent": "ready", "op": "=", "amount": 1}]},
        {"id": "fire", "duration": 1,
         "start_condition": [{"fluent": {"id": "ready", "op": "==", "value": 1}}],
         "invariant": [], "effects": []},
    ],
    "goal": {"all": []},
}

# Consumable pool: two debits of 2 from a stock of 3 cannot overlap in time
# (stock would go negative at the second start); sequentially they can.
CONSUMABLE: dict[str, Any] = {
    "horizon": 6,
    "fluents": {"done": 0},
    "resources": [{"id": "fuel", "capacity": 3, "kind": "consumable"}],
    "actions": [
        {"id": "burn", "duration": 2, "start_condition": [], "invariant": [],
         "effects": [{"fluent": "done", "op": "+", "amount": 1}],
         "resource_use": [{"resource": "fuel", "amount": 2}]},
    ],
    "goal": {"fluent": {"id": "done", "op": ">=", "value": 1}},
}

# Nothing can raise x to 5: proven infeasibility.
UNSAT: dict[str, Any] = {
    "horizon": 3,
    "fluents": {"x": 0},
    "resources": [],
    "actions": [
        {"id": "inc", "duration": 1, "start_condition": [], "invariant": [],
         "effects": [{"fluent": "x", "op": "+", "amount": 1}]},
    ],
    "goal": {"fluent": {"id": "x", "op": ">=", "value": 5}},
}

# Three small increments vs one big jump. Search discovers the 3-action plan
# first (action order), so an early budget stop yields a feasible plan whose
# optimality is not yet proven.
OPTIMALITY_GAP: dict[str, Any] = {
    "horizon": 8,
    "fluents": {"x": 0},
    "resources": [],
    "actions": [
        {"id": "inc", "duration": 1, "start_condition": [], "invariant": [],
         "effects": [{"fluent": "x", "op": "+", "amount": 1}]},
        {"id": "big", "duration": 1, "start_condition": [], "invariant": [],
         "effects": [{"fluent": "x", "op": "+", "amount": 3}]},
    ],
    "goal": {"fluent": {"id": "x", "op": ">=", "value": 3}},
}

# Exact-rational arithmetic: 1/3 applied three times must equal 1 exactly.
FRACTIONAL: dict[str, Any] = {
    "horizon": 4,
    "fluents": {"x": 0},
    "resources": [],
    "actions": [
        {"id": "third", "duration": 1, "start_condition": [], "invariant": [],
         "effects": [{"fluent": "x", "op": "+", "amount": "1/3"}]},
    ],
    "goal": {"fluent": {"id": "x", "op": "==", "value": 1}},
}

# Small cases exhaustively cross-checked against the independent oracle:
# (label, problem). Kept tiny on purpose (horizon <= 4, each action <= once).
ORACLE_CASES: list[tuple[str, dict[str, Any]]] = [
    ("zero_dur", ZERO_DURATION),
    ("start_cond", START_CONDITION),
    ("fractional", FRACTIONAL),
    (
        "two_step",
        {
            "horizon": 4,
            "fluents": {"x": 0, "y": 0},
            "resources": [],
            "actions": [
                {"id": "a", "duration": 1, "start_condition": [], "invariant": [],
                 "effects": [{"fluent": "x", "op": "+", "amount": 1}]},
                {"id": "b", "duration": 1,
                 "start_condition": [{"fluent": {"id": "x", "op": ">=", "value": 1}}],
                 "invariant": [], "effects": [{"fluent": "y", "op": "+", "amount": 1}]},
            ],
            "goal": {"fluent": {"id": "y", "op": ">=", "value": 1}},
        },
    ),
    (
        "cap1_chain",
        {
            "horizon": 3,
            "fluents": {"x": 0},
            "resources": [{"id": "r", "capacity": 1, "kind": "renewable"}],
            "actions": [
                {"id": "a", "duration": 2, "start_condition": [], "invariant": [],
                 "effects": [{"fluent": "x", "op": "+", "amount": 1}],
                 "resource_use": [{"resource": "r", "amount": 1}]},
                {"id": "b", "duration": 1,
                 "start_condition": [{"fluent": {"id": "x", "op": ">=", "value": 1}}],
                 "invariant": [], "effects": [],
                 "resource_use": [{"resource": "r", "amount": 1}]},
            ],
            "goal": {"all": []},
        },
    ),
    (
        "invariant_guard",
        {
            "horizon": 4,
            "fluents": {"x": 2},
            "resources": [],
            "actions": [
                {"id": "hold", "duration": 3, "start_condition": [],
                 "invariant": [{"fluent": {"id": "x", "op": ">=", "value": 2}}],
                 "effects": []},
                {"id": "dip", "duration": 1, "start_condition": [], "invariant": [],
                 "effects": [{"fluent": "x", "op": "-", "amount": 1}]},
            ],
            "goal": {"all": []},
        },
    ),
    (
        "assign_and_not",
        {
            "horizon": 3,
            "fluents": {"x": 0},
            "resources": [],
            "actions": [
                {"id": "set5", "duration": 1, "start_condition": [], "invariant": [],
                 "effects": [{"fluent": "x", "op": "=", "amount": 5}]},
            ],
            "goal": {"not": {"fluent": {"id": "x", "op": "<", "value": 5}}},
        },
    ),
]
