"""Shared fixtures for the minigrad test suite.

All data is synthetic and deterministic (fixed seeds / literal arrays);
no external services or production data are involved.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

FIXTURES_DIR = Path(__file__).parent / "fixtures"


@pytest.fixture()
def rng():
    return np.random.default_rng(20260927)


@pytest.fixture()
def reference_grads():
    """Hand-derivable reference gradients generated by scripts/generate_fixtures.py
    using pure NumPy (independent of the autodiff engine)."""
    return json.loads((FIXTURES_DIR / "reference_grads.json").read_text())


@pytest.fixture()
def sample_matrix():
    return np.array([[0.5, -1.2, 0.3], [2.0, 0.1, -0.7]])
