"""Shared test fixtures.

Keys and expected answers come from committed, out-of-band fixture files
under ``fixtures/`` (generated by ``scripts/generate_fixtures.py``), never
from the service under test.
"""

from __future__ import annotations

import base64
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.core.audit import AuditLog  # noqa: E402
from app.core.crypto import CryptographyBackend, PyCryptodomeBackend  # noqa: E402
from app.core.keyring import KeyBundle  # noqa: E402
from app.core.service import SegmentedAEADService  # noqa: E402
from app.core.staging import StagingArea  # noqa: E402
from app.db.store import Store  # noqa: E402


@pytest.fixture(scope="session")
def fixture_keys() -> KeyBundle:
    data = json.loads((ROOT / "fixtures" / "test-keys.json").read_text())
    return KeyBundle(
        key_id=data["key_id"],
        aead_key=base64.b64decode(data["aead_key_b64"]),
        nonce_key=base64.b64decode(data["nonce_key_b64"]))


@pytest.fixture(scope="session")
def vectors() -> dict:
    return json.loads((ROOT / "fixtures" / "vectors.json").read_text())


@pytest.fixture(scope="session")
def gcm_kat() -> dict:
    return json.loads((ROOT / "fixtures" / "gcm-kat.json").read_text())


@pytest.fixture
def crypto_backend():
    return CryptographyBackend()


@pytest.fixture
def alt_backend():
    return PyCryptodomeBackend()


@pytest.fixture
def make_service(tmp_path, fixture_keys, crypto_backend):
    """Factory for an isolated service instance backed by tmp_path."""
    created: list[SegmentedAEADService] = []

    def _make(backend=None, max_segment: int = 1 << 20,
              max_total: int = 64 << 20) -> SegmentedAEADService:
        db = tmp_path / f"ssea-{len(created)}.sqlite3"
        staging = tmp_path / f"staging-{len(created)}"
        released = tmp_path / f"released-{len(created)}"
        store = Store(db)
        area = StagingArea(staging, released)
        svc = SegmentedAEADService(
            store, area, fixture_keys, backend or crypto_backend,
            audit=AuditLog(), max_segment_bytes=max_segment,
            max_total_bytes=max_total)
        created.append(svc)
        return svc

    yield _make

    for svc in created:
        svc._store.close()
