//! Cross-validation: direct recursive evaluation of each fixture formula is
//! compared against the evaluated expanded formula produced by QE, and
//! against hand-written reference answers stored in the fixture bundle.
//! The reference answers are authored by hand, not generated by the core.
use qe_fol::eval::eval_closed;
use qe_fol::model::Model;
use qe_fol::qe::{Eliminator, QeStatus};
use qe_fol::run_pipeline;
use qe_fol::syntax::FormulaBundle;

fn load_model(name: &str) -> Model {
    let path = match name {
        "two" => concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/model_two.json"),
        "empty-ok" => concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/model_empty.json"),
        other => panic!("no fixture model registered for '{other}'"),
    };
    Model::from_json_str(&std::fs::read_to_string(path).unwrap()).unwrap()
}

fn load_bundle() -> FormulaBundle {
    let text = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/formulas.json"
    ))
    .unwrap();
    FormulaBundle::from_json_str(&text).unwrap()
}

#[test]
fn recursive_eval_matches_expansion_and_handwritten_answers() {
    let bundle = load_bundle();
    assert!(bundle.formulas.len() >= 10, "fixture bundle should be rich");
    for entry in &bundle.formulas {
        for (model_name, expected) in &entry.expect {
            let model = load_model(model_name);
            let report = run_pipeline(&model, &entry.formula, None).unwrap_or_else(|e| {
                panic!("pipeline failed for '{}' on '{model_name}': {e}", entry.name)
            });
            assert_eq!(
                report.status,
                QeStatus::Eliminated,
                "unlimited budget must eliminate '{}'",
                entry.name
            );
            assert!(
                report.check.ok,
                "independent check failed for '{}' on '{}': {:?}",
                entry.name,
                model_name,
                report.check.violations
            );
            assert_eq!(
                report.value, *expected,
                "hand-written reference mismatch for '{}' on '{model_name}'",
                entry.name
            );
            // Direct comparison: recursive eval of original vs expanded.
            let expanded_value = eval_closed(&model, &report.result_formula).unwrap();
            let original_value = eval_closed(&model, &entry.formula).unwrap();
            assert_eq!(original_value, expanded_value);
            assert_eq!(original_value, *expected);
        }
    }
}

#[test]
fn budget_sweep_respects_partial_contract() {
    let bundle = load_bundle();
    let model = load_model("two");
    for entry in &bundle.formulas {
        let reference = eval_closed(&model, &entry.formula).unwrap();
        for budget in 0..=4u64 {
            let outcome = Eliminator::new(&model, Some(budget))
                .run(&entry.formula)
                .unwrap();
            match outcome.status {
                QeStatus::Eliminated => {
                    assert!(!outcome.unknown, "'{}': eliminated but unknown", entry.name);
                    assert_eq!(outcome.remaining_quantifiers, 0);
                    // A fully eliminated expansion must evaluate to the
                    // same value as the original under recursive eval.
                    let value = eval_closed(&model, &outcome.formula).unwrap();
                    assert_eq!(
                        value, reference,
                        "'{}': expanded formula disagrees at budget {budget}",
                        entry.name
                    );
                }
                QeStatus::Partial => {
                    assert!(outcome.unknown, "'{}': partial but not unknown", entry.name);
                    assert!(outcome.remaining_quantifiers > 0);
                    assert!(!outcome.formula.is_quantifier_free());
                    // Even a partial expansion stays equivalent on the model.
                    let value = eval_closed(&model, &outcome.formula).unwrap();
                    assert_eq!(
                        value, reference,
                        "'{}': partial expansion disagrees at budget {budget}",
                        entry.name
                    );
                }
            }
        }
    }
}
