"""Synthetic fixtures: thin bridges, holes, flat zones, border markers.

Every fixture returns (marker, mask, expected) where ``expected`` is
hand-computed from the geodesic dilation definition — NOT generated by
any kernel under test — so the kernels are checked against an
independent reference.
"""

from __future__ import annotations

import numpy as np


def thin_bridge() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """1-pixel-wide winding bridge in a zero mask.

    A seed of 150 at one end of a 200-valued bridge must travel the
    whole bridge (min(150, 200) = 150 at every step) and stop exactly
    at the bridge ends; the surrounding zero mask stays zero.
    """
    mask = np.zeros((9, 9), dtype=np.uint8)
    path = [(1, 1), (1, 2), (1, 3), (2, 3), (3, 3), (3, 4), (3, 5),
            (4, 5), (5, 5), (5, 6), (5, 7)]
    for r, c in path:
        mask[r, c] = 200
    marker = np.zeros_like(mask)
    marker[1, 1] = 150
    expected = np.zeros_like(mask)
    for r, c in path:
        expected[r, c] = 150
    return marker, mask, expected


def hole() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Zero-valued hole inside a bright mask.

    The reconstruction floods the mask at the seed level (100) but the
    hole is masked to 0, so it must remain 0 — geodesic dilation cannot
    cross a zero barrier lower than the propagating value... it can go
    around it: here the hole is enclosed but the flood still cannot
    raise the hole pixels above their mask value of 0.
    """
    mask = np.full((11, 11), 180, dtype=np.uint8)
    mask[4:7, 4:7] = 0  # 3x3 hole
    marker = np.zeros_like(mask)
    marker[0, 0] = 100
    expected = np.full((11, 11), 100, dtype=np.uint8)
    expected[4:7, 4:7] = 0
    return marker, mask, expected


def flat_zone() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Plateau mask: two flat levels.

    Seed 60 sits on the low plateau (mask 80); the high plateau
    (mask 200) can only be reached through the low one, so the
    propagated value is capped at min(60, ...) = 60 everywhere.
    """
    mask = np.full((8, 12), 200, dtype=np.uint8)
    mask[:, :5] = 80  # low plateau on the left
    marker = np.zeros_like(mask)
    marker[3, 2] = 60
    expected = np.full((8, 12), 60, dtype=np.uint8)
    return marker, mask, expected


def border_marker() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Marker on the image border; verifies the fixed boundary rule.

    Mask is 255 only on row 0.  With no wrap-around, the flood fills
    row 0 only; the opposite border (row H-1) must stay 0.  A kernel
    that wrapped edges would leak value into row H-1.
    """
    mask = np.zeros((6, 7), dtype=np.uint8)
    mask[0, :] = 255
    marker = np.zeros_like(mask)
    marker[0, 0] = 90
    expected = np.zeros_like(mask)
    expected[0, :] = 90
    return marker, mask, expected


def binary_regions() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Binary (0/255) marker and mask: the degenerate grayscale case."""
    mask = np.zeros((10, 10), dtype=np.uint8)
    mask[2:8, 2:8] = 255
    mask[4:6, 4:6] = 0  # binary hole
    marker = np.zeros_like(mask)
    marker[2, 2] = 255
    expected = mask.copy()  # flood fills the whole foreground ring
    return marker, mask, expected


def gradient_steps() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Hand-computed 1-row case with a stepped mask (4-connectivity).

    mask   = [ 7, 3, 7, 3, 7]
    marker = [ 7, 0, 0, 0, 0]
    The 7 at position 0 is capped by mask 3 at position 1, and that 3
    caps everything further right: result = [7, 3, 3, 3, 3].
    """
    mask = np.array([[7, 3, 7, 3, 7]], dtype=np.uint8)
    marker = np.array([[7, 0, 0, 0, 0]], dtype=np.uint8)
    expected = np.array([[7, 3, 3, 3, 3]], dtype=np.uint8)
    return marker, mask, expected


def two_seeds() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Two seeds of different heights on a flat mask.

    mask = 100 everywhere; seeds 40 (left) and 70 (right).  Each pixel
    takes the highest value any seed can deliver: max(40, 70) = 70
    everywhere (both seeds propagate across the whole flat mask).
    """
    mask = np.full((5, 9), 100, dtype=np.uint8)
    marker = np.zeros_like(mask)
    marker[2, 1] = 40
    marker[2, 7] = 70
    expected = np.full((5, 9), 70, dtype=np.uint8)
    return marker, mask, expected


ALL_FIXTURES = {
    "thin_bridge": thin_bridge,
    "hole": hole,
    "flat_zone": flat_zone,
    "border_marker": border_marker,
    "binary_regions": binary_regions,
    "gradient_steps": gradient_steps,
    "two_seeds": two_seeds,
}
