//! Phase 3 validation against the local synthetic fixture:
//! accent/case equivalence, numeric sequences, normalization; sort-agg vs hash-agg
//! group counts; and agreement with the independent oracle.
//!
//! Expected answers come from tests/fixtures/strings.json (hand-authored) AND from the
//! independent oracle — never generated by the code under test.

mod common;

use std::collections::BTreeSet;

use collate_agg::batch::batch_from_json_rows;
use collate_agg::collation::{rule_for, RepresentativePolicy, RuleVersion};
use collate_agg::exec::{hash_groups, sort_groups};
use collate_agg::oracle::oracle_partition;
use collate_agg::service::run_comparison;
use common::{test_state, Fixture};

#[test]
fn fixture_matches_hand_authored_expected_groups() {
    let fx = Fixture::load();
    let values = fx.values();
    let rule = rule_for(RuleVersion::V2026R1).unwrap();
    let batch =
        batch_from_json_rows(&fx.column, &fixture_rows_json(&fx)).expect("fixture batch builds");
    assert_eq!(batch.len(), values.len());

    let sort_set = sort_groups(rule, &batch, RepresentativePolicy::FirstWins);
    let hash_set = hash_groups(rule, &batch, RepresentativePolicy::FirstWins);

    // Concrete group count from the hand-authored fixture.
    assert_eq!(
        sort_set.group_count(),
        fx.expected_under_2026R1.group_count,
        "sort-agg group count"
    );
    assert_eq!(
        hash_set.group_count(),
        fx.expected_under_2026R1.group_count,
        "hash-agg group count"
    );

    // Concrete per-class membership and representatives.
    let expected: BTreeSet<Vec<usize>> = fx
        .expected_under_2026R1
        .classes
        .iter()
        .map(|c| {
            let mut rows = c.rows.clone();
            rows.sort_unstable();
            rows
        })
        .collect();

    let actual: BTreeSet<Vec<usize>> = sort_set
        .groups
        .iter()
        .map(|g| {
            let mut rows = g.rows.clone();
            rows.sort_unstable();
            rows
        })
        .collect();
    assert_eq!(actual, expected, "sort-agg classes vs fixture");

    let actual_hash: BTreeSet<Vec<usize>> = hash_set
        .groups
        .iter()
        .map(|g| {
            let mut rows = g.rows.clone();
            rows.sort_unstable();
            rows
        })
        .collect();
    assert_eq!(actual_hash, expected, "hash-agg classes vs fixture");

    // Representatives are the exact first-seen originals named in the fixture.
    let mut reps: Vec<String> = sort_set
        .groups
        .iter()
        .map(|g| g.representative.clone())
        .collect();
    reps.sort();
    let mut expected_reps: Vec<String> = fx
        .expected_under_2026R1
        .classes
        .iter()
        .map(|c| c.representative.clone())
        .collect();
    expected_reps.sort();
    assert_eq!(reps, expected_reps);
}

#[test]
fn numeric_sequence_classes_are_distinct_and_naturally_ordered() {
    let fx = Fixture::load();
    let values = fx.values();
    let rule = rule_for(RuleVersion::V2026R1).unwrap();
    let batch = batch_from_json_rows(&fx.column, &fixture_rows_json(&fx)).unwrap();
    let gs = sort_groups(rule, &batch, RepresentativePolicy::FirstWins);

    // item2 and ITEM02 collapse; item10 and item100 do not.
    let g2 = gs.group_for_identity("item2").unwrap();
    assert_eq!(g2.row_count, 2);
    assert!(g2.distinct_identities.contains(&"ITEM02".to_string()));
    assert_eq!(gs.group_for_identity("item10").unwrap().row_count, 1);
    assert_eq!(gs.group_for_identity("item100").unwrap().row_count, 1);

    // Ordering: in sort-key presentation the item2 group precedes item10 precedes item100.
    let pos = |rep: &str| {
        gs.groups
            .iter()
            .position(|g| g.representative == rep)
            .unwrap_or_else(|| panic!("missing {rep} in {:?}", values))
    };
    assert!(pos("item2") < pos("item10"));
    assert!(pos("item10") < pos("item100"));
}

#[test]
fn normalization_and_german_sharp_s_scope_are_respected() {
    let fx = Fixture::load();
    let values = fx.values();
    let rule = rule_for(RuleVersion::V2026R1).unwrap();
    let batch = batch_from_json_rows(&fx.column, &fixture_rows_json(&fx)).unwrap();
    let gs = sort_groups(rule, &batch, RepresentativePolicy::FirstWins);

    // NFD row 3 joins the NFC cafe class.
    let cafe = gs.group_for_identity("Café").unwrap();
    assert_eq!(cafe.rows, vec![0, 1, 2, 3, 4]);

    // Documented limitation: no ß <-> ss folding in scope -> distinct classes.
    let ss = gs.group_for_identity("straße").unwrap();
    assert_eq!(ss.row_count, 1);
    assert!(gs.group_for_identity("STRASSE").unwrap().rows == vec![11]);

    // Accent stripping: naïve / NAIVE / naive one class.
    let naive = gs.group_for_identity("naïve").unwrap();
    assert_eq!(naive.rows, vec![12, 13, 14]);
    let _ = values;
}

#[test]
fn independent_oracle_agrees_with_both_executors() {
    let fx = Fixture::load();
    let values = fx.values();
    let oracle = btreeset(oracle_partition(RuleVersion::V2026R1, &values));

    let rule = rule_for(RuleVersion::V2026R1).unwrap();
    let batch = batch_from_json_rows(&fx.column, &fixture_rows_json(&fx)).unwrap();
    let s = sort_groups(rule, &batch, RepresentativePolicy::FirstWins);
    let h = hash_groups(rule, &batch, RepresentativePolicy::FirstWins);

    let sort_part = btreeset(s.groups.iter().map(|g| g.rows.clone()).collect());
    let hash_part = btreeset(h.groups.iter().map(|g| g.rows.clone()).collect());
    assert_eq!(sort_part, oracle, "sort-agg vs independent oracle");
    assert_eq!(hash_part, oracle, "hash-agg vs independent oracle");
    assert_eq!(oracle.len(), fx.expected_under_2026R1.group_count);
}

#[test]
fn end_to_end_verdict_is_accepted_with_all_agreement_flags() {
    let fx = Fixture::load();
    let state = test_state();
    let verdict = run_comparison(&state, fx.request());
    assert!(
        verdict.accepted(),
        "expected accept, got failure {:?} diags {:?}",
        verdict.failure,
        verdict.diagnostics
    );
    let cmp = verdict.comparison.clone().expect("report present");
    assert!(cmp.partitions_agree);
    assert!(cmp.per_key_hashes_agree);
    assert!(cmp.representatives_agree);
    assert_eq!(cmp.sort_group_count, cmp.hash_group_count);
    assert_eq!(cmp.sort_group_count, cmp.oracle_group_count);
    assert_eq!(cmp.sort_group_count, fx.expected_under_2026R1.group_count);
    // Dedup list has one representative per class.
    assert_eq!(
        verdict.deduplicated.len(),
        fx.expected_under_2026R1.group_count
    );
    // Diagnostics carry the request id and never echo raw sensitive values in keys.
    assert!(!verdict.request_id.is_empty());
    assert!(verdict
        .diagnostics
        .iter()
        .all(|d| !d.request_id.is_empty() && !d.reason.is_empty()));
}

#[test]
fn r2_does_not_collapse_case_or_accent_and_oracle_confirms() {
    // Under 2026R2 the 5 cafe-row spellings split; oracle independently agrees.
    let fx = Fixture::load();
    let values = fx.values();
    let rule = rule_for(RuleVersion::V2026R2).unwrap();
    let batch = batch_from_json_rows(&fx.column, &fixture_rows_json(&fx)).unwrap();
    let s = sort_groups(rule, &batch, RepresentativePolicy::FirstWins);
    let h = hash_groups(rule, &batch, RepresentativePolicy::FirstWins);
    let oracle = btreeset(oracle_partition(RuleVersion::V2026R2, &values));
    assert_eq!(
        btreeset(s.groups.iter().map(|g| g.rows.clone()).collect()),
        oracle
    );
    assert_eq!(
        btreeset(h.groups.iter().map(|g| g.rows.clone()).collect()),
        oracle
    );
    // R2 produces strictly more groups than R1.
    assert!(s.group_count() > fx.expected_under_2026R1.group_count);
    // "cafe" and "CAFE" are separate under R2.
    assert_ne!(
        s.group_for_identity("cafe").unwrap().rows,
        s.group_for_identity("CAFE").unwrap().rows
    );
}

// --- helpers -------------------------------------------------------------------

fn fixture_rows_json(fx: &Fixture) -> Vec<u8> {
    let column = fx.column.as_str();
    let objs: Vec<serde_json::Value> = fx
        .rows
        .iter()
        .map(|r| serde_json::json!({ column: r.value }))
        .collect();
    serde_json::to_vec(&objs).unwrap()
}

fn btreeset(classes: Vec<Vec<usize>>) -> BTreeSet<Vec<usize>> {
    classes
        .into_iter()
        .map(|mut c| {
            c.sort_unstable();
            c
        })
        .collect()
}
