//! Golden-vector tests: expected byte layouts are hand-computed from
//! docs/FORMAT.md and hardcoded here — they are NOT generated by the codec
//! under test. These pin the wire format against accidental drift.

mod common;

use common::TestLog;
use rib::budget::DecodeBudget;
use rib::decode::decode_column;
use rib::encode::{encode_column, EncodeOptions};

/// BITPACK, 8 values [1..8], max 8 -> bit_width 4, one full group, 4 payload
/// bytes. Nibbles LSB-first: byte0 = 1 | 2<<4 = 0x21, byte1 = 0x43,
/// byte2 = 0x65, byte3 = 0x87.
const GOLDEN_BITPACK: [u8; 20] = [
    0x52, 0x49, 0x42, 0x31, // magic "RIB1"
    0x01, // version
    0x00, // mode BITPACK
    0x04, // bit_width 4
    0x00, // reserved
    0x08, 0x00, 0x00, 0x00, // value_count = 8
    0x04, 0x00, 0x00, 0x00, // payload_len = 4
    0x21, 0x43, 0x65, 0x87, // payload
];

/// RLE, three 9s: bit_width 4 -> 1 value byte; payload = run_len(4) + value(1).
const GOLDEN_RLE: [u8; 21] = [
    0x52, 0x49, 0x42, 0x31, // magic
    0x01, // version
    0x01, // mode RLE
    0x04, // bit_width 4
    0x00, // reserved
    0x03, 0x00, 0x00, 0x00, // value_count = 3
    0x05, 0x00, 0x00, 0x00, // payload_len = 5
    0x03, 0x00, 0x00, 0x00, // run_len = 3
    0x09, // value = 9
];

/// BITPACK with a partial tail group: 5 values [1,2,3,4,5], width 3,
/// one group padded to 8 values -> 3 payload bytes.
/// Derivation (LSB-first, each value's bit0 goes to the next free stream bit):
///   v=1 (001) -> bits 0,1,2   = 1,0,0
///   v=2 (010) -> bits 3,4,5   = 0,1,0
///   v=3 (011) -> bits 6,7,8   = 1,1,0
///   v=4 (100) -> bits 9,10,11 = 0,0,1
///   v=5 (101) -> bits 12,13,14= 1,0,1
///   padding   -> bits 15..23  = 0
///   byte0 = bits0..7  = 1+16+64+128      = 0xD1
///   byte1 = bits8..15 = 8+16+64          = 0x58
///   byte2 = bits16..23= 0                = 0x00
const GOLDEN_BITPACK_TAIL: [u8; 19] = [
    0x52, 0x49, 0x42, 0x31, 0x01, 0x00, 0x03, 0x00, // header part 1
    0x05, 0x00, 0x00, 0x00, // value_count = 5
    0x03, 0x00, 0x00, 0x00, // payload_len = 3
    0xD1, 0x58, 0x00, // payload
];

#[test]
fn golden_bitpack_full_group() {
    let log = TestLog::new("golden-bitpack");
    let values: Vec<u64> = (1..=8).collect();

    let encoded = encode_column(&values, &EncodeOptions::default());
    log.step("encode", &format!("bytes={:02x?}", encoded));
    assert_eq!(encoded, GOLDEN_BITPACK, "encoder wire format drifted");

    let decoded = decode_column(&GOLDEN_BITPACK, &DecodeBudget::default()).unwrap();
    assert_eq!(decoded, values);
    log.verdict(true, "hand-computed bytes == encoder output == decoder input");
}

#[test]
fn golden_rle_block() {
    let log = TestLog::new("golden-rle");
    // min_run default is 8, so force RLE by encoding a run of 9 directly.
    let values = vec![9u64; 9];
    let encoded = encode_column(&values, &EncodeOptions::default());
    log.step("encode", &format!("bytes={:02x?}", encoded));
    // 9 identical values -> one RLE block identical in shape to GOLDEN_RLE
    // except value_count/run_len are 9.
    let mut expected = GOLDEN_RLE;
    expected[8] = 9; // value_count
    expected[16] = 9; // run_len
    assert_eq!(encoded, expected, "encoder wire format drifted");

    let decoded = decode_column(&GOLDEN_RLE, &DecodeBudget::default()).unwrap();
    assert_eq!(decoded, vec![9u64, 9, 9]);
    log.verdict(true, "hand-computed RLE block decodes to three 9s");
}

#[test]
fn golden_bitpack_partial_tail_group() {
    let log = TestLog::new("golden-bitpack-tail");
    // The decoder must reproduce [1,2,3,4,5] from the hand-computed bytes
    // and must not emit the 3 zero padding values of the final group.
    let decoded = decode_column(&GOLDEN_BITPACK_TAIL, &DecodeBudget::default()).unwrap();
    log.step("decode", &format!("values={:?}", decoded));
    assert_eq!(decoded, vec![1u64, 2, 3, 4, 5]);

    let encoded = encode_column(&[1, 2, 3, 4, 5], &EncodeOptions::default());
    assert_eq!(encoded, GOLDEN_BITPACK_TAIL, "encoder wire format drifted");
    log.verdict(true, "partial tail group: 5 values out, padding not emitted");
}
