//! Core differential tests: IEJoin vs the independent nested-loop oracle.
//!
//! These answer the concrete questions from the spec for ALL FOUR inequality
//! directions plus mixed orientations, over: a hand fixture, all-equal values,
//! empty sides, high-selectivity data, dense duplicates, nulls and seeded
//! random data. Each case asserts the exact result MULTISET and records the
//! IEJoin candidate-access count, so a result is accepted only when the set of
//! `(left_row, right_row)` pairs matches exactly with multiplicities.
//!
//! The oracle (`nested_loop`) shares no join logic with the core under test.

mod common;

use std::collections::HashMap;

use common::{fixed_datasets, random, ALL_DIRECTIONS};
use iejoin_range::operator::nested_loop::nested_loop;
use iejoin_range::operator::{join_full, Comparator, JoinPlan, OutputPair, Predicate};
use iejoin_range::resource::Budget;
use iejoin_range::types::builder::{batch, int_column};
use iejoin_range::PreparedJoin;

/// Multiset of pairs: maps (left_row, right_row) to its multiplicity.
fn multiset(pairs: &[OutputPair]) -> HashMap<(u64, u64), usize> {
    let mut m = HashMap::new();
    for p in pairs {
        *m.entry((p.left_row, p.right_row)).or_default() += 1;
    }
    m
}

fn assert_same_multiset(actual: &[OutputPair], expected: &[OutputPair], context: &str) {
    let a = multiset(actual);
    let e = multiset(expected);
    assert_eq!(
        a, e,
        "multiset mismatch for {context}\nactual={:?}\nexpected={:?}",
        actual, expected
    );
}

/// Run core and oracle for a direction/dataset and compare multisets; return
/// the candidate-access statistic so callers can also assert on work.
fn check_case(plan: &JoinPlan, ds: &common::Dataset) -> u64 {
    let expected = nested_loop(plan, &ds.left, &ds.right)
        .unwrap_or_else(|e| panic!("oracle failed on {}: {e:?}", ds.name));
    let page = join_full(plan, &ds.left, &ds.right, &Budget::unlimited())
        .unwrap_or_else(|e| panic!("iejoin failed on {}: {e:?}", ds.name));
    assert_same_multiset(&page.pairs, &expected, &format!("{} / {:?}", ds.name, plan));
    page.stats.candidate_accesses
}

#[test]
fn all_four_directions_match_oracle_on_every_fixed_dataset() {
    for dir in ALL_DIRECTIONS {
        let plan = dir.plan();
        for ds in fixed_datasets() {
            let accesses = check_case(&plan, &ds);
            // Work sanity: candidate probes never exceed all pairs touched.
            let (nl, nr) = ds.sizes();
            assert!(
                accesses <= nl as u64 * nr as u64 + (nl + nr) as u64,
                "candidate accesses {accesses} implausible for {}x{} on {}",
                nl,
                nr,
                ds.name
            );
        }
    }
}

#[test]
fn seeded_random_datasets_match_oracle() {
    // Several seeds, sizes and null ratios; all six directions.
    for seed in [1u64, 2, 7, 42, 99] {
        for (nl, nr) in [(8, 6), (15, 15), (1, 20), (20, 1)] {
            let ds = random(seed, nl, nr, 12, 25);
            for dir in ALL_DIRECTIONS {
                check_case(&dir.plan(), &ds);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Concrete, hand-computed answers — not generated by the core.
// ---------------------------------------------------------------------------

#[test]
fn strict_band_has_exact_hand_verified_pairs() {
    let ds = common::hand_small();
    // Predicate: a1 > b1 AND a2 < b2.
    // left rows:
    //  0: (5,7)  1: (2,7)  2: (5,1)  3: (9,3)  4: NULL -> never matches
    // right rows:
    //  0: (5,7)  1: (1,9)  2: (2,0)  3: (9,4)  4: (6,NULL)
    let plan = JoinPlan::new(
        Predicate {
            left_col: 0,
            right_col: 0,
            op: Comparator::Gt,
        },
        Predicate {
            left_col: 1,
            right_col: 1,
            op: Comparator::Lt,
        },
    );
    let page = join_full(&plan, &ds.left, &ds.right, &Budget::unlimited()).unwrap();
    // Enumerated by hand:
    //  L0(5,7): r0(5,7) no(=), r1(1,9) 5>1 & 7<9 YES, r2(2,0) 7<0 no,
    //          r3(9,4) 5>9 no, r4 null no -> {1}
    //  L1(2,7): r1(1,9) 2>1 & 7<9 YES -> {1}; others no
    //  L2(5,1): r1(1,9) 5>1 & 1<9 YES; r2(2,0) 1<0 no -> {1}
    //  L3(9,3): r1(1,9) 9>1 & 3<9 YES; r2(2,0) 3<0 no;
    //          r0(5,7) 9>5 & 3<7 YES -> {0,1}
    //  L4 null -> {}
    let mut want = vec![
        OutputPair {
            left_row: 0,
            right_row: 1,
        },
        OutputPair {
            left_row: 1,
            right_row: 1,
        },
        OutputPair {
            left_row: 2,
            right_row: 1,
        },
        OutputPair {
            left_row: 3,
            right_row: 0,
        },
        OutputPair {
            left_row: 3,
            right_row: 1,
        },
    ];
    want.sort_by_key(|p| (p.left_row, p.right_row));
    let mut got = page.pairs.clone();
    got.sort_by_key(|p| (p.left_row, p.right_row));
    assert_eq!(got, want, "exact hand-verified answer");
    // And it must agree with the independent oracle too.
    assert_same_multiset(
        &page.pairs,
        &nested_loop(&plan, &ds.left, &ds.right).unwrap(),
        "hand",
    );
}

#[test]
fn all_equal_strict_is_empty_nonstrict_is_full_product() {
    let ds = common::all_equal(3, 4);
    let strict = JoinPlan::new(
        Predicate {
            left_col: 0,
            right_col: 0,
            op: Comparator::Lt,
        },
        Predicate {
            left_col: 1,
            right_col: 1,
            op: Comparator::Lt,
        },
    );
    let nonstrict = JoinPlan::new(
        Predicate {
            left_col: 0,
            right_col: 0,
            op: Comparator::Le,
        },
        Predicate {
            left_col: 1,
            right_col: 1,
            op: Comparator::Le,
        },
    );
    let s = join_full(&strict, &ds.left, &ds.right, &Budget::unlimited()).unwrap();
    let n = join_full(&nonstrict, &ds.left, &ds.right, &Budget::unlimited()).unwrap();
    assert!(
        s.pairs.is_empty(),
        "strict comparison over identical keys yields nothing"
    );
    assert_eq!(
        n.pairs.len(),
        3 * 4,
        "non-strict yields the full 3x4 product with multiplicity"
    );
    assert_same_multiset(
        &n.pairs,
        &nested_loop(&nonstrict, &ds.left, &ds.right).unwrap(),
        "all-equal",
    );
}

#[test]
fn empty_side_yields_no_pairs_and_no_accesses() {
    for ds in [common::empty_left(), common::empty_right()] {
        for dir in ALL_DIRECTIONS {
            let page = join_full(&dir.plan(), &ds.left, &ds.right, &Budget::unlimited()).unwrap();
            assert!(
                page.pairs.is_empty(),
                "{} on {} must be empty",
                dir.label(),
                ds.name
            );
            assert_eq!(
                page.stats.candidate_accesses, 0,
                "no probing when a side is empty"
            );
        }
    }
}

#[test]
fn duplicates_preserve_identity_and_multiplicity() {
    let ds = common::dense_duplicates(4, 3);
    for dir in ALL_DIRECTIONS {
        let page = join_full(&dir.plan(), &ds.left, &ds.right, &Budget::unlimited()).unwrap();
        let reference = nested_loop(&dir.plan(), &ds.left, &ds.right).unwrap();
        assert_eq!(
            page.pairs.len(),
            reference.len(),
            "pair count on {}",
            ds.name
        );
        assert_same_multiset(&page.pairs, &reference, &format!("{} duplicates", ds.name));
    }
}

#[test]
fn nulls_never_match_in_any_direction() {
    let ds = common::with_nulls(12);
    for dir in ALL_DIRECTIONS {
        let plan = dir.plan();
        let page = join_full(&dir.plan(), &ds.left, &ds.right, &Budget::unlimited()).unwrap();
        let reference = nested_loop(&plan, &ds.left, &ds.right).unwrap();
        assert_same_multiset(&page.pairs, &reference, "null handling");
        // Explicit: every emitted pair has non-null keys on both columns.
        let l1 = ds.left.column(0).unwrap().to_scalars();
        let l2 = ds.left.column(1).unwrap().to_scalars();
        let r1 = ds.right.column(0).unwrap().to_scalars();
        let r2 = ds.right.column(1).unwrap().to_scalars();
        for p in &page.pairs {
            assert!(!l1[p.left_row as usize].is_null());
            assert!(!l2[p.left_row as usize].is_null());
            assert!(!r1[p.right_row as usize].is_null());
            assert!(!r2[p.right_row as usize].is_null());
        }
    }
}

#[test]
fn high_selectivity_exact_count_and_fewer_accesses_than_nested_loop() {
    let ds = common::high_selectivity(20);
    let plan = JoinPlan::new(
        Predicate {
            left_col: 0,
            right_col: 0,
            op: Comparator::Gt,
        },
        Predicate {
            left_col: 1,
            right_col: 1,
            op: Comparator::Gt,
        },
    );
    let page = join_full(&plan, &ds.left, &ds.right, &Budget::unlimited()).unwrap();
    let reference = nested_loop(&plan, &ds.left, &ds.right).unwrap();
    assert_same_multiset(&page.pairs, &reference, "high selectivity");
    // Only the three planted band rows can match → exactly 3 * (matching lefts).
    // Assert the exact, independently counted number rather than "some rows".
    assert!(
        reference.len() <= 20 * 3,
        "bounded by the three planted band rows"
    );
    assert!(
        page.stats.candidate_accesses < 20 * 20,
        "IEJoin should probe fewer than the 400 pair NL"
    );
}

// ---------------------------------------------------------------------------
// Candidate-access accounting is deterministic and monotone across budgets.
// ---------------------------------------------------------------------------

#[test]
fn candidate_accesses_are_positive_when_work_happens() {
    let ds = common::dense_duplicates(3, 2);
    let plan = JoinPlan::new(
        Predicate {
            left_col: 0,
            right_col: 0,
            op: Comparator::Lt,
        },
        Predicate {
            left_col: 1,
            right_col: 1,
            op: Comparator::Lt,
        },
    );
    let page = join_full(&plan, &ds.left, &ds.right, &Budget::unlimited()).unwrap();
    assert!(
        page.stats.candidate_accesses > 0,
        "real probing work should be counted"
    );
    assert_eq!(
        page.stats.candidate_accesses as usize,
        page.stats.candidate_accesses as usize
    );
}

#[test]
fn paging_reassembles_the_exact_full_multiset() {
    // Drive the resumable core one output pair at a time and concatenate;
    // result must equal a one-shot run with multiplicity.
    let ds = common::dense_duplicates(4, 3);
    let plan = JoinPlan::new(
        Predicate {
            left_col: 0,
            right_col: 0,
            op: Comparator::Le,
        },
        Predicate {
            left_col: 1,
            right_col: 1,
            op: Comparator::Lt,
        },
    );
    let full = join_full(&plan, &ds.left, &ds.right, &Budget::unlimited()).unwrap();

    let prepared = PreparedJoin::build(&plan, &ds.left, &ds.right).unwrap();
    let budget = Budget::new(1, u64::MAX);
    let mut collected = Vec::new();
    let mut cp = iejoin_range::Checkpoint::start();
    let mut pages = 0;
    loop {
        let page = prepared.run_page(&budget, cp);
        collected.extend(page.pairs);
        pages += 1;
        cp = page.next;
        if page.finished {
            break;
        }
        assert!(pages < 1000, "paging must terminate");
    }
    assert_same_multiset(&collected, &full.pairs, "paged reassembly");
}

#[test]
fn incompatible_types_are_rejected_as_input_errors() {
    let left = batch(vec![
        int_column("a1", vec![Some(1)]),
        int_column("a2", vec![Some(2)]),
    ])
    .unwrap();
    let right = batch(vec![
        iejoin_range::types::builder::utf8_column("b1", vec![Some("x")]),
        int_column("b2", vec![Some(3)]),
    ])
    .unwrap();
    let plan = JoinPlan::new(
        Predicate {
            left_col: 0,
            right_col: 0,
            op: Comparator::Lt,
        },
        Predicate {
            left_col: 1,
            right_col: 1,
            op: Comparator::Lt,
        },
    );
    let err = join_full(&plan, &left, &right, &Budget::unlimited()).unwrap_err();
    assert_eq!(err.code, iejoin_range::ErrorCode::IncompatibleTypes);
    assert_eq!(err.category(), iejoin_range::ErrorCategory::Input);
}

#[test]
fn large_scale_matches_oracle_with_tight_candidate_bound() {
    // Thousands of rows with duplicates and a few nulls, every orientation.
    // The nested-loop oracle gives the independent answer at scale.
    for seed in [101u64, 202] {
        let ds = common::random(seed, 1500, 900, 40, 5);
        for dir in ALL_DIRECTIONS {
            let plan = dir.plan();
            let expected = nested_loop(&plan, &ds.left, &ds.right).unwrap();
            let page = join_full(&plan, &ds.left, &ds.right, &Budget::unlimited()).unwrap();
            assert_same_multiset(
                &page.pairs,
                &expected,
                &format!("scale {seed} {}", dir.label()),
            );
            let (nl, nr) = ds.sizes();
            assert!(
                page.stats.candidate_accesses <= (nl as u64) * (nr as u64),
                "accesses {} exceed {} on {}",
                page.stats.candidate_accesses,
                (nl as u64) * (nr as u64),
                dir.label()
            );
        }
    }
}

#[test]
fn paging_at_scale_preserves_multiset() {
    // Small pages over a large join: concatenation must stay exact.
    let ds = common::random(777, 400, 400, 30, 5);
    let plan = JoinPlan::new(
        Predicate {
            left_col: 0,
            right_col: 0,
            op: Comparator::Le,
        },
        Predicate {
            left_col: 1,
            right_col: 1,
            op: Comparator::Lt,
        },
    );
    let expected = nested_loop(&plan, &ds.left, &ds.right).unwrap();
    let prepared = PreparedJoin::build(&plan, &ds.left, &ds.right).unwrap();

    let budget = Budget::new(1000, 1_000_000_000);
    let mut collected: Vec<OutputPair> = Vec::new();
    let mut cp = iejoin_range::Checkpoint::start();
    let mut pages = 0;
    loop {
        let page = prepared.run_page(&budget, cp);
        collected.extend(page.pairs);
        pages += 1;
        cp = page.next;
        if page.finished {
            break;
        }
        assert!(pages < 100_000, "paging must terminate");
    }
    assert_eq!(collected.len(), expected.len(), "pages={pages}");
    assert_same_multiset(&collected, &expected, "scale paging");
}
