//! Independent cross-checks: the reasoning core is compared against
//! brute-force truth-table enumeration (a separate code path) and
//! against hand-computed reference values written into this file.

use dmc::check::brute_force_count;
use dmc::config::Config;
use dmc::count::count_models;
use dmc::proof::ValidationProof;
use dmc::syntax::{Circuit, Node};
use dmc::validate::validate;
use num_bigint::BigUint;
use std::collections::BTreeSet;

fn lit(id: u32, var: u32, phase: bool) -> Node {
    Node::Lit { id, var, phase }
}

fn universe(max_var: u32) -> BTreeSet<u32> {
    (1..=max_var).collect()
}

/// (name, circuit, declared max var, hand-computed expected count)
fn cases() -> Vec<(&'static str, Circuit, u32, u64)> {
    vec![
        // x1 : 1 model over {1}
        ("lit", Circuit { root: 0, nodes: vec![lit(0, 1, true)] }, 1, 1),
        // x1 OR (NOT x1 AND x2): 3 models over {1,2}
        (
            "or_split",
            Circuit {
                root: 0,
                nodes: vec![
                    Node::Or {
                        id: 0,
                        children: vec![1, 2],
                    },
                    lit(1, 1, true),
                    Node::And {
                        id: 2,
                        children: vec![3, 4],
                    },
                    lit(3, 1, false),
                    lit(4, 2, true),
                ],
            },
            2,
            3,
        ),
        // (x1 OR NOT x1) AND (x2 OR NOT x2): 4 models over {1,2}
        (
            "two_tautologies",
            Circuit {
                root: 0,
                nodes: vec![
                    Node::And {
                        id: 0,
                        children: vec![1, 2],
                    },
                    Node::Or {
                        id: 1,
                        children: vec![3, 4],
                    },
                    Node::Or {
                        id: 2,
                        children: vec![5, 6],
                    },
                    lit(3, 1, true),
                    lit(4, 1, false),
                    lit(5, 2, true),
                    lit(6, 2, false),
                ],
            },
            2,
            4,
        ),
        // XNOR over {1,2}: assignments 00 and 11 -> 2 models
        (
            "xnor",
            Circuit {
                root: 0,
                nodes: vec![
                    Node::Or {
                        id: 0,
                        children: vec![1, 2],
                    },
                    Node::And {
                        id: 1,
                        children: vec![3, 4],
                    },
                    Node::And {
                        id: 2,
                        children: vec![5, 6],
                    },
                    lit(3, 1, true),
                    lit(4, 2, true),
                    lit(5, 1, false),
                    lit(6, 2, false),
                ],
            },
            2,
            2,
        ),
        // (x1 OR (NOT x1 AND x2)) AND (x3 OR NOT x3): 3*2 = 6 over {1,2,3}
        (
            "and_of_ors",
            Circuit {
                root: 0,
                nodes: vec![
                    Node::And {
                        id: 0,
                        children: vec![1, 2],
                    },
                    Node::Or {
                        id: 1,
                        children: vec![3, 4],
                    },
                    Node::Or {
                        id: 2,
                        children: vec![5, 6],
                    },
                    lit(3, 1, true),
                    Node::And {
                        id: 4,
                        children: vec![7, 8],
                    },
                    lit(5, 3, true),
                    lit(6, 3, false),
                    lit(7, 1, false),
                    lit(8, 2, true),
                ],
            },
            3,
            6,
        ),
        // TRUE over {1,2,3,4}: 16 models
        ("true_4", Circuit { root: 0, nodes: vec![Node::True { id: 0 }] }, 4, 16),
        // FALSE over {1,2}: 0 models
        ("false_2", Circuit { root: 0, nodes: vec![Node::False { id: 0 }] }, 2, 0),
    ]
}

#[test]
fn core_matches_brute_force_and_hand_reference() {
    for (name, circuit, max_var, expected) in cases() {
        let vars = universe(max_var);
        // Reference 1: hand-computed value above (not generated by core).
        // Reference 2: independent brute-force enumeration module.
        let brute = brute_force_count(&circuit, &vars);
        assert_eq!(
            brute,
            BigUint::from(expected),
            "case {name}: brute-force disagrees with hand reference"
        );
        // Core under test: validate, then count.
        let proof = validate(&circuit, &Config::default())
            .unwrap_or_else(|e| panic!("case {name}: should validate, got {e:?}"));
        let out = count_models(&circuit, &vars, name, proof);
        assert_eq!(
            out.total, brute,
            "case {name}: core count disagrees with brute force"
        );
        assert_eq!(
            out.total,
            BigUint::from(expected),
            "case {name}: core count disagrees with hand reference"
        );
    }
}

#[test]
fn truth_table_spot_check() {
    // Circuit: x1 OR (NOT x1 AND x2). Full truth table over {1,2}:
    //   x1 x2 | value
    //    0  0 | 0
    //    0  1 | 1
    //    1  0 | 1
    //    1  1 | 1
    let c = Circuit {
        root: 0,
        nodes: vec![
            Node::Or {
                id: 0,
                children: vec![1, 2],
            },
            lit(1, 1, true),
            Node::And {
                id: 2,
                children: vec![3, 4],
            },
            lit(3, 1, false),
            lit(4, 2, true),
        ],
    };
    let table = [
        (false, false, false),
        (false, true, true),
        (true, false, true),
        (true, true, true),
    ];
    for (x1, x2, want) in table {
        let got = c.eval(c.root, &|v| match v {
            1 => x1,
            2 => x2,
            _ => false,
        });
        assert_eq!(got, want, "x1={x1} x2={x2}");
    }
    // And the brute-force module must count exactly the 3 true rows.
    assert_eq!(brute_force_count(&c, &universe(2)), BigUint::from(3u64));
}

#[test]
fn proof_record_accounts_for_everything() {
    // The proof of a validated circuit must explain the final count:
    // top-level smoothing plus per-node raw counts.
    let c = Circuit {
        root: 0,
        nodes: vec![lit(0, 1, true)],
    };
    let vars = universe(5);
    let out = count_models(&c, &vars, "proof-check", ValidationProof::default());
    assert_eq!(out.proof.top_smooth_exp, 4);
    assert_eq!(out.total, BigUint::from(16u64));
    let entry = out
        .proof
        .entries
        .iter()
        .find(|e| e.node == 0)
        .expect("root entry");
    assert_eq!(entry.raw_count, "1");
    assert_eq!(entry.scope, vec![1]);
    // JSON round-trip keeps the record intact.
    let json = out.proof.to_json();
    let back: dmc::proof::ProofRecord = serde_json::from_str(&json).expect("proof json");
    assert_eq!(back.total, "16");
    assert_eq!(back.request_id, "proof-check");
}
