//! Interop tests: the Rust chunker is checked against fixtures/vectors.json,
//! which is generated by tools/reference_chunker.py — an INDEPENDENT Python
//! implementation that shares no code with the core under test.

use cdc_service::chunker::{chunk_buffer, ChunkParams};
use cdc_service::error::ErrorCategory;
use cdc_service::format;
use cdc_service::manifest::Manifest;
use cdc_service::recovery;
use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::path::PathBuf;

#[derive(Deserialize)]
struct VectorFile {
    algorithm: String,
    cases: Vec<VectorCase>,
}

#[derive(Deserialize)]
struct VectorCase {
    name: String,
    params: ParamsJson,
    payload_file: String,
    payload_len: usize,
    payload_sha256: String,
    chunks: Vec<ChunkJson>,
}

#[derive(Deserialize)]
struct ParamsJson {
    min_size: usize,
    max_size: usize,
    mask_bits: u32,
    pattern: u64,
}

#[derive(Deserialize)]
struct ChunkJson {
    offset: u64,
    len: u32,
    sha256: String,
}

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures")
}

fn load_vectors() -> VectorFile {
    let text = std::fs::read_to_string(fixtures_dir().join("vectors.json"))
        .expect("fixtures/vectors.json missing — run tools/reference_chunker.py --generate-vectors fixtures");
    serde_json::from_str(&text).unwrap()
}

#[test]
fn rust_chunker_matches_python_reference_vectors() {
    let vectors = load_vectors();
    assert_eq!(vectors.algorithm, "gear64-cdc-v1");
    assert!(vectors.cases.len() >= 6, "expected a meaningful vector set");

    for case in &vectors.cases {
        let payload = std::fs::read(fixtures_dir().join(&case.payload_file)).unwrap();
        assert_eq!(payload.len(), case.payload_len, "{}: payload length", case.name);
        assert_eq!(
            hex::encode(Sha256::digest(&payload)),
            case.payload_sha256,
            "{}: payload digest (fixture file corrupted?)",
            case.name
        );

        let params = ChunkParams {
            min_size: case.params.min_size,
            max_size: case.params.max_size,
            mask_bits: case.params.mask_bits,
            pattern: case.params.pattern,
        };
        let chunks = chunk_buffer(params, &payload).unwrap();

        assert_eq!(
            chunks.len(),
            case.chunks.len(),
            "{}: chunk count differs from Python reference",
            case.name
        );
        for (i, (got, want)) in chunks.iter().zip(case.chunks.iter()).enumerate() {
            assert_eq!(got.offset, want.offset, "{}: chunk {i} offset", case.name);
            assert_eq!(got.len, want.len, "{}: chunk {i} len", case.name);
            let digest = hex::encode(Sha256::digest(
                &payload[got.offset as usize..(got.offset + got.len as u64) as usize],
            ));
            assert_eq!(digest, want.sha256, "{}: chunk {i} digest", case.name);
        }
    }
}

#[test]
fn container_round_trip_on_every_vector_case() {
    let vectors = load_vectors();
    for case in &vectors.cases {
        let payload = std::fs::read(fixtures_dir().join(&case.payload_file)).unwrap();
        let params = ChunkParams {
            min_size: case.params.min_size,
            max_size: case.params.max_size,
            mask_bits: case.params.mask_bits,
            pattern: case.params.pattern,
        };
        let chunks = chunk_buffer(params, &payload).unwrap();
        let manifest = Manifest::for_params(params);
        let encoded = format::encode(&manifest, &chunks, &payload);
        let rec = recovery::recover(&encoded, Some(&payload))
            .unwrap_or_else(|e| panic!("{}: honest container must recover: {e}", case.name));
        assert_eq!(rec.payload, payload, "{}: recovered bytes", case.name);
        assert_eq!(rec.chunks, chunks, "{}: recovered chunk map", case.name);
    }
}

#[test]
fn tampered_container_fails_with_digest_mismatch_category() {
    let vectors = load_vectors();
    let case = vectors
        .cases
        .iter()
        .find(|c| c.name == "random")
        .expect("random case exists");
    let payload = std::fs::read(fixtures_dir().join(&case.payload_file)).unwrap();
    let params = ChunkParams {
        min_size: case.params.min_size,
        max_size: case.params.max_size,
        mask_bits: case.params.mask_bits,
        pattern: case.params.pattern,
    };
    let chunks = chunk_buffer(params, &payload).unwrap();
    let mut encoded = format::encode(&Manifest::for_params(params), &chunks, &payload);

    // Flip one payload byte (last byte of the container is payload).
    let last = encoded.len() - 1;
    encoded[last] ^= 0x01;
    let err = recovery::recover(&encoded, None).unwrap_err();
    assert_eq!(err.category, ErrorCategory::DigestMismatch);

    // Truncate the container.
    let truncated = &encoded[..encoded.len() / 2];
    let err = recovery::recover(truncated, None).unwrap_err();
    assert_eq!(err.category, ErrorCategory::MalformedContainer);
}
