"""Independent brute-force oracle for small time grids.

This reference implementation is deliberately **separate from the code under
test**: it imports only the parsed ``Problem`` data classes and re-derives
feasibility with a different method than ``tplan.simulator``:

* occupancy is computed by closed-interval summation at every grid point
  instead of event-counters,
* state is produced by a time-stepped loop instead of grouped event objects,
* candidate schedules are enumerated exhaustively from start-time tuples.

The test-suite cross-checks the search kernel against this oracle, so a
reference answer is never generated by the kernel it is meant to validate.
"""

from __future__ import annotations

from fractions import Fraction
from itertools import combinations_with_replacement, product

from tplan.model import Problem, ResourceKind, ScheduledAction

# An instance is (action_id, start, end).
Instance = tuple[str, int, int]


class OracleVerdict:
    FEASIBLE = "feasible"
    START_CONDITION = "start_condition_violated"
    INVARIANT = "invariant_violated"
    RESOURCE = "resource_conflict"
    SIMULTANEOUS = "simultaneous_conflict"


def enumerate_schedules(problem: Problem, max_repeats: int = 2) -> list[list[Instance]]:
    """All candidate schedules (each action used 0..max_repeats times)."""
    options_per_action: list[list[tuple[int, ...]]] = []
    for aid in problem.action_order:
        duration = problem.actions[aid].duration
        starts = list(range(0, problem.horizon - duration + 1))
        choices: list[tuple[int, ...]] = [()]
        for r in range(1, max_repeats + 1):
            for combo in combinations_with_replacement(starts, r):
                choices.append(combo)
        options_per_action.append(choices)

    out: list[list[Instance]] = []
    for pick in product(*options_per_action):
        schedule: list[Instance] = []
        for aid, starts in zip(problem.action_order, pick):
            d = problem.actions[aid].duration
            for s in starts:
                schedule.append((aid, s, s + d))
        out.append(schedule)
    return out


def check_schedule(problem: Problem, instances: list[Instance]) -> tuple[str, int | None]:
    """Independent feasibility check. Returns (verdict, failing_time).

    Detection order deliberately matches the simulator's deterministic event
    order at each grid point (ends, tick, start-condition, resource debit,
    capacity, invariants), so schedules with several defects report the same
    *first* failure category. The implementation remains independent:
    renewable occupancy is re-derived by closed summation at every point.
    """
    h = problem.horizon

    # --- structural simultaneity rules (half-open interval policy) --------
    start_map: dict[int, str] = {}
    end_map: dict[int, str] = {}
    for aid, s, e in instances:
        if s == e:  # zero-duration TICK owns the instant as start and end
            for bucket, label in ((start_map, "start"), (end_map, "end")):
                if s in bucket:
                    return OracleVerdict.SIMULTANEOUS, s
            start_map[s] = aid
            end_map[s] = aid
        else:
            if s in start_map:
                return OracleVerdict.SIMULTANEOUS, s
            if e in end_map:
                return OracleVerdict.SIMULTANEOUS, e
            start_map[s] = aid
            end_map[e] = aid

    ticks = {s for aid, s, e in instances if s == e}

    state: dict[str, Fraction] = dict(problem.fluents)
    consumable = {
        rid: res.capacity
        for rid, res in problem.resources.items()
        if res.kind is ResourceKind.CONSUMABLE
    }
    by_end: dict[int, list[str]] = {}
    by_start: dict[int, list[str]] = {}
    for aid, s, e in instances:
        by_end.setdefault(e, []).append(aid)
        by_start.setdefault(s, []).append(aid)

    for t in range(h + 1):
        # 1. ends first: effects and consumable credits (release cannot fail).
        for aid in by_end.get(t, []):
            if problem.actions[aid].duration == 0:
                continue
            for eff in problem.actions[aid].effects:
                state[eff.fluent] = eff.apply(state[eff.fluent])
            for rid, qty in problem.actions[aid].resource_use.items():
                if rid in consumable:
                    consumable[rid] += qty

        # 2. zero-duration tick (at most one by construction).
        if t in ticks:
            act = problem.actions[start_map[t]]
            if not all(c.evaluate(state) for c in act.start_condition):
                return OracleVerdict.START_CONDITION, t
            for rid, qty in act.resource_use.items():
                if rid in consumable and consumable[rid] - qty < 0:
                    return OracleVerdict.RESOURCE, t
            for rid, qty in act.resource_use.items():
                if rid in consumable:
                    consumable[rid] -= qty
            for eff in act.effects:
                state[eff.fluent] = eff.apply(state[eff.fluent])
            for rid, qty in act.resource_use.items():
                if rid in consumable:
                    consumable[rid] += qty
            if not all(c.evaluate(state) for c in act.invariant):
                return OracleVerdict.INVARIANT, t

        # 3. positive-duration start (at most one by construction):
        #    condition before debit, then capacity.
        for aid in by_start.get(t, []):
            act = problem.actions[aid]
            if act.duration == 0:
                continue
            if not all(c.evaluate(state) for c in act.start_condition):
                return OracleVerdict.START_CONDITION, t
            for rid, qty in act.resource_use.items():
                if rid in consumable and consumable[rid] - qty < 0:
                    return OracleVerdict.RESOURCE, t
                if rid not in consumable:
                    res = problem.resources[rid]
                    used = sum(
                        problem.actions[a2].resource_use.get(rid, 0)
                        for a2, s2, e2 in instances
                        if s2 <= t < e2
                    )
                    if used > res.capacity:
                        return OracleVerdict.RESOURCE, t
            for rid, qty in act.resource_use.items():
                if rid in consumable:
                    consumable[rid] -= qty

        # 4. invariants of every positive-duration action alive at t: [s, e)
        for aid, s, e in instances:
            if s <= t < e:
                if not all(c.evaluate(state) for c in problem.actions[aid].invariant):
                    return OracleVerdict.INVARIANT, t

    return OracleVerdict.FEASIBLE, None


def goal_time(problem: Problem, instances: list[Instance]) -> int | None:
    """Completion time if the goal holds once every action has finished.

    Under completion semantics the answer is either the schedule's last end
    instant (goal holds in the post-completion state) or ``None``.
    """
    h = problem.horizon
    completion = max((e for _, _, e in instances), default=0)
    state: dict[str, Fraction] = dict(problem.fluents)
    ticks = {s for aid, s, e in instances if s == e}
    start_map = {s: aid for aid, s, e in instances if s == e}
    by_end: dict[int, list[str]] = {}
    for aid, s, e in instances:
        by_end.setdefault(e, []).append(aid)

    for t in range(completion + 1):
        for aid in by_end.get(t, []):
            if problem.actions[aid].duration == 0:
                continue
            for eff in problem.actions[aid].effects:
                state[eff.fluent] = eff.apply(state[eff.fluent])
        if t in ticks:
            for eff in problem.actions[start_map[t]].effects:
                state[eff.fluent] = eff.apply(state[eff.fluent])
    return completion if problem.goal.evaluate(state) else None


def optimal(problem: Problem, max_repeats: int = 2) -> tuple[int, int] | None:
    """Return (minimum action count, earliest goal time) or None if UNSAT."""
    best: tuple[int, int] | None = None
    for instances in enumerate_schedules(problem, max_repeats=max_repeats):
        verdict, _ = check_schedule(problem, instances)
        if verdict is not OracleVerdict.FEASIBLE:
            continue
        gt = goal_time(problem, instances)
        if gt is None:
            continue
        cand = (len(instances), gt)
        if best is None or cand < best:
            best = cand
    return best


def to_scheduled(instances: list[Instance]) -> list[ScheduledAction]:
    return [ScheduledAction(aid, s, e) for aid, s, e in instances]
