"""Independent brute-force oracle.

NOTHING in this module imports from :mod:`wfst_service.core` -- reference
answers must never be generated by the code under test.  It works on raw
state/arc tuples and enumerates paths by depth-first search.

Termination with positive-cost epsilon-output loops
---------------------------------------------------
The synthetic fixtures intentionally contain epsilon *insertion* loops
(emit a character without consuming input), so the relation can be
infinite even for a finite input.  Enumeration is bounded by limiting how
many times a configuration ``(state, input_position)`` may be revisited
along one DFS root-to-node chain.  Every truncation records the path cost
at the cut frontier; the oracle first asserts that every input-epsilon
arc has non-negative weight, therefore every cut descendant costs at
least the frontier cost.  Tests compare that frontier against the k-th
best cost: when the frontier is strictly more expensive, truncation is
provably irrelevant for the top-k comparison.
"""

from __future__ import annotations

from dataclasses import dataclass

EPS = ""


@dataclass(frozen=True)
class RawFst:
    start: int
    finals: dict[int, float]
    arcs: tuple[tuple[int, int, str, str, float], ...]


def _normalize(label: str) -> str:
    return "" if label == "<eps>" else label


def raw_from_spec_body(body: dict) -> RawFst:
    arcs = tuple(
        (
            int(a["src"]),
            int(a["dst"]),
            _normalize(a["in"]),
            _normalize(a["out"]),
            float(a.get("cost", 0.0)),
        )
        for a in body.get("arcs", [])
    )
    finals = {int(f["state"]): float(f.get("cost", 0.0)) for f in body["finals"]}
    return RawFst(start=int(body["start"]), finals=finals, arcs=arcs)


@dataclass
class Enumeration:
    best: dict[str, float]
    cut_frontier: float  # inf if no truncation happened
    nonneg_weights: bool


def enumerate_relation(
    fst: RawFst,
    text: str,
    *,
    max_revisits: int = 6,
    max_steps: int = 2_000_000,
) -> Enumeration:
    """Minimum cost per distinct output for consuming exactly ``text``."""
    best: dict[str, float] = {}
    state = {"steps": 0, "cut": float("inf")}

    nonneg = all(w >= 0.0 for _s, _d, _i, _o, w in fst.arcs) and all(
        w >= 0.0 for w in fst.finals.values()
    )

    def dfs(
        st: int,
        pos: int,
        emitted: str,
        cost: float,
        visits: dict[tuple[int, int], int],
    ) -> None:
        state["steps"] += 1
        assert state["steps"] < max_steps, "oracle step cap bound"

        if pos == len(text) and st in fst.finals:
            total = cost + fst.finals[st]
            prev = best.get(emitted)
            if prev is None or total < prev:
                best[emitted] = total

        for _src, dst, ilab, olab, w in fst.arcs:
            if _src != st:
                continue
            if ilab != EPS:
                if pos < len(text) and text[pos] == ilab:
                    key = (dst, pos + 1)
                    visits2 = dict(visits)
                    visits2[key] = visits.get(key, 0) + 1
                    if visits2[key] > max_revisits:
                        state["cut"] = min(state["cut"], cost + w)
                        continue
                    dfs(
                        dst,
                        pos + 1,
                        emitted + ("" if olab == EPS else olab),
                        cost + w,
                        visits2,
                    )
            else:
                key = (dst, pos)
                count = visits.get(key, 0) + 1
                if count > max_revisits:
                    state["cut"] = min(state["cut"], cost + w)
                    continue
                visits2 = dict(visits)
                visits2[key] = count
                dfs(
                    dst,
                    pos,
                    emitted + ("" if olab == EPS else olab),
                    cost + w,
                    visits2,
                )

    dfs(fst.start, 0, "", 0.0, {(fst.start, 0): 1})
    return Enumeration(
        best=best, cut_frontier=state["cut"], nonneg_weights=nonneg
    )


def compose_relations(
    left: Enumeration,
    right: RawFst,
    *,
    max_middle_len: int = 10,
    max_revisits: int = 6,
) -> Enumeration:
    """Independent relational composition through middle strings.

    No transducer code is used: the left relation is a plain
    output->cost map; each middle string is enumerated through the right
    machine from scratch, and costs summed and minimised.  The cut
    frontier is the cheapest composed cost that truncation could hide.
    """
    composed: dict[str, float] = {}
    cut = float("inf")
    for middle, cost_l in left.best.items():
        if len(middle) > max_middle_len:
            cut = min(cut, cost_l)
            continue
        enumeration = enumerate_relation(
            right, middle, max_revisits=max_revisits
        )
        if enumeration.cut_frontier != float("inf"):
            cut = min(cut, cost_l + enumeration.cut_frontier)
        for output, cost_r in enumeration.best.items():
            total = cost_l + cost_r
            prev = composed.get(output)
            if prev is None or total < prev:
                composed[output] = total
    if left.cut_frontier != float("inf"):
        cut = min(cut, left.cut_frontier)
    return Enumeration(best=composed, cut_frontier=cut, nonneg_weights=True)


def kbest_reference(
    relation: dict[str, float],
    k: int,
) -> list[tuple[str, float]]:
    """Exact expected ordering: (cost asc, output lexicographic asc)."""
    return sorted(relation.items(), key=lambda kv: (kv[1], kv[0]))[:k]


def assert_topk_exact(
    enumeration: Enumeration,
    actual: list[tuple[str, float]],
    *,
    tol: float = 1e-9,
) -> None:
    """Assert SUT top-k matches the oracle and truncation was irrelevant."""
    k = len(actual)
    expected = kbest_reference(enumeration.best, k)
    assert len(actual) == len(expected), (
        f"result count mismatch: oracle={len(expected)} actual={len(actual)}"
    )
    for (eo, ec), (ao, ac) in zip(expected, actual):
        assert eo == ao, f"output mismatch: oracle={eo!r} actual={ao!r}"
        assert abs(ec - ac) <= tol, f"cost mismatch for {eo!r}: {ec} vs {ac}"
    if expected:
        kth = expected[-1][1]
        assert enumeration.cut_frontier > kth + tol, (
            f"oracle truncation frontier {enumeration.cut_frontier:g} is not "
            f"strictly above k-th cost {kth:g}; reference answer would not "
            "be provably exact"
        )
