"""Independent reference oracle for cross-checking the estimation kernel.

NOTHING here imports ``app.kernel``. Every quantity is re-derived from raw
matrix primitives so that the test answers are not generated by the code under
test. An optional comparison against the mature ``linearmodels`` package is
provided separately and self-skips when that package is unavailable.

Notation: structural model y = [1, W] gamma + X beta + e; full instrument set
Zm = [1, W, Z].
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy import stats


@dataclass(frozen=True)
class OracleIV:
    beta: np.ndarray
    vcv_conventional: np.ndarray
    vcv_robust: np.ndarray
    vcv_naive_second_stage: np.ndarray
    residuals: np.ndarray
    second_stage_residuals_wrong: np.ndarray
    first_stage_pi: np.ndarray
    cragg_donald: float
    partial_f: np.ndarray
    sargan: float
    gmm_beta: np.ndarray
    hansen_j: float
    dwh_stat: float


def _proj(a: np.ndarray) -> np.ndarray:
    """Orthogonal projection P_A = A(A'A)^-1 A' (via QR for stability)."""
    q, _ = np.linalg.qr(a, mode="reduced")
    return q @ q.T


def oracle_iv(
    y: np.ndarray, X: np.ndarray, W: np.ndarray, Z: np.ndarray,
    *, add_constant: bool = True,
) -> OracleIV:
    n = y.shape[0]
    ones = np.ones((n, 1))
    Q = np.hstack([ones, W]) if add_constant else W
    Zm = np.hstack([Q, Z])
    R = np.hstack([Q, X])
    k_total = R.shape[1]
    K, L, J = X.shape[1], Z.shape[1], Q.shape[1]

    Pz = _proj(Zm)

    # Correct IV/2SLS estimator.
    rhs = R.T @ Pz @ R
    score = R.T @ Pz @ y
    beta = np.linalg.solve(rhs, score)
    u = y - R @ beta                      # structural residuals, original X

    s2 = float(u @ u) / (n - k_total)
    vcv_conv = s2 * np.linalg.inv(rhs)

    # Robust 2SLS sandwich: (R'PzR)^-1 (Rhat' diag(u^2) Rhat) (R'PzR)^-1
    # with Rhat = Pz R -- BOTH sides of the meat carry Pz.
    rhs_inv = np.linalg.inv(rhs)
    r_hat = Pz @ R
    meat = r_hat.T @ ((u[:, None] ** 2) * r_hat)
    vcv_rob = (n / (n - k_total)) * rhs_inv @ meat @ rhs_inv

    # Naive (WRONG) second-stage OLS: refit OLS on fitted R using its own
    # residuals. Numerator happens to equal rhs; the difference is the
    # residual scale -- this is the exact mistake the brief forbids.
    pi = np.linalg.solve(Zm.T @ Zm, Zm.T @ X)
    Xhat = Zm @ pi
    Rhat = np.hstack([Q, Xhat])
    u_wrong = y - Rhat @ beta
    s2_wrong = float(u_wrong @ u_wrong) / (n - k_total)
    vcv_naive = s2_wrong * np.linalg.inv(Rhat.T @ Rhat)

    # Cragg-Donald via Frisch-Waugh residualization off Q.
    Mq = np.eye(n) - _proj(Q) if J else np.eye(n)
    Xd = Mq @ X
    Zd = Mq @ Z
    pi_d = np.linalg.solve(Zd.T @ Zd, Zd.T @ Xd)
    Xhd = Zd @ pi_d
    E = Xhd.T @ Xhd
    Rm = Xd.T @ Xd - E
    eigvals = np.linalg.eigvals(np.linalg.solve(Rm, E)).real
    cd = float((n - J - L) / L * eigvals.min())

    df = n - J - L
    ssr_r = np.sum(Xd**2, axis=0)
    ssr_ur = np.sum((Xd - Xhd) ** 2, axis=0)
    partial_f = ((ssr_r - ssr_ur) / L) / (ssr_ur / df)

    # Sargan (homoskedastic over-id score).
    sargan = float(n * (u @ Pz @ u) / (u @ u))

    # Independently coded two-step efficient GMM + Hansen J.
    # Step 1 weight is built from 2SLS residuals; step 2 solves with it and
    # the J statistic reuses that SAME weight (standard two-step convention).
    g_bar = Zm.T @ R / n
    h_bar = Zm.T @ y / n
    u0 = y - R @ beta
    s1 = Zm.T @ ((u0[:, None] ** 2) * Zm) / n
    s1_inv = np.linalg.inv(s1)
    b_gmm = np.linalg.solve(g_bar.T @ s1_inv @ g_bar, g_bar.T @ s1_inv @ h_bar)
    u2 = y - R @ b_gmm
    g_final = Zm.T @ u2 / n
    hansen = float(n * g_final @ s1_inv @ g_final)

    # DWH augmented regression: add V = X - Xhat, test its K coefficients.
    V = X - Xhat
    A = np.hstack([R, V])
    b_a = np.linalg.solve(A.T @ A, A.T @ y)
    ua = y - A @ b_a
    s2_a = float(ua @ ua) / (n - A.shape[1])
    vcv_a = s2_a * np.linalg.inv(A.T @ A)
    theta = b_a[-K:]
    dwh = float(theta @ np.linalg.solve(vcv_a[-K:, -K:], theta))

    return OracleIV(
        beta=beta,
        vcv_conventional=vcv_conv,
        vcv_robust=vcv_rob,
        vcv_naive_second_stage=vcv_naive,
        residuals=u,
        second_stage_residuals_wrong=u_wrong,
        first_stage_pi=pi,
        cragg_donald=cd,
        partial_f=partial_f,
        sargan=sargan,
        gmm_beta=b_gmm,
        hansen_j=hansen,
        dwh_stat=dwh,
    )


def ols(y: np.ndarray, R: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Plain OLS beta and conventional VCV (independent comparison estimator)."""
    n, k = R.shape
    b = np.linalg.solve(R.T @ R, R.T @ y)
    u = y - R @ b
    s2 = float(u @ u) / (n - k)
    return b, s2 * np.linalg.inv(R.T @ R)


def chi2_pvalue(stat: float, df: int) -> float:
    return float(stats.chi2.sf(stat, df))


def f_pvalue(stat: float, df1: int, df2: int) -> float:
    return float(stats.f.sf(stat, df1, df2))
