"""Independent reference oracle for small-scale clustering verification.

This module deliberately does NOT import the kernel. It enumerates all set
partitions of the record ids (Bell-number exhaustive search, only feasible
for tiny n), scores each feasible partition with its own simple similarity
and a correlation-clustering objective, and returns the optimum.

The kernel under test is compared against this oracle on small fixtures, so
the reference answer is generated by independent logic — not by the code
being tested.
"""

from __future__ import annotations

import re
from typing import Iterable, Iterator

# The oracle's own minimal legal-form list (independent of the kernel's).
_ORACLE_LEGAL_TOKENS = frozenset(
    {"ltd", "limited", "inc", "corp", "corporation", "co", "company", "llc"}
)
_SPLIT_RE = re.compile(r"[^a-z0-9]+")


def oracle_tokens(name: str) -> frozenset[str]:
    tokens = [
        t
        for t in _SPLIT_RE.split(name.lower())
        if t and t not in _ORACLE_LEGAL_TOKENS
    ]
    return frozenset(tokens)


def oracle_sim(a: frozenset[str], b: frozenset[str]) -> float:
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def set_partitions(items: list[str]) -> Iterator[list[list[str]]]:
    """All set partitions via restricted-growth enumeration."""
    if not items:
        yield []
        return
    first, rest = items[0], items[1:]
    for partition in set_partitions(rest):
        yield [[first]] + [list(block) for block in partition]
        for i in range(len(partition)):
            grown = [list(block) for block in partition]
            grown[i] = sorted(grown[i] + [first])
            yield grown


def _canonical(partition: Iterable[Iterable[str]]) -> frozenset[frozenset[str]]:
    return frozenset(frozenset(block) for block in partition)


def best_partition(
    names: dict[str, str],
    *,
    must_link: Iterable[tuple[str, str]] = (),
    cannot_link: Iterable[tuple[str, str]] = (),
    tau: float = 0.75,
) -> frozenset[frozenset[str]]:
    """Exhaustively optimal feasible partition under sum(sim - tau)."""
    ids = sorted(names)
    tokens = {rid: oracle_tokens(names[rid]) for rid in ids}
    must = {frozenset(p) for p in must_link}
    cannot = {frozenset(p) for p in cannot_link}

    def feasible(partition: list[list[str]]) -> bool:
        block_of = {}
        for idx, block in enumerate(partition):
            for rid in block:
                block_of[rid] = idx
        for pair in must:
            a, b = pair
            if block_of[a] != block_of[b]:
                return False
        for pair in cannot:
            a, b = pair
            if block_of[a] == block_of[b]:
                return False
        return True

    def objective(partition: list[list[str]]) -> float:
        total = 0.0
        for block in partition:
            for i, a in enumerate(sorted(block)):
                for b in sorted(block)[i + 1 :]:
                    total += oracle_sim(tokens[a], tokens[b]) - tau
        return round(total, 9)

    best_key: tuple[float, str] | None = None
    best: frozenset[frozenset[str]] | None = None
    for partition in set_partitions(ids):
        if not feasible(partition):
            continue
        canon = _canonical(partition)
        # Deterministic tie-break on the canonical string form.
        key = (objective(partition), repr(sorted(map(sorted, canon))))
        if best_key is None or key > best_key:
            best_key, best = key, canon
    assert best is not None, "no feasible partition exists"
    return best
