"""Independent reference implementation used ONLY by tests.

This module re-derives the limiter output with a deliberately different
code structure (vectorized window minimum via slicing instead of the
monotonic deque, explicit Python smoother loop) so that full-trajectory
comparisons against limiter.stream are not generated by the tested core
itself. Closed-form analytic expectations (ceiling, recovery curve) are
computed here directly from math.exp.
"""

from __future__ import annotations

import math

import numpy as np


def ref_coeffs(sample_rate: int, attack_ms: float, release_ms: float) -> tuple[float, float]:
    a = math.exp(-1.0 / (attack_ms * 1e-3 * sample_rate))
    r = math.exp(-1.0 / (release_ms * 1e-3 * sample_rate))
    return a, r


def ref_lookahead_samples(sample_rate: int, lookahead_ms: float) -> int:
    return int(round(lookahead_ms * 1e-3 * sample_rate))


def ref_ceiling(threshold: float, input_peak: float, attack_coeff: float, lookahead: int) -> float:
    """Closed-form promised ceiling: T + (A - T) * a^(L+1)."""
    return threshold + max(0.0, input_peak - threshold) * attack_coeff ** (lookahead + 1)


def ref_limit(pcm: np.ndarray, *, threshold: float, sample_rate: int,
              attack_ms: float, release_ms: float, lookahead_ms: float):
    """Straight-line reference: returns (output, gain), both aligned to input."""
    pcm = np.asarray(pcm, dtype=np.float64)
    n = len(pcm)
    L = ref_lookahead_samples(sample_rate, lookahead_ms)
    a, rel = ref_coeffs(sample_rate, attack_ms, release_ms)

    peaks = np.max(np.abs(pcm), axis=1)
    r = np.divide(threshold, peaks, out=np.ones_like(peaks), where=peaks > threshold)
    # flush appends L silent frames with r = 1
    r_ext = np.concatenate([r, np.ones(L)])

    # R[j] = min(r_ext[j .. j+L])  (lookahead window minimum)
    R = np.empty(n)
    for j in range(n):
        R[j] = r_ext[j:j + L + 1].min()

    g = np.empty(n)
    g_prev = 1.0
    for j in range(n):
        c = a if R[j] < g_prev else rel
        g_prev = c * g_prev + (1.0 - c) * R[j]
        g[j] = g_prev

    return pcm * g[:, None], g


def ref_recovery_curve(g_start: float, release_coeff: float, steps: int) -> np.ndarray:
    """Closed-form gain recovery after the window minimum returns to 1:
    g(j) = 1 - (1 - g_start) * release_coeff**j."""
    j = np.arange(steps, dtype=np.float64)
    return 1.0 - (1.0 - g_start) * release_coeff ** j
