"""Independent statistical oracle for the test suite.

Nothing in this module imports :mod:`ssp.kernels` or :mod:`ssp.planning`.
Power values are recomputed directly from SciPy distribution primitives
(``norm``, ``nct``, ``binom``, ``hypergeom``) with the rejection regions
enumerated from scratch.  Tests use this oracle to check the production
kernels, so the reference answers cannot be generated by the code under test.
"""
from __future__ import annotations

import math

import numpy as np
from scipy.stats import binom, hypergeom, nct, norm


def zcrit(alpha: float, alternative: str) -> float:
    a_star = alpha / 2.0 if alternative == "two_sided" else alpha
    return float(norm.ppf(1.0 - a_star))


# ---------------------------------------------------------------------------
# Normal endpoints
# ---------------------------------------------------------------------------


def normal_z_power_one(n: int, d: float, alpha: float, alternative: str) -> float:
    """One-sample z power from the shifted-normal integral directly."""
    lam = abs(d) * math.sqrt(n)
    z = zcrit(alpha, alternative)
    if alternative == "two_sided":
        return float(norm.sf(z - lam) + norm.cdf(-z - lam))
    if alternative == "greater":
        return float(norm.sf(z - lam))
    return float(norm.cdf(-z + lam))  # shift is -lam for less


def normal_t_power_one(n: int, d: float, alpha: float, alternative: str) -> float:
    df = n - 1
    lam = abs(d) * math.sqrt(n)
    z = zcrit(alpha, alternative)
    tcrit = float(nct.ppf(1.0 - (alpha / 2.0 if alternative == "two_sided" else alpha), df, 0.0))
    if alternative == "two_sided":
        return float(nct.sf(tcrit, df, lam) + nct.cdf(-tcrit, df, lam))
    if alternative == "greater":
        return float(nct.sf(tcrit, df, lam))
    return float(nct.cdf(-tcrit, df, -lam))


def normal_z_power_two(n0: int, n1: int, d: float, alpha: float, alternative: str) -> float:
    lam = abs(d) * math.sqrt(n0 * n1 / (n0 + n1))
    z = zcrit(alpha, alternative)
    if alternative == "two_sided":
        return float(norm.sf(z - lam) + norm.cdf(-z - lam))
    if alternative == "greater":
        return float(norm.sf(z - lam))
    return float(norm.cdf(-z + lam))


# ---------------------------------------------------------------------------
# Binomial endpoints
# ---------------------------------------------------------------------------


def binom_exact_critical_one(n: int, p0: float, alpha: float, alternative: str):
    """Brute-force scan of k=0..n choosing the maximal size-respecting region."""
    ks = np.arange(n + 1)
    pmf = binom.pmf(ks, n, p0)
    if alternative == "greater":
        tail = np.fromiter((pmf[k:].sum() for k in ks), dtype=float)
        valid = np.nonzero(tail <= alpha + 1e-15)[0]
        c = int(valid[0]) if valid.size else n + 1
        return None, c, float(tail[c]) if c <= n else 0.0
    if alternative == "less":
        tail = np.fromiter((pmf[: k + 1].sum() for k in ks), dtype=float)
        valid = np.nonzero(tail <= alpha + 1e-15)[0]
        c = int(valid[-1]) if valid.size else -1
        return c, None, float(tail[c]) if c >= 0 else 0.0
    half = alpha / 2.0
    upper_tail = np.fromiter((pmf[k:].sum() for k in ks), dtype=float)
    lower_tail = np.fromiter((pmf[: k + 1].sum() for k in ks), dtype=float)
    up = np.nonzero(upper_tail <= half + 1e-15)[0]
    lo = np.nonzero(lower_tail <= half + 1e-15)[0]
    c_hi = int(up[0]) if up.size else n + 1
    c_lo = int(lo[-1]) if lo.size else -1
    size = 0.0
    if c_hi <= n:
        size += float(upper_tail[c_hi])
    if c_lo >= 0:
        size += float(lower_tail[c_lo])
    return c_lo, c_hi, size


def binom_exact_power_one(n: int, p0: float, p1: float, alpha: float, alternative: str) -> float:
    c_lo, c_hi, _ = binom_exact_critical_one(n, p0, alpha, alternative)
    ks = np.arange(n + 1)
    pmf1 = binom.pmf(ks, n, p1)
    power = 0.0
    if c_hi is not None and c_hi <= n:
        power += float(pmf1[c_hi:].sum())
    if c_lo is not None and c_lo >= 0:
        power += float(pmf1[: c_lo + 1].sum())
    return min(1.0, power)


def fisher_power_two_bruteforce(
    n0: int, n1: int, p0: float, p1: float, alpha: float, alternative: str
) -> float:
    """Unconditional exact power by full (x0,x1) table enumeration.

    For each table the conditional Fisher p-value region is built directly from
    the hypergeometric distribution of X1|S.  Joint mass under the
    alternative is Bin(n0,p0)*Bin(n1,p1).  O(n0*n1), used only at small n.
    """
    total = n0 + n1
    half = alpha / 2.0 if alternative == "two_sided" else alpha
    x0 = np.arange(n0 + 1)
    x1 = np.arange(n1 + 1)
    j0 = binom.pmf(x0[:, None], n0, p0)
    j1 = binom.pmf(x1[None, :], n1, p1)
    joint = j0 * j1
    s_grid = x0[:, None] + x1[None, :]
    x1_grid = np.broadcast_to(x1[None, :], (n0 + 1, n1 + 1))
    upper = hypergeom.sf(x1_grid - 1, total, n1, s_grid)  # P(X1 >= x1 | S)
    lower = hypergeom.cdf(x1_grid, total, n1, s_grid)      # P(X1 <= x1 | S)
    if alternative == "greater":
        reject = upper <= half + 1e-15
    elif alternative == "less":
        reject = lower <= half + 1e-15
    else:
        reject = (upper <= half + 1e-15) | (lower <= half + 1e-15)
    return float(min(1.0, joint[reject].sum()))


def binom_asymp_power_one(n: int, p0: float, p1: float, alpha: float, alternative: str) -> float:
    se = math.sqrt(p0 * (1 - p0) / n)
    lam = (p1 - p0) / se
    z = zcrit(alpha, alternative)
    if alternative == "two_sided":
        return float(norm.sf(z - lam) + norm.cdf(-z - lam))
    if alternative == "greater":
        return float(norm.sf(z - lam))
    return float(norm.cdf(-z - lam))


def binom_asymp_power_two(
    n0: int, n1: int, p0: float, p1: float, alpha: float, alternative: str
) -> float:
    p_bar = (n0 * p0 + n1 * p1) / (n0 + n1)
    se = math.sqrt(p_bar * (1 - p_bar) * (1.0 / n0 + 1.0 / n1))
    lam = (p1 - p0) / se
    z = zcrit(alpha, alternative)
    if alternative == "two_sided":
        return float(norm.sf(z - lam) + norm.cdf(-z - lam))
    if alternative == "greater":
        return float(norm.sf(z - lam))
    return float(norm.cdf(-z - lam))


def score_statistic_power_two(
    n0: int, n1: int, p0: float, p1: float, alpha: float, alternative: str
) -> float:
    """Exact rejection probability of the RANDOM-DENOMINATOR score statistic.

    The production asymptotic kernel approximates this with a fixed-SE normal
    shift.  Here the actual discrete statistic
    ``(p1_hat-p0_hat)/sqrt(p_bar(1-p_bar)(1/n0+1/n1))``
    is enumerated exactly over all (x0,x1) tables under the alternative -
    this is the quantity Monte-Carlo evidence must converge to, and it is
    computed without importing any production code.
    """
    x0 = np.arange(n0 + 1)
    x1 = np.arange(n1 + 1)
    j0 = binom.pmf(x0[:, None], n0, p0)
    j1 = binom.pmf(x1[None, :], n1, p1)
    joint = j0 * j1
    p0_hat = x0[:, None] / n0
    p1_hat = x1[None, :] / n1
    p_bar = (x0[:, None] + x1[None, :]) / (n0 + n1)
    se = np.sqrt(p_bar * (1 - p_bar) * (1.0 / n0 + 1.0 / n1))
    with np.errstate(divide="ignore", invalid="ignore"):
        stat = np.where(se > 0, (p1_hat - p0_hat) / np.where(se > 0, se, 1.0), 0.0)
    z = zcrit(alpha, alternative)
    if alternative == "two_sided":
        reject = np.abs(stat) >= z
    elif alternative == "greater":
        reject = stat >= z
    else:
        reject = stat <= -z
    return float(joint[reject].sum())


def derive_n1(n0: int, ratio: float) -> int:
    return max(1, int(math.floor(ratio * n0 + 0.5)))


def minimal_n0(
    power_at,
    target: float,
    two_sample: bool,
    ratio: float = 1.0,
    start: int = 1,
    hard_stop: int = 100_000,
) -> tuple[int, int, float, float]:
    """Linear scan over control size n0 (n1 derived as round(r*n0)).

    Mirrors the production allocation contract but recomputes power from the
    independent primitives in this module.  Returns
    ``(n0, n1, power_at_n0, power_at_n0_minus_one)``.
    """
    prev = 0.0
    for n0 in range(start, hard_stop + 1):
        n1 = derive_n1(n0, ratio) if two_sample else 0
        pwr = power_at(n0, n1)
        if pwr >= target:
            return n0, n1, pwr, prev
        prev = pwr
    raise AssertionError("oracle scan reached hard_stop")


def minimal_total(
    power_at, target: float, two_sample: bool, start: int = 1, hard_stop: int = 100_000
) -> tuple[int, float, float]:
    """Legacy fixed-total balanced scan; retained for explicit comparisons."""
    prev = 0.0
    for n in range(start, hard_stop + 1):
        if two_sample:
            n1 = n // 2
            n0 = n - n1
            pwr = power_at(n0, n1)
        else:
            pwr = power_at(n, 0)
        if pwr >= target:
            return n, pwr, prev
        prev = pwr
    raise AssertionError("oracle scan reached hard_stop")
