"""Independent brute-force reference for short sequences.

This module deliberately shares no code with dtw_service.core: it enumerates
every legal path by recursion and computes local distances with plain Python.
The exhaustive tests compare the DP core against this reference, so the
expected answers are not generated by the implementation under test.
"""

from __future__ import annotations

import math

STEPS = ((1, 1), (1, 0), (0, 1))


def _local_cost(a: list[list[float]], b: list[list[float]], i: int, j: int) -> float:
    return math.dist(a[i], b[j])


def enumerate_legal_paths(
    a: list[list[float]],
    b: list[list[float]],
    window: int,
    max_run: int,
) -> list[tuple[list[tuple[int, int]], float]]:
    """All legal (path, cost) pairs from (0,0) to (n-1, m-1)."""
    n, m = len(a), len(b)
    results: list[tuple[list[tuple[int, int]], float]] = []

    def rec(
        i: int,
        j: int,
        last_dir: tuple[int, int] | None,
        run_len: int,
        path: list[tuple[int, int]],
        cost: float,
    ) -> None:
        if (i, j) == (n - 1, m - 1):
            results.append((list(path), cost))
            return
        for step in STEPS:
            ni, nj = i + step[0], j + step[1]
            if ni >= n or nj >= m or abs(ni - nj) > window:
                continue
            if step == (1, 1):
                n_dir, n_run = None, 0
            elif step == last_dir:
                n_run = run_len + 1
                if n_run > max_run:
                    continue
                n_dir = step
            else:
                n_dir, n_run = step, 1
            path.append((ni, nj))
            rec(ni, nj, n_dir, n_run, path, cost + _local_cost(a, b, ni, nj))
            path.pop()

    if n >= 1 and m >= 1 and abs((n - 1) - (m - 1)) <= window:
        rec(0, 0, None, 0, [(0, 0)], _local_cost(a, b, 0, 0))
    return results


def best_path_cost(
    a: list[list[float]], b: list[list[float]], window: int, max_run: int
) -> float | None:
    """Minimum legal path cost, or None when the endpoint is unreachable."""
    paths = enumerate_legal_paths(a, b, window, max_run)
    if not paths:
        return None
    return min(cost for _, cost in paths)
