//! First vertical-slice test: real exercises of the resolution rule.
//! These literals are hand-authored; nothing is generated by the code under
//! test and then asserted back.

use resolution_checker::resolution::{resolve, validate_step, ParentSide, ResolutionError};
use resolution_checker::syntax::Clause;

fn clause(raw: &[i64]) -> Clause {
    Clause::from_signed(raw).expect("hand-authored valid clause")
}

#[test]
fn resolves_on_pivot_and_drops_both_signs() {
    // (p ∨ q) and (¬p ∨ r) => (q ∨ r)
    let left = clause(&[1, 2]);
    let right = clause(&[-1, 3]);
    let resolvent = resolve(&left, &right, 1).expect("legal step");
    assert_eq!(resolvent.to_signed(), vec![2, 3]);

    let claimed = clause(&[2, 3]);
    assert!(validate_step(&left, &right, 1, &claimed).is_ok());
}

#[test]
fn rejects_when_positive_pivot_missing() {
    let left = clause(&[2]);
    let right = clause(&[-1, 3]);
    let claimed = clause(&[2, 3]);
    let err = validate_step(&left, &right, 1, &claimed).unwrap_err();
    assert_eq!(err, ResolutionError::MissingPositivePivot { var: 1 });
}

#[test]
fn detects_single_step_tampering_with_resolvent() {
    // Correct resolvent is (2,3); a tampered claim (2,4) must be rejected.
    let left = clause(&[1, 2]);
    let right = clause(&[-1, 3]);
    let tampered = clause(&[2, 4]);
    let err = validate_step(&left, &right, 1, &tampered).unwrap_err();
    match err {
        ResolutionError::ResolventMismatch { expected, claimed } => {
            assert_eq!(expected, vec![2, 3]);
            assert_eq!(claimed, vec![2, 4]);
        }
        other => panic!("expected resolvent mismatch, got {other:?}"),
    }
}

#[test]
fn rejects_tautological_parent_on_pivot() {
    let left = clause(&[1, -1, 2]);
    let right = clause(&[-1, 3]);
    let claimed = clause(&[2, 3]);
    let err = validate_step(&left, &right, 1, &claimed).unwrap_err();
    assert_eq!(
        err,
        ResolutionError::ParentContainsBothPolarities {
            var: 1,
            parent: ParentSide::Left
        }
    );
}

#[test]
fn resolving_complementary_units_yields_empty_clause() {
    let left = clause(&[1]);
    let right = clause(&[-1]);
    let empty = clause(&[]);
    assert!(validate_step(&left, &right, 1, &empty).is_ok());
}

#[test]
fn duplicate_literals_are_canonicalized() {
    // A repeated literal in a claimed clause must not create a false mismatch.
    let repeated = clause(&[2, 2, 3]);
    let canonical = clause(&[3, 2]);
    assert_eq!(repeated, canonical);
}
