//! Scan pollution trace, hand-computed from the algorithm rules in
//! README.md (capacity 2). Expected values below were derived on paper, not
//! generated by the implementation.
//!
//! Trace: read 1, 2, 1, 2 (hot pair lands in T2), then a one-shot scan
//! 11..14, then re-read 1, 2. An LRU cache of size 2 would lose both hot
//! pages to the scan; ARC must keep page 2 resident and only lose page 1 to
//! a ghost entry.

mod common;

use arc_cache::arc::{Class, Outcome};
use arc_cache::diag::Op;
use arc_cache::engine::Request;

use common::{never_fail, pair};

fn read(engine: &mut arc_cache::engine::Engine, page: u64) -> Outcome {
    engine
        .submit(Request {
            request_id: None,
            op: Op::Read,
            page,
            data: None,
        })
        .result
        .expect("read must succeed")
        .outcome
}

#[test]
fn scan_does_not_evict_hot_set() {
    let (mut engine, _model, _store) = pair(2, 16, never_fail());

    let outcomes: Vec<Outcome> = [1, 2, 1, 2, 11, 12, 13, 14, 1, 2]
        .into_iter()
        .map(|p| read(&mut engine, p))
        .collect();

    assert_eq!(
        outcomes,
        vec![
            Outcome::MissFill,
            Outcome::MissFill,
            Outcome::HitT1,
            Outcome::HitT1,
            Outcome::MissFill,
            Outcome::MissFill,
            Outcome::MissFill,
            Outcome::MissFill,
            Outcome::GhostHitB2, // page 1 was pushed to B2 by the scan
            Outcome::HitT2,      // page 2 survived the scan as a resident
        ]
    );

    let cache = engine.cache();
    assert_eq!(cache.p(), 0);
    let lists = cache.lists();
    assert_eq!(lists.t1, Vec::<u64>::new());
    assert_eq!(lists.t2, vec![1, 2]);
    assert_eq!(lists.b1, vec![13, 14]);
    assert_eq!(lists.b2, Vec::<u64>::new());

    // Ghost entries hold no data.
    assert!(!cache.contains_data(13));
    assert!(!cache.contains_data(14));
    assert_eq!(cache.classify(13), Class::B1);

    let stats = engine.stats();
    assert_eq!(stats.reads, 10);
    assert_eq!(stats.hits_t1, 2);
    assert_eq!(stats.hits_t2, 1);
    assert_eq!(stats.ghost_hits_b1, 0);
    assert_eq!(stats.ghost_hits_b2, 1);
    assert_eq!(stats.misses, 6);
    // 6 misses + 1 ghost hit each fetched exactly once from the store.
    assert_eq!(stats.store_fetches, 7);
    assert_eq!(stats.evictions_clean, 5);
    assert_eq!(stats.ghost_evictions, 2);
    assert_eq!(stats.dropped_t1, 0);
}

#[test]
fn ghost_hit_fetches_from_store_not_from_cache() {
    let (mut engine, _model, store) = pair(2, 16, never_fail());
    for p in [1, 2, 1, 2, 11, 12, 13, 14] {
        read(&mut engine, p);
    }
    // Page 1 is now a B2 ghost: id known, content gone.
    assert_eq!(engine.cache().classify(1), Class::B2);
    assert!(!engine.cache().contains_data(1));

    let loads_before = store.load_count();
    let resp = engine.submit(Request {
        request_id: Some("ghost-check".into()),
        op: Op::Read,
        page: 1,
        data: None,
    });
    let ok = resp.result.expect("ghost hit read succeeds");
    assert_eq!(ok.outcome, Outcome::GhostHitB2);
    assert!(ok.report.fetched, "ghost hit must fetch content");
    assert_eq!(
        store.load_count(),
        loads_before + 1,
        "ghost hit must hit the backing store"
    );
    assert_eq!(ok.data.unwrap(), common::fixture_content(1));
}
