"""The oracle must stay independent of the system under test.

These tests make the "reference answer is not generated by the core itself"
guarantee machine-checkable: the reference matcher source may only share the
rule *data* model and the pure comparison helper - never the Rete network,
agenda, engine or service code.
"""

from __future__ import annotations

import ast
from pathlib import Path

REFERENCE = Path(__file__).resolve().parent / "reference_matcher.py"
FORBIDDEN_MODULES = (
    "reteapp.core",
    "reteapp.service",
    "reteapp.api",
    "reteapp.storage",
)


def test_reference_matcher_does_not_import_the_engine_core() -> None:
    tree = ast.parse(REFERENCE.read_text(encoding="utf-8"))
    imported: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported.extend(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            imported.append(node.module)
    forbidden = [name for name in imported if name.startswith(FORBIDDEN_MODULES)]
    assert forbidden == [], f"oracle must not import SUT internals, found: {forbidden}"

    # The only behavioural sharing allowed is the pure predicate evaluator.
    allowed_shared = {"reteapp.lang.model", "reteapp.lang.predicates"}
    shared = {name for name in imported if name.startswith("reteapp")}
    assert shared <= allowed_shared, f"unexpected shared imports: {shared - allowed_shared}"


def test_reference_matcher_is_exhaustive_enumerator() -> None:
    # Guards against someone quietly rewriting the oracle to call the engine.
    source = REFERENCE.read_text(encoding="utf-8")
    assert "itertools.product" in source
    assert "ReteNetwork" not in source and "Engine" not in source and "Agenda" not in source
