"""Fixture-driven integration tests.

Each case loads a reusable domain/problem fixture and a *hand-written*
expected-result file.  The expected files were authored from the domain
semantics, never generated by the planner, so these are genuine cross-checks
on concrete outcomes and failure categories - not 'the endpoint responds'
smoke tests.
"""

from __future__ import annotations

from typing import Any

import pytest

from htn_planner.core.engine import Bounds, Planner
from htn_planner.verify import Verifier
from tests.conftest import (
    EXPECTED,
    FIXTURE_CASES,
    load_domain,
    load_expected,
    load_problem,
)


def _cases() -> list[tuple[str, str, str]]:
    return FIXTURE_CASES


@pytest.fixture(params=_cases(), ids=[c[2] for c in _cases()])
def case(request: pytest.FixtureRequest) -> dict[str, Any]:
    dom_file, prob_file, exp_file = request.param
    bounds_dict = load_expected(exp_file).get("bounds")
    bounds = Bounds(**(bounds_dict or {})) if bounds_dict else Bounds(max_depth=12)
    return {
        "domain": load_domain(dom_file),
        "problem": load_problem(prob_file),
        "expected": load_expected(exp_file),
        "bounds": bounds,
    }


class TestFixtureOutcomes:
    def test_status_matches_handwritten_expectation(self, case: dict[str, Any]) -> None:
        result = Planner(case["bounds"]).solve(
            case["domain"], case["problem"], "req-fixture"
        )
        assert result.status == case["expected"]["expected_status"]

    def test_action_sequence_is_exact(self, case: dict[str, Any]) -> None:
        expected = case["expected"]
        if "expected_actions" not in expected:
            pytest.skip("no exact action expectation")
        result = Planner(case["bounds"]).solve(
            case["domain"], case["problem"], "req-fixture"
        )
        actual = [[a.operator, list(a.args)] for a in result.plan]
        assert actual == expected["expected_actions"]

    def test_failure_categories_match(self, case: dict[str, Any]) -> None:
        expected = case["expected"]
        result = Planner(case["bounds"]).solve(
            case["domain"], case["problem"], "req-fixture"
        )
        actual = sorted({f.category for f in result.failures})
        assert actual == sorted(expected["expected_failure_categories"])
        if "expected_uncertain_categories" in expected:
            assert sorted({u.category for u in result.uncertain}) == sorted(
                expected["expected_uncertain_categories"]
            )

    def test_independent_verifier_verdict(self, case: dict[str, Any]) -> None:
        expected_verification = case["expected"]["verification"]
        result = Planner(case["bounds"]).solve(
            case["domain"], case["problem"], "req-fixture"
        )
        report = Verifier().verify(case["domain"], case["problem"], result)
        assert report.ok is expected_verification["ok"]
        for key in (
            "executable",
            "hierarchy_consistent",
            "order_consistent",
            "failure_sound",
        ):
            if key in expected_verification:
                assert getattr(report, key) is expected_verification[key], key
        if "feasible_linearizations" in expected_verification:
            assert (
                len(report.feasible_linearizations)
                == expected_verification["feasible_linearizations"]
            )
        if "linearizations_examined" in expected_verification:
            assert (
                report.linearizations_examined
                == expected_verification["linearizations_examined"]
            )


class TestFixtureFailureDetail:
    """Hand-authored assertions on the *content* of failure evidence."""

    def _result_for(self, expected_file: str) -> Any:
        mapping = {c[2]: c for c in FIXTURE_CASES}
        dom_file, prob_file, _ = mapping[expected_file]
        expected = load_expected(expected_file)
        bounds_dict = expected.get("bounds")
        bounds = Bounds(**(bounds_dict or {})) if bounds_dict else Bounds(max_depth=12)
        domain = load_domain(dom_file)
        problem = load_problem(prob_file)
        return Planner(bounds).solve(domain, problem, "req-detail"), expected

    def test_unreachable_lists_both_methods_and_literals(self) -> None:
        result, expected = self._result_for("logistics_unreachable.json")
        detail = expected["expected_failure_details"][0]
        record = result.failures[0]
        assert record.category == detail["category"]
        assert record.task[0] == detail["task_head"]
        rejected_names = [m["method"] for m in record.rejected_methods]
        assert rejected_names == detail["rejected_methods_exactly"]
        unmet_literals = [m["unmet"] for m in record.rejected_methods]
        for fragment in detail["rejected_unmet_substrings"]:
            assert any(fragment in u for u in unmet_literals), fragment

    def test_permit_deadlock_snapshots_two_minimal_tasks(self) -> None:
        result, expected = self._result_for("permit_two.json")
        detail = expected["expected_failure_details"][0]
        deadlocks = [f for f in result.failures if f.category == "deadlock"]
        assert deadlocks, "expected at least one deadlock record"
        # Each explored dead end: the first grab is already in the executed
        # prefix, leaving exactly one minimal primitive blocked on the permit.
        blocked_claimers: set[str] = set()
        prefix_claimers: set[str] = set()
        for record in deadlocks:
            minimal = [t for t in record.remaining_tasks if t["minimal"]]
            assert len(minimal) == detail["snapshot_minimal_count"]
            assert all(t["task"][0].startswith("!") for t in minimal)
            blocked_claimers.update(b["task"][-1] for b in record.blocked)
            # Exactly one !grab precedes the dead end in that branch.
            grabs = [args for name, args in record.action_prefix if name == "!grab"]
            assert len(grabs) == detail["snapshot_prefix_grabs"]
            prefix_claimers.update(args[-1] for args in grabs)
            assert all(
                detail["unmet_substring"] in b["unmet"] for b in record.blocked
            )
        # Backtracking tries BOTH first choices; across the two dead ends the
        # blocked and the already-executed claimers each union to {p1,p2}.
        assert blocked_claimers == set(detail["blocked_claimers_union"])
        assert prefix_claimers == set(detail["prefix_claimers_union"])

    def test_spin_cycle_chain_is_closed(self) -> None:
        result, expected = self._result_for("bounds_spin.json")
        detail = expected["expected_failure_details"][0]
        record = next(f for f in result.failures if f.category == "cycle")
        chain = [tuple(t) for t in record.cycle_chain]
        assert chain[0] == chain[-1]
        assert chain[-1][0] == detail["task_head"]


class TestRecursionAndBacktracking:
    def test_recursive_plan_preserves_hierarchy(self) -> None:
        from tests.conftest import load_domain, load_problem

        domain = load_domain("logistics.htn")
        problem = load_problem("logistics_recursive.pddl")
        result = Planner(Bounds(max_depth=10)).solve(domain, problem, "rec")
        expected = load_expected("logistics_recursive.json")
        methods = {
            r.expanded_by for r in result.expansion if r.kind == "compound"
        }
        assert set(expected["expected_methods_on_path"]).issubset(methods)
        # Abstract deliver task nests a deliver task: recursion is visible in
        # the tree, not flattened into a bare action list.
        deliver_nodes = [
            r for r in result.expansion if tuple(r.task)[0] == "deliver"
        ]
        assert len(deliver_nodes) == 2
        depths = sorted(r.depth for r in deliver_nodes)
        assert depths[0] < depths[1]

    def test_mutual_exclusion_selects_direct_not_hub(self) -> None:
        from tests.conftest import load_domain, load_problem

        domain = load_domain("logistics.htn")
        problem = load_problem("logistics_direct.pddl")
        result = Planner().solve(domain, problem, "mutex")
        chosen = {
            r.expanded_by for r in result.expansion if r.kind == "compound"
        }
        assert chosen == {"m-direct"}

    def test_partial_order_alpha_precedes_gamma_in_plan(self) -> None:
        from tests.conftest import load_domain, load_problem

        domain = load_domain("docks.htn")
        problem = load_problem("docks_three.pddl")
        result = Planner(Bounds(max_depth=10)).solve(domain, problem, "po")
        seq = [(a.operator, a.args[-1]) for a in result.plan]
        alpha_lock = next(i for i, (op, w) in enumerate(seq) if op == "!lock" and w == "alpha")
        gamma_unlock = next(
            i for i, (op, w) in enumerate(seq) if op == "!unlock" and w == "gamma"
        )
        assert alpha_lock < gamma_unlock


class TestAdequateBoundsResolveInconclusiveCase:
    def test_walk_long_succeeds_with_adequate_depth(self) -> None:
        expected = load_expected("bounds_walk_long.json")
        mapping = {c[2]: c for c in FIXTURE_CASES}
        dom_file, prob_file, _ = mapping["bounds_walk_long.json"]
        domain = load_domain(dom_file)
        problem = load_problem(prob_file)
        tight = Planner(Bounds(**expected["bounds"])).solve(domain, problem, "tight")
        assert tight.status == "inconclusive"
        adequate = Planner(Bounds(**expected["adequate_bounds"])).solve(
            domain, problem, "adequate"
        )
        assert adequate.status == expected["adequate_expected_status"]
        actual = [[a.operator, list(a.args)] for a in adequate.plan]
        assert actual == expected["adequate_expected_actions"]


def test_all_nine_fixture_cases_are_covered() -> None:
    names = {c[2] for c in FIXTURE_CASES}
    on_disk = {p.name for p in EXPECTED.glob("*.json")}
    assert names == on_disk
