"""Validation against INDEPENDENT references and known-truth DGPs.

The reference module shares no code with the estimator under test: it
re-derives the fit from raw weighted normal equations (scipy.linalg.solve),
from numerical minimisation (scipy.optimize BFGS), and via a per-draw
bootstrap-t. The known-truth DGPs are a third, statistical reference.

The reference answers here are therefore not generated by the core itself.
"""
from __future__ import annotations

import numpy as np
import pytest

from app.contract import BandwidthMethod, DataPoint, KernelName, RDRequest, RunStatus
from app import reference as ref
from app.datasets import sharp_jump
from app.pipeline import run_analysis

H = 0.22
KERNEL_TOL = 1e-8


def _core(settings, x, y, h, kernel=KernelName.TRIANGULAR):
    req = RDRequest(
        input_label="reference-cross-check",
        data=[DataPoint(x=float(a), y=float(b)) for a, b in zip(x, y)],
        cutoff=0.0,
        kernel=kernel,
        bandwidth_method=BandwidthMethod.MANUAL,
        bandwidth=h,
        bootstrap_reps=0,
    )
    resp = run_analysis(req, settings)
    assert resp.status is RunStatus.OK
    return resp


@pytest.mark.integration
def test_core_matches_explicit_normal_equations(settings) -> None:
    dgp = sharp_jump(n=4000, seed=909)
    resp = _core(settings, dgp.x, dgp.y, H)
    expected = ref.explicit_jump(dgp.x, dgp.y, 0.0, H, "triangular")
    assert resp.estimate.tau == pytest.approx(expected, abs=KERNEL_TOL)


@pytest.mark.integration
@pytest.mark.parametrize("kernel", ["triangular", "epanechnikov", "uniform"])
def test_core_matches_explicit_path_for_every_kernel(settings, kernel) -> None:
    dgp = sharp_jump(n=4000, seed=910)
    enum_kernel = KernelName(kernel)
    resp = _core(settings, dgp.x, dgp.y, H, enum_kernel)
    expected = ref.explicit_jump(dgp.x, dgp.y, 0.0, H, kernel)
    assert resp.estimate.tau == pytest.approx(expected, abs=1e-7)


@pytest.mark.integration
def test_core_matches_numerical_optimisation_path(settings) -> None:
    dgp = sharp_jump(n=4000, seed=911)
    resp = _core(settings, dgp.x, dgp.y, H)
    a_r = ref.optimized_side_intercept(dgp.x, dgp.y, 0.0, H, "triangular", "right")
    a_l = ref.optimized_side_intercept(dgp.x, dgp.y, 0.0, H, "triangular", "left")
    assert resp.estimate.tau == pytest.approx(a_r - a_l, abs=1e-6)


@pytest.mark.integration
def test_known_truth_within_tolerance_and_reference_agrees(settings) -> None:
    # Statistical reference: the DGP's true jump, not the core output.
    dgp = sharp_jump(n=8000, seed=912)
    resp = _core(settings, dgp.x, dgp.y, H)
    assert resp.estimate.tau == pytest.approx(dgp.tau, abs=0.12)
    assert ref.explicit_jump(dgp.x, dgp.y, 0.0, H) == pytest.approx(
        dgp.tau, abs=0.12
    )


@pytest.mark.integration
def test_bootstrap_t_reference_detects_jump_and_null_t_is_gaussian(settings) -> None:
    dgp = sharp_jump(n=4000, seed=913)
    bt = ref.wild_bootstrap_t(dgp.x, dgp.y, 0.0, H, "triangular", reps=999, seed=4)
    assert bt["tau_obs"] == pytest.approx(3.0, abs=0.15)
    assert bt["p_value"] <= 0.01
    # null distribution should not reject standard-normality at 1% level
    assert bt["null_t_ks_pvalue"] > 0.01


@pytest.mark.integration
def test_core_se_matches_independent_hc3_reference(settings) -> None:
    dgp = sharp_jump(n=4000, seed=914)
    resp = _core(settings, dgp.x, dgp.y, H)
    # independent SE from raw sums on each side
    dl, yl, wl = ref._gather(dgp.x, dgp.y, 0.0, H, "triangular", "left")
    dr, yr, wr = ref._gather(dgp.x, dgp.y, 0.0, H, "triangular", "right")
    se_ref = float(
        np.sqrt(ref._explicit_se(dl, yl, wl) ** 2 + ref._explicit_se(dr, yr, wr) ** 2)
    )
    assert resp.estimate.se == pytest.approx(se_ref, rel=1e-6)
