"""Core WSOLA tests.

References here are closed-form or hand-computed (exact lengths from the
spec formula, known fixture frequencies/periods, hand-built search cases),
not regenerated by the stretch core itself.
"""
import numpy as np
import pytest

from fixtures.synth import get_fixture
from wsola_backend.metrics import (
    dominant_frequency,
    impulse_spacings,
    seam_report,
    sinusoid_residual_snr_db,
)
from wsola_backend.wsola import (
    choose_match_position,
    frame_count,
    make_params,
    target_length,
    wsola_stretch,
)

SR = 16_000


# --- Hand-computed local-search cases (choose_match_position) ---------------

def test_search_unique_best_nonzero_offset():
    # Only position 2 holds the reference pattern [1,2,3].
    x = np.array([5.0, 5.0, 1.0, 2.0, 3.0, 7.0, 7.0])
    pos, score, tied = choose_match_position(np.array([1.0, 2.0, 3.0]), x, x_nat=0, lo=0, hi=4, ov_len=3)
    assert pos == 2
    assert score == pytest.approx(1.0)
    assert tied == 1


def test_search_tie_picks_smallest_absolute_offset():
    # Pattern occurs at positions 0 (delta -4) and 6 (delta +2); +2 wins.
    x = np.array([1.0, 2.0, 3.0, 9.0, 9.0, 9.0, 1.0, 2.0, 3.0])
    pos, score, tied = choose_match_position(np.array([1.0, 2.0, 3.0]), x, x_nat=4, lo=0, hi=6, ov_len=3)
    assert pos == 6
    assert tied == 2


def test_search_equidistant_tie_picks_smaller_position():
    # Pattern at positions 0 (delta -2) and 4 (delta +2): negative side wins.
    x = np.array([1.0, 2.0, 3.0, 9.0, 1.0, 2.0, 3.0])
    pos, _, tied = choose_match_position(np.array([1.0, 2.0, 3.0]), x, x_nat=2, lo=0, hi=4, ov_len=3)
    assert pos == 0
    assert tied == 2


def test_search_silence_reference_defaults_to_natural_position():
    x = np.array([1.0, 5.0, 2.0, 4.0, 3.0, 6.0, 7.0])
    pos, score, tied = choose_match_position(np.zeros(3), x, x_nat=2, lo=0, hi=4, ov_len=3)
    assert pos == 2
    assert score == 0.0
    assert tied == 5  # every candidate tied at 0 -> deterministic default


# --- Length contract ---------------------------------------------------------

@pytest.mark.parametrize("ts", [0.5, 0.75, 1.0, 1.3, 2.0])
def test_output_length_exact_even_and_odd(ts):
    sr, x = get_fixture("tone_440hz")
    inputs = (x, np.concatenate([x, x[:1]]))  # 16000 and 16001 samples
    for samples in inputs:
        n = samples.shape[0]
        out = wsola_stretch(samples, make_params(sr, ts))
        assert out.output.shape[0] == round(n * ts)
        assert out.target_length == target_length(n, ts)


def test_frame_count_matches_offsets():
    sr, x = get_fixture("tone_440hz")
    params = make_params(sr, 1.5)
    out = wsola_stretch(x, params)
    assert len(out.frames) == frame_count(params, out.target_length)
    assert len(out.offsets) == len(out.frames)


# --- Determinism and identity ------------------------------------------------

def test_identity_scale_reconstructs_noise():
    sr, x = get_fixture("noise_seeded")
    out = wsola_stretch(x, make_params(sr, 1.0))
    # Window endpoint is 0 at sample 0; interior reconstructs exactly.
    np.testing.assert_allclose(out.output[1:], x[1:], atol=1e-9)
    assert all(o == 0 for o in out.offsets)


def test_determinism_repeated_runs_identical():
    sr, x = get_fixture("tone_440hz")
    a = wsola_stretch(x, make_params(sr, 1.3))
    b = wsola_stretch(x, make_params(sr, 1.3))
    np.testing.assert_array_equal(a.output, b.output)
    assert a.offsets == b.offsets


# --- Content preservation ----------------------------------------------------

@pytest.mark.parametrize("ts", [0.5, 0.8, 1.0, 1.5, 2.0])
def test_tone_dominant_frequency_preserved(ts):
    sr, x = get_fixture("tone_440hz")
    out = wsola_stretch(x, make_params(sr, ts))
    assert dominant_frequency(out.output, sr) == pytest.approx(440.0, abs=5.0)


@pytest.mark.parametrize("ts", [0.5, 2.0])
def test_tone_distortion_bounded_at_extreme_scales(ts):
    sr, x = get_fixture("tone_440hz")
    out = wsola_stretch(x, make_params(sr, ts))
    snr = sinusoid_residual_snr_db(out.output, sr, 440.0)
    assert snr > 20.0, f"residual SNR {snr:.1f} dB below 20 dB bound"


@pytest.mark.parametrize("ts", [0.5, 1.5])
def test_impulse_train_period_preserved(ts):
    sr, x = get_fixture("impulse_train_100hz")  # period 160 samples
    out = wsola_stretch(x, make_params(sr, ts))
    spacings = impulse_spacings(out.output)
    assert spacings.size >= 3
    assert np.median(spacings) == pytest.approx(160, abs=4)


def test_silence_yields_silence_with_zero_offsets():
    sr, x = get_fixture("silence")
    out = wsola_stretch(x, make_params(sr, 1.5))
    assert np.all(out.output == 0.0)
    assert all(o == 0 for o in out.offsets)
    # Every frame after the first saw an all-tie search (deterministic default).
    assert all(f.tied_candidates > 1 for f in out.frames[1:])


# --- Seams and end compensation ----------------------------------------------

def test_seam_continuity_on_tone():
    sr, x = get_fixture("tone_440hz")
    params = make_params(sr, 1.3)
    out = wsola_stretch(x, params)
    joins = [f.synthesis_pos for f in out.frames[1:]]
    report = seam_report(out.output, joins)
    assert report["worst_ratio"] < 3.0


def test_end_clamping_on_stretch():
    # At 2.0x the natural analysis position runs past the input tail; the
    # clamp engages and the output length is still exact.
    sr, x = get_fixture("tone_440hz")
    params = make_params(sr, 2.0)
    out = wsola_stretch(x, params)
    clamped = [f for f in out.frames if f.natural_pos != f.index * params.analysis_hop]
    assert clamped, "expected end clamping to engage at 2.0x"
    assert out.output.shape[0] == round(x.shape[0] * 2.0)
    assert np.all(np.isfinite(out.output))
