"""Noisy gradient fixture: invariant checks (seed preservation, label
connectivity, permutation stability, ridge separation) plus a frozen
regression anchor.

The frozen anchor in ``fixtures/data/noise_labels_expected.json`` is a
regression snapshot regenerated by ``scripts/freeze_noise_fixture.py``; the
authoritative references in this suite are the hand-computed fixtures
(two-basin, plateau, saddle), not this snapshot.
"""

from __future__ import annotations

import json
import random
from pathlib import Path

import numpy as np
from scipy import ndimage

from tests.fixtures.synthetic import noisy_gradient
from tests.helpers import assert_boundary_separates, run_from_seeds

ANCHOR_PATH = Path(__file__).parent / "fixtures" / "data" / "noise_labels_expected.json"


def test_seeds_preserved_on_noisy_gradient():
    gradient, seeds = noisy_gradient()
    result = run_from_seeds(gradient, seeds)
    for seed in seeds:
        assert result.labels[seed.row, seed.col] == seed.label


def test_each_basin_is_single_connected_component():
    gradient, seeds = noisy_gradient()
    result = run_from_seeds(gradient, seeds)
    structure = np.ones((3, 3), dtype=int)  # 8-connectivity, matches kernel
    for label in (1, 2, 3, 4):
        _, count = ndimage.label(result.labels == label, structure=structure)
        assert count == 1, f"label {label} splits into {count} components"


def test_full_coverage_without_mask():
    gradient, seeds = noisy_gradient()
    result = run_from_seeds(gradient, seeds)
    assert result.stats.unreached_pixels == 0
    assert (result.labels >= 0).all()


def test_boundary_separates_basins_on_noise():
    gradient, seeds = noisy_gradient()
    result = run_from_seeds(gradient, seeds)
    assert_boundary_separates(result.labels)


def test_seed_permutation_stability_on_noise():
    gradient, seeds = noisy_gradient()
    reference = run_from_seeds(gradient, seeds)
    rng = random.Random(7)
    for _ in range(5):
        shuffled = seeds[:]
        rng.shuffle(shuffled)
        result = run_from_seeds(gradient, shuffled)
        np.testing.assert_array_equal(result.labels, reference.labels)
        np.testing.assert_array_equal(result.boundary, reference.boundary)


def test_frozen_regression_anchor():
    gradient, seeds = noisy_gradient()
    result = run_from_seeds(gradient, seeds)
    anchor = json.loads(ANCHOR_PATH.read_text(encoding="utf-8"))
    assert anchor["fixture_seed"] == 20260927
    np.testing.assert_array_equal(
        result.labels, np.array(anchor["labels"], dtype=np.int32)
    )
