"""Tests for the provenance-aware relational evaluation engine.

Expected polynomials are hand-derived per the semiring rules:

* repeated derivations of the same answer add,
* each join binding multiplies its witnesses,
* a row joined with itself keeps the squared witness (x*x = x^2).

Numeric cross-checks use an *independent* naive weighted enumerator defined in
this test module (it never imports the engine), so expected numbers are not
generated by the code under test.
"""
import pytest

from app.provenance import language
from app.provenance.engine import evaluate
from app.provenance.expressions import Polynomial
from app.provenance.store import InputRow, RelationData


# ---------------------------------------------------------------------------
# Independent reference: naive bag semantics with weighted inputs.
# Plain Python loops over in-memory rows; shares no code with the engine.
# ---------------------------------------------------------------------------

def _scan(rel: RelationData):
    return [(dict(zip(rel.columns, row.values)), row.row_id, row.weight)
            for row in rel.rows]


def _weighted_select(rows, col, op, const):
    import operator
    ops = {"=": operator.eq, "!=": operator.ne, "<": operator.lt,
           "<=": operator.le, ">": operator.gt, ">=": operator.ge}
    out = {}
    for vals, wid, w in rows:
        v = vals[col]
        if v is None:
            continue
        try:
            keep = ops[op](v, const)
        except TypeError:
            keep = False
        if keep:
            key = tuple(vals[c] for c in sorted(vals))
            out[key] = out.get(key, 0) + w
    return out


def _weighted_join(rel_l, rel_r, pairs, out_cols):
    acc = {}
    for l, wl in [(r.values, r.weight) for r in rel_l.rows]:
        lmap = dict(zip(rel_l.columns, l))
        for r, wr in [(r.values, r.weight) for r in rel_r.rows]:
            rmap = dict(zip(rel_r.columns, r))
            ok = True
            for lc, rc in pairs:
                a, b = lmap[lc], rmap[rc]
                if a is None or b is None or a != b:
                    ok = False
                    break
            if ok:
                merged = {**{f"l.{k}": v for k, v in lmap.items()},
                          **{f"r.{k}": v for k, v in rmap.items()}}
                key = tuple(merged[c] for c in out_cols)
                acc[key] = acc.get(key, 0) + wl * wr
    return acc


def _poly_map(result):
    return {row.values: row.provenance for row in result.rows}


def _dataset(tmp_store_rows):
    """Build {relation: RelationData} from (name, cols, InputRow...)."""
    out = {}
    for name, cols, rows in tmp_store_rows:
        out[name] = RelationData(name=name, columns=cols, rows=tuple(rows))
    return out


# ---------------------------------------------------------------------------
# fixtures
# ---------------------------------------------------------------------------

R_ROWS = [
    InputRow("r1", ("a", 1), weight=2.0),
    InputRow("r2", ("a", 2), weight=3.0),
    InputRow("r3", ("b", 1), weight=4.0),  # duplicate join key 1
]
S_ROWS = [
    InputRow("s1", (1, "x"), weight=5.0),
    InputRow("s2", (2, "y"), weight=7.0),
    InputRow("s3", (None, "z"), weight=11.0),  # NULL key
]


@pytest.fixture
def dataset():
    return _dataset([
        ("R", ("id", "b"), R_ROWS),
        ("S", ("b", "c"), S_ROWS),
    ])


SCHEMA = {"R": ("id", "b"), "S": ("b", "c")}


def test_scan_duplicate_values_become_sum(dataset):
    # Two identical rows would be distinct witnesses: emulate with extra row.
    dataset["R2"] = RelationData("R2", ("id", "b"), (
        InputRow("d1", ("a", 1)), InputRow("d2", ("a", 1)),
    ))
    node = language.parse_query({"op": "relation", "relation": "R2"},
                                {"R2": ("id", "b")})
    result = evaluate(node, {"R2": dataset["R2"]})
    pm = _poly_map(result)
    assert pm[("a", 1)] == Polynomial.var("R2.d1") + Polynomial.var("R2.d2")


def test_select_filters_and_null_drops(dataset):
    node = language.parse_query(
        {"op": "select", "condition": {"col": "b", "op": ">=", "value": 2},
         "input": {"op": "relation", "relation": "R"}},
        SCHEMA,
    )
    result = evaluate(node, dataset)
    assert [r.values for r in result.rows] == [("a", 2)]
    assert _poly_map(result)[("a", 2)] == Polynomial.var("R.r2")


def test_select_null_never_satisfies_comparison(dataset):
    node = language.parse_query(
        {"op": "select", "condition": {"col": "b", "op": "!=", "value": 1},
         "input": {"op": "relation", "relation": "S"}},
        SCHEMA,
    )
    result = evaluate(node, dataset)
    # s3 has NULL b: NULL != 1 is UNKNOWN, so it must NOT appear
    assert {r.values for r in result.rows} == {(2, "y")}


def test_is_null_predicate(dataset):
    node = language.parse_query(
        {"op": "select", "condition": {"col": "b", "op": "is_null"},
         "input": {"op": "relation", "relation": "S"}},
        SCHEMA,
    )
    result = evaluate(node, dataset)
    assert [r.values for r in result.rows] == [(None, "z")]


def test_join_polynomial_is_hand_computed(dataset):
    query = {
        "op": "join",
        "left": {"op": "relation", "relation": "R", "alias": "l"},
        "right": {"op": "relation", "relation": "S", "alias": "r"},
        "on": [["l.b", "r.b"]],
    }
    node = language.parse_query(query, SCHEMA)
    result = evaluate(node, dataset)
    pm = _poly_map(result)

    # bindings: (r1,s1) key 1 ; (r3,s1) key 1 ; (r2,s2) key 2 ; s3 NULL -> none
    assert pm[("a", 1, 1, "x")] == Polynomial.var("R.r1") * Polynomial.var("S.s1")
    assert pm[("b", 1, 1, "x")] == Polynomial.var("R.r3") * Polynomial.var("S.s1")
    assert pm[("a", 2, 2, "y")] == Polynomial.var("R.r2") * Polynomial.var("S.s2")
    # the NULL-key row s3 joins with nothing
    assert all(vals[2:] != (None, "z") for vals in pm)
    assert set(pm) == {
        ("a", 1, 1, "x"), ("b", 1, 1, "x"), ("a", 2, 2, "y"),
    }

    # independent numeric cross-check
    weights = {f"R.{r.row_id}": r.weight for r in R_ROWS}
    weights.update({f"S.{r.row_id}": r.weight for r in S_ROWS})
    cols = ("l.id", "l.b", "r.b", "r.c")
    expected = _weighted_join(
        dataset["R"], dataset["S"], [("b", "b")], cols
    )
    for values, poly in pm.items():
        assert poly.evaluate(weights) == expected[values]


def test_self_join_squares_the_witness(dataset):
    # R R on b: r1*r1 (b=1, r1 pairs with itself and r3)
    query = {
        "op": "join",
        "left": {"op": "relation", "relation": "R", "alias": "l"},
        "right": {"op": "relation", "relation": "R", "alias": "r"},
        "on": [["l.b", "r.b"]],
    }
    schema = {"R": ("id", "b")}
    node = language.parse_query(query, schema)
    result = evaluate(node, {"R": dataset["R"]})
    pm = _poly_map(result)

    # r1 pairs with r1 -> r1^2 ; r1 pairs with r3 -> r1*r3 ; and symmetric
    out = pm[("a", 1, "a", 1)]
    assert out == (
        Polynomial.var("R.r1") * Polynomial.var("R.r1")
    )
    cross = pm[("a", 1, "b", 1)]
    assert cross == Polynomial.var("R.r1") * Polynomial.var("R.r3")
    # symmetric binding r3(left) x r1(right)
    cross_sym = pm[("b", 1, "a", 1)]
    assert cross_sym == Polynomial.var("R.r3") * Polynomial.var("R.r1")

    weights = {f"R.{r.row_id}": r.weight for r in R_ROWS}
    # weighted self-join enumerator: both branches read the SAME weighted R
    expected = _weighted_join(dataset["R"], dataset["R"], [("b", "b")],
                              ("l.id", "l.b", "r.id", "r.b"))
    for values, poly in pm.items():
        assert poly.evaluate(weights) == expected[values]


def test_union_duplicates_add(dataset):
    # R UNION T where T contains a row identical to one in R
    t_rows = [InputRow("t1", ("a", 1)), InputRow("t2", ("c", 3))]
    dataset["T"] = RelationData("T", ("id", "b"), tuple(t_rows))
    schema = {"R": ("id", "b"), "T": ("id", "b")}
    query = {
        "op": "union",
        "left": {"op": "relation", "relation": "R"},
        "right": {"op": "relation", "relation": "T"},
    }
    node = language.parse_query(query, schema)
    result = evaluate(node, dataset)
    pm = _poly_map(result)
    # the ("a",1) answer is witnessed once by R.r1 and once by T.t1 -> sum
    assert pm[("a", 1)] == Polynomial.var("R.r1") + Polynomial.var("T.t1")
    assert pm[("c", 3)] == Polynomial.var("T.t2")  # single witness
    weights = {**{f"R.{r.row_id}": r.weight for r in R_ROWS},
               "T.t1": 6.0, "T.t2": 8.0}
    assert pm[("a", 1)].evaluate(weights) == 2.0 + 6.0


def test_projection_merges_equal_projected_tuples(dataset):
    # project id only from R: r1 and r2 share... use distinct: project a
    # constant-ish column; here project b -> b=1 appears from r1 and r3
    query = {
        "op": "project", "columns": ["R.b"],
        "input": {"op": "relation", "relation": "R"},
    }
    node = language.parse_query(query, SCHEMA)
    result = evaluate(node, dataset)
    pm = _poly_map(result)
    assert pm[(1,)] == Polynomial.var("R.r1") + Polynomial.var("R.r3")
    assert pm[(2,)] == Polynomial.var("R.r2")


def test_full_pipeline_select_project_join_union_numeric(dataset):
    # (select R b=1) join S on b, project id,c ; UNION an identical-looking T.
    t_rows = [InputRow("t1", ("a", "x"))]
    dataset["T"] = RelationData("T", ("id", "c"), tuple(t_rows))
    schema = {"R": ("id", "b"), "S": ("b", "c"), "T": ("id", "c")}
    query = {
        "op": "union",
        "left": {
            "op": "project",
            "columns": ["l.id", "r.c"],
            "input": {
                "op": "join",
                "left": {
                    "op": "select",
                    "condition": {"col": "l.b", "op": "=", "value": 1},
                    "input": {"op": "relation", "relation": "R", "alias": "l"},
                },
                "right": {"op": "relation", "relation": "S", "alias": "r"},
                "on": [["l.b", "r.b"]],
            },
        },
        "right": {"op": "relation", "relation": "T"},
    }
    node = language.parse_query(query, schema)
    result = evaluate(node, dataset)
    pm = _poly_map(result)
    # ("a","x") derivations: r1*s1 from the join, t1 from the union -> sum
    assert pm[("a", "x")] == (
        Polynomial.var("R.r1") * Polynomial.var("S.s1")
        + Polynomial.var("T.t1")
    )
    assert pm[("b", "x")] == Polynomial.var("R.r3") * Polynomial.var("S.s1")

    weights = {**{f"R.{r.row_id}": r.weight for r in R_ROWS},
               **{f"S.{r.row_id}": r.weight for r in S_ROWS},
               "T.t1": 100.0}
    assert pm[("a", "x")].evaluate(weights) == 2 * 5 + 100
    assert pm[("b", "x")].evaluate(weights) == 4 * 5


def test_result_carries_labels(dataset):
    query = {
        "op": "project", "columns": ["l.id"],
        "input": {
            "op": "join",
            "left": {"op": "relation", "relation": "R", "alias": "l"},
            "right": {"op": "relation", "relation": "S", "alias": "r"},
            "on": [["l.b", "r.b"]],
        },
    }
    node = language.parse_query(query, SCHEMA)
    result = evaluate(node, dataset)
    assert result.labels == ("l.id",)
