"""Hand-computed provenance tests for the annotated-relational operators.

Leaves are built directly (no SQLite, no planner) so the reference polynomials
are computed by hand and cannot be generated by the code under test.
"""
from __future__ import annotations

from fractions import Fraction

import pytest

from provenance import engine
from provenance.engine import AnnotatedRelation, LeafRelation
from provenance.errors import PlanError, TypeRuleError
from provenance.polynomial import Poly, mono
from provenance.rule_language import Comparison


def leaf(name: str, columns, rows, binding: str | None = None) -> LeafRelation:
    return LeafRelation(
        binding=binding or name,
        name=name,
        columns=tuple(columns),
        tuples=tuple((str(i), dict(zip(columns, values))) for i, values in rows),
    )


def poly_for(relation: AnnotatedRelation, key) -> Poly:
    return relation.rows[tuple(key)]


# --------------------------------------------------------------------------- #
# Base relation + duplicate tuples
# --------------------------------------------------------------------------- #
def test_base_relation_duplicates_add():
    rel = engine.base_relation(
        leaf("R", ["A", "B"], [("1", ("a", "b")), ("2", ("a", "b")), ("3", ("a", "c"))])
    )
    # Two distinct input tuples with equal content coexist and add.
    assert poly_for(rel, ("a", "b")) == Poly(
        [(mono("R.1"), 1), (mono("R.2"), 1)]
    )
    assert poly_for(rel, ("a", "c")) == Poly.var("R.3")


# --------------------------------------------------------------------------- #
# Selection
# --------------------------------------------------------------------------- #
def test_select_keeps_polynomial_and_filters():
    rel = engine.base_relation(
        leaf("R", ["A", "B"], [("1", ("a", "b")), ("2", ("a", "c"))])
    )
    result, judgements = engine.select(rel, (Comparison("=", "B", literal="b"),))
    assert set(result.rows) == {("a", "b")}
    assert poly_for(result, ("a", "b")) == Poly.var("R.1")
    assert {j.truth for j in judgements} == {engine.TRUE, engine.FALSE}


def test_select_null_comparison_is_unknown_and_excluded():
    rel = engine.base_relation(
        leaf("R", ["A", "B"], [("1", ("a", None)), ("2", ("a", "b"))])
    )
    result, judgements = engine.select(rel, (Comparison("=", "B", literal="b"),))
    assert set(result.rows) == {("a", "b")}
    by_record = {j.record_id: j.truth for j in judgements}
    assert engine.UNKNOWN in by_record.values()  # the NULL row is indeterminate


def test_select_conjunction_three_valued_logic():
    # Row matches p1 but p2 is UNKNOWN -> overall UNKNOWN (excluded).
    rel = engine.base_relation(
        leaf("R", ["A", "B"], [("1", ("a", None))])
    )
    preds = (
        Comparison("=", "A", literal="a"),
        Comparison("=", "B", literal="x"),
    )
    result, _ = engine.select(rel, preds)
    assert result.rows == {}


# --------------------------------------------------------------------------- #
# Projection
# --------------------------------------------------------------------------- #
def test_projection_sums_collapsing_rows():
    rel = engine.base_relation(
        leaf("R", ["A", "B"], [("1", ("a", "b")), ("2", ("a", "b")), ("3", ("a", "c"))])
    )
    result = engine.project(rel, ("A",))
    assert poly_for(result, ("a",)) == Poly(
        [(mono("R.1"), 1), (mono("R.2"), 1), (mono("R.3"), 1)]
    )
    assert engine.multiplicity(poly_for(result, ("a",))) == 3


# --------------------------------------------------------------------------- #
# Join
# --------------------------------------------------------------------------- #
def test_join_multiplies_pairings():
    left = engine.base_relation(leaf("R", ["A", "B"], [("1", ("a", "b"))], binding="R"))
    right = engine.base_relation(
        leaf("S", ["B", "C"], [("1", ("b", "x")), ("2", ("b", "y"))], binding="S")
    )
    result, _ = engine.join(left, right, (Comparison("=", "R.B", right="S.B"),))
    assert poly_for(result, ("a", "b", "b", "x")) == Poly(
        [(mono("R.1", "S.1"), 1)]
    )
    assert poly_for(result, ("a", "b", "b", "y")) == Poly(
        [(mono("R.1", "S.2"), 1)]
    )


def test_self_join_same_tuple_pairs_to_square():
    # edge (d,d) joined with itself on dst=src: e6 pairs with itself -> x**2.
    left = engine.base_relation(
        leaf("edge", ["src", "dst"], [("6", ("d", "d"))], binding="eL")
    )
    right = engine.base_relation(
        leaf("edge", ["src", "dst"], [("6", ("d", "d"))], binding="eR")
    )
    result, _ = engine.join(left, right, (Comparison("=", "eL.dst", right="eR.src"),))
    ((key, poly)), = result.rows.items()
    assert key == ("d", "d", "d", "d")
    # Same physical input tuple on both sides -> variable squared, never 2*x.
    assert poly == Poly({mono("edge.6", "edge.6"): 1})
    assert poly.to_string() == "edge.6**2"


def test_join_rejects_unaliased_shared_binding():
    left = engine.base_relation(leaf("R", ["A"], [("1", ("a",))]))
    with pytest.raises(PlanError) as exc:
        engine.join(left, left, ())
    assert exc.value.category == "rejected_plan"


# --------------------------------------------------------------------------- #
# Union
# --------------------------------------------------------------------------- #
def test_union_adds_branches():
    left = engine.base_relation(
        leaf("U", ["A", "B"], [("1", ("a", 1)), ("2", ("a", 1))], binding="U")
    )
    right = engine.base_relation(
        leaf("V", ["A", "B"], [("1", ("a", 1)), ("2", ("a", 2))], binding="V")
    )
    result = engine.union(left, right)
    # (a,1) derivable via u1,u2,v1 -> three additive ways.
    assert poly_for(result, ("a", 1)) == Poly(
        [(mono("U.1"), 1), (mono("U.2"), 1), (mono("V.1"), 1)]
    )
    assert poly_for(result, ("a", 2)) == Poly.var("V.2")


def test_union_arity_mismatch_rejected():
    left = engine.base_relation(leaf("U", ["A"], [("1", ("a",))]))
    right = engine.base_relation(leaf("V", ["A", "B"], [("1", ("a", 1))]))
    with pytest.raises(PlanError) as exc:
        engine.union(left, right)
    assert exc.value.category == "rejected_plan"


# --------------------------------------------------------------------------- #
# Comparison typing / NULL scope
# --------------------------------------------------------------------------- #
def test_cross_type_ordering_is_indeterminate():
    with pytest.raises(TypeRuleError) as exc:
        engine.compare("<", "a", 1)
    assert exc.value.category == "indeterminate_type"


def test_cross_type_equality_is_false_not_an_ordering_guess():
    assert engine.compare("=", "1", 1) == engine.FALSE
    assert engine.compare("!=", "1", 1) == engine.TRUE


def test_numeric_equality_across_int_and_float():
    assert engine.compare("=", 1, 1.0) == engine.TRUE


# --------------------------------------------------------------------------- #
# Homomorphism: multiplicity equals the all-ones evaluation
# --------------------------------------------------------------------------- #
def test_full_tree_weight_and_multiplicity():
    # R(a,b) x2 distinct ids ; S(b,c) x2 ; join then project A.
    left = engine.base_relation(
        leaf("R", ["A", "B"], [("1", ("a", "b")), ("2", ("a", "b"))], binding="R")
    )
    right = engine.base_relation(
        leaf("S", ["B", "C"], [("1", ("b", "c1")), ("2", ("b", "c2"))], binding="S")
    )
    joined, _ = engine.join(left, right, (Comparison("=", "R.B", right="S.B"),))
    projected = engine.project(joined, ("A",))
    poly = poly_for(projected, ("a",))
    # 2 R tuples * 2 S tuples = 4 pairings.
    assert engine.multiplicity(poly) == 4
    # Hand expansion: r1*s1 + r1*s2 + r2*s1 + r2*s2
    expected = Poly(
        [
            (mono("R.1", "S.1"), 1),
            (mono("R.1", "S.2"), 1),
            (mono("R.2", "S.1"), 1),
            (mono("R.2", "S.2"), 1),
        ]
    )
    assert poly == expected
    weights = {
        "R.1": Fraction(2),
        "R.2": Fraction(3),
        "S.1": Fraction(5),
        "S.2": Fraction(7),
    }
    # (2+3)*(5+7) = 5*12 = 60
    assert poly.evaluate(weights) == Fraction(60)
