"""Tests for the independent finite-model enumerator.

The expected answers here are *hand-computed* from set-theoretic semantics, not
produced by the kernel.  A separate test module (test_cross_check.py) then
asserts the two independent implementations agree on every fixture, which is
the "reference answer must not be generated by the system under test itself"
requirement.
"""

from __future__ import annotations

from min_iowl.oracle.enumerator import enumerate_ontology, normalize

from .conftest import fixture_items, functional_items


def _verdict(items):
    nodes = [a for _, a in items]
    return enumerate_ontology(normalize(nodes))


# --------------------------------------------------------------- hand truth --
def test_simple_hierarchy_hand_computed_subsumptions() -> None:
    # Dog <= Mammal <= Animal. Enumerating all 8 labels by hand, the only
    # non-tautological subsumptions are the transitive closure edges.
    v = _verdict(functional_items(
        "SubClassOf(Dog Mammal)\nSubClassOf(Mammal Animal)"
    ))
    subs = set(v.subsumptions)
    assert ("Dog", "Mammal") in subs
    assert ("Mammal", "Animal") in subs
    assert ("Dog", "Animal") in subs
    assert ("Animal", "Dog") not in subs
    assert ("Mammal", "Dog") not in subs
    # all three classes are satisfiable; empty label is always valid
    assert all(c.satisfiable for c in v.classes)


def test_disjoint_classes_hand_computed_valid_labels() -> None:
    # DisjointClasses(A B): valid labels over {A,B} are {}, {A}, {B} (not {A,B})
    v = _verdict(functional_items("DisjointClasses(A B)"))
    assert v.labels_explored == 4
    a = next(c for c in v.classes if c.cls == "A")
    b = next(c for c in v.classes if c.cls == "B")
    assert a.satisfiable and a.witness == frozenset({"A"})
    assert b.satisfiable and b.witness == frozenset({"B"})
    # no individual here -> consistent
    assert v.ontology_consistent


def test_unsatisfiable_class_has_no_witness() -> None:
    # C <= A, C <= B, A disjoint B -> every valid label containing C impossible
    v = _verdict(functional_items(
        "SubClassOf(C A)\nSubClassOf(C B)\nDisjointClasses(A B)"
    ))
    c = next(x for x in v.classes if x.cls == "C")
    assert c.satisfiable is False and c.witness is None
    a = next(x for x in v.classes if x.cls == "A")
    assert a.satisfiable and a.witness == frozenset({"A"})
    # unsatisfiable TBox class with NO instance: ontology still consistent
    assert v.ontology_consistent is True


def test_instance_conflict_is_inconsistent_independently() -> None:
    # x asserted both A and B, A disjoint B -> no label fits x
    v = _verdict(functional_items(
        "DisjointClasses(A B)\nClassAssertion(A x)\nClassAssertion(B x)"
    ))
    assert v.ontology_consistent is False
    x = next(i for i in v.individuals if i.individual == "x")
    assert x.satisfiable is False and x.valid_labels == ()


def test_individual_entailed_types_hand_computed() -> None:
    # Dog <= Mammal <= Animal; rex : Dog -> in every fitting label rex carries
    # exactly {Dog, Mammal, Animal} (nothing else forced)
    v = _verdict(functional_items(
        "SubClassOf(Dog Mammal)\nSubClassOf(Mammal Animal)\nClassAssertion(Dog rex)"
    ))
    rex = next(i for i in v.individuals if i.individual == "rex")
    assert rex.entailed_types == frozenset({"Dog", "Mammal", "Animal"})


def test_equivalence_forces_labels_together() -> None:
    # EquivalentClasses(A B): valid labels are {} and {A,B}; an A-instance
    # necessarily carries B too.
    v = _verdict(functional_items(
        "EquivalentClasses(A B)\nClassAssertion(A z)"
    ))
    z = next(i for i in v.individuals if i.individual == "z")
    assert z.entailed_types == frozenset({"A", "B"})


def test_intersection_semantics_by_enumeration() -> None:
    # Father = Male & Parent (equivalence). An instance of Father must carry both.
    v = _verdict(functional_items(
        "EquivalentClasses(Father ObjectIntersectionOf(Male Parent))\n"
        "ClassAssertion(Father bob)"
    ))
    bob = next(i for i in v.individuals if i.individual == "bob")
    assert bob.entailed_types == frozenset({"Father", "Male", "Parent"})


# ------------------------------------------------------------- independence --
def test_oracle_module_does_not_import_kernel_or_rule_packages() -> None:
    import ast as py_ast
    import inspect
    import min_iowl.oracle.enumerator as enum_mod

    tree = py_ast.parse(inspect.getsource(enum_mod))
    imported_roots: set[str] = set()
    for node in py_ast.walk(tree):
        if isinstance(node, py_ast.Import):
            imported_roots.update(alias.name.split(".")[0] for alias in node.names)
        elif isinstance(node, py_ast.ImportFrom) and node.module:
            parts = node.module.split(".")
            # relative imports resolve inside min_iowl; record full local path
            if node.level == 0:
                imported_roots.add(parts[0])
            else:
                imported_roots.add("min_iowl." + parts[1] if len(parts) > 1 else "min_iowl")
    # Only shared dependency allowed is the purely-syntactic AST package.
    forbidden = {
        "min_iowl.kernel",
        "min_iowl.lang.compiler",
        "min_iowl.service",
    }
    assert not (imported_roots & forbidden), imported_roots
    # and concretely, no production-rule / fixpoint symbols are referenced
    src = inspect.getsource(enum_mod)
    assert " import engine" not in src
    assert "from ..kernel" not in src
    assert "from ..lang.compiler" not in src


# --------------------------------------------------------- fixture verdicts --
def test_fixture_unsat_but_consistent_oracle() -> None:
    v = _verdict(fixture_items("fixture_intersection_disjoint.json"))
    unsat = {c.cls for c in v.classes if not c.satisfiable}
    assert unsat == {"Hermaphrodite"}
    assert v.ontology_consistent is True


def test_fixture_mutex_oracle() -> None:
    v = _verdict(fixture_items("fixture_mutex_instance.json"))
    assert v.ontology_consistent is False
    assert all(c.satisfiable for c in v.classes)  # classes fine; instance breaks
