"""Kernel tests: concrete topology outcomes + an independent naive reference.

The naive reference below is a deliberately slow, per-pixel Python
re-implementation of Zhang-Suen written for this test file. The vectorized
kernel under test must match it exactly, so the expected answers are NOT
generated by the implementation under test.
"""

from __future__ import annotations

import numpy as np

from app import topology
from app.kernel import deletion_mask, thin


# --- independent naive reference (test-only) --------------------------------

def _naive_deletable(img: np.ndarray, r: int, c: int, sub: int) -> bool:
    p2 = img[r - 1, c]
    p3 = img[r - 1, c + 1]
    p4 = img[r, c + 1]
    p5 = img[r + 1, c + 1]
    p6 = img[r + 1, c]
    p7 = img[r + 1, c - 1]
    p8 = img[r, c - 1]
    p9 = img[r - 1, c - 1]
    ring = [p2, p3, p4, p5, p6, p7, p8, p9]
    b = sum(ring)
    if not 2 <= b <= 6:
        return False
    a = sum(1 for i in range(8) if ring[i] == 0 and ring[(i + 1) % 8] == 1)
    if a != 1:
        return False
    if sub == 1:
        return p2 * p4 * p6 == 0 and p4 * p6 * p8 == 0
    return p2 * p4 * p8 == 0 and p2 * p6 * p8 == 0


def naive_thin(img: np.ndarray, max_rounds: int = 10_000) -> np.ndarray:
    work = (img != 0).astype(np.uint8)
    work = np.pad(work, 1)  # guard border so indexing stays in range
    for _ in range(max_rounds):
        changed = False
        for sub in (1, 2):
            # synchronous: collect from one pre-state, apply afterwards
            to_delete = [
                (r, c)
                for r in range(1, work.shape[0] - 1)
                for c in range(1, work.shape[1] - 1)
                if work[r, c] == 1 and _naive_deletable(work, r, c, sub)
            ]
            for r, c in to_delete:
                work[r, c] = 0
            changed = changed or bool(to_delete)
        if not changed:
            break
    return work[1:-1, 1:-1]


# --- tests -------------------------------------------------------------------

def test_kernel_matches_naive_reference_on_random_image():
    rng = np.random.default_rng(20261003)
    img = (rng.random((24, 24)) < 0.45).astype(np.uint8)
    expected = naive_thin(img)
    got = thin(img).skeleton
    np.testing.assert_array_equal(got, expected)


def test_deletion_is_synchronous_within_subiteration():
    # A 2xN bar: sequential deletion would eat it from one end in a single
    # sub-iteration; synchronous deletion removes only the outer layer.
    img = np.zeros((7, 12), dtype=np.uint8)
    img[2:5, 1:11] = 1
    # Interior pixels of a solid bar must NOT be deletable in the same
    # sub-iteration as the boundary pixels.
    mask1 = deletion_mask(img, 1)
    assert not mask1[3, 3:9].any()
    # Zhang-Suen sub-iteration 1 peels the bottom row of the bar...
    assert mask1[4, 2:10].all()
    # ...and sub-iteration 2 peels the top row (from the same pre-state here).
    mask2 = deletion_mask(img, 2)
    assert mask2[2, 2:10].all()
    assert not mask2[3, 3:9].any()


def test_ring_skeleton_preserves_hole_and_has_no_endpoints(ring):
    result = thin(ring)
    skel = result.skeleton
    assert result.total_deleted > 0
    assert len(result.rounds) >= 2
    assert topology.count_foreground_components(skel) == 1
    assert topology.count_holes(skel) == 1  # the ring's hole survives
    assert int(topology.endpoint_pixels(skel).sum()) == 0  # closed loop
    assert topology.count_foreground_components(ring) == 1  # fixture sanity
    assert topology.count_holes(ring) == 1


def test_thin_bridge_is_already_skeleton(thin_bridge):
    result = thin(thin_bridge)
    np.testing.assert_array_equal(result.skeleton, thin_bridge)
    assert result.total_deleted == 0
    assert int(topology.endpoint_pixels(result.skeleton).sum()) == 2


def test_fork_skeleton_keeps_three_endpoints_and_one_component(fork):
    result = thin(fork)
    skel = result.skeleton
    assert topology.count_foreground_components(skel) == 1
    assert topology.count_holes(skel) == 0
    assert int(topology.endpoint_pixels(skel).sum()) == 3
    assert int(topology.junction_pixels(skel).sum()) >= 1


def test_empty_image_yields_empty_skeleton():
    result = thin(np.zeros((9, 9), dtype=np.uint8))
    assert int(result.skeleton.sum()) == 0
    assert result.total_deleted == 0
