"""Reference tests: kernel output vs hand-computed expectations in fixtures/.

The expected supports and embeddings in the fixture files were derived by
hand, not generated by the kernel, so this is an independent cross-check of
the full pattern/support/evidence output.
"""

import pytest

from app.corpus.fixtures import list_fixtures, load_fixture
from tests.conftest import embeddings_of, run_fixture_case

CASES = [
    (fixture_name, case["label"])
    for fixture_name in list_fixtures()
    for case in load_fixture(fixture_name)["cases"]
]


@pytest.mark.parametrize("fixture_name,case_label", CASES, ids=[f"{f}:{c}" for f, c in CASES])
def test_kernel_matches_hand_computed_reference(fixture_name, case_label):
    fixture = load_fixture(fixture_name)
    case = next(c for c in fixture["cases"] if c["label"] == case_label)
    actual = run_fixture_case(fixture, case)

    expected_patterns = set(case["expected"])
    absent = set(case.get("expected_absent", []))

    # exact support-set equality: nothing missing, nothing extra
    assert set(actual) == expected_patterns, (
        f"pattern set mismatch: missing={expected_patterns - set(actual)}, "
        f"unexpected={set(actual) - expected_patterns}"
    )
    assert absent.isdisjoint(actual)

    for pattern, expected in case["expected"].items():
        result = actual[pattern]
        assert result.support == expected["support"], (
            f"{pattern}: support {result.support} != {expected['support']}"
        )
        expected_embeddings = {
            sid: sorted(embs) for sid, embs in expected["embeddings"].items()
        }
        assert embeddings_of(result) == expected_embeddings, (
            f"{pattern}: embedding evidence mismatch"
        )
