"""Keyword vs identifier: longest match beats priority; offsets are original."""

from __future__ import annotations

from conftest import create_ok

RULES = [
    {"name": "KW", "pattern": "if|else|while", "priority": 0},
    {"name": "ID", "pattern": "[a-z][a-z0-9]*", "priority": 1},
    {"name": "WS", "pattern": "[ \\t\\n]+", "priority": 2},
]


def test_longest_match_beats_priority_and_offsets(client):
    created = create_ok(client, "kw-id", RULES)
    response = client.post(
        f"/api/rulesets/{created['ruleset_id']}/lex",
        json={"text": "if ifx else1 while"},
    )
    assert response.status_code == 200
    data = response.json()
    assert data["error"] is None
    got = [(t["rule"], t["text"], t["start"], t["end"]) for t in data["tokens"]]
    # Reference answer written by hand, not generated by the kernel.
    assert got == [
        ("KW", "if", 0, 2),      # exact keyword beats ID prefix
        ("WS", " ", 2, 3),
        ("ID", "ifx", 3, 6),     # longer than keyword "if" -> identifier wins
        ("WS", " ", 6, 7),
        ("ID", "else1", 7, 12),  # keyword "else" + digit -> identifier wins
        ("WS", " ", 12, 13),
        ("KW", "while", 13, 18),
    ]


def test_keyword_identifier_overlap_witness(client):
    created = create_ok(client, "kw-id-diag", RULES)
    overlaps = created["diagnostics"]["overlaps"]
    pair = {(o["rule_a"], o["rule_b"]): o["witness"] for o in overlaps}
    # KW and ID overlap on exactly the keywords; the shortest is "if".
    assert pair[("KW", "ID")] == "if"
    # WS shares no string with KW or ID.
    assert ("KW", "WS") not in pair
    assert ("ID", "WS") not in pair
    # Every rule can win something: nothing is unreachable here.
    assert created["diagnostics"]["unreachable"] == []
