"""Randomized differential test: kernel vs an independent brute-force oracle.

The oracle below is deliberately naive (enumerate every substring of every
document, test membership with ``in``) and shares no code with the mining
kernel, so reference answers are not generated by the implementation under
test.
"""

import random

from conftest import make_kernel


def brute_force_lcs(docs: list[bytes], min_docs: int):
    """Returns (max_length, {substring: {doc_index: [offsets]}})."""
    best: dict[bytes, dict[int, list[int]]] = {}
    best_len = 0
    for haystack_index, haystack in enumerate(docs):
        for start in range(len(haystack)):
            for stop in range(start + 1, len(haystack) + 1):
                sub = haystack[start:stop]
                if len(sub) < best_len:
                    continue
                coverage = {}
                for doc_index, doc in enumerate(docs):
                    offsets = []
                    pos = doc.find(sub)
                    while pos != -1:
                        offsets.append(pos)
                        pos = doc.find(sub, pos + 1)  # overlapping matches
                    if offsets:
                        coverage[doc_index] = offsets
                if len(coverage) < min_docs:
                    continue
                if len(sub) > best_len:
                    best_len = len(sub)
                    best = {}
                if sub not in best:
                    best[sub] = coverage
                else:
                    # merge offsets for this doc occurrence set
                    for doc_index, offsets in coverage.items():
                        best[sub].setdefault(doc_index, offsets)
    return best_len, best


def kernel_as_dict(kernel, min_docs: int):
    result = kernel.longest_common_substrings(min_docs=min_docs, max_candidates=1000)
    assert not result.truncated  # 1000 must be enough for these tiny corpora
    table = {}
    for candidate in result.candidates:
        coverage: dict[int, list[int]] = {}
        for occ in candidate.occurrences:
            coverage.setdefault(occ.doc_index, []).append(occ.offset)
        table[candidate.substring] = coverage
    return result.max_length, table


def test_kernel_matches_brute_force_on_random_corpora():
    rng = random.Random(20260927)
    alphabet = [ord("a"), ord("b"), ord("c"), 0x00, 0xFF]
    cases = 0
    for _ in range(150):
        doc_count = rng.randint(2, 4)
        docs = [
            bytes(rng.choice(alphabet) for _ in range(rng.randint(1, 12)))
            for _ in range(doc_count)
        ]
        min_docs = rng.randint(2, doc_count)
        kernel = make_kernel(docs)

        expected_len, expected = brute_force_lcs(docs, min_docs)
        actual_len, actual = kernel_as_dict(kernel, min_docs)

        assert actual_len == expected_len, f"docs={docs} min_docs={min_docs}"
        assert set(actual) == set(expected), f"docs={docs} min_docs={min_docs}"
        for sub, coverage in expected.items():
            assert actual[sub] == coverage, (
                f"coverage mismatch for {sub!r} in docs={docs} min_docs={min_docs}"
            )
        cases += 1
    assert cases == 150


def test_kernel_matches_brute_force_on_high_repetition_corpora():
    # Tiny alphabet maximizes ties and overlapping occurrences.
    rng = random.Random(7)
    for _ in range(60):
        docs = [
            bytes(rng.choice((ord("a"), ord("b"))) for _ in range(rng.randint(1, 10)))
            for _ in range(rng.randint(2, 3))
        ]
        min_docs = rng.randint(2, len(docs))
        kernel = make_kernel(docs)
        expected_len, expected = brute_force_lcs(docs, min_docs)
        actual_len, actual = kernel_as_dict(kernel, min_docs)
        assert actual_len == expected_len, f"docs={docs} min_docs={min_docs}"
        assert set(actual) == set(expected), f"docs={docs} min_docs={min_docs}"
        for sub, coverage in expected.items():
            assert actual[sub] == coverage
