"""Tests driven by the checked-in CSV fixture and its independently computed truth.

The CSV and its metadata are regenerated by ``experiments/make_fixture.py``.
The reference ATE is the empirical mean of the declared tau(X), recomputed
here from the raw columns rather than read from the estimator.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

import numpy as np
import pytest

from ipwate.pipeline import run_ipw

FIXTURE_DIR = Path(__file__).parent / "fixtures"


def _load_csv() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    rows = list(csv.DictReader((FIXTURE_DIR / "synth_good_n300.csv").open()))
    x = np.array([[float(r["x0"]), float(r["x1"]), float(r["x2"])] for r in rows])
    a = np.array([int(r["a"]) for r in rows], dtype=np.int8)
    y = np.array([float(r["y"]) for r in rows])
    return x, a, y


def test_fixture_matches_metadata_and_independent_truth():
    x, a, y = _load_csv()
    meta = json.loads((FIXTURE_DIR / "synth_good_n300.json").read_text())
    assert len(a) == meta["n"] == 300
    assert int(a.sum()) == meta["n_treated"]

    # Independent reference: recompute E[tau(X)] straight from the DGP formula.
    truth = float(np.mean(2.0 + 0.5 * x[:, 0]))
    assert truth == pytest.approx(meta["ate_true_on_sample"], abs=1e-10)

    result = run_ipw(x, a, y, overrides={"crossfit.n_splits": 3})
    assert result.verdict in ("accept", "warn")
    # n=300 has limited information; allow a generous but concrete tolerance.
    assert result.estimate.point == pytest.approx(truth, abs=0.6)
    assert result.n_covariates == 3


def test_fixture_is_deterministic_bytes():
    # Guards against accidental fixture drift breaking the reference answers.
    data = (FIXTURE_DIR / "synth_good_n300.csv").read_bytes()
    assert data.splitlines()[0] == b"x0,x1,x2,a,y"
    assert len(data.splitlines()) == 301
