"""Tests for site classification and distance models.

Reference values below are hand-computed from the published formulas
(NOT generated by the implementation under test):

- JC69:  d = -3/4 * ln(1 - 4p/3)
    p = 0.10 -> d = -0.75 * ln(0.866666...) = 0.10732563273050497
    p = 0.25 -> d = -0.75 * ln(0.666666...) = 0.30409883108112323
- K2P:   d = -1/2 * ln(1 - 2P - Q) - 1/4 * ln(1 - 2Q)
    P = 0.10, Q = 0.05 -> -0.5*ln(0.75) - 0.25*ln(0.90) = 0.17018116514034703
"""

from __future__ import annotations

import pytest

from app.models import (
    MATCH,
    TRANSITION,
    TRANSVERSION,
    EstimateStatus,
    Model,
    classify_site,
    count_sites,
    estimate_distance,
    site_outcomes,
)

# Hand-computed reference constants (see module docstring).
JC69_P010 = 0.10732563273050497
JC69_P025 = 0.30409883108112323
K2P_P010_Q005 = 0.17018116514034703


class TestSiteClassification:
    @pytest.mark.parametrize("a,b,expected", [
        ("A", "A", MATCH),
        ("A", "G", TRANSITION), ("G", "A", TRANSITION),
        ("C", "T", TRANSITION), ("T", "C", TRANSITION),
        ("A", "C", TRANSVERSION), ("A", "T", TRANSVERSION),
        ("G", "C", TRANSVERSION), ("G", "T", TRANSVERSION),
    ])
    def test_base_pairs(self, a, b, expected):
        assert classify_site(a, b) == expected

    @pytest.mark.parametrize("a,b", [
        ("A", "N"), ("N", "A"), ("-", "A"), ("A", "-"),
        ("R", "A"), ("A", "Y"), ("N", "-"), ("X", "X"),
    ])
    def test_missing_or_ambiguous_is_not_comparable(self, a, b):
        assert classify_site(a, b) is None

    def test_ambiguous_sites_excluded_from_counts(self):
        # positions: 0 match, 1 excluded (N), 2 match, 3 match, 4 match, 5 excluded
        counts = count_sites("ANCGT-", "AACGTN")
        assert counts.n_valid == 4
        assert counts.n_match == 4
        assert counts.p == 0.0


class TestPDistance:
    def test_known_mismatch_ratio(self, pair_factory):
        seq_a, seq_b = pair_factory(100, n_transition=6, n_transversion=4)
        est = estimate_distance(count_sites(seq_a, seq_b), Model.P_DISTANCE)
        assert est.status is EstimateStatus.OK
        assert est.distance == pytest.approx(0.10, abs=1e-12)
        assert est.p_distance == pytest.approx(0.10, abs=1e-12)

    def test_identical_sequences(self):
        est = estimate_distance(count_sites("ACGTACGT", "ACGTACGT"), Model.P_DISTANCE)
        assert est.distance == 0.0


class TestJC69:
    def test_hand_computed_value_p010(self, pair_factory):
        seq_a, seq_b = pair_factory(100, n_transition=6, n_transversion=4)
        est = estimate_distance(count_sites(seq_a, seq_b), Model.JC69)
        assert est.status is EstimateStatus.OK
        assert est.distance == pytest.approx(JC69_P010, rel=1e-12)

    def test_hand_computed_value_p025(self, pair_factory):
        seq_a, seq_b = pair_factory(100, n_transition=15, n_transversion=10)
        est = estimate_distance(count_sites(seq_a, seq_b), Model.JC69)
        assert est.distance == pytest.approx(JC69_P025, rel=1e-12)

    def test_identical_sequences_zero(self):
        est = estimate_distance(count_sites("ACGT", "ACGT"), Model.JC69)
        assert est.status is EstimateStatus.OK
        assert est.distance == 0.0

    def test_beyond_domain_is_saturated_not_abs_of_negative_log(self, pair_factory):
        # p = 0.80 >= 0.75 -> 1 - 4p/3 < 0. A buggy implementation would
        # return abs(-0.75*ln(|arg|)) = a fabricated positive number.
        seq_a, seq_b = pair_factory(100, n_transition=40, n_transversion=40)
        est = estimate_distance(count_sites(seq_a, seq_b), Model.JC69)
        assert est.status is EstimateStatus.SATURATED
        assert est.distance is None
        assert est.p_distance == pytest.approx(0.80)
        assert any("valid domain" in r for r in est.rationale)

    def test_exact_boundary_p_three_quarters_is_saturated(self, pair_factory):
        # p = 0.75 exactly -> log argument == 0 -> not estimable.
        seq_a, seq_b = pair_factory(100, n_transition=45, n_transversion=30)
        est = estimate_distance(count_sites(seq_a, seq_b), Model.JC69)
        assert est.status is EstimateStatus.SATURATED
        assert est.distance is None


class TestK2P:
    def test_hand_computed_value(self, pair_factory):
        # 100 sites: 10 transitions, 5 transversions -> P=0.10, Q=0.05
        seq_a, seq_b = pair_factory(100, n_transition=10, n_transversion=5)
        counts = count_sites(seq_a, seq_b)
        assert counts.P == pytest.approx(0.10)
        assert counts.Q == pytest.approx(0.05)
        est = estimate_distance(counts, Model.K2P)
        assert est.status is EstimateStatus.OK
        assert est.distance == pytest.approx(K2P_P010_Q005, rel=1e-12)

    def test_saturated_when_transversion_term_nonpositive(self, pair_factory):
        # Q = 0.60 -> 1 - 2Q = -0.2 <= 0
        seq_a, seq_b = pair_factory(100, n_transition=0, n_transversion=60)
        est = estimate_distance(count_sites(seq_a, seq_b), Model.K2P)
        assert est.status is EstimateStatus.SATURATED
        assert est.distance is None

    def test_saturated_when_combined_term_nonpositive(self, pair_factory):
        # P = 0.30, Q = 0.45 -> 1 - 2P - Q = -0.05 <= 0 (while 1 - 2Q > 0)
        seq_a, seq_b = pair_factory(100, n_transition=30, n_transversion=45)
        est = estimate_distance(count_sites(seq_a, seq_b), Model.K2P)
        assert est.status is EstimateStatus.SATURATED
        assert est.distance is None

    def test_identical_sequences_zero(self):
        est = estimate_distance(count_sites("ACGT", "ACGT"), Model.K2P)
        assert est.distance == 0.0


class TestUndefined:
    def test_all_missing_sequences(self):
        counts = count_sites("NNNN----", "NNNN----")
        assert counts.n_valid == 0
        for model in Model:
            est = estimate_distance(counts, model)
            assert est.status is EstimateStatus.UNDEFINED
            assert est.distance is None
            assert est.p_distance is None
            assert any("no comparable sites" in r for r in est.rationale)

    def test_site_outcomes_skips_noncomparable(self):
        assert site_outcomes("AN-C", "AT-G") == [MATCH, TRANSVERSION]
