"""Tests for the seeded site-resampling bootstrap.

The reference interval in TestReferenceInterval is produced by an
independent re-implementation written in this test file (plain-Python
counting and a hand-rolled linear-interpolation percentile), following
the documented algorithm spec - it does not call app.bootstrap or
app.models, so the reference answer is not generated by the code under
test.
"""

from __future__ import annotations

import math

import numpy as np
import pytest

from app.bootstrap import BootstrapStatus, bootstrap_ci
from app.errors import ResourceExhaustedError
from app.models import Model


def _reference_p_distance_ci(outcomes, replicates, confidence, seed):
    """Independent reference: p-distance bootstrap, plain-Python version."""
    n = len(outcomes)
    rng = np.random.Generator(np.random.PCG64(seed))
    values = []
    for _ in range(replicates):
        idx = rng.integers(0, n, size=n)
        mismatches = sum(1 for i in idx if outcomes[i] != 0)
        values.append(mismatches / n)
    values.sort()
    lo_q = (1.0 - confidence) / 2.0
    hi_q = (1.0 + confidence) / 2.0

    def percentile(sorted_vals, q):
        rank = q * (len(sorted_vals) - 1)
        low = math.floor(rank)
        high = min(low + 1, len(sorted_vals) - 1)
        frac = rank - low
        return sorted_vals[low] + frac * (sorted_vals[high] - sorted_vals[low])

    return percentile(values, lo_q), percentile(values, hi_q)


class TestReproducibility:
    def test_same_seed_same_interval(self):
        outcomes = [0] * 85 + [1] * 10 + [2] * 5
        r1 = bootstrap_ci(outcomes, Model.JC69, replicates=500, confidence=0.95, seed=42)
        r2 = bootstrap_ci(outcomes, Model.JC69, replicates=500, confidence=0.95, seed=42)
        assert (r1.ci_low, r1.ci_high, r1.n_saturated) == (r2.ci_low, r2.ci_high, r2.n_saturated)

    def test_different_seed_changes_interval(self):
        outcomes = [0] * 85 + [1] * 10 + [2] * 5
        r1 = bootstrap_ci(outcomes, Model.P_DISTANCE, 500, 0.95, seed=1)
        r2 = bootstrap_ci(outcomes, Model.P_DISTANCE, 500, 0.95, seed=2)
        assert (r1.ci_low, r1.ci_high) != (r2.ci_low, r2.ci_high)


class TestReferenceInterval:
    def test_matches_independent_reference_implementation(self):
        outcomes = [0] * 85 + [1] * 10 + [2] * 5
        result = bootstrap_ci(outcomes, Model.P_DISTANCE, replicates=400,
                              confidence=0.90, seed=7)
        ref_low, ref_high = _reference_p_distance_ci(outcomes, 400, 0.90, 7)
        assert result.status is BootstrapStatus.OK
        assert result.ci_low == pytest.approx(ref_low, abs=1e-12)
        assert result.ci_high == pytest.approx(ref_high, abs=1e-12)

    def test_interval_brackets_point_estimate(self):
        outcomes = [0] * 90 + [1] * 6 + [2] * 4  # p = 0.10
        result = bootstrap_ci(outcomes, Model.P_DISTANCE, 2000, 0.95, seed=123)
        assert result.ci_low < 0.10 < result.ci_high


class TestEdgeCases:
    def test_identical_sequences_degenerate_interval(self):
        result = bootstrap_ci([0] * 50, Model.K2P, 200, 0.95, seed=0)
        assert result.status is BootstrapStatus.OK
        assert result.ci_low == 0.0
        assert result.ci_high == 0.0
        assert result.n_saturated == 0

    def test_fully_saturated_replicates_not_estimable(self):
        # p = 1.0: every resample is entirely mismatched, so every JC69
        # replicate is deterministically out of domain.
        outcomes = [1] * 50 + [2] * 50
        result = bootstrap_ci(outcomes, Model.JC69, 100, 0.95, seed=5)
        assert result.status is BootstrapStatus.NOT_ESTIMABLE
        assert result.ci_low is None and result.ci_high is None
        assert result.n_saturated == 100

    def test_partial_saturation_is_counted_not_clamped(self):
        # p = 0.70: some resamples cross the 0.75 JC69 boundary.
        outcomes = [0] * 30 + [1] * 35 + [2] * 35
        result = bootstrap_ci(outcomes, Model.JC69, 1000, 0.95, seed=11)
        assert result.status is BootstrapStatus.OK
        assert 0 < result.n_saturated < 1000
        assert result.ci_low is not None and result.ci_high is not None

    def test_no_sites_not_estimable(self):
        result = bootstrap_ci([], Model.P_DISTANCE, 100, 0.95, seed=0)
        assert result.status is BootstrapStatus.NOT_ESTIMABLE

    def test_replicate_limit_is_resource_exhaustion(self):
        with pytest.raises(ResourceExhaustedError):
            bootstrap_ci([0, 1], Model.P_DISTANCE, replicates=100_001,
                         confidence=0.95, seed=0)
