"""Fixture-driven tests against INDEPENDENT hand/known-constant answers.

The fixture file (``tests/fixtures/root_cases.json``) contains:

* a hand-authored Sturm sign table for ``x^2 - 1`` (the headline constraint:
  sign variations are checked against the hand table, not the kernel);
* exact roots known from the factored form;
* a published decimal expansion of ``sqrt(2)`` and a known ``10^-20``
  scientific constant, neither produced by the system under test.
"""

from __future__ import annotations

import json
from fractions import Fraction as F
from pathlib import Path

import pytest

from root_isolator.evidence.verifier import build_verdict
from root_isolator.kernel.euclidean import sign_sequence, sturm_chain, variations_at
from root_isolator.kernel.isolate import isolate_roots
from root_isolator.kernel.polynomial import RationalPoly
from root_isolator.input.parser import parse_dense_coefficients

from . import oracle

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "root_cases.json"


@pytest.fixture(scope="module")
def fixtures():
    with FIXTURE_PATH.open() as handle:
        data = json.load(handle)
    return {case["id"]: case for case in data["cases"]}


def _poly_from_case(case, budget) -> RationalPoly:
    spec = case["polynomial"]
    parsed = parse_dense_coefficients(
        spec["coefficients"], order=spec.get("order", "descending"), budget=budget
    )
    return parsed.polynomial


# --------------------------------------------------------------------------- #
# Hand Sturm sign table for x^2 - 1: kernel signs must match the hand table
# --------------------------------------------------------------------------- #
def test_hand_sign_table_x_squared_minus_1(fixtures, budget):
    case = fixtures["x_squared_minus_1"]
    poly = _poly_from_case(case, budget)
    chain = sturm_chain(poly)

    assert len(chain) == len(case["hand_sturm_chain"])
    for row in case["hand_sign_table"]:
        point = F(row["point"])
        raw_signs = sign_sequence(chain, point)
        assert raw_signs == row["raw_signs"], f"signs mismatch at {point}"
        # Variation count is recomputed from the HAND signs, not from kernel.
        hand_nonzero = [s for s in row["raw_signs"] if s != 0]
        hand_variations = sum(
            1 for a, b in zip(hand_nonzero, hand_nonzero[1:]) if a != b
        )
        assert hand_variations == row["variations_ignoring_zeros"]
        assert variations_at(chain, point) == hand_variations
        assert (raw_signs[0] == 0) is row["first_member_is_zero"]


def test_half_open_counts_match_hand_table(fixtures, budget):
    case = fixtures["x_squared_minus_1"]
    sparse = oracle.poly_from_roots([(F(-1), 1), (F(1), 1)])
    ochain = oracle.sturm_chain_oracle(sparse)
    for entry in case["half_open_counts"]:
        interval = entry["interval"]
        # parse "(lo, hi]"
        lo, hi = interval.strip("()[] ").split(",")
        count = oracle.count_distinct_roots_open_closed(ochain, F(lo), F(hi))
        assert count == entry["count"], interval


# --------------------------------------------------------------------------- #
# Concrete count / multiplicity assertions for every fixture
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize(
    "case_id",
    [
        "x_squared_minus_1",
        "double_root_times_simple",
        "no_real_roots",
        "irrational_roots_sqrt2",
        "triple_root",
        "high_dynamic_range_tiny_roots",
    ],
)
def test_fixture_root_counts(fixtures, case_id, budget, numeric):
    case = fixtures[case_id]
    poly = _poly_from_case(case, budget)
    result = isolate_roots(poly, budget)
    assert result.distinct_real_roots == case["distinct_real_roots"], case_id
    assert (
        result.total_real_roots_with_multiplicity
        == case["real_roots_with_multiplicity"]
    ), case_id
    verdict = build_verdict(poly, result, numeric)
    assert verdict.complex_roots_with_multiplicity == (
        case["complex_roots_with_multiplicity"]
    )
    # Valid synthetic inputs are never rejected by exact evidence.
    assert verdict.status in {"accepted", "indeterminate"}


def test_double_root_multiplicities_from_fixture(fixtures, budget):
    case = fixtures["double_root_times_simple"]
    poly = _poly_from_case(case, budget)
    result = isolate_roots(poly, budget)
    mults = sorted(iv.multiplicity for iv in result.intervals)
    assert mults == [1, 2]


def test_triple_root_multiplicity_from_fixture(fixtures, budget):
    case = fixtures["triple_root"]
    poly = _poly_from_case(case, budget)
    result = isolate_roots(poly, budget)
    assert result.intervals[0].multiplicity == 3


# --------------------------------------------------------------------------- #
# Independent decimal constants (not generated by the kernel)
# --------------------------------------------------------------------------- #
def test_sqrt2_roots_match_published_decimal(fixtures, budget, numeric):
    from decimal import Decimal, localcontext

    case = fixtures["irrational_roots_sqrt2"]
    poly = _poly_from_case(case, budget)
    result = isolate_roots(poly, budget)
    verdict = build_verdict(poly, result, numeric)

    # mpmath renders 25 significant digits rounded; the fixture holds the full
    # published expansion. Compare as high-precision Decimals to 24 significant
    # digits (well beyond any float64, independently authored reference).
    produced = sorted(
        Decimal(bundle.mpmath["approximate_root"]) for bundle in verdict.intervals
    )
    reference = sorted(Decimal(value) for value in case["reference_roots_decimal"])
    with localcontext() as ctx:
        ctx.prec = 24
        for got, want in zip(produced, reference):
            assert +got == +want
            assert got == want or abs(got - want) < Decimal("1e-23")


def test_high_dynamic_range_float64_status(fixtures, budget, numeric):
    case = fixtures["high_dynamic_range_tiny_roots"]
    poly = _poly_from_case(case, budget)
    verdict = build_verdict(poly, isolate_roots(poly, budget), numeric)
    assert verdict.float64.status == case["float64_expected_status"]
    # Exact answer still correct despite the weak float64 witness.
    assert verdict.distinct_real_roots == 2
