"""Core crypto/draw output must match frozen vectors produced by the
stdlib-only reference implementation (tests/helpers/reference_impl.py).

These vectors are constants checked into tests/fixtures/; they are NOT
generated by the code under test, so a regression in the core cannot
silently move the goalposts.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from commit_reveal.crypto import commitment as commit_mod
from commit_reveal.crypto import seed as seed_mod
from commit_reveal.draw.deterministic import deterministic_ranking

VECTORS = json.loads(
    (Path(__file__).parent / "fixtures" / "reference_vectors.json").read_text()
)
ROUND_ID = VECTORS["round_id"]


@pytest.mark.parametrize("name", VECTORS["participants"])
def test_commitment_matches_frozen_vector(name):
    computed = commit_mod.compute_commitment(
        ROUND_ID,
        name,
        bytes.fromhex(VECTORS["values"][name]),
        bytes.fromhex(VECTORS["salts"][name]),
    )
    assert computed == VECTORS["commitments"][name]


def test_commitment_set_hash_matches_frozen_vector():
    entries = list(VECTORS["commitments"].items())
    assert commit_mod.commitment_set_hash(entries) == VECTORS["commitment_set_hash"]


def test_seed_full_reveal_matches_frozen_vector():
    values = [bytes.fromhex(v) for v in VECTORS["values"].values()]
    assert seed_mod.derive_seed(ROUND_ID, values).hex() == (
        VECTORS["full_reveal"]["seed"]
    )


def test_ranking_full_reveal_matches_frozen_vector():
    seed = bytes.fromhex(VECTORS["full_reveal"]["seed"])
    ranking = deterministic_ranking(VECTORS["participants"], seed)
    assert ranking == VECTORS["full_reveal"]["ranking"]
    assert ranking[0] == VECTORS["full_reveal"]["winner"]


def test_seed_abstention_matches_frozen_vector():
    values = [
        bytes.fromhex(VECTORS["values"][n]) for n in ("alice", "bob")
    ]
    assert seed_mod.derive_seed(ROUND_ID, values).hex() == (
        VECTORS["abstain_carol"]["seed"]
    )


def test_ranking_abstention_matches_frozen_vector():
    seed = bytes.fromhex(VECTORS["abstain_carol"]["seed"])
    ranking = deterministic_ranking(["alice", "bob"], seed)
    assert ranking == VECTORS["abstain_carol"]["ranking"]
    assert ranking[0] == VECTORS["abstain_carol"]["winner"]
