"""Unit tests for the allocation kernel.

Expected sequences are FROZEN LITERALS generated once from the independent
standard-library oracle (``reference/pbr.py``) and cross-checked against a
hand-written HKDF. They are deliberately not regenerated by the code under
test, so a change to either implementation breaks these tests instead of
silently re-baselining.
"""
from __future__ import annotations

import pytest

from stratblock.contract import TailPolicy, build_study_config, hamilton_counts
from stratblock.rng import (
    CounterStream,
    RngState,
    derive_stream_key,
    draw_next,
    initial_state,
)

# --- Frozen vectors (master_seed=20260927, study trial-X, stratum site=A)
FROZEN_STREAM_KEY_HEX = "ed790aa511e7fcca2e8b557a9d32caa9e4622c9ff6af3949947b43b4febbc70b"
FROZEN_SEQUENCE_12 = [1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1]
# block sizes drawn for the first three blocks (all size 4 for this stream)
FROZEN_BLOCK_SIZES = [4, 4, 4]

# --- 1:1:1 balanced-prefix, seed 7, study s2, stratum age=old|sex=F
FROZEN_BALANCED_SEQUENCE_9 = [0, 1, 2, 0, 1, 2, 0, 1, 2]

# --- 2:1 permuted, block size 3, seed 42, study s3
FROZEN_2_TO_1_A = [0, 1, 0, 0, 0, 1]
FROZEN_2_TO_1_B = [0, 0, 1, 0, 1, 0]


def _sequence(cfg, key: bytes, n: int) -> tuple[list[int], list[int]]:
    state = initial_state()
    arms: list[int] = []
    sizes: list[int] = []
    for _ in range(n):
        draw, state = draw_next(cfg, key, state)
        arms.append(draw.arm_index)
        if draw.position_in_block == 0:
            sizes.append(draw.block_size)
    return arms, sizes


@pytest.mark.unit
def test_stream_key_matches_frozen_vector() -> None:
    key = derive_stream_key(20260927, "trial-X", "site=A")
    assert key.hex() == FROZEN_STREAM_KEY_HEX


@pytest.mark.unit
def test_permuted_sequence_matches_frozen_vector(two_arm_cfg) -> None:
    key = derive_stream_key(20260927, "trial-X", "site=A")
    arms, sizes = _sequence(two_arm_cfg, key, 12)
    assert arms == FROZEN_SEQUENCE_12
    assert sizes == FROZEN_BLOCK_SIZES
    # Every complete block is exactly 2/2.
    for start in range(0, 12, 4):
        block = arms[start : start + 4]
        assert sorted(block) == [0, 0, 1, 1]


@pytest.mark.unit
def test_balanced_prefix_sequence_and_every_prefix_on_target(balanced_cfg) -> None:
    key = derive_stream_key(7, "bp-trial", "age=old|sex=F")
    arms, sizes = _sequence(balanced_cfg, key, 9)
    assert arms == FROZEN_BALANCED_SEQUENCE_9
    for n in range(1, 10):
        realised = [arms[:n].count(i) for i in range(3)]
        assert tuple(realised) == hamilton_counts(n, (1, 1, 1))


@pytest.mark.unit
def test_two_to_one_ratio_complete_blocks() -> None:
    cfg = build_study_config(
        "s3", ["C", "T"], ["k"], [3], [2, 1], TailPolicy.PERMUTED
    )
    arms_a, _ = _sequence(cfg, derive_stream_key(42, "s3", "k=A"), 6)
    arms_b, _ = _sequence(cfg, derive_stream_key(42, "s3", "k=B"), 6)
    assert arms_a == FROZEN_2_TO_1_A
    assert arms_b == FROZEN_2_TO_1_B
    for start in (0, 3):
        assert sorted(arms_a[start : start + 3]) == [0, 0, 1]


@pytest.mark.unit
def test_distinct_strata_get_independent_streams(two_arm_cfg) -> None:
    # Across many strata the streams must not be identical (derivation
    # binds the stratum key into the HKDF info field).
    sequences = set()
    for level in "ABCDEFGH":
        key = derive_stream_key(20260927, "trial-X", f"site={level}")
        arms, _ = _sequence(two_arm_cfg, key, 8)
        sequences.add(tuple(arms))
    assert len(sequences) >= 4  # coincidental equality of short runs is possible


@pytest.mark.unit
def test_rng_state_round_trip_is_bit_exact(two_arm_cfg) -> None:
    key = derive_stream_key(20260927, "trial-X", "site=A")
    state = initial_state()
    first_three = []
    for _ in range(3):
        draw, state = draw_next(two_arm_cfg, key, state)
        first_three.append(draw.arm_index)
    # Serialise the state midway and resume: results 4..12 must equal a
    # single uninterrupted run.
    resumed = state
    full_arms, _ = _sequence(two_arm_cfg, key, 12)
    tail: list[int] = []
    for _ in range(9):
        draw, resumed = draw_next(two_arm_cfg, key, resumed)
        tail.append(draw.arm_index)
    assert first_three + tail == full_arms


@pytest.mark.unit
def test_rejection_uniform_is_biased_free_on_distribution() -> None:
    # Bound 3 does not divide 2**32: rejection sampling must stay uniform.
    stream = CounterStream(derive_stream_key(1, "x", "y"), RngState())
    counts = [0, 0, 0]
    n = 30_000
    for _ in range(n):
        counts[stream.uniform(3)] += 1
    expected = n / 3
    # chi-square goodness of fit at 1% level (critical ~9.21 for df=2)
    chi2 = sum((c - expected) ** 2 / expected for c in counts)
    assert chi2 < 9.21
