// Reference tests: the kernel is compared against answers that are NOT
// produced by the kernel itself:
//   1. hand-derived closed-form nodes/weights for n = 1..5, generated by
//      tools/gen_reference_fixtures.cpp from textbook formulas
//      (Abramowitz & Stegun 25.4) into a TSV fixture;
//   2. the independent Golub-Welsch implementation (Eigen eigensolver)
//      from the benchmark module.

#include <cmath>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#include "benchmark/golub_welsch.hpp"
#include "gauss/legendre.hpp"
#include "tests.hpp"

#ifndef GAUSS_FIXTURE_PATH
#define GAUSS_FIXTURE_PATH "gauss_legendre_reference.tsv"
#endif

namespace gauss::test {

namespace {

struct FixtureRow {
  std::size_t n;
  std::size_t index;
  double node;
  double weight;
};

}  // namespace

void test_hand_computed_fixtures(TestContext& ctx) {
  std::ifstream in(GAUSS_FIXTURE_PATH);
  GAUSS_CHECK(ctx, in.good(), "reference fixture file must exist");
  if (!in) return;

  std::map<std::size_t, std::vector<std::pair<double, double>>> by_order;
  std::string line;
  std::size_t rows = 0;
  while (std::getline(in, line)) {
    if (line.empty() || line[0] == '#') continue;
    std::istringstream ls(line);
    FixtureRow row{};
    if (!(ls >> row.n >> row.index >> row.node >> row.weight)) continue;
    by_order[row.n].push_back({row.node, row.weight});
    ++rows;
  }
  // 1 + 2 + 3 + 4 + 5 nodes for the five reference rules.
  GAUSS_CHECK(ctx, rows == 15, "fixture must contain 15 node rows (n = 1..5)");
  GAUSS_CHECK(ctx, by_order.size() == 5, "fixture must cover orders 1..5");

  const LegendreSolver solver;
  for (const auto& [n, expected] : by_order) {
    auto result = solver.compute(n);
    GAUSS_CHECK(ctx, result.has_value(), "solver must succeed for fixture order");
    if (!result) continue;
    const auto& x = result.value().nodes();
    const auto& w = result.value().weights();
    double max_node_diff = 0.0;
    double max_weight_diff = 0.0;
    for (std::size_t i = 0; i < n; ++i) {
      max_node_diff = std::max(max_node_diff, std::abs(x[i] - expected[i].first));
      max_weight_diff =
          std::max(max_weight_diff, std::abs(w[i] - expected[i].second));
    }
    ctx.state({{"order", static_cast<long long>(n)},
               {"max_node_diff_vs_closed_form", max_node_diff},
               {"max_weight_diff_vs_closed_form", max_weight_diff}});
    GAUSS_CHECK(ctx, max_node_diff <= 1e-13,
                "nodes must match hand-derived closed forms to 1e-13");
    GAUSS_CHECK(ctx, max_weight_diff <= 1e-13,
                "weights must match hand-derived closed forms to 1e-13");
  }
}

void test_cross_check_golub_welsch(TestContext& ctx) {
  const LegendreSolver solver;
  for (const std::size_t n : {2, 3, 5, 16, 64}) {
    auto kernel = solver.compute(n);
    auto reference = benchmark::golub_welsch_legendre(n);
    GAUSS_CHECK(ctx, kernel.has_value() && reference.has_value(),
                "both kernel and Golub-Welsch reference must succeed");
    if (!kernel || !reference) continue;
    const auto& x = kernel.value().nodes();
    const auto& w = kernel.value().weights();
    const auto& rx = reference.value().nodes;
    const auto& rw = reference.value().weights;
    double max_node_diff = 0.0;
    double max_weight_diff = 0.0;
    for (std::size_t i = 0; i < n; ++i) {
      max_node_diff = std::max(max_node_diff, std::abs(x[i] - rx[i]));
      max_weight_diff = std::max(max_weight_diff, std::abs(w[i] - rw[i]));
    }
    ctx.state({{"order", static_cast<long long>(n)},
               {"max_node_diff_vs_golub_welsch", max_node_diff},
               {"max_weight_diff_vs_golub_welsch", max_weight_diff}});
    GAUSS_CHECK(ctx, max_node_diff <= 1e-12,
                "kernel nodes must agree with the independent eigensolver");
    GAUSS_CHECK(ctx, max_weight_diff <= 1e-11,
                "kernel weights must agree with the independent eigensolver");
  }
}

}  // namespace gauss::test
