"""Fixture reference answers must be correct independently of the kernel.

Every hand-written reference p-value in the fixture catalogue is checked with
the plain-Python ``itertools`` oracle, so the tests' expected answers cannot
silently be generated by the code under test.
"""
from __future__ import annotations

import pytest

from app.evidence import oracle_pvalue
from app.repro.fixtures import FIXTURES


@pytest.mark.parametrize("fixture_name", [
    "identical_outcomes",
    "balanced_small",
    "extreme_differences",
    "one_extreme_pair",
    "monotone_differences",
])
def test_fixture_reference_pvalues_are_independently_correct(fixture_name):
    fx = FIXTURES[fixture_name]
    ref = fx.reference
    for key, effect in (("pvalue_effect_0", 0.0),
                        ("pvalue_effect_1", 1.0),
                        ("pvalue_effect_10", 10.0)):
        if key not in ref:
            continue
        oracle_p, count, total = oracle_pvalue(fx.differences, effect)
        assert oracle_p == pytest.approx(ref[key]), (
            fixture_name, key, oracle_p, ref[key]
        )
        assert total == ref["randomization_set_size"]
        assert count == round(ref[key] * total)


def test_large_fixture_actually_exceeds_budget():
    from app.config import settings

    fx = FIXTURES["large_for_monte_carlo"]
    assert 2 ** fx.reference["n_pairs"] > settings.exact_budget_flips
