"""The independent reference Adam is validated against PyTorch-style math by hand.

Crucially these answers are NOT generated by ``adam_shard.adam``; the
reference path must stand on its own before it is trusted as an oracle.
"""

from __future__ import annotations

import numpy as np

from adam_shard.adam import AdamConfig
from adam_shard.reference_adam import ReferenceAdam


def _textbook_adam_run(params: dict, grads_seq: list[dict], cfg: AdamConfig):
    m = {n: np.zeros_like(p) for n, p in params.items()}
    v = {n: np.zeros_like(p) for n, p in params.items()}
    p = {n: x.copy() for n, x in params.items()}
    for t, grads in enumerate(grads_seq, start=1):
        for n in p:
            g = grads[n]
            m[n] = cfg.beta1 * m[n] + (1 - cfg.beta1) * g
            v[n] = cfg.beta2 * v[n] + (1 - cfg.beta2) * g * g
            mh = m[n] / (1 - cfg.beta1**t)
            vh = v[n] / (1 - cfg.beta2**t)
            p[n] = p[n] - cfg.lr * mh / (np.sqrt(vh) + cfg.eps)
    return p


def test_reference_matches_hand_textbook_over_several_steps():
    cfg = AdamConfig(lr=0.013, beta1=0.87, beta2=0.995, eps=1e-9)
    rng = np.random.default_rng(99)
    params = {"w": rng.standard_normal((4, 3)), "b": rng.standard_normal(4)}
    grads_seq = [
        {"w": rng.standard_normal((4, 3)), "b": rng.standard_normal(4)} for _ in range(5)
    ]

    opt = ReferenceAdam.initialize({n: p.copy() for n, p in params.items()}, cfg)
    running = {n: p.copy() for n, p in params.items()}
    for grads in grads_seq:
        running = opt.step(running, {n: g.copy() for n, g in grads.items()})

    expected = _textbook_adam_run(params, grads_seq, cfg)
    for n in expected:
        np.testing.assert_allclose(running[n], expected[n], rtol=1e-12, atol=1e-14)


def test_reference_step_counter_advances_and_moments_persist():
    cfg = AdamConfig()
    rng = np.random.default_rng(1)
    params = {"a": rng.standard_normal(5)}
    opt = ReferenceAdam.initialize(params, cfg)
    g = rng.standard_normal(5)
    params = opt.step(params, {"a": g})
    assert opt.t == 1
    m1, v1 = opt.moments["a"]
    np.testing.assert_allclose(m1, 0.1 * g)
    params = opt.step(params, {"a": g})
    assert opt.t == 2
    m2, _ = opt.moments["a"]
    np.testing.assert_allclose(m2, 0.9 * (0.1 * g) + 0.1 * g)


def test_reference_rejects_mismatched_name_sets():
    cfg = AdamConfig()
    opt = ReferenceAdam.initialize({"a": np.zeros(2)}, cfg)
    try:
        opt.step({"a": np.zeros(2), "b": np.zeros(1)}, {"a": np.zeros(2), "b": np.zeros(1)})
    except ValueError:
        return
    raise AssertionError("expected name-set mismatch rejection")
