"""RFC 5869 golden test vectors for HKDF-SHA256.

The expected OKM/PRK values below are transcribed from RFC 5869 Appendix A
— they are independent reference answers, NOT generated by the code under
test. Both the primary backend (cryptography) and the independent reference
backend (PyCryptodome) must reproduce them exactly.
"""

from __future__ import annotations

import pytest

from kds.crypto_adapter import hkdf_sha256, hkdf_sha256_reference

# RFC 5869, Appendix A.1 (Test Case 1, SHA-256)
CASE_1 = {
    "ikm": bytes.fromhex("0b" * 22),
    "salt": bytes.fromhex("000102030405060708090a0b0c"),
    "info": bytes.fromhex("f0f1f2f3f4f5f6f7f8f9"),
    "length": 42,
    "prk": "077709362c2e32df0ddc3f0dc47bba6390b6c73bb50f9c3122ec844ad7c2b3e5",
    "okm": (
        "3cb25f25faacd57a90434f64d0362f2a"
        "2d2d0a90cf1a5a4c5db02d56ecc4c5bf"
        "34007208d5b887185865"
    ),
}

# RFC 5869, Appendix A.2 (Test Case 2, SHA-256, longer inputs)
CASE_2 = {
    "ikm": bytes(range(0x00, 0x50)),
    "salt": bytes(range(0x60, 0xB0)),
    "info": bytes(range(0xB0, 0x100)),
    "length": 82,
    "okm": (
        "b11e398dc80327a1c8e7f78c596a4934"
        "4f012eda2d4efad8a050cc4c19afa97c"
        "59045a99cac7827271cb41c65e590e09"
        "da3275600c2f09b8367793a9aca3db71"
        "cc30c58179ec3e87c14c01d5c1f3434f"
        "1d87"
    ),
}

# RFC 5869, Appendix A.3 (Test Case 3, SHA-256, empty salt and info)
CASE_3 = {
    "ikm": bytes.fromhex("0b" * 22),
    "salt": b"",
    "info": b"",
    "length": 42,
    "okm": (
        "8da4e775a563c18f715f802a063c5a31"
        "b8a11f5c5ee1879ec3454e5f3c738d2d"
        "9d201395faa4b61a96c8"
    ),
}

CASES = [CASE_1, CASE_2, CASE_3]


@pytest.mark.parametrize("case", CASES, ids=["rfc5869-case1", "rfc5869-case2", "rfc5869-case3"])
def test_primary_backend_matches_rfc5869(case):
    okm = hkdf_sha256(case["ikm"], case["info"], case["length"], salt=case["salt"])
    assert okm.hex() == case["okm"]


@pytest.mark.parametrize("case", CASES, ids=["rfc5869-case1", "rfc5869-case2", "rfc5869-case3"])
def test_reference_backend_matches_rfc5869(case):
    okm = hkdf_sha256_reference(
        case["ikm"], case["info"], case["length"], salt=case["salt"]
    )
    assert okm.hex() == case["okm"]
