// Independent tests for the Pade kernel.
// Reference values are hand-derived as exact rationals (documented inline),
// NOT generated by the implementation under test.
#include <cmath>
#include <string>
#include <vector>

#include "pade/io.hpp"
#include "pade/solver.hpp"
#include "test_framework.hpp"

using pade::Options;
using pade::PadeResult;
using pade::StatusCode;
using pade::Real;

namespace {

std::vector<Real> expSeries(int nterms) {
    std::vector<Real> c(nterms);
    Real f = 1.0;
    for (int k = 0; k < nterms; ++k) {
        c[k] = (k == 0 ? 1.0 : f / k);
        f = c[k] * k; // keep factorial: after c[k]=1/k!
        f = c[k];
        c[k] = (k == 0 ? 1.0 : c[k]);
    }
    // rebuild cleanly: c_k = 1/k!
    f = 1.0;
    for (int k = 0; k < nterms; ++k) {
        if (k == 0) f = 1.0; else f *= k;
        c[k] = 1.0 / f;
    }
    return c;
}

} // namespace

// [1/1] of exp(x): (1+x/2)/(1-x/2).
TEST_CASE("exp[1/1] exact rational coefficients (hand calc)") {
    auto c = expSeries(8);
    Options o; o.numerator_order = 1; o.denominator_order = 1;
    PadeResult r = pade::padeApproximate(c, o);
    CHECK_MSG(r.status == StatusCode::kOk, pade::statusName(r.status));
    CHECK(r.normalized);
    CHECK_CLOSE(r.numerator_full[0], 1.0, 1e-14);
    CHECK_CLOSE(r.numerator_full[1], 0.5, 1e-14);
    CHECK_CLOSE(r.denominator_full[0], 1.0, 1e-14);
    CHECK_CLOSE(r.denominator_full[1], -0.5, 1e-14);
    CHECK(r.residual.matches_to_order);
    for (int k = 0; k <= 2; ++k)
        CHECK_CLOSE(r.residual.residual[k], 0.0, 1e-13);
    // first uncontrolled term r_{m+n+1} = (CB-A)_3 = -1/12
    // for exp[1/1] (leading error of the approximation is +1/12).
    CHECK(r.residual.next_term_available);
    CHECK_CLOSE(r.residual.next_term_residual, -1.0 / 12.0, 1e-13);
    // value at x=0.1 vs exp(0.1)
    pade::EvalResult e = pade::evaluatePade(r, 0.1);
    CHECK_MSG(e.status == StatusCode::kOk, e.message);
    CHECK_CLOSE(e.value, std::exp(0.1), 2e-4);
}

// [2/2] of exp(x): (1+x/2+x^2/12)/(1-x/2+x^2/12).
TEST_CASE("exp[2/2] exact rational coefficients (hand calc)") {
    auto c = expSeries(8);
    Options o; o.numerator_order = 2; o.denominator_order = 2;
    PadeResult r = pade::padeApproximate(c, o);
    CHECK_MSG(r.status == StatusCode::kOk, pade::statusName(r.status));
    CHECK_CLOSE(r.numerator_full[0], 1.0, 1e-14);
    CHECK_CLOSE(r.numerator_full[1], 0.5, 1e-14);
    CHECK_CLOSE(r.numerator_full[2], 1.0 / 12.0, 1e-14);
    CHECK_CLOSE(r.denominator_full[0], 1.0, 1e-14);
    CHECK_CLOSE(r.denominator_full[1], -0.5, 1e-14);
    CHECK_CLOSE(r.denominator_full[2], 1.0 / 12.0, 1e-14);
    CHECK(r.residual.matches_to_order);
    for (int k = 0; k <= 4; ++k)
        CHECK_CLOSE(r.residual.residual[k], 0.0, 1e-12);
    CHECK(r.residual.next_term_available);
    // r_5 = +1/720 for CB-A (R-f leading term is -1/720)
    CHECK_CLOSE(r.residual.next_term_residual, 1.0 / 720.0, 1e-13);
    CHECK(r.rank.numerical_rank == 2);
    CHECK(r.rank.nullity == 1);
    CHECK(r.reduction.monomial_shift == 0);
    CHECK(r.reduction.polynomial_gcd_degree == 0);
    CHECK(r.reduction.reduced_m == 2);
    CHECK(r.reduction.reduced_n == 2);
}

// [0/1] of exp(x): 1/(1-x).
TEST_CASE("exp[0/1] and zero-order edge cases") {
    auto c = expSeries(4);
    Options o; o.numerator_order = 0; o.denominator_order = 1;
    PadeResult r = pade::padeApproximate(c, o);
    CHECK_MSG(r.status == StatusCode::kOk, pade::statusName(r.status));
    CHECK_CLOSE(r.numerator_full[0], 1.0, 1e-15);
    CHECK_CLOSE(r.denominator_full[1], -1.0, 1e-14);

    Options o2; o2.numerator_order = 2; o2.denominator_order = 0;
    PadeResult r2 = pade::padeApproximate(c, o2);
    CHECK_MSG(r2.status == StatusCode::kOk, pade::statusName(r2.status));
    for (int k = 0; k <= 2; ++k)
        CHECK_CLOSE(r2.numerator_full[k], c[k], 1e-15);
    CHECK_CLOSE(r2.denominator_full[0], 1.0, 1e-15);
}
