"""Tests for the independent verifier.

The verifier must not rubber-stamp the kernel.  These tests take a valid
result and corrupt it in specific ways; the verifier is required to catch
each corruption.  They also hand the verifier a hand-built fake result object
so nothing about the expected outputs is generated by the planner.
"""

from __future__ import annotations

from dataclasses import replace

import pytest

from htn_planner.core.engine import Bounds, Planner
from htn_planner.lang import parse_domain, parse_problem
from htn_planner.verify import Verifier

SIMPLE_DOMAIN = """
(:domain d
  (:operator (!a) (:pre (ready)) (:del (ready)) (:add (done-a)))
  (:operator (!b) (:pre (done-a)) (:del (done-a)) (:add (done-b)))
  (:method m (go) (:pre) (:tasks (!a) (!b))))
"""


def _plan():
    domain = parse_domain(SIMPLE_DOMAIN)
    problem = parse_problem(
        "(:problem p (:domain d) (:init (ready)) (:tasks (go)))"
    )
    result = Planner().solve(domain, problem, "req-v")
    return domain, problem, result


class TestVerifierAcceptsValidPlan:
    def test_valid_plan_passes_all_dimensions(self) -> None:
        domain, problem, result = _plan()
        report = Verifier().verify(domain, problem, result)
        assert report.ok is True
        assert report.executable is True
        assert report.hierarchy_consistent is True
        assert report.order_consistent is True


class TestVerifierDetectsCorruption:
    def test_swapped_action_order_is_detected(self) -> None:
        domain, problem, result = _plan()
        # Swap the two actions: !b before !a violates !b's precondition.
        a1, a2 = result.plan
        corrupted = replace(result, plan=(a2, a1))
        report = Verifier().verify(domain, problem, corrupted)
        assert report.executable is False
        assert any(v.code == "precondition_failed" for v in report.violations)

    def test_fabricated_action_is_detected(self) -> None:
        domain, problem, result = _plan()
        fake = replace(result.plan[0], operator="!ghost")
        corrupted = replace(result, plan=(fake,) + result.plan[1:])
        report = Verifier().verify(domain, problem, corrupted)
        assert report.ok is False
        assert any(v.code == "unknown_operator" for v in report.violations)

    def test_removing_precondition_dependency_from_tree_is_detected(self) -> None:
        domain, problem, result = _plan()
        # Claim the method had only !a as a child while the plan has two ops.
        tree = list(result.expansion)
        method_node = next(r for r in tree if r.expanded_by == "m")
        tampered_node = replace(method_node, children=(method_node.children[0],))
        tampered_tree = tuple(
            tampered_node if r.node_id == method_node.node_id else r for r in tree
        )
        corrupted = replace(result, expansion=tampered_tree)
        report = Verifier().verify(domain, problem, corrupted)
        assert report.hierarchy_consistent is False

    def test_tree_action_arity_mismatch_is_detected(self) -> None:
        domain, problem, result = _plan()
        leaves = [r for r in result.expansion if r.kind == "primitive"]
        tampered = replace(leaves[0], task=("!a", "extra-arg"))
        tampered_tree = tuple(
            tampered if r.node_id == leaves[0].node_id else r
            for r in result.expansion
        )
        corrupted = replace(result, expansion=tampered_tree)
        report = Verifier().verify(domain, problem, corrupted)
        assert any(v.code == "tree_action_mismatch" for v in report.violations)

    def test_inverting_order_edge_is_detected(self) -> None:
        domain = parse_domain(
            """
            (:domain d
              (:operator (!a) (:pre) (:del) (:add (pa)))
              (:operator (!b) (:pre (pa)) (:del (pa)) (:add (pb)))
              (:method m (t) (:pre) (:tasks (!a) (!b))))
            """
        )
        problem = parse_problem("(:problem p (:domain d) (:init) (:tasks (t)))")
        result = Planner().solve(domain, problem, "req-o")
        # Flip the ordered method's child order in the tree only.
        tampered_tree = tuple(
            replace(r, children=tuple(reversed(r.children)))
            if r.expanded_by == "m"
            else r
            for r in result.expansion
        )
        corrupted = replace(result, expansion=tampered_tree)
        report = Verifier().verify(domain, problem, corrupted)
        assert report.hierarchy_consistent is False


class TestVerifierFailures:
    def test_spurious_no_method_is_rejected(self) -> None:
        # A task that DOES have an applicable method, but the planner (falsely)
        # claims none applies.  The verifier must independently find m.
        domain = parse_domain(SIMPLE_DOMAIN)
        problem = parse_problem(
            "(:problem p (:domain d) (:init (ready)) (:tasks (go)))"
        )
        result = Planner().solve(domain, problem, "req-f")
        from htn_planner.core.evidence import FailureRecord

        fake_failure = FailureRecord(
            category="no_applicable_method",
            task=["go"],
            detail="fabricated",
            depth=0,
            method_chain=("root",),
            action_prefix=(),
            rejected_methods=(
                {"method": "m", "reason": "precondition", "unmet": "(ready)",
                 "failure_kind": "no_matching_fact"},
            ),
        )
        corrupted = replace(
            result, status="failure", plan=(), expansion=(), failures=(fake_failure,)
        )
        report = Verifier().verify(domain, problem, corrupted)
        assert report.failure_sound is False
        assert any(v.code == "unsound_failure" for v in report.violations)

    def test_real_deadlock_is_corroborated(self) -> None:
        domain = parse_domain(
            """
            (:domain d
              (:operator (!g ?r) (:pre (free ?r)) (:del (free ?r)) (:add (h ?r)))
              (:method mc (c ?r) (:pre) (:tasks (!g ?r)))
              (:method mb (both ?r) (:pre)
                (:tasks (:partial ((c ?r) (c ?r))))))
            """
        )
        problem = parse_problem(
            "(:problem p (:domain d) (:init (free R)) (:tasks (both R)))"
        )
        result = Planner().solve(domain, problem, "req-d")
        assert result.status == "failure"
        report = Verifier().verify(domain, problem, result)
        assert report.failure_sound is True
        assert report.ok is True

    def test_deadlock_claim_with_executable_minimal_is_rejected(self) -> None:
        # Verifier is handed a deadlock snapshot whose minimal action actually
        # has its precondition satisfied - it must call the claim spurious.
        from htn_planner.core.evidence import FailureRecord

        domain = parse_domain(SIMPLE_DOMAIN)
        problem = parse_problem(
            "(:problem p (:domain d) (:init (ready)) (:tasks (go)))"
        )
        result = Planner().solve(domain, problem, "req-x")
        fake = FailureRecord(
            category="deadlock",
            task=None,
            detail="fabricated deadlock",
            depth=0,
            method_chain=("root",),
            action_prefix=(),
            blocked=(
                {"task": ["!a"], "operator": "!a", "reason": "precondition",
                 "unmet": "(ready)"},
            ),
            remaining_tasks=(
                {"node": "t1", "task": ["!a"], "depth": 0, "minimal": True},
            ),
            remaining_edges=(),
        )
        corrupted = replace(
            result, status="failure", plan=(), expansion=(), failures=(fake,)
        )
        report = Verifier().verify(domain, problem, corrupted)
        assert report.failure_sound is False
        assert any("actually executable" in v.detail for v in report.violations)


class TestInconclusiveIsNotVerified:
    def test_budget_cut_is_reported_as_unverifiable(self) -> None:
        domain = parse_domain(
            """
            (:domain d
              (:operator (!t ?x) (:pre (at ?x)) (:del (at ?x)) (:add (done ?x)))
              (:operator (!h ?x ?y) (:pre (at ?x) (e ?x ?y)) (:del (at ?x)) (:add (at ?y)))
              (:method mb (w ?x) (:pre (target ?x)) (:tasks (!t ?x)))
              (:method ms (w ?x) (:pre (e ?x ?y) (not (target ?x)))
                (:tasks (!h ?x ?y) (w ?y))))
            """
        )
        problem = parse_problem(
            "(:problem p (:domain d) (:init (at a) (e a b) (target b)) (:tasks (w a)))"
        )
        result = Planner(Bounds(max_depth=0)).solve(domain, problem, "req-i")
        assert result.status == "inconclusive"
        report = Verifier().verify(domain, problem, result)
        assert report.ok is False
        assert any(
            v.code == "inconclusive_not_verifiable" for v in report.violations
        )
