"""Domain algorithm tests with hand-computed reference values.

Reference values are computed inline with math.log directly from the
published formulas (JC69, K80), independently of the implementation under
test; none of them are generated by seqdist itself.
"""
import math

import pytest

from seqdist.distance import (
    EstimateStatus,
    classify_sites,
    correct,
    estimate_from_stats,
)
from seqdist.errors import ErrorCategory, NoValidSitesError
from seqdist.parsing import parse_pair


def stats_of(s1: str, s2: str):
    return classify_sites(parse_pair(s1, s2))


# --- site classification -------------------------------------------------

def test_identical_sequences_give_zero_distances():
    stats = stats_of("ACGTACGT", "ACGTACGT")
    assert stats.n_valid == 8 and stats.n_mismatch == 0
    for model in ("p", "jc69", "k80"):
        est = estimate_from_stats(stats, model)
        assert est.status is EstimateStatus.OK
        assert est.value == 0.0


def test_ambiguous_and_gap_sites_are_excluded_and_counted():
    # columns: A/A match | N/C ambiguous | -/G gap | G/C transversion
    stats = stats_of("AN-G", "ACGC")
    assert stats.n_valid == 2
    assert stats.n_match == 1
    assert stats.n_transversion == 1
    assert stats.n_excluded_ambiguous == 1
    assert stats.n_excluded_gap == 1
    assert stats.p == pytest.approx(0.5)


def test_all_missing_sequences_raise_no_valid_sites():
    with pytest.raises(NoValidSitesError) as excinfo:
        stats_of("NNNN", "N-NN")
    err = excinfo.value
    assert err.category is ErrorCategory.COMPUTATION_FAILURE
    assert err.detail["n_excluded_ambiguous"] == 3
    assert err.detail["n_excluded_gap"] == 1


def test_transition_transversion_classification():
    # A->G, A->G, C->T are transitions; C->A is a transversion.
    stats = stats_of("AACC", "GGTA")
    assert (stats.n_transition, stats.n_transversion) == (3, 1)


# --- hand-computed corrections --------------------------------------------

def test_jc69_hand_computed_p_02():
    # 20 sites, 4 mismatches (all transitions): p = 0.2
    stats = stats_of("A" * 20, "A" * 16 + "G" * 4)
    assert stats.p == pytest.approx(0.2)
    est = estimate_from_stats(stats, "jc69")
    expected = -0.75 * math.log(1.0 - 4.0 * 0.2 / 3.0)  # = 0.232616...
    assert est.status is EstimateStatus.OK
    assert est.value == pytest.approx(expected, rel=1e-12)
    assert est.value == pytest.approx(0.23261619622787967, rel=1e-9)


def test_k80_hand_computed_mixed_ti_tv():
    # 20 sites vs all-A reference: 10 matches, 4 A->G transitions,
    # 4 A->C + 2 A->T transversions  =>  P = 0.2, Q = 0.3
    stats = stats_of("A" * 20, "A" * 10 + "G" * 4 + "C" * 4 + "T" * 2)
    assert stats.transition_fraction == pytest.approx(0.2)
    assert stats.transversion_fraction == pytest.approx(0.3)
    est = estimate_from_stats(stats, "k80")
    expected = -0.5 * math.log(1 - 2 * 0.2 - 0.3) - 0.25 * math.log(1 - 2 * 0.3)
    assert est.status is EstimateStatus.OK
    assert est.value == pytest.approx(expected, rel=1e-12)
    assert est.value == pytest.approx(0.8310590851315068, rel=1e-9)


def test_k80_hand_computed_transitions_only():
    # P = 0.2, Q = 0  =>  d = -1/2 ln(0.6)
    stats = stats_of("A" * 20, "A" * 16 + "G" * 4)
    est = estimate_from_stats(stats, "k80")
    assert est.value == pytest.approx(-0.5 * math.log(0.6), rel=1e-12)


# --- saturation / valid domain --------------------------------------------

def test_jc69_saturates_at_p_equal_three_quarters():
    # p = 0.75 exactly: log argument is 0 -> SATURATED, value None
    stats = stats_of("AAAA", "AGCT")
    assert stats.p == pytest.approx(0.75)
    est = estimate_from_stats(stats, "jc69")
    assert est.status is EstimateStatus.SATURATED
    assert est.value is None
    assert "1-4p/3" in est.reason


def test_jc69_saturates_beyond_domain_without_abs_of_negative_log():
    # p = 0.8 (4 mismatches of 5): log argument is negative. A bogus
    # implementation would return abs(-0.75*ln(|1-4p/3|)); we must not.
    stats = stats_of("AAAAA", "AGCTT")
    assert stats.p == pytest.approx(0.8)
    est = estimate_from_stats(stats, "jc69")
    assert est.status is EstimateStatus.SATURATED
    assert est.value is None


def test_k80_saturates_when_transversions_hit_half():
    # Q = 1.0 (all transversions): 1 - 2Q = -1 <= 0
    stats = stats_of("AAAA", "CCTT")
    est = estimate_from_stats(stats, "k80")
    assert est.status is EstimateStatus.SATURATED
    assert est.value is None


def test_p_distance_is_defined_where_corrections_saturate():
    # Same saturated pair: the plain p-distance remains a valid estimate.
    stats = stats_of("AAAAA", "AGCTT")
    est = estimate_from_stats(stats, "p")
    assert est.status is EstimateStatus.OK
    assert est.value == pytest.approx(0.8)


def test_correct_rejects_unknown_model_as_input_error():
    from seqdist.errors import InputValidationError

    with pytest.raises(InputValidationError):
        correct(0.1, 0.05, 0.05, "tn93")
