"""Blind index properties, cross-checked against a stdlib-only recomputation
so the reference is not generated by the implementation under test."""
import hashlib
import hmac

from sensitive_layer.crypto.blind_index import compute_index
from sensitive_layer.protocol.framing import index_message

KEY = bytes.fromhex("520e455d90a99a8b4e35ca4f42184cf5c8ad5630400be761330fce015251a0ed")
OTHER_KEY = bytes.fromhex("053c2743457ff13a16d3ace29e3cc3e501d825dc48364d1a5dde0d4e74e8bff2")


def stdlib_index(key, purpose, norm_version, normalized, bits):
    def lp(b):
        return len(b).to_bytes(2, "big") + b
    msg = (b"BI\x01" + lp(purpose.encode()) + lp(norm_version.encode())
           + lp(normalized.encode()))
    digest = hmac.new(key, msg, hashlib.sha256).digest()
    nbytes = (bits + 7) // 8
    out = bytearray(digest[:nbytes])
    if bits % 8:
        out[-1] &= (0xFF << (8 - bits % 8)) & 0xFF
    return bytes(out)


def test_deterministic():
    msg = index_message("lookup:email", "nfkc-casefold-v1", "alice@example.com")
    assert compute_index(KEY, msg, 32) == compute_index(KEY, msg, 32)


def test_matches_stdlib_reference():
    for bits in (8, 16, 32, 64, 256):
        msg = index_message("lookup:email", "nfkc-casefold-v1", "alice@example.com")
        assert compute_index(KEY, msg, bits) == stdlib_index(
            KEY, "lookup:email", "nfkc-casefold-v1", "alice@example.com", bits)


def test_domain_separation_by_purpose():
    a = compute_index(KEY, index_message("lookup:email", "nfkc-casefold-v1", "x@example.com"), 64)
    b = compute_index(KEY, index_message("alias:email", "nfkc-casefold-v1", "x@example.com"), 64)
    assert a != b


def test_domain_separation_by_norm_version():
    a = compute_index(KEY, index_message("lookup:email", "nfkc-casefold-v1", "x@example.com"), 64)
    b = compute_index(KEY, index_message("lookup:email", "nfkc-casefold-v2", "x@example.com"), 64)
    assert a != b


def test_key_change_changes_index():
    msg = index_message("lookup:email", "nfkc-casefold-v1", "x@example.com")
    assert compute_index(KEY, msg, 64) != compute_index(OTHER_KEY, msg, 64)


def test_truncation_length():
    msg = index_message("lookup:email", "nfkc-casefold-v1", "x@example.com")
    assert len(compute_index(KEY, msg, 8)) == 1
    assert len(compute_index(KEY, msg, 16)) == 2
    assert len(compute_index(KEY, msg, 12)) == 2  # non-byte-aligned rounds up


def test_framing_has_no_concat_ambiguity():
    # ("ab", "c") and ("a", "bc") must not collapse to the same message.
    a = index_message("ab", "v1", "c")
    b = index_message("a", "v1", "bc")
    assert a != b
