// SPDX-License-Identifier: MIT
//
// Reusable local synthetic fixtures: CSV loader and SHA-256 manifest check.
// No external/network data participates; fixtures are generated by
// tools/gen_fixtures and verified before use.
#ifndef CHEBCORE_FIXTURES_HPP
#define CHEBCORE_FIXTURES_HPP

#include <cstdint>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <vector>

namespace chebcore::fixtures {

struct Columns {
  std::vector<std::string> header;
  std::vector<std::vector<double>> data;
  // Rows whose final field is non-numeric keep that field here (index aligned
  // with numeric rows); useful for human-readable labels such as a case name.
  std::vector<std::string> trailing_labels;
};

Columns load_csv(const std::string& path, char delimiter = ',');

// SHA-256 of a file, lowercase hex. Implemented locally (no OpenSSL dep).
std::string sha256_file(const std::string& path);

// Manifest lines: "<sha256hex>  <relative/path>".
using Manifest = std::unordered_map<std::string, std::string>;
Manifest load_manifest(const std::string& manifest_path);

// Throws std::runtime_error with the offending file if a digest mismatches.
void verify_manifest(const std::string& base_dir, const Manifest& m);

}  // namespace chebcore::fixtures

#endif
