/**
 * HTTP-date parsing and date-validator comparison (RFC 9110 §5.6.7, §13.1.4).
 *
 * Only IMF-fixdate (`Sun, 06 Nov 1994 08:49:37 GMT`) is accepted in request
 * headers; the legacy RFC 850 and asctime formats are not generated by modern
 * clients and are rejected. A malformed date validator makes the header
 * invalid as a whole, which the caller maps to a 400.
 */

const IMF_FIXDATE =
  /^(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun), (\d{2}) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) (\d{4}) (\d{2}):(\d{2}):(\d{2}) GMT$/;

const MONTHS: Readonly<Record<string, number>> = {
  Jan: 0, Feb: 1, Mar: 2, Apr: 3, May: 4, Jun: 5,
  Jul: 6, Aug: 7, Sep: 8, Oct: 9, Nov: 10, Dec: 11
};

/** Parse an IMF-fixdate. Returns null for anything else. */
export function parseHttpDate(raw: string): Date | null {
  const match = IMF_FIXDATE.exec(raw.trim());
  if (!match) return null;
  const [, day, mon, year, hour, min, sec] = match;
  const date = new Date(Date.UTC(
    Number(year), MONTHS[mon!], Number(day),
    Number(hour), Number(min), Number(sec)
  ));
  // Reject impossible calendar days such as 31 Feb.
  if (date.getUTCDate() !== Number(day)) return null;
  return date;
}

/** Format a timestamp (ms since epoch) as an IMF-fixdate. */
export function formatHttpDate(ms: number): string {
  return new Date(ms).toUTCString();
}

/**
 * Normalize a Last-Modified value: representations only carry per-second
 * resolution for date validators, so truncate milliseconds before comparing.
 */
export function truncateToSeconds(ms: number): number {
  return Math.floor(ms / 1000) * 1000;
}
