// Package compat runs the raw-frame fixtures generated by
// fixtures/gen_fixtures.py against the real h2 state machine wired to the
// real predefined-route handler. Expected values come from the Python
// reference, not from the Go implementation under test.
package compat

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"testing"
	"time"

	"h2svc/internal/frame"
	"h2svc/internal/h2"
	"h2svc/internal/server"
)

type fixtureConfig struct {
	MaxFrameSize        uint32 `json:"max_frame_size"`
	InitialRecvWindow   int64  `json:"initial_recv_window"`
	SendQueueCapacity   int    `json:"send_queue_capacity"`
	MaxPendingBodyBytes int    `json:"max_pending_body_bytes"`
	LargeBodyBytes      int    `json:"large_body_bytes"`
}

type expectedFrame struct {
	Type       string  `json:"type"`
	Flags      *uint8  `json:"flags"`
	Stream     *uint32 `json:"stream"`
	Length     *uint32 `json:"length"`
	ErrorCode  string  `json:"error_code"`
	PayloadHex string  `json:"payload_hex"`
	GoAwayLast *uint32 `json:"goaway_last_stream"`
}

type streamAssertion struct {
	ID    uint32 `json:"id"`
	State string `json:"state"`
}

type windowAssertion struct {
	ID    uint32 `json:"id"`
	Value int64  `json:"value"`
}

type pendingAssertion struct {
	ID    uint32 `json:"id"`
	Bytes int    `json:"bytes"`
}

type step struct {
	FeedHex           string           `json:"feed_hex"`
	Action            string           `json:"action"`
	Code              *uint32          `json:"code"`
	Debug             string           `json:"debug"`
	Expect            []expectedFrame  `json:"expect"`
	ExpectConnError   string           `json:"expect_conn_error"`
	ExpectConnClosed  bool             `json:"expect_conn_closed"`
	ExpectStreamState *streamAssertion `json:"expect_stream_state"`
	ExpectSendWindow  *windowAssertion `json:"expect_send_window"`
	ExpectPending     *pendingAssertion `json:"expect_pending"`
	Comment           string           `json:"comment"`
}

type fixtureCase struct {
	Name        string       `json:"name"`
	Description string       `json:"description"`
	RFC         string       `json:"rfc"`
	Config      fixtureConfig `json:"config"`
	Steps       []step       `json:"steps"`
}

var frameTypeByName = map[string]frame.Type{
	"DATA": frame.Data, "HEADERS": frame.Headers, "PRIORITY": frame.Priority,
	"RST_STREAM": frame.RSTStream, "SETTINGS": frame.Settings,
	"PUSH_PROMISE": frame.PushPromise, "PING": frame.Ping,
	"GOAWAY": frame.GoAway, "WINDOW_UPDATE": frame.WindowUpdate,
	"CONTINUATION": frame.Continuation,
}

func loadCases(t *testing.T) []fixtureCase {
	t.Helper()
	dir := filepath.Join("..", "..", "fixtures", "cases")
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read fixtures dir: %v (run fixtures/gen_fixtures.py first)", err)
	}
	var names []string
	for _, e := range entries {
		if filepath.Ext(e.Name()) == ".json" {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)
	if len(names) == 0 {
		t.Fatalf("no fixture cases in %s", dir)
	}
	var cases []fixtureCase
	for _, n := range names {
		b, err := os.ReadFile(filepath.Join(dir, n))
		if err != nil {
			t.Fatalf("read %s: %v", n, err)
		}
		var c fixtureCase
		if err := json.Unmarshal(b, &c); err != nil {
			t.Fatalf("parse %s: %v", n, err)
		}
		cases = append(cases, c)
	}
	return cases
}

// TestFixtures drives every generated case through the state machine. Each
// case runs under a watchdog so a deadlock fails the test instead of hanging
// the suite.
func TestFixtures(t *testing.T) {
	for _, c := range loadCases(t) {
		c := c
		t.Run(c.Name, func(t *testing.T) {
			runID := fmt.Sprintf("fixture-%s-%d", c.Name, time.Now().UnixNano())
			t.Logf("run_id=%s case=%s go=%s rfc=%s", runID, c.Name, runtime.Version(), c.RFC)
			t.Logf("run_id=%s description=%s", runID, c.Description)
			done := make(chan struct{})
			go func() {
				defer close(done)
				runCase(t, runID, c)
			}()
			select {
			case <-done:
			case <-time.After(15 * time.Second):
				t.Fatalf("run_id=%s case %s: watchdog timeout — possible deadlock", runID, c.Name)
			}
		})
	}
}

func runCase(t *testing.T, runID string, c fixtureCase) {
	t.Helper()
	cfg := h2.Config{
		MaxFrameSize:        c.Config.MaxFrameSize,
		InitialRecvWindow:   c.Config.InitialRecvWindow,
		SendQueueCapacity:   c.Config.SendQueueCapacity,
		MaxPendingBodyBytes: c.Config.MaxPendingBodyBytes,
	}
	conn := h2.NewConn(1, cfg, server.NewHandler(c.Config.LargeBodyBytes), nil)
	defer conn.Close()

	var lastConnErr *h2.ConnError
	for i, st := range c.Steps {
		logCtx := fmt.Sprintf("run_id=%s case=%s step=%d", runID, c.Name, i)
		if st.Comment != "" {
			t.Logf("%s note=%q", logCtx, st.Comment)
		}

		switch st.Action {
		case "":
		case "send_server_settings":
			if err := conn.SendServerSettings(); err != nil {
				t.Fatalf("%s send_server_settings: %v", logCtx, err)
			}
			t.Logf("%s action=send_server_settings", logCtx)
		case "goaway":
			code := frame.ErrCode(0)
			if st.Code != nil {
				code = frame.ErrCode(*st.Code)
			}
			if err := conn.InitiateGoAway(code, st.Debug); err != nil {
				t.Fatalf("%s goaway: %v", logCtx, err)
			}
			t.Logf("%s action=goaway code=%s", logCtx, code)
		default:
			t.Fatalf("%s unknown action %q", logCtx, st.Action)
		}

		if st.FeedHex != "" {
			raw, err := hex.DecodeString(st.FeedHex)
			if err != nil {
				t.Fatalf("%s bad feed_hex: %v", logCtx, err)
			}
			lastConnErr = feedFrames(t, logCtx, conn, raw)
		}

		got := drain(conn)
		assertExpectedFrames(t, logCtx, st.Expect, got)

		if st.ExpectConnError != "" {
			if lastConnErr == nil {
				t.Fatalf("%s expected connection error %s, got none", logCtx, st.ExpectConnError)
			}
			if got := lastConnErr.Code.String(); got != st.ExpectConnError {
				t.Fatalf("%s connection error code: want %s, got %s", logCtx, st.ExpectConnError, got)
			}
			t.Logf("%s judgment=conn_error code=%s (as expected)", logCtx, lastConnErr.Code)
		} else if lastConnErr != nil {
			t.Fatalf("%s unexpected connection error: %v", logCtx, lastConnErr)
		}

		if st.ExpectConnClosed && !conn.IsClosed() {
			t.Fatalf("%s expected connection to be closed", logCtx)
		}
		if a := st.ExpectStreamState; a != nil {
			state, ok := conn.StreamStateOf(a.ID)
			if !ok {
				t.Fatalf("%s stream %d does not exist, want state %s", logCtx, a.ID, a.State)
			}
			if state.String() != a.State {
				t.Fatalf("%s stream %d state: want %s, got %s", logCtx, a.ID, a.State, state)
			}
			t.Logf("%s judgment=stream_state id=%d state=%s (as expected)", logCtx, a.ID, state)
		}
		if a := st.ExpectSendWindow; a != nil {
			w, ok := conn.StreamSendWindow(a.ID)
			if !ok {
				t.Fatalf("%s stream %d does not exist, want window %d", logCtx, a.ID, a.Value)
			}
			if w != a.Value {
				t.Fatalf("%s stream %d send window: want %d, got %d", logCtx, a.ID, a.Value, w)
			}
			t.Logf("%s judgment=send_window id=%d value=%d (as expected)", logCtx, a.ID, w)
		}
		if a := st.ExpectPending; a != nil {
			if p := conn.PendingBytes(a.ID); p != a.Bytes {
				t.Fatalf("%s stream %d pending bytes: want %d, got %d", logCtx, a.ID, a.Bytes, p)
			}
			t.Logf("%s judgment=pending id=%d bytes=%d (as expected)", logCtx, a.ID, a.Bytes)
		}
	}
}

// feedFrames parses raw bytes into frames and feeds them one by one. It
// returns the first connection-level error, if any.
func feedFrames(t *testing.T, logCtx string, conn *h2.Conn, raw []byte) *h2.ConnError {
	t.Helper()
	var connErr *h2.ConnError
	for len(raw) > 0 {
		if len(raw) < frame.HeaderLen {
			t.Fatalf("%s truncated frame header in feed (%d bytes left)", logCtx, len(raw))
		}
		var hdr [frame.HeaderLen]byte
		copy(hdr[:], raw[:frame.HeaderLen])
		h := frame.ParseHeader(hdr)
		raw = raw[frame.HeaderLen:]
		if uint32(len(raw)) < h.Length {
			t.Fatalf("%s truncated payload for %s", logCtx, h)
		}
		payload := raw[:h.Length]
		raw = raw[h.Length:]
		t.Logf("%s feed=%s", logCtx, h)
		if err := conn.HandleFrame(h, payload); err != nil {
			if ce, ok := err.(*h2.ConnError); ok {
				t.Logf("%s conn_error=%s debug=%q", logCtx, ce.Code, ce.Debug)
				connErr = ce
				break // connection is done; remaining bytes are irrelevant
			}
			t.Fatalf("%s HandleFrame: %v", logCtx, err)
		}
	}
	return connErr
}

func drain(conn *h2.Conn) []h2.OutFrame {
	var out []h2.OutFrame
	for {
		select {
		case f := <-conn.Outbound():
			out = append(out, f)
		default:
			return out
		}
	}
}

func assertExpectedFrames(t *testing.T, logCtx string, want []expectedFrame, got []h2.OutFrame) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("%s outbound frame count: want %d, got %d (%s)",
			logCtx, len(want), len(got), summarize(got))
	}
	for i, w := range want {
		g := got[i]
		wt, ok := frameTypeByName[w.Type]
		if !ok {
			t.Fatalf("%s unknown expected frame type %q", logCtx, w.Type)
		}
		if g.Header.Type != wt {
			t.Fatalf("%s frame[%d] type: want %s, got %s", logCtx, i, w.Type, g.Header.Type)
		}
		if w.Flags != nil && g.Header.Flags != *w.Flags {
			t.Fatalf("%s frame[%d] %s flags: want 0x%02x, got 0x%02x",
				logCtx, i, w.Type, *w.Flags, g.Header.Flags)
		}
		if w.Stream != nil && g.Header.StreamID != *w.Stream {
			t.Fatalf("%s frame[%d] %s stream: want %d, got %d",
				logCtx, i, w.Type, *w.Stream, g.Header.StreamID)
		}
		if w.Length != nil && g.Header.Length != *w.Length {
			t.Fatalf("%s frame[%d] %s length: want %d, got %d",
				logCtx, i, w.Type, *w.Length, g.Header.Length)
		}
		if w.PayloadHex != "" {
			if got := hex.EncodeToString(g.Payload); got != w.PayloadHex {
				t.Fatalf("%s frame[%d] %s payload: want %s, got %s",
					logCtx, i, w.Type, w.PayloadHex, got)
			}
		}
		if w.ErrorCode != "" {
			assertErrorCode(t, logCtx, i, w, g)
		}
		if w.GoAwayLast != nil {
			if g.Header.Type != frame.GoAway || len(g.Payload) < 8 {
				t.Fatalf("%s frame[%d] expected GOAWAY with last-stream field", logCtx, i)
			}
			last := uint32(g.Payload[0])<<24 | uint32(g.Payload[1])<<16 |
				uint32(g.Payload[2])<<8 | uint32(g.Payload[3])
			if last != *w.GoAwayLast {
				t.Fatalf("%s frame[%d] GOAWAY lastStreamID: want %d, got %d",
					logCtx, i, *w.GoAwayLast, last)
			}
		}
		t.Logf("%s judgment=frame[%d] %s matched expectation", logCtx, i, g.Header)
	}
}

func assertErrorCode(t *testing.T, logCtx string, i int, w expectedFrame, g h2.OutFrame) {
	t.Helper()
	var codeOff int
	switch g.Header.Type {
	case frame.RSTStream:
		codeOff = 0
	case frame.GoAway:
		codeOff = 4
	default:
		t.Fatalf("%s frame[%d] error_code expectation only valid for RST_STREAM/GOAWAY, got %s",
			logCtx, i, g.Header.Type)
	}
	if len(g.Payload) < codeOff+4 {
		t.Fatalf("%s frame[%d] %s payload too short for error code", logCtx, i, g.Header.Type)
	}
	p := g.Payload[codeOff:]
	got := frame.ErrCode(uint32(p[0])<<24 | uint32(p[1])<<16 | uint32(p[2])<<8 | uint32(p[3]))
	if got.String() != w.ErrorCode {
		t.Fatalf("%s frame[%d] %s error code: want %s, got %s",
			logCtx, i, g.Header.Type, w.ErrorCode, got)
	}
}

func summarize(frames []h2.OutFrame) string {
	s := ""
	for i, f := range frames {
		if i > 0 {
			s += ", "
		}
		s += f.Header.String()
	}
	return s
}
