"""Independent spatial-domain NCC reference.

Deliberately shares no code with the FFT kernel: the contract requires
reference answers that are not generated by the core under test. This is
an exhaustive integer-shift search scoring each candidate with the
Pearson correlation over the overlap region — O(shifts x pixels), so it
is only practical for bounded ``max_shift`` and moderate images, which is
exactly the validation use case.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass
class ReferenceResult:
    best_shift: tuple[int, int] | None
    best_score: float
    runner_up: tuple[tuple[int, int], float] | None
    evaluated: int  # number of candidate shifts scored


def ncc_reference(
    img1: np.ndarray,
    img2: np.ndarray,
    max_shift: int,
    min_overlap_fraction: float = 0.25,
) -> ReferenceResult:
    """Best integer shift (dy, dx) with img2[y, x] ~= img1[y - dy, x - dx]."""
    if img1.shape != img2.shape or img1.ndim != 2:
        raise ValueError("reference requires a same-shape 2-D pair")
    h, w = img1.shape
    min_area = min_overlap_fraction * h * w

    best: tuple[tuple[int, int], float] | None = None
    second: tuple[tuple[int, int], float] | None = None
    evaluated = 0

    for dy in range(-max_shift, max_shift + 1):
        y_lo, y_hi = max(0, dy), min(h, h + dy)
        for dx in range(-max_shift, max_shift + 1):
            x_lo, x_hi = max(0, dx), min(w, w + dx)
            area = (y_hi - y_lo) * (x_hi - x_lo)
            if area < min_area:
                continue
            a = img1[y_lo - dy : y_hi - dy, x_lo - dx : x_hi - dx]
            b = img2[y_lo:y_hi, x_lo:x_hi]
            aa = a - a.mean()
            bb = b - b.mean()
            denom = float(np.sqrt((aa * aa).sum() * (bb * bb).sum()))
            score = float((aa * bb).sum() / denom) if denom > 0.0 else 0.0
            evaluated += 1
            if best is None or score > best[1]:
                second = best
                best = ((dy, dx), score)
            elif second is None or score > second[1]:
                second = ((dy, dx), score)

    if best is None:
        return ReferenceResult(None, 0.0, None, 0)
    return ReferenceResult(best[0], best[1], second, evaluated)
