"""Independent single-process reference oracle.

This module re-derives every quantity the distributed runtime produces,
**without importing the runtime's reduction or coordination code**.  Tests
compare the runtime against this oracle, so the reference answer is not
generated by the implementation under test.  It is deliberately written in
the most naive, obviously-correct style (plain NumPy, one joint batch).

Ground truths provided here:

- joint-batch gradient over all workers' data (the "single-process joint
  batch" baseline),
- sample-count-weighted mean of per-worker gradient sums,
- one SGD step,
- a full multi-round reference run.
"""

from __future__ import annotations

from typing import Dict, List, Sequence, Tuple

import numpy as np

from bucket_sync.training import BIAS_PARAM, WEIGHT_PARAM


def joint_linear_mse(
    params: Dict[str, np.ndarray],
    x: np.ndarray,
    y: np.ndarray,
) -> Dict[str, np.ndarray]:
    """Mean MSE gradient over one joint batch (the single-process baseline).

    Independent re-derivation: residual, then normal-equation gradients.
    Returns *mean* gradients (divided by the joint sample count).
    """
    x = np.asarray(x, dtype=np.float64)
    y = np.asarray(y, dtype=np.float64)
    w = np.asarray(params[WEIGHT_PARAM], dtype=np.float64)
    b = np.asarray(params[BIAS_PARAM], dtype=np.float64)
    n = x.shape[0]
    residual = x @ w + b - y
    return {
        WEIGHT_PARAM: (2.0 / n) * (x.T @ residual),
        BIAS_PARAM: (2.0 / n) * np.sum(residual, axis=0, keepdims=False).reshape(1),
    }


def reference_weighted_mean(
    contribs: Sequence[Tuple[Dict[str, np.ndarray], int]],
    param_names: Sequence[str],
) -> Dict[str, np.ndarray]:
    """Sample-count-weighted mean of per-worker gradient *sums*.

    Each contribution is ``(grad_sums, n_samples)`` where ``grad_sums`` are
    gradients summed (not averaged) over that worker's local batch.  The
    result equals the joint-batch mean gradient if and only if the
    weighting uses true sample counts; a naive "average of averages" is
    wrong whenever batch sizes differ.
    """
    if not contribs:
        raise ValueError("reference_weighted_mean: no contributions")
    total = sum(n for _, n in contribs)
    if total <= 0:
        raise ValueError("reference_weighted_mean: total sample count must be > 0")
    out: Dict[str, np.ndarray] = {}
    for name in param_names:
        acc = None
        for grads, _n in contribs:
            g = np.asarray(grads[name], dtype=np.float64)
            acc = g.copy() if acc is None else acc + g
        out[name] = acc / float(total)
    return out


def reference_sgd_step(
    params: Dict[str, np.ndarray],
    mean_grads: Dict[str, np.ndarray],
    lr: float,
) -> Dict[str, np.ndarray]:
    """One plain SGD step: ``p - lr * grad`` for every parameter."""
    return {
        name: np.asarray(params[name], dtype=np.float64) - lr * np.asarray(g, dtype=np.float64)
        for name, g in mean_grads.items()
    }


def reference_run(
    init_params: Dict[str, np.ndarray],
    shards: Sequence[Tuple[np.ndarray, np.ndarray]],
    lr: float,
    rounds: int,
) -> Dict[str, np.ndarray]:
    """Multi-round reference: each round pools all shards into a joint batch.

    This is the "what should synchronous data-parallel training compute"
    specification, written independently of the runtime under test.
    """
    params = {k: np.array(v, dtype=np.float64, copy=True) for k, v in init_params.items()}
    for _ in range(rounds):
        contribs: List[Tuple[Dict[str, np.ndarray], int]] = []
        for x_shard, y_shard in shards:
            x_shard = np.asarray(x_shard, dtype=np.float64)
            y_shard = np.asarray(y_shard, dtype=np.float64)
            n = x_shard.shape[0]
            residual = x_shard @ params[WEIGHT_PARAM] + params[BIAS_PARAM] - y_shard
            sums = {
                WEIGHT_PARAM: 2.0 * (x_shard.T @ residual),
                BIAS_PARAM: 2.0 * np.sum(residual, axis=0, keepdims=False).reshape(1),
            }
            contribs.append((sums, n))
        mean = reference_weighted_mean(contribs, [WEIGHT_PARAM, BIAS_PARAM])
        params = reference_sgd_step(params, mean, lr)
    return params
