// Package semdiff classifies fingerprint changes and compares runtime
// behavior on declared probes. Expected probe results live in external
// fixtures; they are never generated by the system under test.
package semdiff

import (
	"fmt"

	"rlc/internal/fp"
	"rlc/internal/interp"
	"rlc/internal/ir"
)

type ChangeClass string

const (
	ClassStable        ChangeClass = "stable"
	ClassPrivateBody   ChangeClass = "private_body_only"
	ClassPublicType    ChangeClass = "public_type_change"
	ClassInlineConst   ChangeClass = "inline_const_change"
	ClassGenericBody   ChangeClass = "generic_body_change"
	ClassIfaceDep      ChangeClass = "interface_dependency_change"
	ClassSymbolAdded   ChangeClass = "symbol_added"
	ClassSymbolRemoved ChangeClass = "symbol_removed"
)

type SymbolDelta struct {
	Key     string      `json:"key"`
	Class   ChangeClass `json:"class"`
	IfaceUp bool        `json:"interface_hash_changed"`
	ImplUp  bool        `json:"impl_hash_changed"`
	SigUp   bool        `json:"signature_changed"`
}

type Diff struct {
	Symbols     []SymbolDelta `json:"symbols"`
	InterfaceUp []string      `json:"interface_changed"`
	BodyOnlyUp  []string      `json:"body_only_changed"`
}

// Compare classifies every symbol between two fingerprint sets.
func Compare(before, after *fp.FingerprintSet) Diff {
	d := Diff{}
	keys := map[string]bool{}
	for k := range before.Symbols {
		keys[k] = true
	}
	for k := range after.Symbols {
		keys[k] = true
	}
	for k := range keys {
		o, bok := before.Symbols[k]
		n, ank := after.Symbols[k]
		sd := SymbolDelta{Key: k}
		switch {
		case !bok:
			sd.Class = ClassSymbolAdded
			sd.IfaceUp, sd.SigUp = true, true
		case !ank:
			sd.Class = ClassSymbolRemoved
			sd.IfaceUp, sd.SigUp = true, true
		default:
			sd.IfaceUp = o.InterfaceHash != n.InterfaceHash
			sd.ImplUp = o.ImplHash != n.ImplHash
			sd.SigUp = o.Signature != n.Signature
			switch {
			case !sd.IfaceUp && sd.ImplUp:
				sd.Class = ClassPrivateBody
			case sd.IfaceUp && isGeneric(o):
				sd.Class = ClassGenericBody
			case sd.IfaceUp && sd.SigUp && isConst(o):
				sd.Class = ClassInlineConst
			case sd.IfaceUp && !sd.SigUp:
				sd.Class = ClassIfaceDep
			case sd.IfaceUp:
				sd.Class = ClassPublicType
			default:
				sd.Class = ClassStable
			}
		}
		if sd.Class != ClassStable {
			d.Symbols = append(d.Symbols, sd)
		}
		if sd.IfaceUp {
			d.InterfaceUp = append(d.InterfaceUp, k)
		} else if sd.ImplUp {
			d.BodyOnlyUp = append(d.BodyOnlyUp, k)
		}
	}
	sortDeltas(d.Symbols)
	sortStrings(d.InterfaceUp)
	sortStrings(d.BodyOnlyUp)
	return d
}

func isGeneric(f *fp.Fingerprint) bool {
	for _, s := range f.Signature {
		if s == '<' {
			return true
		}
	}
	return false
}

func isConst(f *fp.Fingerprint) bool {
	return f.Kind == "const"
}

// Probe is an externally specified behavioral check.
type Probe struct {
	Name   string   `json:"name"`
	Target string   `json:"target"`
	Args   []Arg    `json:"args"`
	Expect Expected `json:"expect"`
}

type Arg struct {
	Type string `json:"type"`
	Int  int64  `json:"int,omitempty"`
	Str  string `json:"str,omitempty"`
	Bool bool   `json:"bool,omitempty"`
}

type Expected struct {
	Kind          string `json:"kind"` // value | runtime_error
	Type          string `json:"type,omitempty"`
	Int           int64  `json:"int,omitempty"`
	Str           string `json:"str,omitempty"`
	Bool          bool   `json:"bool,omitempty"`
	ErrorCategory string `json:"error_category,omitempty"`
}

type ProbeResult struct {
	Probe    string `json:"probe"`
	Pass     bool   `json:"pass"`
	Reason   string `json:"reason,omitempty"`
	GotRepr  string `json:"got,omitempty"`
	WantRepr string `json:"want,omitempty"`
}

// RunProbes executes external probes against a linked program.
func RunProbes(prog *ir.Program, probes []Probe, redact bool) []ProbeResult {
	eng := interp.New(prog)
	results := make([]ProbeResult, 0, len(probes))
	for _, pr := range probes {
		args := make([]ir.Value, len(pr.Args))
		for i, a := range pr.Args {
			args[i] = toValue(a)
		}
		got, err := eng.Call(pr.Target, args)
		res := ProbeResult{Probe: pr.Name, WantRepr: reprExpect(pr.Expect, redact)}
		if pr.Expect.Kind == "runtime_error" {
			if err == nil {
				res.Reason = "expected runtime error but call succeeded"
				res.GotRepr = reprValue(got, redact)
			} else {
				res.Pass = true
				res.GotRepr = "error:" + errCategory(err)
			}
			results = append(results, res)
			continue
		}
		if err != nil {
			res.Reason = "unexpected runtime error: " + err.Error()
			results = append(results, res)
			continue
		}
		res.GotRepr = reprValue(got, redact)
		if matchExpect(got, pr.Expect) {
			res.Pass = true
		} else {
			res.Reason = "value mismatch"
		}
		results = append(results, res)
	}
	return results
}

func errCategory(err error) string {
	type categorizer interface{ Error() string }
	_ = categorizer(nil)
	if err == nil {
		return ""
	}
	msg := err.Error()
	switch {
	case contains(msg, "division by zero"), contains(msg, "modulo by zero"):
		return "division_by_zero"
	case contains(msg, "undefined"), contains(msg, "uninstantiated"):
		return "unresolved"
	case contains(msg, "arity"):
		return "arity"
	case contains(msg, "depth"):
		return "stack_overflow"
	}
	return "runtime"
}

func contains(s, sub string) bool {
	return len(s) >= len(sub) && (func() bool {
		for i := 0; i+len(sub) <= len(s); i++ {
			if s[i:i+len(sub)] == sub {
				return true
			}
		}
		return false
	})()
}

func toValue(a Arg) ir.Value {
	switch a.Type {
	case "int":
		return ir.Value{Type: "int", I: a.Int}
	case "bool":
		return ir.Value{Type: "bool", B: a.Bool}
	case "string":
		return ir.Value{Type: "string", S: a.Str}
	}
	return ir.Value{}
}

func matchExpect(v ir.Value, e Expected) bool {
	if e.Type != v.Type {
		return false
	}
	switch v.Type {
	case "int":
		return v.I == e.Int
	case "bool":
		return v.B == e.Bool
	case "string":
		return v.S == e.Str
	}
	return false
}

func reprValue(v ir.Value, redact bool) string {
	switch v.Type {
	case "int":
		return fmt.Sprintf("int:%d", v.I)
	case "bool":
		return fmt.Sprintf("bool:%t", v.B)
	case "string":
		if redact {
			return "string:<redacted>"
		}
		return fmt.Sprintf("string:%q", v.S)
	}
	return "void"
}

func reprExpect(e Expected, redact bool) string {
	if e.Kind == "runtime_error" {
		return "error:" + e.ErrorCategory
	}
	v := ir.Value{Type: e.Type, I: e.Int, S: e.Str, B: e.Bool}
	return reprValue(v, redact)
}

func sortStrings(xs []string) {
	for i := 1; i < len(xs); i++ {
		for j := i; j > 0 && xs[j-1] > xs[j]; j-- {
			xs[j-1], xs[j] = xs[j], xs[j-1]
		}
	}
}

func sortDeltas(xs []SymbolDelta) {
	for i := 1; i < len(xs); i++ {
		for j := i; j > 0 && xs[j-1].Key > xs[j].Key; j-- {
			xs[j-1], xs[j] = xs[j], xs[j-1]
		}
	}
}
