"""Synthetic model + fixture loading and offline calibration bootstrap.

Boot sequence is strictly offline:

1. load deterministic synthetic weights/biases and a *fixed* calibration
   dataset from ``fixtures/`` (shipped with the repo, generated by
   ``scripts/generate_fixtures.py``);
2. run :class:`~app.calibration.CalibrationBuilder` once;
3. freeze the lifecycle and register the model.

After startup the registry is read-only — no request can trigger estimation.
"""

from __future__ import annotations

import json
import os

import numpy as np

from .calibration import CalibrationBuilder
from .config import Settings
from .graph import ModelRegistry, build_model_from_float
from .training_state import ModelLifecycle


def _fixture_path(settings: Settings, suffix: str) -> str:
    return os.path.join(settings.fixture_dir, f"{settings.model_id}{suffix}")


def build_registry(settings: Settings) -> ModelRegistry:
    """Build the frozen registry from local synthetic fixtures."""
    weights_npz = np.load(_fixture_path(settings, ".weights.npz"))
    calib_npz = np.load(_fixture_path(settings, ".calib.npz"))
    with open(_fixture_path(settings, ".meta.json"), "r", encoding="utf-8") as fh:
        meta = json.load(fh)

    if meta["model_version"] != settings.model_version:
        raise RuntimeError(
            "fixture/model version mismatch: "
            f"fixture={meta['model_version']} service={settings.model_version}"
        )

    # Fixture layout: two tiny stacked layers.
    float_weights = {
        "fc1": weights_npz["fc1"].astype(np.float32),
        "fc2": weights_npz["fc2"].astype(np.float32),
    }
    float_biases = {
        "fc1": weights_npz["fc1_bias"].astype(np.float32),
        "fc2": weights_npz["fc2_bias"].astype(np.float32),
    }
    x_cal = calib_npz["x"].astype(np.float32)

    # Offline pass through the *float* graph to collect per-layer stats.
    h_cal = x_cal @ float_weights["fc1"].T + float_biases["fc1"]
    y_cal = h_cal @ float_weights["fc2"].T + float_biases["fc2"]

    builder = CalibrationBuilder(settings.model_id, settings.model_version)
    builder.observe_input("fc1", x_cal)
    builder.observe_output("fc1", h_cal)
    builder.observe_input("fc2", h_cal)
    builder.observe_output("fc2", y_cal)
    bundle = builder.build(float_weights)

    model = build_model_from_float(
        settings.model_id, settings.model_version,
        float_weights, float_biases, bundle,
    )
    lifecycle = ModelLifecycle(settings.model_id, settings.model_version)
    lifecycle.freeze(bundle)

    registry = ModelRegistry()
    registry.register(model, bundle, lifecycle)
    return registry
