"""Independent evidence and diagnostics.

This module is deliberately written *without importing*
:mod:`app.core.kernel`. Its purpose is to supply reference answers generated by
a separate, auditable implementation (plain Python enumeration over
``itertools.product`` of within-pair flips), then compare the engine under test
against it. Test fixtures therefore do not inherit the engine's own answers.

It also produces human-readable diagnostic summaries in which hard failures and
uncertain conclusions are listed separately.
"""
from __future__ import annotations

import itertools
import math
from dataclasses import dataclass, field

import numpy as np

from app.core import contract
from app.core.intervals import Interval, IntervalSet

# A discrepancy category means one of the checks below disagrees with the core.
DISCREPANCY_KINDS = (
    "PVALUE_MISMATCH",
    "ACCEPTANCE_MEMBERSHIP_MISMATCH",
    "COMPONENT_COUNT_MISMATCH",
    "RANDOMIZATION_SET_VIOLATION",
)


# ---------------------------------------------------------------------------
# Independent oracle (no kernel import)
# ---------------------------------------------------------------------------

def oracle_pvalue(differences: list[float] | np.ndarray,
                  effect: float) -> tuple[float, int, int]:
    """Exact two-sided p-value from a brute-force independent enumeration.

    Enumerates ``itertools.product((-1, 1), repeat=n)`` - every combination of
    independent within-pair treatment coins - directly in Python. Returns
    ``(p_value, count_as_extreme, n_assignments)``.
    """
    d = [float(x) for x in differences]
    n = len(d)
    residuals = [x - float(effect) for x in d]
    observed = abs(sum(residuals))
    total = 0
    count = 0
    for signs in itertools.product((-1, 1), repeat=n):
        total += 1
        statistic = abs(sum(s * r for s, r in zip(signs, residuals)))
        if statistic >= observed - 1e-12:
            count += 1
    return count / total, count, total


def oracle_acceptance(differences: list[float] | np.ndarray, alpha: float,
                      taus: list[float] | np.ndarray) -> list[bool]:
    """Per-grid-point acceptance ``p(tau) >= alpha`` from the oracle."""
    d = [float(x) for x in differences]
    return [oracle_pvalue(d, float(tau))[0] >= alpha - 1e-12
            for tau in taus]


def oracle_paired_randomization_size(n_pairs: int) -> int:
    """Independent statement of the design size: one coin per pair => 2**n."""
    return 2 ** int(n_pairs)


def oracle_sign_vectors_honor_pairs(n_pairs: int) -> bool:
    """Structural property of the paired randomization set.

    Every assignment is a vector of per-pair +/-1 coins; its entries must be
    exactly +/-1 (units never move across pair boundaries). This is checked
    element-wise over the full enumeration.
    """
    for signs in itertools.product((-1, 1), repeat=n_pairs):
        if any(s not in (-1, 1) for s in signs):
            return False
        if len(signs) != n_pairs:
            return False
    return True


# ---------------------------------------------------------------------------
# Cross-check reports
# ---------------------------------------------------------------------------

@dataclass
class CrossCheckReport:
    ok: bool
    n_pairs: int
    n_assignments: int
    p_value_core: float
    p_value_oracle: float
    discrepancies: list[dict] = field(default_factory=list)
    checks: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "ok": self.ok,
            "n_pairs": self.n_pairs,
            "n_assignments": self.n_assignments,
            "p_value_core": self.p_value_core,
            "p_value_oracle": self.p_value_oracle,
            "discrepancies": self.discrepancies,
            "checks": self.checks,
        }


def cross_check_pvalue(differences: np.ndarray, effect: float,
                       core_p_value: float,
                       tolerance: float = 1e-12) -> CrossCheckReport:
    """Compare one core p-value against the independent oracle."""
    d = np.asarray(differences, dtype=float)
    n = d.size
    total = oracle_paired_randomization_size(n)
    oracle_p, _, oracle_total = oracle_pvalue(d, effect)
    report = CrossCheckReport(
        ok=True,
        n_pairs=n,
        n_assignments=oracle_total,
        p_value_core=float(core_p_value),
        p_value_oracle=float(oracle_p),
    )
    report.checks.append("paired design size equals 2**n (not (2n)! or n!)")
    report.checks.append("oracle enumeration uses independent implementation")
    if total != oracle_total:
        report.ok = False
        report.discrepancies.append({
            "kind": "RANDOMIZATION_SET_VIOLATION",
            "detail": f"core size {total} != oracle size {oracle_total}",
        })
    if abs(core_p_value - oracle_p) > tolerance:
        report.ok = False
        report.discrepancies.append({
            "kind": "PVALUE_MISMATCH",
            "effect": float(effect),
            "core": float(core_p_value),
            "oracle": float(oracle_p),
            "difference": float(abs(core_p_value - oracle_p)),
        })
    return report


def cross_check_interval_set(differences: np.ndarray, alpha: float,
                             interval_set: IntervalSet,
                             probe_grid: np.ndarray,
                             membership_tolerance: float = 0.0
                             ) -> list[dict]:
    """Compare membership of a core interval set against the oracle pointwise.

    Grid-based sets may legitimately differ from the exact set within
    ``membership_tolerance`` of a boundary; mismatches strictly inside the
    probe spacing are reported as discrepancies.
    """
    d = np.asarray(differences, dtype=float)
    expected = oracle_acceptance(d.tolist(), alpha, probe_grid)
    discrepancies: list[dict] = []
    for tau, oracle_contains in zip(probe_grid.tolist(), expected):
        core_contains = interval_set.contains(float(tau),
                                              tolerance=membership_tolerance)
        if core_contains != oracle_contains:
            discrepancies.append({
                "kind": "ACCEPTANCE_MEMBERSHIP_MISMATCH",
                "tau": float(tau),
                "core_contains": bool(core_contains),
                "oracle_contains": bool(oracle_contains),
            })
    return discrepancies


# ---------------------------------------------------------------------------
# Diagnostic summaries
# ---------------------------------------------------------------------------

UNCERTAINTY_CODES = {
    "BUDGET_EXCEEDED":
        "2**n exceeds the exact enumeration budget; result uses Monte-Carlo",
    "MONTE_CARLO_ERROR":
        "p-value carries binomial Monte-Carlo sampling error",
    "GRID_APPROXIMATION":
        "interval endpoints lie on a finite grid (endpoint error <= one step)",
    "DISCONNECTED_SET":
        "the acceptance set has multiple components; report it as a union, "
        "not a single interval",
    "UNBOUNDED_SET":
        "the acceptance set extends to +/-infinity at this alpha (a weak-test "
        "artifact, not numerical failure)",
}


@dataclass
class DiagnosticSummary:
    point_estimate: float
    n_pairs: int
    n_assignments: int
    method: str
    statistic: str
    failures: list[dict]
    uncertainties: list[dict]
    steps: list[dict]
    version: str
    request_id: str | None

    def to_dict(self) -> dict:
        return {
            "point_estimate_mean_difference": self.point_estimate,
            "n_pairs": self.n_pairs,
            "n_assignments": self.n_assignments,
            "method": self.method,
            "statistic": self.statistic,
            "failures": self.failures,
            "uncertainties": self.uncertainties,
            "processing_steps": self.steps,
            "version": self.version,
            "request_id": self.request_id,
        }


def build_diagnostic_summary(
    differences: np.ndarray,
    method: str,
    steps: list[dict],
    failures: list[dict] | None = None,
    interval_set: IntervalSet | None = None,
    mc_error_halfwidth: float | None = None,
    grid_used: bool = False,
    budget_exceeded: bool = False,
    request_id: str | None = None,
) -> DiagnosticSummary:
    """Assemble the explainability block, separating failures from doubt."""
    d = np.asarray(differences, dtype=float)
    uncertainties: list[dict] = []
    if budget_exceeded:
        uncertainties.append({
            "code": "BUDGET_EXCEEDED",
            "message": UNCERTAINTY_CODES["BUDGET_EXCEEDED"],
        })
    if mc_error_halfwidth is not None:
        uncertainties.append({
            "code": "MONTE_CARLO_ERROR",
            "message": UNCERTAINTY_CODES["MONTE_CARLO_ERROR"],
            "halfwidth": float(mc_error_halfwidth),
        })
    if grid_used:
        uncertainties.append({
            "code": "GRID_APPROXIMATION",
            "message": UNCERTAINTY_CODES["GRID_APPROXIMATION"],
        })
    if interval_set is not None:
        if not interval_set.is_connected:
            uncertainties.append({
                "code": "DISCONNECTED_SET",
                "message": UNCERTAINTY_CODES["DISCONNECTED_SET"],
                "n_components": interval_set.n_intervals,
            })
        if any(not math.isfinite(iv.lower) or not math.isfinite(iv.upper)
               for iv in interval_set.intervals):
            uncertainties.append({
                "code": "UNBOUNDED_SET",
                "message": UNCERTAINTY_CODES["UNBOUNDED_SET"],
            })

    from app import __version__

    return DiagnosticSummary(
        point_estimate=float(d.mean()),
        n_pairs=int(d.size),
        n_assignments=contract.n_assignments(int(d.size)),
        method=method,
        statistic=contract.STATISTIC_NAME,
        failures=list(failures or []),
        uncertainties=uncertainties,
        steps=list(steps),
        version=__version__,
        request_id=request_id,
    )
