// Local synthetic fixture generator (C++ only). Writes text series files.
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

static void writeSeries(const fs::path& p, const std::string& name,
                        const std::vector<double>& c) {
    std::ofstream out(p);
    out << "# synthetic local fixture generated by gen_fixtures\n";
    out << "name = " << name << "\ncoefficients = ";
    out.setf(std::ios::scientific);
    out.precision(17);
    for (std::size_t i = 0; i < c.size(); ++i) {
        if (i) out << ", ";
        out << c[i];
    }
    out << "\n";
}

int main(int argc, char** argv) {
    fs::path dir = (argc > 1) ? fs::path(argv[1]) : fs::path("data");
    fs::create_directories(dir);

    { // exp(x), 12 terms
        std::vector<double> c(12);
        double fact = 1.0;
        for (int k = 0; k < 12; ++k) {
            if (k) fact *= k;
            c[k] = 1.0 / fact;
        }
        writeSeries(dir / "exp12.series", "exp12", c);
    }
    { // geometric 1/(1-x), 10 terms
        std::vector<double> c(10, 1.0);
        writeSeries(dir / "geometric10.series", "geometric10", c);
    }
    { // -ln(1-x)/x style: c_0=1, c_k=1/(k+1)
        std::vector<double> c(10);
        for (int k = 0; k < 10; ++k) c[k] = 1.0 / (k + 1);
        writeSeries(dir / "logseries10.series", "logseries10", c);
    }
    { // degenerate: f = x (single x factor), 5 terms
        std::vector<double> c(5, 0.0);
        c[1] = 1.0;
        writeSeries(dir / "x_factor5.series", "x_factor5", c);
    }
    { // degenerate: f = x^3, 5 terms (b0 normalization impossible at [1/2])
        std::vector<double> c(5, 0.0);
        c[3] = 1.0;
        writeSeries(dir / "x3_factor5.series", "x3_factor5", c);
    }
    { // degenerate: f = 1 + x^2 (b0=0 unique null vector at [1/1])
        std::vector<double> c(5, 0.0);
        c[0] = 1.0;
        c[2] = 1.0;
        writeSeries(dir / "one_plus_x2_5.series", "one_plus_x2_5", c);
    }
    std::cout << "fixtures written to " << dir << "\n";
    return 0;
}
