"""Loader for the synthetic fixture corpora under fixtures/.

Each fixture file holds a corpus plus one or more mining cases whose
expected outputs were computed by hand (not generated by the kernel), so
tests and the CLI can check the kernel against an independent reference.
"""

from __future__ import annotations

import json
from pathlib import Path

FIXTURES_DIR = Path(__file__).resolve().parent.parent.parent / "fixtures"


def load_fixture(name: str) -> dict:
    path = FIXTURES_DIR / f"{name}.json"
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def list_fixtures() -> list[str]:
    return sorted(p.stem for p in FIXTURES_DIR.glob("*.json"))
