package com.example.nonoverlap.oracle;

import com.example.nonoverlap.support.GenCase;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.TreeSet;

/**
 * Independent brute-force oracle written from scratch for tests.
 *
 * <p>It does NOT call any production kernel class: it enumerates every
 * existence resolution (TRUE/FALSE, constrained by each rectangle's declared
 * state) and every integer anchor, checks strict interior overlap directly,
 * and records canonical assignment strings. It is the evidence source that the
 * kernel results are compared against - reference answers are therefore not
 * generated by the code under test.
 */
public final class BruteOracle {

    /** Canonical assignment: for every rect either "F" or "x,y". */
    public record Answer(List<String> terms) implements Comparable<Answer> {

        public String canonical() {
            return String.join("|", terms);
        }

        @Override
        public int compareTo(Answer o) {
            return canonical().compareTo(o.canonical());
        }
    }

    public TreeSet<Answer> enumerate(GenCase c) {
        TreeSet<Answer> answers = new TreeSet<>();
        int n = c.rects().size();
        int[] xs = new int[n];
        int[] ys = new int[n];
        int[] present = new int[n];
        recurse(c, 0, xs, ys, present, answers);
        return answers;
    }

    private void recurse(GenCase c, int i, int[] xs, int[] ys, int[] present,
                         TreeSet<Answer> answers) {
        if (i == c.rects().size()) {
            if (pairwiseDisjoint(c, xs, ys, present)) {
                List<String> terms = new ArrayList<>(c.rects().size());
                for (int k = 0; k < c.rects().size(); k++) {
                    terms.add(present[k] == 1 ? xs[k] + "," + ys[k] : "F");
                }
                answers.add(new Answer(terms));
            }
            return;
        }
        GenCase.GenRect r = c.rects().get(i);
        switch (r.existence()) {
            case "TRUE" -> enumerateAnchors(c, i, r, 1, xs, ys, present, answers);
            case "FALSE" -> {
                present[i] = 0;
                recurse(c, i + 1, xs, ys, present, answers);
            }
            default -> {
                enumerateAnchors(c, i, r, 1, xs, ys, present, answers);
                present[i] = 0;
                recurse(c, i + 1, xs, ys, present, answers);
            }
        }
    }

    private void enumerateAnchors(GenCase c, int i, GenCase.GenRect r, int p,
                                  int[] xs, int[] ys, int[] present,
                                  TreeSet<Answer> answers) {
        present[i] = p;
        int maxX = r.w() == 0 ? c.gridW() : c.gridW() - r.w();
        int maxY = r.h() == 0 ? c.gridH() : c.gridH() - r.h();
        for (int x = 0; x <= maxX; x++) {
            for (int y = 0; y <= maxY; y++) {
                xs[i] = x;
                ys[i] = y;
                recurse(c, i + 1, xs, ys, present, answers);
            }
        }
    }

    /** Half-open interval overlap, written independently of production Geometry. */
    private boolean pairwiseDisjoint(GenCase c, int[] xs, int[] ys, int[] present) {
        int n = c.rects().size();
        for (int a = 0; a < n; a++) {
            if (present[a] == 0) {
                continue;
            }
            GenCase.GenRect ra = c.rects().get(a);
            if (ra.w() == 0 || ra.h() == 0) {
                continue;
            }
            for (int b = a + 1; b < n; b++) {
                if (present[b] == 0) {
                    continue;
                }
                GenCase.GenRect rb = c.rects().get(b);
                if (rb.w() == 0 || rb.h() == 0) {
                    continue;
                }
                boolean separated = xs[a] + ra.w() <= xs[b]
                        || xs[b] + rb.w() <= xs[a]
                        || ys[a] + ra.h() <= ys[b]
                        || ys[b] + rb.h() <= ys[a];
                if (!separated) {
                    return false;
                }
            }
        }
        return true;
    }

    /** Counts solutions in which a given rectangle is present. */
    public int presentCount(TreeSet<Answer> answers, int index) {
        int count = 0;
        for (Answer a : answers) {
            if (!a.terms().get(index).equals("F")) {
                count++;
            }
        }
        return count;
    }

    public List<String> canonicalAll(TreeSet<Answer> answers) {
        return answers.stream().map(Answer::canonical).toList();
    }

    public List<String> sortedCopy(String... terms) {
        String[] t = terms.clone();
        Arrays.sort(t);
        return List.of(t);
    }
}
