//! Shared helpers for fixture-driven integration tests.
//!
//! Each integration-test binary compiles this module independently and uses a
//! different subset of the helpers, so unused-code warnings are expected and
//! suppressed here.
#![allow(dead_code)]

use std::path::PathBuf;

use proc_diff::engine::{Engine, EngineConfig, IngestOutcome};
use proc_diff::model::{
    CpuDelta, ExitEvent, Pid, ProcessIdentity, ReparentEvent, UndeterminedInterval,
};
use serde::Deserialize;

#[derive(Deserialize)]
pub struct FixtureConfig {
    pub counter_max: u64,
    pub wrap_max_plausible_delta: u64,
}

/// Hand-written reference answers (fixtures/*/expected.json). These are NOT
/// generated by the engine; tests assert the engine reproduces them.
#[derive(Deserialize)]
pub struct Expected {
    pub deltas: Vec<CpuDelta>,
    pub exits: Vec<ExitEvent>,
    pub reparents: Vec<ReparentEvent>,
    pub undetermined: Vec<UndeterminedInterval>,
}

pub fn id(pid: Pid, gen: u64) -> ProcessIdentity {
    ProcessIdentity { pid, start_generation: gen }
}

pub fn fixture_root(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures").join(name)
}

/// Load a fixture, replay its snapshots through the engine, return the engine
/// and the hand-written expected answers.
pub fn run_fixture(name: &str) -> (Engine, Expected) {
    let root = fixture_root(name);
    let cfg: FixtureConfig = serde_json::from_str(
        &std::fs::read_to_string(root.join("fixture.json")).expect("fixture.json"),
    )
    .expect("parse fixture.json");
    let expected: Expected = serde_json::from_str(
        &std::fs::read_to_string(root.join("expected.json")).expect("expected.json"),
    )
    .expect("parse expected.json");
    let snaps = proc_diff::snapshot::load_series(&root).expect("load snapshot series");
    assert!(!snaps.is_empty(), "fixture {name} has no snapshots");
    let mut engine = Engine::new(EngineConfig {
        counter_max: cfg.counter_max,
        wrap_max_plausible_delta: cfg.wrap_max_plausible_delta,
    });
    for snap in &snaps {
        match engine.apply(snap) {
            IngestOutcome::Accepted { .. } => {}
            other => panic!("fixture {name} snapshot {} rejected: {other:?}", snap.meta.seq),
        }
    }
    (engine, expected)
}

fn strip_reasons(mut d: Vec<CpuDelta>) -> Vec<CpuDelta> {
    for d in &mut d {
        d.reason.clear();
    }
    d
}

fn strip_undetermined_reasons(mut u: Vec<UndeterminedInterval>) -> Vec<UndeterminedInterval> {
    for u in &mut u {
        u.reason.clear();
    }
    u
}

/// Full comparison of engine output against the hand-written reference.
pub fn assert_fixture_matches(engine: &Engine, expected: &Expected) {
    assert_eq!(
        strip_reasons(engine.deltas().to_vec()),
        strip_reasons(expected.deltas.clone()),
        "deltas mismatch"
    );
    assert_eq!(engine.exits(), expected.exits.as_slice(), "exits mismatch");
    assert_eq!(engine.reparents(), expected.reparents.as_slice(), "reparents mismatch");
    assert_eq!(
        strip_undetermined_reasons(engine.undetermined().to_vec()),
        strip_undetermined_reasons(expected.undetermined.clone()),
        "undetermined intervals mismatch"
    );
}
