//! Shared synthetic fixtures for integration tests.
//!
//! Nothing here depends on the IEJoin implementation; datasets are either
//! hand-specified literals or generated by a tiny seeded PRNG. The reference
//! answers are produced independently by
//! `iejoin_range::operator::nested_loop` (and, for one fixture, by a literal
//! hand-written pair list) — never derived from the core under test.

#![allow(dead_code)]

use iejoin_range::operator::{Comparator, JoinPlan, Predicate};
use iejoin_range::types::builder::{batch, int_column};
use iejoin_range::types::TypedBatch;

/// Two-column integer batch: `k1` drives predicate 1, `k2` predicate 2.
pub fn two_col_int(
    name1: &str,
    v1: Vec<Option<i64>>,
    name2: &str,
    v2: Vec<Option<i64>>,
) -> TypedBatch {
    batch(vec![int_column(name1, v1), int_column(name2, v2)]).expect("valid fixture batch")
}

/// Every inequality direction under test. Columns are `(a1,a2)` vs `(b1,b2)`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Direction {
    LtLt,
    LeLe,
    GtGt,
    GeGe,
    /// Mixed orientation: active side is smaller on p1 but greater on p2.
    LtGt,
    /// The opposite mixed orientation.
    GeLe,
}

pub const ALL_DIRECTIONS: [Direction; 6] = [
    Direction::LtLt,
    Direction::LeLe,
    Direction::GtGt,
    Direction::GeGe,
    Direction::LtGt,
    Direction::GeLe,
];

impl Direction {
    pub fn plan(self) -> JoinPlan {
        let pred = |op1: Comparator, op2: Comparator| {
            JoinPlan::new(
                Predicate {
                    left_col: 0,
                    right_col: 0,
                    op: op1,
                },
                Predicate {
                    left_col: 1,
                    right_col: 1,
                    op: op2,
                },
            )
        };
        match self {
            Direction::LtLt => pred(Comparator::Lt, Comparator::Lt),
            Direction::LeLe => pred(Comparator::Le, Comparator::Le),
            Direction::GtGt => pred(Comparator::Gt, Comparator::Gt),
            Direction::GeGe => pred(Comparator::Ge, Comparator::Ge),
            Direction::LtGt => pred(Comparator::Lt, Comparator::Gt),
            Direction::GeLe => pred(Comparator::Ge, Comparator::Le),
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Direction::LtLt => "lt_lt",
            Direction::LeLe => "le_le",
            Direction::GtGt => "gt_gt",
            Direction::GeGe => "ge_ge",
            Direction::LtGt => "lt_gt",
            Direction::GeLe => "ge_le",
        }
    }
}

/// A named pair of typed batches.
pub struct Dataset {
    pub name: String,
    pub left: TypedBatch,
    pub right: TypedBatch,
}

impl Dataset {
    pub fn sizes(&self) -> (usize, usize) {
        (self.left.row_count(), self.right.row_count())
    }
}

/// Tiny hand-authored dataset with deliberately placed duplicates and gaps.
pub fn hand_small() -> Dataset {
    // left:  (a1, a2)
    let left = two_col_int(
        "a1",
        vec![Some(5), Some(2), Some(5), Some(9), None],
        "a2",
        vec![Some(7), Some(7), Some(1), Some(3), Some(8)],
    );
    // right: (b1, b2)
    let right = two_col_int(
        "b1",
        vec![Some(5), Some(1), Some(2), Some(9), Some(6)],
        "b2",
        vec![Some(7), Some(9), Some(0), Some(4), None],
    );
    Dataset {
        name: "hand_small".into(),
        left,
        right,
    }
}

/// Every non-null key is identical, with real multiplicities on both sides.
pub fn all_equal(n_left: usize, n_right: usize) -> Dataset {
    Dataset {
        name: format!("all_equal_{n_left}x{n_right}"),
        left: two_col_int("a1", vec![Some(4); n_left], "a2", vec![Some(4); n_left]),
        right: two_col_int("b1", vec![Some(4); n_right], "b2", vec![Some(4); n_right]),
    }
}

/// One side empty (schema still present, zero rows).
pub fn empty_left() -> Dataset {
    Dataset {
        name: "empty_left".into(),
        left: two_col_int("a1", vec![], "a2", vec![]),
        right: two_col_int("b1", vec![Some(1), Some(2)], "b2", vec![Some(1), Some(2)]),
    }
}

pub fn empty_right() -> Dataset {
    Dataset {
        name: "empty_right".into(),
        left: two_col_int("a1", vec![Some(1), Some(2)], "a2", vec![Some(1), Some(2)]),
        right: two_col_int("b1", vec![], "b2", vec![]),
    }
}

/// High-selectivity: only a narrow band of right rows can ever match.
/// Left keys cluster high; right keys are mostly far away with one tight band.
pub fn high_selectivity(n: usize) -> Dataset {
    let a1: Vec<Option<i64>> = (0..n).map(|i| Some(500 + (i as i64 % 7))).collect();
    let a2: Vec<Option<i64>> = (0..n).map(|i| Some(900 - (i as i64 % 5))).collect();
    let mut b1: Vec<Option<i64>> = (0..n)
        .map(|i| Some(10_000 + (i as i64 % 13) * 100))
        .collect();
    let mut b2: Vec<Option<i64>> = (0..n)
        .map(|i| Some(20_000 + (i as i64 % 11) * 100))
        .collect();
    // Three rows inside the band for both predicates (a1 < b1, a2 < b2 is rare
    // here; instead place rows that satisfy the gt/gt band).
    b1[0] = Some(490);
    b2[0] = Some(880);
    b1[n / 2] = Some(503);
    b2[n / 2] = Some(895);
    b1[n - 1] = Some(495);
    b2[n - 1] = Some(890);
    Dataset {
        name: format!("high_selectivity_{n}"),
        left: two_col_int("a1", a1, "a2", a2),
        right: two_col_int("b1", b1, "b2", b2),
    }
}

/// Dense duplicates: each value repeats `dups` times, checking multiplicity.
pub fn dense_duplicates(distinct: usize, dups: usize) -> Dataset {
    let n = distinct * dups;
    let gen = |offset: i64| -> Vec<Option<i64>> {
        (0..n)
            .map(|i| {
                let v = (i / dups) as i64 * 3 + offset;
                Some(v)
            })
            .collect()
    };
    Dataset {
        name: format!("dense_duplicates_d{distinct}_x{dups}"),
        left: two_col_int("a1", gen(0), "a2", gen(1)),
        right: two_col_int("b1", gen(1), "b2", gen(2)),
    }
}

/// Mix of NULL and non-null keys on both sides and both columns.
pub fn with_nulls(n: usize) -> Dataset {
    let pick = |i: usize, base: i64| -> Option<i64> {
        if i.is_multiple_of(4) {
            None
        } else {
            Some(base + (i as i64 % 9))
        }
    };
    let a1: Vec<Option<i64>> = (0..n).map(|i| pick(i, 10)).collect();
    let a2: Vec<Option<i64>> = (0..n).map(|i| pick(i, 20)).collect();
    let b1: Vec<Option<i64>> = (0..n).map(|i| pick((i + 1) % n, 12)).collect();
    let b2: Vec<Option<i64>> = (0..n).map(|i| pick((i + 2) % n, 22)).collect();
    Dataset {
        name: format!("with_nulls_{n}"),
        left: two_col_int("a1", a1, "a2", a2),
        right: two_col_int("b1", b1, "b2", b2),
    }
}

/// Deterministic xorshift PRNG so randomized runs are replayable by seed.
pub struct Rng(u64);

impl Rng {
    pub fn new(seed: u64) -> Self {
        Rng(seed.max(1))
    }
    pub fn next_u64(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        x
    }
    pub fn below(&mut self, bound: i64) -> i64 {
        (self.next_u64() % bound as u64) as i64
    }
}

/// Random nullable dataset, reproducible from `seed`.
pub fn random(seed: u64, n_left: usize, n_right: usize, span: i64, null_pct: u32) -> Dataset {
    let mut rng = Rng::new(seed);
    let mut gen = |n: usize, base: i64| -> Vec<Option<i64>> {
        (0..n)
            .map(|_| {
                if rng.below(100) < null_pct as i64 {
                    None
                } else {
                    Some(base + rng.below(span) - span / 2)
                }
            })
            .collect()
    };
    let l1 = gen(n_left, 0);
    let l2 = gen(n_left, 1_000);
    let r1 = gen(n_right, 0);
    let r2 = gen(n_right, 1_000);
    Dataset {
        name: format!("random_seed{seed}_{n_left}x{n_right}"),
        left: two_col_int("a1", l1, "a2", l2),
        right: two_col_int("b1", r1, "b2", r2),
    }
}

/// The full fixed (non-random) dataset battery every direction is checked on.
pub fn fixed_datasets() -> Vec<Dataset> {
    vec![
        hand_small(),
        all_equal(3, 4),
        all_equal(1, 1),
        empty_left(),
        empty_right(),
        high_selectivity(20),
        dense_duplicates(4, 3),
        with_nulls(12),
    ]
}
