//! Independent test harness shared by integration tests.
//!
//! The [`oracle`] here is a *separate* per-outer-row interpreter written only
//! for the tests. It reads the raw fixture JSON itself and never calls the
//! crate's `executor`, `service`, or `validator` — expected answers are not
//! generated by the implementation under test. Tests then compare the engine's
//! decorrelated output (and its own row-by-row output) against this oracle and
//! against hand-written literal expectations.

#![allow(dead_code)]

use std::collections::BTreeMap;

use serde_json::{json, Map, Value};

pub const FIXTURES_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/main_fixtures.json"
);

pub fn fixture_json() -> Value {
    let raw = std::fs::read_to_string(FIXTURES_PATH).expect("read main_fixtures.json");
    serde_json::from_str(&raw).expect("fixture JSON parses")
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OracleQuery<'a> {
    pub outer_relation: &'a str,
    pub inner_relation: &'a str,
    pub select: &'a [&'a str],
    /// (outer column, inner column) equality conjuncts.
    pub correlation: &'a [(&'a str, &'a str)],
    pub op: &'a str,
    pub aggregate: Option<&'a str>,
    pub value_column: Option<&'a str>,
    pub output_column: &'a str,
}

#[derive(Debug, Clone, PartialEq)]
pub enum OracleOutcome {
    Rows(Vec<Map<String, Value>>),
    /// Failure category code plus the 0-based outer row that triggered it.
    Failure {
        category: String,
        outer_row: Option<usize>,
    },
}

/// Naive nested-loop semantics implemented directly over JSON.
pub fn run_oracle(fixtures: &Value, q: &OracleQuery<'_>) -> OracleOutcome {
    let outer = &fixtures["relations"][q.outer_relation]["rows"];
    let inner = &fixtures["relations"][q.inner_relation]["rows"];
    let outer_rows = outer.as_array().expect("outer rows array");
    let inner_rows = inner.as_array().expect("inner rows array");

    let project: Vec<String> = if q.select.is_empty() {
        fixtures["relations"][q.outer_relation]["columns"]
            .as_array()
            .unwrap()
            .iter()
            .map(|c| c["name"].as_str().unwrap().to_string())
            .collect()
    } else {
        q.select.iter().map(|s| s.to_string()).collect()
    };

    let mut out = Vec::new();
    for (outer_row_idx, outer_row) in outer_rows.iter().enumerate() {
        // Dependent nested-loop evaluation: re-scan the whole inner relation.
        let mut matched: Vec<&Value> = Vec::new();
        for inner_row in inner_rows {
            let mut all_eq = true;
            for (outer_col, inner_col) in q.correlation {
                if !sql_eq(outer_row.get(outer_col), inner_row.get(inner_col)) {
                    all_eq = false;
                    break;
                }
            }
            if all_eq {
                matched.push(inner_row);
            }
        }

        let sub_value = match evaluate(q, &matched, outer_row_idx) {
            Ok(v) => v,
            Err(failure) => return failure,
        };

        let mut row = Map::new();
        for col in &project {
            row.insert(
                col.clone(),
                outer_row.get(col).cloned().unwrap_or(Value::Null),
            );
        }
        row.insert(q.output_column.to_string(), sub_value);
        out.push(row);
    }
    OracleOutcome::Rows(out)
}

/// SQL equality for correlation keys: NULL never equals anything.
fn sql_eq(a: Option<&Value>, b: Option<&Value>) -> bool {
    match (a, b) {
        (Some(Value::Null), _) | (_, Some(Value::Null)) | (None, _) | (_, None) => false,
        (Some(x), Some(y)) => x == y,
    }
}

fn evaluate(
    q: &OracleQuery<'_>,
    matched: &[&Value],
    outer_row: usize,
) -> Result<Value, OracleOutcome> {
    match q.op {
        "exists" => Ok(Value::Bool(!matched.is_empty())),
        "not_exists" => Ok(Value::Bool(matched.is_empty())),
        "scalar" => match matched.len() {
            0 => Ok(Value::Null),
            1 => Ok(matched[0]
                .get(q.value_column.expect("value_column"))
                .cloned()
                .unwrap_or(Value::Null)),
            _ => Err(OracleOutcome::Failure {
                category: "scalar_cardinality_violation".to_string(),
                outer_row: Some(outer_row),
            }),
        },
        "scalar_aggregate" => match q.aggregate {
            Some("count_star") => Ok(json!(matched.len() as i64)),
            Some("sum") => {
                let mut sum: Option<i64> = None;
                for row in matched {
                    if let Some(Value::Number(n)) = row.get(q.value_column.expect("value_column")) {
                        if let Some(v) = n.as_i64() {
                            sum = Some(sum.map_or(v, |acc| acc + v));
                        }
                    }
                }
                Ok(match sum {
                    Some(v) => json!(v),
                    None => Value::Null,
                })
            }
            other => panic!("oracle: unsupported aggregate {other:?}"),
        },
        other => panic!("oracle: unsupported op {other}"),
    }
}

/// Convenience: build a query request body fragment as the HTTP API expects.
pub fn query_request_json(q: &OracleQuery<'_>, query_id: &str) -> Value {
    let correlation: Vec<Value> = q
        .correlation
        .iter()
        .map(|(o, i)| json!({ "outer": o, "inner": i }))
        .collect();
    let mut body = BTreeMap::new();
    body.insert("query_id".to_string(), json!(query_id));
    body.insert(
        "outer".to_string(),
        json!({ "relation": q.outer_relation, "select": q.select }),
    );
    let mut sq = BTreeMap::new();
    sq.insert("op".to_string(), json!(q.op));
    sq.insert("inner_relation".to_string(), json!(q.inner_relation));
    sq.insert("correlation".to_string(), json!(correlation));
    if let Some(agg) = q.aggregate {
        sq.insert("aggregate".to_string(), json!(agg));
    }
    if let Some(vc) = q.value_column {
        sq.insert("value_column".to_string(), json!(vc));
    }
    sq.insert("output_column".to_string(), json!(q.output_column));
    body.insert(
        "subquery".to_string(),
        Value::Object(sq.into_iter().collect()),
    );
    Value::Object(body.into_iter().collect())
}
