//! Test-only reference oracle.
//!
//! This module is compiled only for integration tests.  It recomputes every
//! expected answer with the simplest possible in-memory implementation that
//! shares **no code** with the engine under test: groups are built with a
//! `HashMap`, values are filtered with `retain`, sorted with the standard
//! library and the percentile/mode/string-agg rules are written out directly
//! from the SQL definitions.  If the streaming external-sort engine and this
//! naive oracle agree over fixtures and randomized inputs, the design has real
//! cross-validation rather than tests generated by the code being tested.

use std::collections::BTreeMap;

use groupagg::batch::{Batch, Column, Field};
use groupagg::plan::{AggOp, Plan, SortOrder};

/// Naively evaluate a plan over batches.  Keys are JSON-ish `Vec<RefValue>` to
/// stay independent of the engine's `Cell` type.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum RefValue {
    Null,
    Int(i64),
    Float(u64), // f64 bit pattern for Eq/Ord via total order wrapper
    Text(String),
}

impl RefValue {
    fn as_f64(&self) -> Option<f64> {
        match self {
            RefValue::Int(i) => Some(*i as f64),
            RefValue::Float(bits) => Some(f64::from_bits(*bits)),
            _ => None,
        }
    }

    fn numeric_key(&self) -> f64 {
        self.as_f64().unwrap_or(f64::NAN)
    }
}

fn from_column(col: &Column, row: usize) -> RefValue {
    match col {
        Column::Int64(a) => match a.get(row) {
            Some(v) => RefValue::Int(v),
            None => RefValue::Null,
        },
        Column::Float64(a) => match a.get(row) {
            Some(v) => RefValue::Float(v.to_bits()),
            None => RefValue::Null,
        },
        Column::Utf8(a) => match a.get(row) {
            Some(v) => RefValue::Text(v.to_string()),
            None => RefValue::Null,
        },
    }
}

/// Reference result for one group: alias → nullable value rendered as JSON.
#[derive(Debug, Clone)]
pub struct RefGroup {
    pub key: Vec<RefValue>,
    pub values: BTreeMap<String, Option<serde_json::Value>>,
}

/// Reference evaluator, keyed insertion order sorted afterwards.
pub fn reference_eval(schema: &[Field], batches: &[Batch], plan: &Plan) -> Vec<RefGroup> {
    let key_idx: Vec<usize> = plan
        .group_by
        .iter()
        .map(|name| schema.iter().position(|f| &f.name == name).unwrap())
        .collect();
    let agg_idx: Vec<usize> = plan
        .aggregations
        .iter()
        .map(|a| schema.iter().position(|f| f.name == a.input).unwrap())
        .collect();

    // Collect raw (key, per-agg value) pairs.
    let mut grouped: BTreeMap<Vec<RefValue>, Vec<Vec<RefValue>>> = BTreeMap::new();
    for batch in batches {
        for row in 0..batch.row_count() {
            let key: Vec<RefValue> = key_idx
                .iter()
                .map(|&i| from_column(&batch.columns()[i], row))
                .collect();
            let entry = grouped.entry(key).or_default();
            if entry.is_empty() {
                for _ in 0..plan.aggregations.len() {
                    entry.push(Vec::new());
                }
            }
            for (j, &ci) in agg_idx.iter().enumerate() {
                entry[j].push(from_column(&batch.columns()[ci], row));
            }
        }
    }
    // Empty aggregation (no rows at all): one group with all-null results when
    // there are no group keys, mirroring SQL scalar aggregation semantics.
    if grouped.is_empty() && plan.group_by.is_empty() {
        grouped.insert(Vec::new(), vec![Vec::new(); plan.aggregations.len()]);
    }

    grouped
        .into_iter()
        .map(|(key, mut per_agg)| {
            let mut values = BTreeMap::new();
            for (agg, raw) in plan.aggregations.iter().zip(per_agg.iter_mut()) {
                raw.retain(|v| !matches!(v, RefValue::Null));
                let rendered = eval_one(agg.op.clone(), raw);
                values.insert(agg.alias.clone(), rendered);
            }
            RefGroup { key, values }
        })
        .collect()
}

fn eval_one(op: AggOp, raw: &[RefValue]) -> Option<serde_json::Value> {
    if raw.is_empty() {
        return None;
    }
    match op {
        AggOp::PercentileCont { q } => {
            let mut nums: Vec<f64> = raw.iter().map(RefValue::numeric_key).collect();
            nums.sort_by(f64::total_cmp);
            let n = nums.len();
            let rank = q * (n as f64 - 1.0);
            let lo = nums[rank.floor() as usize];
            let hi = nums[rank.ceil() as usize];
            Some(serde_json::Value::from(
                lo + (rank - rank.floor()) * (hi - lo),
            ))
        }
        AggOp::PercentileDisc { q } => {
            // Sort typed values: numeric comparison, text bytewise.
            let mut sorted: Vec<&RefValue> = raw.iter().collect();
            sorted.sort_by(|a, b| compare_ref(a, b));
            let n = sorted.len();
            let idx = ((q * n as f64).ceil() as usize).max(1) - 1;
            Some(render(sorted[idx]))
        }
        AggOp::Mode => {
            let mut sorted: Vec<&RefValue> = raw.iter().collect();
            sorted.sort_by(|a, b| compare_ref(a, b));
            let mut best = sorted[0].clone();
            let mut best_count = 0usize;
            let mut i = 0;
            while i < sorted.len() {
                let run = sorted[i..]
                    .iter()
                    .take_while(|v| ***v == *sorted[i])
                    .count();
                if run > best_count {
                    best_count = run;
                    best = sorted[i].clone();
                }
                i += run;
            }
            Some(render(&best))
        }
        AggOp::StringAgg { delimiter, order } => {
            let mut texts: Vec<&str> = raw
                .iter()
                .filter_map(|v| match v {
                    RefValue::Text(s) => Some(s.as_str()),
                    _ => None,
                })
                .collect();
            match order {
                SortOrder::Asc => texts.sort(),
                // Stable: equal strings retain relative order.
                SortOrder::Desc => {
                    texts.sort();
                    texts.reverse();
                }
            }
            Some(serde_json::Value::from(texts.join(&delimiter)))
        }
    }
}

fn compare_ref(a: &RefValue, b: &RefValue) -> std::cmp::Ordering {
    match (a, b) {
        (RefValue::Int(x), RefValue::Int(y)) => x.cmp(y),
        (RefValue::Text(x), RefValue::Text(y)) => x.cmp(y),
        _ => a.as_f64().unwrap().total_cmp(&b.as_f64().unwrap()),
    }
}

fn render(v: &RefValue) -> serde_json::Value {
    match v {
        RefValue::Null => serde_json::Value::Null,
        RefValue::Int(i) => serde_json::Value::from(*i),
        RefValue::Float(bits) => serde_json::Value::from(f64::from_bits(*bits)),
        RefValue::Text(s) => serde_json::Value::from(s.clone()),
    }
}

/// Flatten engine output groups to `(key_json, alias -> value_json)` rows,
/// making assertions against [`reference_eval`] straightforward.
pub fn engine_groups_as_json(
    groups: &[groupagg::GroupResult],
    plan: &Plan,
) -> Vec<(serde_json::Value, BTreeMap<String, serde_json::Value>)> {
    groups
        .iter()
        .map(|g| {
            let key = if plan.group_by.is_empty() {
                serde_json::json!({})
            } else {
                let mut map = serde_json::Map::new();
                for (name, cell) in plan.group_by.iter().zip(g.key.iter()) {
                    map.insert(name.clone(), groupagg::server::dto::cell_to_json(cell));
                }
                serde_json::Value::Object(map)
            };
            let mut vals = BTreeMap::new();
            for (agg, v) in plan.aggregations.iter().zip(g.values.iter()) {
                vals.insert(
                    agg.alias.clone(),
                    v.as_ref()
                        .map(groupagg::server::dto::cell_to_json)
                        .unwrap_or(serde_json::Value::Null),
                );
            }
            (key, vals)
        })
        .collect()
}
