// Package vectors holds hand-computed Modbus TCP wire vectors. It is the
// independent oracle for every other module: it imports neither mbap nor
// core, so its expectations cannot be generated by the implementation under
// test.
//
// Values were derived by hand from the Modbus Application Protocol
// Specification v1.1b3 (MBAP header §3.1.1, FC03 §6.3, FC16 §6.12):
//
//	+---------------------------------------------------------------+
//	| Transaction ID (2) | Protocol ID (2, 0x0000) | Length (2, BE) |
//	| Unit ID (1)        | PDU (Length-1 bytes)                      |
//	+---------------------------------------------------------------+
//
// Register encoding: each register is a uint16 in network (big) endian.
package vectors

// FrameVector is one request/response pair whose bytes were computed by
// hand and pinned as hexadecimal literals.
type FrameVector struct {
	Name    string
	Desc    string
	ReqHex  string
	RespHex string
}

// Golden are canonical, protocol-valid exchanges.
var Golden = []FrameVector{
	{
		Name: "fc03_read_two_registers",
		Desc: "txn=0x1234 unit=0x05 read addr=0x0000 qty=2; " +
			"server returns 0x1122, 0x3344",
		// 12 34 | 00 00 | 00 06 | 05 | 03 00 00 00 02
		ReqHex: "123400000006050300000002",
		// 12 34 | 00 00 | 00 07 | 05 | 03 04 11 22 33 44
		RespHex: "12340000000705030411223344",
	},
	{
		Name: "fc16_write_two_registers",
		Desc: "txn=0x0001 unit=0x01 write addr=0x000A " +
			"values=0x0001,0x0002; echo addr+qty",
		// 00 01 | 00 00 | 00 0B | 01 | 10 00 0A 00 02 04 00 01 00 02
		ReqHex: "00010000000b0110000a00020400010002",
		// 00 01 | 00 00 | 00 06 | 01 | 10 00 0A 00 02
		RespHex: "0001000000060110000a0002",
	},
	{
		Name:   "fc03_read_single_register",
		Desc:   "txn=0x0002 unit=0x01 read addr=0x0063 (99) qty=1",
		ReqHex: "000200000006010300630001",
		// response value supplied by tests via ReadHoldingResp
		RespHex: "",
	},
	{
		Name: "fc16_write_three_registers_unit_ff",
		Desc: "txn=0x0010 unit=0xFF write addr=0x0000 " +
			"values=0xFFFF,0x0000,0x1234 (full uint16 range)",
		// 00 10 | 00 00 | 00 0D | FF | 10 00 00 00 03 06 FF FF 00 00 12 34
		ReqHex: "00100000000dff100000000306ffff00001234",
		// 00 10 | 00 00 | 00 06 | FF | 10 00 00 00 03
		RespHex: "001000000006ff1000000003",
	},
	{
		Name: "fc03_exception_illegal_address",
		Desc: "txn=0xABCD unit=0x05 FC03 denied with exception " +
			"0x02 ILLEGAL DATA ADDRESS",
		// AB CD | 00 00 | 00 03 | 05 | 83 02
		RespHex: "abcd00000003058302",
	},
}
