#!/usr/bin/env python3
"""Regenerate the frozen noise-fixture regression anchor.

The anchor is a *regression snapshot* produced by the current kernel; the
authoritative references of the test suite are the hand-computed fixtures
(two-basin, plateau, saddle).  Run this only after an intentional,
reviewed change to the kernel's deterministic behaviour.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))

from watershed_backend.version import runtime_versions  # noqa: E402
from tests.fixtures.synthetic import noisy_gradient  # noqa: E402
from tests.helpers import run_from_seeds  # noqa: E402

OUT = ROOT / "tests" / "fixtures" / "data" / "noise_labels_expected.json"


def main() -> None:
    gradient, seeds = noisy_gradient()
    result = run_from_seeds(gradient, seeds)
    payload = {
        "fixture_seed": 20260927,
        "note": "regression snapshot generated by scripts/freeze_noise_fixture.py",
        "versions": runtime_versions(),
        "labels": result.labels.tolist(),
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
