import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

/**
 * Generate the committed sample data under samples/.
 *
 * The manifest's `expectedSlices` are literal slices of the just-generated
 * buffers (plain Buffer arithmetic), NOT outputs of the range engine, so a
 * fresh user can cross-check the server against them independently.
 *
 * Run: npm run make:samples
 */
const ROOT = join(process.cwd(), 'samples');

interface SampleSpec {
  file: string;
  id: string;
  contentType: string;
  build: () => Buffer;
  ranges: Array<{ request: string }>;
}

function hex40(buf: Buffer): string {
  return createHash('sha256').update(buf).digest('hex');
}

function sliceAnswer(data: Buffer, start: number, endInclusive: number) {
  const slice = data.subarray(start, endInclusive + 1);
  return {
    interval: `bytes ${start}-${endInclusive}/${data.length}`,
    length: slice.length,
    sha256: hex40(slice),
  };
}

const specs: SampleSpec[] = [
  {
    file: 'hello.txt',
    id: 'hello-sample',
    contentType: 'text/plain; charset=utf-8',
    build: () => Buffer.from('The quick brown fox jumps over the lazy dog.\n', 'utf8'),
    ranges: [{ request: 'bytes=0-2' }, { request: 'bytes=-4' }, { request: 'bytes=40-' }],
  },
  {
    file: 'octets256.bin',
    id: 'octets-sample',
    contentType: 'application/octet-stream',
    build: () => Buffer.from(Array.from({ length: 256 }, (_, i) => i)),
    ranges: [
      { request: 'bytes=0-15' },
      { request: 'bytes=240-255' },
      { request: 'bytes=0-9,100-109,250-255' },
    ],
  },
];

function main(): void {
  mkdirSync(ROOT, { recursive: true });
  const manifest = {
    generatedAt: 'deterministic',
    note: 'Expected answers are literal slices of the generated bytes, independent of the range engine.',
    objects: [] as Array<Record<string, unknown>>,
  };

  for (const spec of specs) {
    const data = spec.build();
    const path = join(ROOT, spec.file);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, data);

    const expectedSlices: Record<string, unknown> = {};
    // Literal, hand-specified answers for the documented requests.
    if (spec.file === 'hello.txt') {
      expectedSlices['bytes=0-2'] = sliceAnswer(data, 0, 2);
      expectedSlices['bytes=-4'] = sliceAnswer(data, data.length - 4, data.length - 1);
      expectedSlices['bytes=40-'] = sliceAnswer(data, 40, data.length - 1);
    } else {
      expectedSlices['bytes=0-15'] = sliceAnswer(data, 0, 15);
      expectedSlices['bytes=240-255'] = sliceAnswer(data, 240, 255);
      // Multipart request: answer is a list of per-part byte answers;
      // the server frames them with Content-Range headers per part.
      expectedSlices['bytes=0-9,100-109,250-255'] = {
        parts: [
          sliceAnswer(data, 0, 9),
          sliceAnswer(data, 100, 109),
          sliceAnswer(data, 250, 255),
        ],
      };
    }

    manifest.objects.push({
      id: spec.id,
      file: spec.file,
      contentType: spec.contentType,
      size: data.length,
      sha256: hex40(data),
      documentedRequests: spec.ranges.map((r) => r.request),
      expectedSlices,
    });
  }

  writeFileSync(join(ROOT, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  console.log(`Wrote ${specs.length} samples + manifest to ${ROOT}`);
}

main();
