"""Pinned golden expectations captured directly from ICU 74 (Unicode 15.1).

These literals were recorded once with a standalone probe script that talks to
PyICU only — they are NOT generated by the collsvc code under test. Tests
assert that both (a) a fresh raw ICU collator and (b) the collsvc engine
reproduce these exact bytes/orders. If an ICU upgrade changes them, the
golden tests fail loudly and the index version (which embeds the ICU version)
moves, forcing a rebuild.
"""
from __future__ import annotations

# Full tertiary sort keys, en_US, numeric OFF, normalization ON.
EN_TERTIARY_KEYS = {
    "cote": "2e4650320108010800",
    "coté": "2e465032014288010900",
    "côte": "2e46503201448e06010900",
    "côté": "2e46503201448e4488010a00",
}

NUMERIC_ON_KEYS = {
    "file2": "343a40320f040109010900",
    "file02": "343a40320f040109010900",  # identical to file2 with numeric on
    "file10": "343a40320f0c0109010900",
}
NUMERIC_OFF_KEYS = {
    "file2": "343a4032170109010900",
    "file02": "343a40321317010a010a00",
    "file10": "343a40321513010a010a00",
}

ORDER_COTE_TERTIARY = ["cote", "coté", "côte", "côté"]
ORDER_FILE_NUMERIC = ["file1", "file2", "file02", "file10", "file20"]
ORDER_FILE_PLAIN = ["file02", "file1", "file10", "file2", "file20"]

ORDER_CASE_DEFAULT = ["a", "A", "aa", "Aa"]
ORDER_CASE_UPPER_FIRST = ["A", "a", "Aa", "aa"]
ORDER_CASE_LOWER_FIRST = ["a", "A", "aa", "Aa"]

TURKISH_WORDS = [
    "sıcak", "şapka", "SİZ", "sağlam", "üç",
    "öğle", "çay", "ağır", "ırmak", "İstanbul",
]
ORDER_TURKISH_TR = [
    "ağır", "çay", "ırmak", "İstanbul", "öğle",
    "sağlam", "sıcak", "SİZ", "şapka", "üç",
]
ORDER_TURKISH_VIEWED_BY_EN = [
    "ağır", "çay", "İstanbul", "ırmak", "öğle",
    "sağlam", "şapka", "SİZ", "sıcak", "üç",
]

# ICU compare() results at PRIMARY strength in tr_TR / en_US.
#   0 = equal at that strength, positive = different.
TR_PRIMARY_COMPARE = {
    ("id", "Id"): 1,    # dotted i  vs dotless capital I -> distinct in Turkish
    ("id", "ıd"): 1,    # dotted i  vs dotless ı       -> distinct
    ("id", "İd"): 0,    # dotted i  vs dotted capital İ -> same letter
}
EN_PRIMARY_COMPARE = {
    ("id", "İd"): 0,    # English ignores the dot distinction at primary
}

COTE_PRIMARY_DISTINCT_KEYS = 1   # accents ignored
COTE_SECONDARY_DISTINCT_KEYS = 4  # accents significant

# "étude" is collated between e and f, but UTF-8 byte order puts it after f.
ETUDE_IN_E_F = True
UTF8_ETUDE_GREATER_THAN_F = True
