// Package fixtures provides reusable, deterministic test infrastructure:
// an ephemeral proxy backed by a temp SQLite file, static offline resolver,
// echo/slow upstreams and a byte-at-a-time segmented writer.
//
// Nothing here is generated by the code under test; upstreams are ordinary
// net listeners hand-written for the tests.
package fixtures

import (
	"bufio"
	"context"
	"net"
	"sync"
	"testing"
	"time"

	"socks5d.local/socks5d/internal/config"
	"socks5d.local/socks5d/internal/logx"
	"socks5d.local/socks5d/internal/policy"
	"socks5d.local/socks5d/internal/proto"
	"socks5d.local/socks5d/internal/server"
	"socks5d.local/socks5d/internal/store"
)

// LoopbackRules is the default local-only ruleset.
func LoopbackRules(extra ...config.Rule) []config.Rule {
	rules := []config.Rule{
		{Kind: "cidr", Value: "127.0.0.0/8", Note: "loopback v4"},
		{Kind: "cidr", Value: "::1/128", Note: "loopback v6"},
		{Kind: "domain", Value: "echo.local", Mode: "exact", Note: "local echo"},
		{Kind: "domain", Value: "internal", Mode: "suffix", Note: "local suffix"},
	}
	return append(rules, extra...)
}

// Harness is a running proxy plus its dependencies.
type Harness struct {
	T        *testing.T
	Addr     string
	Store    *store.Store
	Server   *server.Server
	cancel   context.CancelFunc
	dbPath   string
	logMu    sync.Mutex
	logLines []string
}

// StartProxy brings up a proxy on an ephemeral loopback port.
func StartProxy(t *testing.T, rules []config.Rule, hosts map[string][]string, authn proto.Authenticator) *Harness {
	t.Helper()
	return StartProxyConfig(t, func(c *config.Config) {
		c.Rules = rules
		c.Resolver.Hosts = hosts
	}, authn)
}

// StartProxyConfig allows full control over the validated config.
func StartProxyConfig(t *testing.T, mutate func(*config.Config), authn proto.Authenticator) *Harness {
	t.Helper()
	tmp := t.TempDir()
	ctx, cancel := context.WithCancel(context.Background())

	st, err := store.Open(ctx, tmp+"/test.db")
	if err != nil {
		cancel()
		t.Fatalf("open store: %v", err)
	}

	cfg := config.Default()
	cfg.Listen = "127.0.0.1:0"
	cfg.HandshakeTimeout = config.Duration{Duration: 3 * time.Second}
	cfg.DialTimeout = config.Duration{Duration: 2 * time.Second}
	cfg.IdleTimeout = config.Duration{Duration: 5 * time.Second}
	cfg.ShutdownTimeout = config.Duration{Duration: 2 * time.Second}
	cfg.MaxConnections = 16
	cfg.ByteBudget = 1 << 20
	cfg.Database.Path = tmp + "/test.db"
	if mutate != nil {
		mutate(&cfg)
	}
	if err := cfg.Validate(); err != nil {
		cancel()
		st.Close()
		t.Fatalf("validate config: %v", err)
	}
	if err := st.ReplaceRules(ctx, cfg.Rules); err != nil {
		cancel()
		st.Close()
		t.Fatalf("seed rules: %v", err)
	}

	pol, err := policy.FromRules(cfg.Rules)
	if err != nil {
		cancel()
		st.Close()
		t.Fatalf("compile policy: %v", err)
	}
	resolver, err := policy.NewStaticResolver(cfg.Resolver.Hosts)
	if err != nil {
		cancel()
		st.Close()
		t.Fatalf("resolver: %v", err)
	}

	h := &Harness{T: t, Store: st, cancel: cancel, dbPath: tmp + "/test.db"}
	lg := logx.New(&lineBuffer{h: h}, server.AppVersion)
	srv := server.New(cfg, pol, resolver, authn, st, lg)
	if err := srv.Listen(); err != nil {
		cancel()
		st.Close()
		t.Fatalf("listen: %v", err)
	}
	h.Server = srv
	h.Addr = srv.Addr().String()
	go func() { _ = srv.Serve(ctx) }()
	t.Cleanup(h.close)
	return h
}

type lineBuffer struct{ h *Harness }

func (b *lineBuffer) Write(p []byte) (int, error) {
	b.h.logMu.Lock()
	b.h.logLines = append(b.h.logLines, string(p))
	b.h.logMu.Unlock()
	return len(p), nil
}

// LogLines returns captured structured log lines.
func (h *Harness) LogLines() []string {
	h.logMu.Lock()
	defer h.logMu.Unlock()
	out := make([]string, len(h.logLines))
	copy(out, h.logLines)
	return out
}

func (h *Harness) close() {
	h.Server.Shutdown(2 * time.Second)
	h.cancel()
	_ = h.Store.Close()
}

// ---------------------------------------------------------------------------
// Upstreams
// ---------------------------------------------------------------------------

// EchoUpstream is a TCP server that echoes every byte it receives and
// half-closes its write side only after the client half-closes, so EOF
// directionality is preserved end to end.
type EchoUpstream struct {
	ln      net.Listener
	accepts chan struct{} // closed-style signal buffer; length = accept count
}

// StartEcho binds an echo server on a loopback ephemeral port.
func StartEcho(t *testing.T) *EchoUpstream {
	t.Helper()
	return startEchoNetwork(t, "tcp4", "127.0.0.1:0")
}

// StartEcho6 binds an IPv6 loopback echo; skip the caller's test if the
// platform has no usable ::1.
func StartEcho6(t *testing.T) *EchoUpstream {
	t.Helper()
	return startEchoNetwork(t, "tcp6", "[::1]:0")
}

func startEchoNetwork(t *testing.T, network, addr string) *EchoUpstream {
	ln, err := net.Listen(network, addr)
	if err != nil {
		t.Skipf("listen %s %s: %v", network, addr, err)
	}
	e := &EchoUpstream{ln: ln, accepts: make(chan struct{}, 1024)}
	go func() {
		for {
			c, err := ln.Accept()
			if err != nil {
				return
			}
			e.accepts <- struct{}{}
			go serveEcho(c)
		}
	}()
	t.Cleanup(func() { _ = ln.Close() })
	return e
}

// AcceptedCount reports how many connections the upstream accepted.
func (e *EchoUpstream) AcceptedCount() int { return len(e.accepts) }

func serveEcho(c net.Conn) {
	tc := c.(*net.TCPConn)
	buf := make([]byte, 4096)
	for {
		n, err := tc.Read(buf)
		if n > 0 {
			// Write the full read prefix before acting on any error so that
			// the last bytes before a FIN are echoed back.
			if _, werr := tc.Write(buf[:n]); werr != nil {
				_ = tc.Close()
				return
			}
		}
		if err != nil {
			// The peer half-closed (or reset): mirror a half-close back so
			// directional EOF semantics are observable end to end.
			_ = tc.CloseWrite()
			// Keep the read side open briefly is unnecessary; once the peer
			// has EOFed its writes the echo is complete. Close fully after.
			_ = tc.CloseRead()
			return
		}
	}
}

// Addr returns the echo listen address.
func (e *EchoUpstream) Addr() string { return e.ln.Addr().String() }

// SlowUpstream accepts a connection and then applies scripted timing: it can
// delay before draining, delay replies, and half-close on demand.
type SlowUpstream struct {
	ln         net.Listener
	conns      chan net.Conn
	ReadDelay  time.Duration
	ReplyDelay time.Duration
}

// StartSlow binds a controllable slow upstream and records accepted conns.
func StartSlow(t *testing.T) *SlowUpstream {
	t.Helper()
	ln, err := net.Listen("tcp4", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("slow listen: %v", err)
	}
	s := &SlowUpstream{ln: ln, conns: make(chan net.Conn, 8)}
	go func() {
		for {
			c, err := ln.Accept()
			if err != nil {
				return
			}
			s.conns <- c
			go s.serve(c)
		}
	}()
	t.Cleanup(func() { _ = ln.Close() })
	return s
}

func (s *SlowUpstream) serve(c net.Conn) {
	tc := c.(*net.TCPConn)
	br := bufio.NewReader(tc)
	// Read one line slowly, echoing it after ReplyDelay.
	line, err := br.ReadBytes('\n')
	if len(line) > 0 {
		if s.ReplyDelay > 0 {
			time.Sleep(s.ReplyDelay)
		}
		_, _ = tc.Write(line)
	}
	_ = err
	// Drain remaining input with the configured read pacing.
	buf := make([]byte, 4096)
	for {
		if s.ReadDelay > 0 {
			time.Sleep(s.ReadDelay)
		}
		n, rerr := br.Read(buf)
		if n > 0 {
			_, _ = tc.Write(buf[:n])
		}
		if rerr != nil {
			_ = tc.CloseWrite()
			return
		}
	}
}

// Addr returns the slow upstream address.
func (s *SlowUpstream) Addr() string { return s.ln.Addr().String() }

// AcceptedConns exposes connections the slow upstream accepted.
func (s *SlowUpstream) AcceptedConns() <-chan net.Conn { return s.conns }

// ---------------------------------------------------------------------------
// Segmented writer
// ---------------------------------------------------------------------------

// Segments writes each frame split one byte at a time with a pause, to prove
// the server reassembles handshakes across arbitrary TCP segmentation.
func Segments(t *testing.T, conn net.Conn, frames [][]byte, pause time.Duration) {
	t.Helper()
	for _, f := range frames {
		for _, b := range f {
			if _, err := conn.Write([]byte{b}); err != nil {
				t.Fatalf("segmented write: %v", err)
			}
			if pause > 0 {
				time.Sleep(pause)
			}
		}
	}
}
