//! Independent nested-loop reference implementation.
//!
//! This is deliberately the simplest possible evaluator and shares NO code
//! with [`super::iejoin`] beyond plan/value types: no permutations, no
//! bitmaps, no boundary logic. It exists so the IEJoin core can be tested
//! against an independently derived answer — the test oracle must not be
//! generated by the code under test itself.

use crate::error::JoinResult;
use crate::operator::iejoin::OutputPair;
use crate::operator::plan::{Comparator, JoinPlan};
use crate::types::{Scalar, TypedBatch};

fn eval(op: Comparator, a: &Scalar, b: &Scalar) -> bool {
    match op {
        Comparator::Lt => a.lt(b),
        Comparator::Le => a.le(b),
        Comparator::Gt => a.gt(b),
        Comparator::Ge => a.ge(b),
    }
}

/// Evaluate both predicates for every (left, right) pair in physical order.
/// Output order: outer left rows ascending, inner right rows ascending.
pub fn nested_loop(
    plan: &JoinPlan,
    left: &TypedBatch,
    right: &TypedBatch,
) -> JoinResult<Vec<OutputPair>> {
    plan.validate(left.column_count(), right.column_count())?;

    let l1 = left.column(plan.p1.left_col).unwrap().to_scalars();
    let r1 = right.column(plan.p1.right_col).unwrap().to_scalars();
    let l2 = left.column(plan.p2.left_col).unwrap().to_scalars();
    let r2 = right.column(plan.p2.right_col).unwrap().to_scalars();

    let mut out = Vec::new();
    for i in 0..left.row_count() {
        for j in 0..right.row_count() {
            if eval(plan.p1.op, &l1[i], &r1[j]) && eval(plan.p2.op, &l2[i], &r2[j]) {
                out.push(OutputPair {
                    left_row: i as u64,
                    right_row: j as u64,
                });
            }
        }
    }
    Ok(out)
}

/// Count the candidate pairs the nested loop *touches* (always |L| * |R|),
/// exposed for tests that compare work characteristics.
pub fn nested_loop_candidate_accesses(left_rows: usize, right_rows: usize) -> u64 {
    left_rows as u64 * right_rows as u64
}
