//! Independent nested-loop reference join.
//!
//! This is the small-scale oracle used by the test suite. It is
//! deliberately written as direct brute force over row pairs and shares
//! **no code** with the IEJoin core beyond the plan/value types: it
//! exists precisely so test expectations cannot be generated by the
//! system under test. Reference answers in the test fixtures are
//! hard-coded literals, independently cross-checked against this
//! implementation.
//!
//! Access accounting is explicit and naive, so tests can contrast work:
//!
//! * `p1_evaluations`  — every Cartesian `(l, r)` pair examined by
//!   predicate 1, i.e. `|L| * |R|` (NULL rows still cost an exam that
//!   returns false),
//! * `p2_evaluations`  — pairs that passed predicate 1 and reached
//!   predicate 2,
//! * `pairs_emitted`   — pairs satisfying both.
//!
//! The IEJoin `candidate_accesses` metric corresponds to work done
//! *after* the sorted gates, comparable in spirit to `p2_evaluations`
//! plus the linear gate motion.

use crate::batch::{Batch, OutputPair};
use crate::error::JoinResult;

use super::plan::JoinPlan;

/// Brute-force counters (independent metric set).
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct NestedLoopStats {
    pub p1_evaluations: u64,
    pub p2_evaluations: u64,
    pub pairs_emitted: u64,
}

/// Materialized reference result.
#[derive(Clone, Debug, Default)]
pub struct NestedLoopResult {
    /// Pairs in deterministic order: outer left, inner right.
    pub pairs: Vec<OutputPair>,
    pub stats: NestedLoopStats,
}

/// Evaluate the plan by nested loops. Complexity `O(|L|·|R|)`; intended
/// for small fixtures only.
///
/// # Errors
/// `Input` when a named column is missing.
pub fn execute(plan: &JoinPlan, left: &Batch, right: &Batch) -> JoinResult<NestedLoopResult> {
    plan.validate()?;
    let [p1, p2] = plan.ordered();

    let lx = col(left, &p1.left_column)?;
    let ly = col(left, &p2.left_column)?;
    let rx = col(right, &p1.right_column)?;
    let ry = col(right, &p2.right_column)?;

    let mut pairs = Vec::new();
    let mut stats = NestedLoopStats::default();

    for li in 0..left.row_count() {
        for ri in 0..right.row_count() {
            stats.p1_evaluations += 1;
            if !p1.op.eval(lx[li], rx[ri]) {
                continue;
            }
            stats.p2_evaluations += 1;
            if !p2.op.eval(ly[li], ry[ri]) {
                continue;
            }
            stats.pairs_emitted += 1;
            pairs.push(OutputPair {
                left_id: left.row_ids[li].clone(),
                right_id: right.row_ids[ri].clone(),
            });
        }
    }

    Ok(NestedLoopResult { pairs, stats })
}

fn col<'a>(b: &'a Batch, name: &str) -> JoinResult<&'a [Option<i64>]> {
    b.column(name).map(|c| c.values.as_slice()).ok_or_else(|| {
        crate::error::JoinError::input(
            "unknown_column",
            format!("reference: column '{name}' not found"),
        )
    })
}
