//! Deterministic hashing for the IBLT kernel.
//!
//! Two hash roles exist and are deliberately distinct:
//!
//! - **index hashes** map a key to `k` distinct cell positions;
//! - **key checksum** maps a key to a 64-bit tag stored in `hash_sum`,
//!   used to verify that a cell with `count == ±1` really holds exactly
//!   that key before it is peeled.
//!
//! Both are derived from splitmix64 so the whole pipeline is deterministic
//! and reproducible from `(seed, k, cells)` alone — no random state.

/// Default seed used when a request does not pin one.
pub const DEFAULT_SEED: u64 = 0x4942_4c54_5f76_3101; // "IBLT_v1" flavored
/// Default number of index hashes per key.
pub const DEFAULT_K: u32 = 3;
/// Maximum supported index-hash count (keeps index generation bounded).
pub const MAX_K: u32 = 8;

const GOLDEN: u64 = 0x9E37_79B9_7F4A_7C15;
/// Domain separator so the checksum stream differs from index streams.
const CHECKSUM_TAG: u64 = 0xC0FF_EE11_5EED_5EED;

/// splitmix64 finalizer: cheap, deterministic, good avalanche behavior.
pub fn splitmix64(mut x: u64) -> u64 {
    x = x.wrapping_add(0x9E37_79B9_7F4A_7C15);
    x = (x ^ (x >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    x = (x ^ (x >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    x ^ (x >> 31)
}

/// Hash context for one table shape `(seed, k, cells)`.
#[derive(Clone, Debug)]
pub struct Hasher {
    seed: u64,
    k: u32,
    cells: usize,
}

impl Hasher {
    pub fn new(seed: u64, k: u32, cells: usize) -> Self {
        debug_assert!((1..=MAX_K).contains(&k));
        debug_assert!(cells >= k as usize);
        Self { seed, k, cells }
    }

    /// 64-bit checksum of a key, stored in `Cell::hash_sum`.
    pub fn key_checksum(&self, key: u64) -> u64 {
        splitmix64(key ^ self.seed ^ CHECKSUM_TAG)
    }

    /// The `k` distinct cell indices for `key`.
    ///
    /// Distinctness matters: if one insert touched the same cell twice,
    /// the key's XOR contribution would cancel while the count would
    /// double, corrupting the cell. Indices are generated by deterministic
    /// rejection sampling, so the sequence is stable across processes.
    pub fn indices(&self, key: u64) -> Vec<usize> {
        let mut out: Vec<usize> = Vec::with_capacity(self.k as usize);
        let mut attempt: u64 = 0;
        while out.len() < self.k as usize {
            let h = splitmix64(key ^ self.seed ^ attempt.wrapping_mul(GOLDEN));
            let idx = (h % self.cells as u64) as usize;
            if !out.contains(&idx) {
                out.push(idx);
            }
            attempt += 1;
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn splitmix64_is_deterministic() {
        assert_eq!(splitmix64(42), splitmix64(42));
        assert_ne!(splitmix64(42), splitmix64(43));
    }

    #[test]
    fn indices_are_distinct_and_in_range() {
        let h = Hasher::new(DEFAULT_SEED, 3, 8);
        for key in 0..500u64 {
            let idx = h.indices(key);
            assert_eq!(idx.len(), 3);
            let mut sorted = idx.clone();
            sorted.sort_unstable();
            sorted.dedup();
            assert_eq!(sorted.len(), 3, "duplicate index for key {key}");
            assert!(idx.iter().all(|&i| i < 8));
        }
    }

    #[test]
    fn checksum_depends_on_seed() {
        let a = Hasher::new(1, 3, 8);
        let b = Hasher::new(2, 3, 8);
        assert_ne!(a.key_checksum(7), b.key_checksum(7));
    }
}
