//! Persistent run store: filesystem-backed sampling state.
//!
//! Layout under `data_dir`:
//! ```text
//! runs/<run_id>/meta.json      run metadata incl. symbol table and state
//! runs/<run_id>/samples.jsonl  one raw SampleInput per line, append-only
//! ```
//!
//! Lifecycle: `open -> sealed`. Ingest is accepted only while open; sealing
//! twice conflicts. Limits (runs, samples per run, batch size, stack depth)
//! are enforced here and reported as `resource_exhausted`.

use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::RwLock;

use crate::config::Limits;
use crate::error::BackendError;
use crate::model::{RunMeta, RunState, SampleInput, SymbolEntry};
use crate::stitch::{stitch_samples, StitchedSample};
use crate::symbols::SymbolTable;

pub struct Run {
    pub meta: RunMeta,
    /// Raw samples as ingested (authoritative, persisted).
    pub raw: Vec<SampleInput>,
    /// Resolved + stitched view, recomputed on every ingest so async
    /// fragments can attach to parents from earlier batches.
    pub stitched: Vec<StitchedSample>,
}

#[derive(Debug)]
pub struct IngestReport {
    pub accepted: usize,
    pub total_samples: usize,
    pub stitched_count: usize,
    pub detached_count: usize,
}

pub struct RunStore {
    /// Runs directory; immutable after open, so path helpers never lock.
    dir: PathBuf,
    inner: RwLock<StoreInner>,
}

struct StoreInner {
    limits: Limits,
    runs: std::collections::HashMap<String, Run>,
}

fn now_unix() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

fn new_run_id() -> String {
    let uuid = uuid::Uuid::new_v4().simple().to_string();
    format!("run-{}-{}", now_unix(), &uuid[..8])
}

impl RunStore {
    /// Opens (or creates) the store directory and reloads persisted runs.
    /// Corrupt runs are skipped with a warning so the diagnostic interface
    /// stays available.
    pub fn open(dir: PathBuf, limits: Limits) -> Result<Self, BackendError> {
        let runs_dir = dir.join("runs");
        fs::create_dir_all(&runs_dir).map_err(|e| {
            BackendError::computation("store_init", format!("cannot create {}: {e}", runs_dir.display()))
        })?;
        let mut runs = std::collections::HashMap::new();
        let entries = fs::read_dir(&runs_dir).map_err(|e| {
            BackendError::computation("store_init", format!("cannot list {}: {e}", runs_dir.display()))
        })?;
        for entry in entries.flatten() {
            match Self::load_run(&entry.path()) {
                Ok(run) => {
                    runs.insert(run.meta.run_id.clone(), run);
                }
                Err(e) => {
                    tracing::warn!(path = %entry.path().display(), error = %e, "skipping corrupt run");
                }
            }
        }
        tracing::info!(loaded = runs.len(), dir = %runs_dir.display(), "run store opened");
        Ok(Self { dir: runs_dir, inner: RwLock::new(StoreInner { limits, runs }) })
    }

    fn load_run(run_dir: &Path) -> Result<Run, BackendError> {
        let meta_text = fs::read_to_string(run_dir.join("meta.json"))
            .map_err(|e| BackendError::computation("store_load", format!("meta.json: {e}")))?;
        let meta: RunMeta = serde_json::from_str(&meta_text)
            .map_err(|e| BackendError::computation("store_load", format!("meta.json parse: {e}")))?;
        let mut raw = Vec::new();
        let samples_path = run_dir.join("samples.jsonl");
        if samples_path.exists() {
            let text = fs::read_to_string(&samples_path)
                .map_err(|e| BackendError::computation("store_load", format!("samples.jsonl: {e}")))?;
            for (lineno, line) in text.lines().enumerate() {
                if line.trim().is_empty() {
                    continue;
                }
                let sample: SampleInput = serde_json::from_str(line).map_err(|e| {
                    BackendError::computation(
                        "store_load",
                        format!("samples.jsonl line {}: {e}", lineno + 1),
                    )
                })?;
                raw.push(sample);
            }
        }
        let table = SymbolTable::build(meta.symbols.clone())?;
        let stitched = stitch_samples(&raw, &table)?;
        Ok(Run { meta, raw, stitched })
    }

    fn run_dir(&self, run_id: &str) -> PathBuf {
        // run_id is generated by this process; reject path separators anyway.
        let safe: String = run_id
            .chars()
            .map(|c| if c.is_ascii_alphanumeric() || c == '-' { c } else { '_' })
            .collect();
        self.dir.join(safe)
    }

    pub fn create_run(
        &self,
        symbols: Vec<SymbolEntry>,
        dropped_samples: u64,
        drop_reason: Option<String>,
    ) -> Result<RunMeta, BackendError> {
        let table = SymbolTable::build(symbols.clone())?;
        let _ = &table; // validation happens now; resolution per ingest
        let mut inner = self.inner.write().unwrap();
        if inner.runs.len() >= inner.limits.max_runs {
            return Err(BackendError::resource(
                "run_limit",
                format!("max_runs {} reached", inner.limits.max_runs),
            ));
        }
        let meta = RunMeta {
            run_id: new_run_id(),
            state: RunState::Open,
            created_unix: now_unix(),
            dropped_samples,
            drop_reason,
            symbols,
        };
        let run_dir = self.dir.join(&meta.run_id);
        fs::create_dir_all(&run_dir).map_err(|e| {
            BackendError::computation("persistence_io", format!("create run dir: {e}"))
        })?;
        let meta_text = serde_json::to_string_pretty(&meta)
            .map_err(|e| BackendError::computation("persistence_io", e.to_string()))?;
        fs::write(run_dir.join("meta.json"), meta_text)
            .map_err(|e| BackendError::computation("persistence_io", format!("write meta.json: {e}")))?;
        inner.runs.insert(
            meta.run_id.clone(),
            Run { meta: meta.clone(), raw: Vec::new(), stitched: Vec::new() },
        );
        tracing::info!(run_id = %meta.run_id, symbols = meta.symbols.len(), "run created");
        Ok(meta)
    }

    pub fn ingest(&self, run_id: &str, batch: Vec<SampleInput>) -> Result<IngestReport, BackendError> {
        let mut inner = self.inner.write().unwrap();
        let limits = inner.limits.clone();
        let run = inner.runs.get_mut(run_id).ok_or_else(|| {
            BackendError::input("run_not_found", format!("no run {run_id}"))
        })?;
        if run.meta.state == RunState::Sealed {
            return Err(BackendError::conflict(
                "run_sealed",
                format!("run {run_id} is sealed; ingest rejected"),
            ));
        }
        if batch.len() > limits.max_samples_per_request {
            return Err(BackendError::resource(
                "batch_too_large",
                format!("batch of {} exceeds max_samples_per_request {}", batch.len(), limits.max_samples_per_request),
            ));
        }
        if run.raw.len() + batch.len() > limits.max_samples_per_run {
            return Err(BackendError::resource(
                "sample_limit",
                format!(
                    "run {run_id}: {} existing + {} new exceeds max_samples_per_run {}",
                    run.raw.len(),
                    batch.len(),
                    limits.max_samples_per_run
                ),
            ));
        }
        let mut seen: HashSet<&str> = run.raw.iter().map(|s| s.sample_id.as_str()).collect();
        for s in &batch {
            s.validate()?;
            if !seen.insert(s.sample_id.as_str()) {
                return Err(BackendError::input(
                    "duplicate_sample_id",
                    format!("sample_id {} already exists in run {run_id}", s.sample_id),
                ));
            }
        }

        // Trial-resolve the full run so async children can attach to parents
        // ingested in earlier batches; commit only on success.
        let mut all = run.raw.clone();
        all.extend(batch.iter().cloned());
        let table = SymbolTable::build(run.meta.symbols.clone())?;
        let stitched = stitch_samples(&all, &table)?;
        for s in &stitched {
            if s.frames.len() > limits.max_stack_depth {
                return Err(BackendError::resource(
                    "stack_too_deep",
                    format!(
                        "sample {}: stitched depth {} exceeds max_stack_depth {}",
                        s.sample_id,
                        s.frames.len(),
                        limits.max_stack_depth
                    ),
                ));
            }
        }

        // Persist first; only then commit in-memory state.
        let mut text = String::new();
        for s in &batch {
            let line = serde_json::to_string(s)
                .map_err(|e| BackendError::computation("persistence_io", e.to_string()))?;
            text.push_str(&line);
            text.push('\n');
        }
        let samples_path = self.run_dir(run_id).join("samples.jsonl");
        fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&samples_path)
            .and_then(|mut f| std::io::Write::write_all(&mut f, text.as_bytes()))
            .map_err(|e| BackendError::computation("persistence_io", format!("append samples: {e}")))?;

        let detached = stitched
            .iter()
            .filter(|s| matches!(s.evidence, crate::stitch::StitchEvidence::Detached { .. }))
            .count();
        let report = IngestReport {
            accepted: batch.len(),
            total_samples: all.len(),
            stitched_count: stitched.len(),
            detached_count: detached,
        };
        run.raw = all;
        run.stitched = stitched;
        tracing::info!(
            run_id,
            accepted = report.accepted,
            total = report.total_samples,
            detached = report.detached_count,
            "ingest committed"
        );
        Ok(report)
    }

    pub fn seal(&self, run_id: &str) -> Result<RunMeta, BackendError> {
        let mut inner = self.inner.write().unwrap();
        let run = inner.runs.get_mut(run_id).ok_or_else(|| {
            BackendError::input("run_not_found", format!("no run {run_id}"))
        })?;
        if run.meta.state == RunState::Sealed {
            return Err(BackendError::conflict(
                "already_sealed",
                format!("run {run_id} was already sealed"),
            ));
        }
        run.meta.state = RunState::Sealed;
        let meta_text = serde_json::to_string_pretty(&run.meta)
            .map_err(|e| BackendError::computation("persistence_io", e.to_string()))?;
        fs::write(self.run_dir(run_id).join("meta.json"), meta_text)
            .map_err(|e| BackendError::computation("persistence_io", format!("write meta.json: {e}")))?;
        tracing::info!(run_id, samples = run.raw.len(), "run sealed");
        Ok(run.meta.clone())
    }

    /// Read-only access to a run for query handlers.
    pub fn with_run<T>(
        &self,
        run_id: &str,
        f: impl FnOnce(&Run) -> Result<T, BackendError>,
    ) -> Result<T, BackendError> {
        let inner = self.inner.read().unwrap();
        let run = inner.runs.get(run_id).ok_or_else(|| {
            BackendError::input("run_not_found", format!("no run {run_id}"))
        })?;
        f(run)
    }

    pub fn list_runs(&self) -> Vec<RunMeta> {
        let inner = self.inner.read().unwrap();
        let mut metas: Vec<RunMeta> = inner.runs.values().map(|r| r.meta.clone()).collect();
        metas.sort_by(|a, b| a.run_id.cmp(&b.run_id));
        metas
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::FrameInput;

    fn limits() -> Limits {
        Limits {
            max_runs: 4,
            max_samples_per_run: 8,
            max_stack_depth: 8,
            max_samples_per_request: 8,
        }
    }

    fn sample(id: &str, addrs: &[u64]) -> SampleInput {
        SampleInput {
            sample_id: id.into(),
            weight: 1.0,
            frames: addrs.iter().map(|&addr| FrameInput { addr, module: None }).collect(),
            async_link: None,
        }
    }

    #[test]
    fn ingest_seal_reload_roundtrip() {
        let dir = tempfile::tempdir().unwrap();
        let store = RunStore::open(dir.path().to_path_buf(), limits()).unwrap();
        let meta = store.create_run(vec![], 0, None).unwrap();
        let report = store
            .ingest(&meta.run_id, vec![sample("a", &[1, 2]), sample("b", &[1, 3])])
            .unwrap();
        assert_eq!(report.accepted, 2);
        store.seal(&meta.run_id).unwrap();

        // Reopen from disk: state and samples must survive.
        let store2 = RunStore::open(dir.path().to_path_buf(), limits()).unwrap();
        store2
            .with_run(&meta.run_id, |run| {
                assert_eq!(run.meta.state, RunState::Sealed);
                assert_eq!(run.raw.len(), 2);
                assert_eq!(run.stitched.len(), 2);
                Ok(())
            })
            .unwrap();
    }

    #[test]
    fn ingest_into_sealed_run_conflicts() {
        let dir = tempfile::tempdir().unwrap();
        let store = RunStore::open(dir.path().to_path_buf(), limits()).unwrap();
        let meta = store.create_run(vec![], 0, None).unwrap();
        store.seal(&meta.run_id).unwrap();
        let err = store.ingest(&meta.run_id, vec![sample("a", &[1])]).unwrap_err();
        assert_eq!(err.category, crate::error::ErrorCategory::StateConflict);
        assert_eq!(err.code, "run_sealed");
    }

    #[test]
    fn limits_are_resource_errors() {
        let dir = tempfile::tempdir().unwrap();
        let store = RunStore::open(dir.path().to_path_buf(), limits()).unwrap();
        let meta = store.create_run(vec![], 0, None).unwrap();
        // Depth 9 > max_stack_depth 8.
        let deep = sample("deep", &[1, 2, 3, 4, 5, 6, 7, 8, 9]);
        let err = store.ingest(&meta.run_id, vec![deep]).unwrap_err();
        assert_eq!(err.category, crate::error::ErrorCategory::ResourceExhausted);
        assert_eq!(err.code, "stack_too_deep");
        // 9 samples > max_samples_per_run 8 (sent in two batches under the
        // per-request cap).
        let first: Vec<SampleInput> = (0..8).map(|i| sample(&format!("s{i}"), &[1])).collect();
        store.ingest(&meta.run_id, first).unwrap();
        let err = store.ingest(&meta.run_id, vec![sample("s8", &[1])]).unwrap_err();
        assert_eq!(err.code, "sample_limit");
    }

    #[test]
    fn unknown_run_is_input_not_found() {
        let dir = tempfile::tempdir().unwrap();
        let store = RunStore::open(dir.path().to_path_buf(), limits()).unwrap();
        let err = store.ingest("run-nope", vec![sample("a", &[1])]).unwrap_err();
        assert_eq!(err.category, crate::error::ErrorCategory::Input);
        assert_eq!(err.code, "run_not_found");
    }

    #[test]
    fn duplicate_sample_id_rejected() {
        let dir = tempfile::tempdir().unwrap();
        let store = RunStore::open(dir.path().to_path_buf(), limits()).unwrap();
        let meta = store.create_run(vec![], 0, None).unwrap();
        store.ingest(&meta.run_id, vec![sample("a", &[1])]).unwrap();
        let err = store.ingest(&meta.run_id, vec![sample("a", &[2])]).unwrap_err();
        assert_eq!(err.code, "duplicate_sample_id");
    }
}
