"""Deterministic synthetic fixtures.

The fixtures are small on purpose: every answer they produce is hand-computable
and is recorded independently in ``tests/reference_expected.py``. That file is
the oracle; it never imports the estimation core, so the expected answers are
not generated by the code being tested.

Fixture catalogue
-----------------
``hand_2x2``
    Clean two-group/two-period panel. DID = 3 by construction.
``missing_period``
    Same panel plus a unit observed in only one period: it must be aligned by
    identity, recorded as excluded, and never imputed as zero.
``nonparallel_pretrend``
    Three periods. Treated and control already diverge before onset: the
    pre-treatment slope difference is exactly 3.0, so the diagnostic must
    FALSIFY (not clear) parallel trends.
``contaminated_control``
    A control unit is treated in the middle period only. It must be recorded
    as contamination; the clean-sample DID is computed without it.
``weighted_2x2``
    Unequal but period-fixed unit weights; weighted DID = 7 by construction.
``staggered_events``
    Two onset cohorts (g=2, g=3) plus never-treated controls, periods 0..3,
    with true event coefficients tau_0 = 5, tau_1 = 8 and zero leads.
``staggered_events_out_of_support``
    Same cohorts, periods 0..3; requesting event time +2 has no support and
    must be refused.

A seed is kept for fixtures that draw noise (none currently need randomness;
all values are explicit constants, which is stronger for auditing).
"""
from __future__ import annotations

from collections.abc import Callable

from app.contracts.models import Observation as O

ObsBuilder = Callable[[], list[O]]


def _hand_2x2() -> list[O]:
    # Treated changes 3 and 5 (mean 4); control changes 0 and 2 (mean 1).
    # Heterogeneous within-group changes give NONZERO residuals, so the
    # clustered sandwich standard error is a meaningful, hand-derived target
    # (se = sqrt(2); see tests/reference_expected.py). DID = 4 - 1 = 3.
    return [
        O(unit_id="t1", period=0, y=2.0, treated=False),
        O(unit_id="t1", period=1, y=5.0, treated=True),
        O(unit_id="t2", period=0, y=4.0, treated=False),
        O(unit_id="t2", period=1, y=9.0, treated=True),
        O(unit_id="c1", period=0, y=1.0, treated=False),
        O(unit_id="c1", period=1, y=1.0, treated=False),
        O(unit_id="c2", period=0, y=3.0, treated=False),
        O(unit_id="c2", period=1, y=5.0, treated=False),
    ]


def _missing_period() -> list[O]:
    obs = _hand_2x2()
    # m1 appears only post. A naive "missing = zero" would assign it y_pre = 0
    # and fabricate a huge treated change; correct behavior excludes it.
    obs.append(O(unit_id="m1", period=1, y=20.0, treated=True))
    # m2 appears only pre; likewise must not become a control with y_post = 0.
    obs.append(O(unit_id="m2", period=0, y=0.0, treated=False))
    return obs


def _nonparallel_pretrend() -> list[O]:
    # Periods 0,1 are pre (onset = period 2). Pre-period period-over-period
    # changes: treated units +3.5,+4,+3 (mean 3.5), controls +0.5,+0,+1
    # (mean 0.5). Interaction (slope gap) = 3.0 exactly. Post values are
    # irrelevant to the pre-trend test but present for completeness.
    rows = []
    treated_levels = {
        "t1": (0.0, 3.5, 7.0),
        "t2": (0.0, 4.0, 8.0),
        "t3": (0.0, 3.0, 6.0),
    }
    control_levels = {
        "c1": (0.0, 0.5, 1.0),
        "c2": (0.0, 0.0, 0.0),
        "c3": (0.0, 1.0, 2.0),
    }
    for uid, (y0, y1, y2) in treated_levels.items():
        rows += [
            O(unit_id=uid, period=0, y=y0, treated=False),
            O(unit_id=uid, period=1, y=y1, treated=False),
            O(unit_id=uid, period=2, y=y2, treated=True),
        ]
    for uid, (y0, y1, y2) in control_levels.items():
        rows += [
            O(unit_id=uid, period=0, y=y0, treated=False),
            O(unit_id=uid, period=1, y=y1, treated=False),
            O(unit_id=uid, period=2, y=y2, treated=False),
        ]
    return rows


def _contaminated_control() -> list[O]:
    # 2x2 uses pre=0, post=2. c2 is untreated at 0 and 2 but TREATED at 1.
    return [
        O(unit_id="t1", period=0, y=1.0, treated=False),
        O(unit_id="t1", period=1, y=1.0, treated=False),
        O(unit_id="t1", period=2, y=5.0, treated=True),
        O(unit_id="c1", period=0, y=2.0, treated=False),
        O(unit_id="c1", period=1, y=2.0, treated=False),
        O(unit_id="c1", period=2, y=2.0, treated=False),
        O(unit_id="c2", period=0, y=2.0, treated=False),
        O(unit_id="c2", period=1, y=9.0, treated=True),   # contamination
        O(unit_id="c2", period=2, y=2.0, treated=False),
    ]


def _weighted_2x2() -> list[O]:
    # Baseline-fixed weights (identical pre and post):
    #   treated weighted change = (3*10 + 1*2)/4 = 8
    #   control weighted change = (1*4 + 3*0)/4  = 1
    #   weighted DID = 7
    return [
        O(unit_id="t1", period=0, y=0.0, treated=False, weight=3.0),
        O(unit_id="t1", period=1, y=10.0, treated=True, weight=3.0),
        O(unit_id="t2", period=0, y=0.0, treated=False, weight=1.0),
        O(unit_id="t2", period=1, y=2.0, treated=True, weight=1.0),
        O(unit_id="c1", period=0, y=0.0, treated=False, weight=1.0),
        O(unit_id="c1", period=1, y=4.0, treated=False, weight=1.0),
        O(unit_id="c2", period=0, y=0.0, treated=False, weight=3.0),
        O(unit_id="c2", period=1, y=0.0, treated=False, weight=3.0),
    ]


def _staggered_events() -> list[O]:
    # DGP: y = gamma_t + tau_k, gamma = (0,1,2,3), tau = 0 pre, 5 at k=0, 8 at k=1.
    rows: list[O] = []
    # cohort g=2
    a = {"a1": (0.0, 1.0, 7.0, 11.0), "a2": (0.0, 1.0, 7.0, 11.0)}
    # cohort g=3
    b = {"b1": (0.0, 1.0, 2.0, 8.0), "b2": (0.0, 1.0, 2.0, 8.0)}
    # never treated
    n = {"n1": (0.0, 1.0, 2.0, 3.0), "n2": (0.0, 1.0, 2.0, 3.0)}
    for uid, vals in a.items():
        for t, y in enumerate(vals):
            rows.append(O(unit_id=uid, period=t, y=y, treated=(t >= 2)))
    for uid, vals in b.items():
        for t, y in enumerate(vals):
            rows.append(O(unit_id=uid, period=t, y=y, treated=(t >= 3)))
    for uid, vals in n.items():
        for t, y in enumerate(vals):
            rows.append(O(unit_id=uid, period=t, y=y, treated=False))
    return rows


def _staggered_out_of_support() -> list[O]:
    # Same information content; the fixture exists so the request intent is
    # explicit and the registry documents the refusal case.
    return _staggered_events()


FIXTURE_REGISTRY: dict[str, ObsBuilder] = {
    "hand_2x2": _hand_2x2,
    "missing_period": _missing_period,
    "nonparallel_pretrend": _nonparallel_pretrend,
    "contaminated_control": _contaminated_control,
    "weighted_2x2": _weighted_2x2,
    "staggered_events": _staggered_events,
    "staggered_events_out_of_support": _staggered_out_of_support,
}


def build_fixture(name: str) -> list[O]:
    try:
        builder = FIXTURE_REGISTRY[name]
    except KeyError:
        raise KeyError(
            f"unknown fixture {name!r}; available: {sorted(FIXTURE_REGISTRY)}"
        ) from None
    return builder()


def list_fixtures() -> list[str]:
    return sorted(FIXTURE_REGISTRY)
