"""Hand-computed label scenarios: independent proofs, shared premises,
subset minimality and propagation through chains.

All expected labels below are worked out by hand, not generated by the
engine under test.
"""

from app.core.engine import ATMS
from app.core.types import Rule


def make_engine(budget) -> ATMS:
    return ATMS(budget)


def test_multiple_independent_proofs_give_two_environments(budget):
    # P is a shared premise; C follows from P,A and independently from P,B.
    # Hand-computed: label(C) = {{A}, {B}}.
    engine = make_engine(budget)
    engine.add_premise("P")
    engine.add_assumption("A")
    engine.add_assumption("B")
    engine.add_rule(Rule("r1", ("P", "A"), "C"))
    engine.add_rule(Rule("r2", ("P", "B"), "C"))

    result = engine.query("C")
    assert result["environments"] == [["A"], ["B"]]
    assert result["status"] == "supported"
    assert result["complete"] is True


def test_label_is_subset_minimal(budget):
    # r2's environment {A,B} is subsumed by r1's {A} and must be dropped.
    engine = make_engine(budget)
    engine.add_assumption("A")
    engine.add_assumption("B")
    engine.add_rule(Rule("r1", ("A",), "X"))
    engine.add_rule(Rule("r2", ("A", "B"), "X"))

    assert engine.query("X")["environments"] == [["A"]]


def test_chain_propagates_single_environment(budget):
    engine = make_engine(budget)
    engine.add_assumption("A")
    engine.add_rule(Rule("r1", ("A",), "B"))
    engine.add_rule(Rule("r2", ("B",), "C"))
    engine.add_rule(Rule("r3", ("C",), "D"))

    assert engine.query("D")["environments"] == [["A"]]


def test_premise_has_empty_environment(budget):
    engine = make_engine(budget)
    engine.add_premise("P")
    engine.add_rule(Rule("r1", ("P",), "Q"))

    assert engine.query("P")["environments"] == [[]]
    assert engine.query("Q")["environments"] == [[]]


def test_unknown_node_is_unsupported_when_complete(budget):
    engine = make_engine(budget)
    engine.add_assumption("A")
    result = engine.query("never-derived")
    assert result["environments"] == []
    assert result["status"] == "unsupported"


def test_rejected_operations_report_reasons(budget):
    engine = make_engine(budget)
    assert engine.add_assumption("A").accepted
    dup = engine.add_assumption("A")
    assert not dup.accepted
    assert dup.reason == "assumption-already-active"

    missing = engine.retract_assumption("ghost")
    assert not missing.accepted
    assert missing.reason == "assumption-not-active"

    reserved = engine.add_assumption("⊥")
    assert not reserved.accepted
    assert reserved.reason == "reserved-name"

    engine.add_rule(Rule("r1", ("A",), "B"))
    dup_rule = engine.add_rule(Rule("r1", ("A",), "C"))
    assert not dup_rule.accepted
    assert dup_rule.reason == "rule-id-exists"
