"""Frozen regression tests on the committed sample datasets.

Reference answers are *frozen numeric constants* computed once from the
independent QR/scalar reference in ``conftest`` (not regenerated by the
production kernel), plus the ground-truth file shipped next to each sample.
If the kernel drifts, these fail with the exact diverging value.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from app.core.contracts import MissingPolicy, Settings
from app.core.service import data_fingerprint, run_analysis

ROOT = Path(__file__).resolve().parents[2]
SAMPLE = ROOT / "data" / "sample"


def _load(name: str) -> tuple[dict, dict]:
    payload = json.loads((SAMPLE / f"{name}.json").read_text())
    truth = json.loads((SAMPLE / f"{name}.truth.json").read_text())
    return payload, truth


# Frozen constants (see module docstring for provenance).
FROZEN = {
    "balanced": {
        "n_rows": 2000,
        "unadjusted": (2.1206074698, 0.1416506956),
        "cuped":       (2.0041737136, 0.0449811703),
        "lin":         (2.0028141308, 0.0449990456),
        "theta_pre_x": 2.99529830,
    },
    "imbalanced": {
        "n_rows": 2000,
        "unadjusted": (1.6909491604, 0.1508499270),
        "cuped":       (1.9248459565, 0.0485723478),
        "lin":         (1.9216823710, 0.0486900717),
        "n_control": 1397,
        "n_treatment": 603,
    },
}


@pytest.mark.parametrize("sample_payload", ["balanced", "imbalanced"],
                         indirect=True)
def test_frozen_point_estimates_and_se(sample_payload, request, case_log):
    name = request.node.callspec.params["sample_payload"]
    result = run_analysis(sample_payload, Settings())
    frozen = FROZEN[name]
    case_log("frozen sample regression", dataset=name,
             run_id=result.run_id, fingerprint=result.data_fingerprint,
             unadjusted=(result.unadjusted.estimate, result.unadjusted.se),
             cuped=(result.cuped.estimate, result.cuped.se),
             lin=(result.lin.estimate, result.lin.se))

    assert result.n_rows == frozen["n_rows"]
    assert result.unadjusted.estimate == pytest.approx(frozen["unadjusted"][0], abs=1e-9)
    assert result.unadjusted.se == pytest.approx(frozen["unadjusted"][1], rel=1e-9)
    assert result.cuped.estimate == pytest.approx(frozen["cuped"][0], abs=1e-9)
    assert result.cuped.se == pytest.approx(frozen["cuped"][1], rel=1e-9)
    assert result.lin.estimate == pytest.approx(frozen["lin"][0], abs=1e-9)
    assert result.lin.se == pytest.approx(frozen["lin"][1], rel=1e-9)


@pytest.mark.parametrize("sample_payload", ["balanced"], indirect=True)
def test_balanced_estimate_near_known_truth_and_var_reduced(
        sample_payload, case_log):
    payload, truth = _load("balanced")
    result = run_analysis(sample_payload, Settings())
    case_log("truth comparison", truth_tau=truth["tau"],
             cuped_estimate=result.cuped.estimate,
             unadjusted_estimate=result.unadjusted.estimate)
    # Adjusted estimates recover tau=2 within 0.05; unadjusted is noisier.
    assert abs(result.cuped.estimate - truth["tau"]) < 0.05
    assert abs(result.lin.estimate - truth["tau"]) < 0.05
    assert result.cuped.se < result.unadjusted.se / 3.0
    theta_by_name = dict(zip(result.cuped.covariate_names, result.cuped.theta))
    assert theta_by_name["pre_x"] == pytest.approx(FROZEN["balanced"]["theta_pre_x"], rel=1e-6)
    # Leakage field excluded from the adjustment, evidence kept.
    assert "post_spend" in result.dropped_covariates
    assert "constant" in result.dropped_covariates
    assert all(c.passed for c in result.cross_checks)


@pytest.mark.parametrize("sample_payload", ["imbalanced"], indirect=True)
def test_imbalanced_arm_counts_and_welch_family(sample_payload):
    result = run_analysis(sample_payload, Settings())
    assert result.groups[0].n == 1397
    assert result.groups[1].n == 603
    # Adjustment corrects the covariate-induced bias toward the truth.
    assert abs(result.cuped.estimate - 2.0) < 0.12
    assert result.cuped.se_type == "welch"
    assert result.cuped.df < result.n_complete_rows - 2


def test_fingerprint_is_deterministic_and_input_sensitive():
    payload, _ = _load("balanced")
    fp1 = data_fingerprint(payload)
    fp2 = data_fingerprint(json.loads(json.dumps(payload)))
    assert fp1 == fp2
    changed = json.loads(json.dumps(payload))
    changed["data"]["y"][0] += 1.0
    assert data_fingerprint(changed) != fp1


def test_fingerprint_changes_with_analysis_choices():
    # Review L1: given_theta / policies materially change the answer and must
    # change the fingerprint even with identical raw data.
    from app.core.contracts import LeakagePolicy, ThetaSource
    p, _ = _load("balanced")
    r1 = run_analysis(p, Settings())
    p2 = json.loads(json.dumps(p))
    p2["given_theta"] = [3.0, 0.0]
    r2 = run_analysis(p2, Settings(theta_source=ThetaSource.GIVEN))
    r3 = run_analysis(p, Settings(leakage_policy=LeakagePolicy.IGNORE))
    assert r1.data_fingerprint != r2.data_fingerprint
    assert r1.data_fingerprint != r3.data_fingerprint


@pytest.mark.parametrize("sample_payload", ["balanced"], indirect=True)
def test_run_identity_fields_populated(sample_payload):
    result = run_analysis(sample_payload, Settings())
    assert len(result.run_id) == 12
    assert len(result.data_fingerprint) == 16
    assert result.created_at.endswith("+00:00")
    assert set(result.versions) == {"python", "numpy", "scipy", "backend"}
    # Unadjusted and adjusted reported side by side.
    assert result.unadjusted.estimator == "groups_unadjusted"
    assert result.cuped.estimator == "cuped"
    assert result.lin.estimator == "lin_ancova"


@pytest.mark.parametrize("policy,expected_n", [
    (MissingPolicy.COMPLETE_CASES, 950),
    (MissingPolicy.MEAN_IMPUTE, 1000),
])
def test_missing_sample_policies(policy, expected_n, case_log):
    payload, truth = _load("missing")
    result = run_analysis(payload, Settings(missing_policy=policy))
    case_log("missing policy", policy=policy.value,
             n_complete=result.n_complete_rows, tau=result.cuped.estimate)
    assert result.n_complete_rows == expected_n
    assert abs(result.cuped.estimate - truth["tau"]) < 0.05


def test_missing_sample_fails_by_default():
    payload, _ = _load("missing")
    with pytest.raises(Exception) as exc:
        run_analysis(payload, Settings())
    from app.core.contracts import EstimationError
    assert isinstance(exc.value, EstimationError)
    assert exc.value.code.value == "MISSING_VALUES_PRESENT"
