"""Architectural independence guards.

The Monte Carlo evidence must be an *external* witness: it recomputes test
decisions from raw synthetic draws and must not reuse the solver or analytic
kernel it is meant to validate (otherwise the reference answer would be
generated by the system under test).
"""
from __future__ import annotations

import ast
from pathlib import Path

import pytest

SRC = Path(__file__).resolve().parents[2] / "src" / "sample_size_planner"


def _imports_of(relative_path: str) -> set[str]:
    tree = ast.parse((SRC / relative_path).read_text())
    modules: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            modules.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            modules.add(node.module)
    return modules


@pytest.mark.unit
def test_simulator_does_not_import_solver_or_kernel() -> None:
    modules = _imports_of("evidence/simulation.py")
    forbidden = [m for m in modules if "estimation" in m or "solvers" in m]
    assert forbidden == [], f"simulation must be independent; found {forbidden}"


@pytest.mark.unit
def test_integer_search_does_not_import_distributions() -> None:
    modules = _imports_of("estimation/integer_search.py")
    assert not any("noncentral" in m or "scipy" in m for m in modules)


@pytest.mark.unit
def test_noncentral_kernel_does_not_import_search_or_solvers() -> None:
    modules = _imports_of("estimation/noncentral.py")
    assert not any("integer_search" in m or "solvers" in m for m in modules)
