"""Unit tests for the Levinson-Durbin recursion.

Cross-checked against an independent Toeplitz solver (scipy) and a
hand-computed second-order example — never against itself.
"""

from __future__ import annotations

import numpy as np
import pytest

from app.lpc.levinson import (
    DIAG_SINGULAR_AUTOCORR,
    DIAG_UNSTABLE_REFLECTION,
    DIAG_ZERO_ENERGY,
    levinson_durbin,
)
from app.lpc.reference import solve_toeplitz_reference


def test_hand_computed_second_order():
    # r = [2, -1, 0.5]; by hand:
    # k1 = -r1/r0 = 0.5, a = [1, 0.5], E1 = 2*(1-0.25) = 1.5
    # k2 = -(r2 + a1*r1)/E1 = -(0.5 - 0.5)/1.5 = 0, a = [1, 0.5, 0]
    res = levinson_durbin(np.array([2.0, -1.0, 0.5]), 2)
    np.testing.assert_allclose(res.lpc, [1.0, 0.5, 0.0], atol=1e-15)
    np.testing.assert_allclose(res.reflection_coeffs, [0.5, 0.0], atol=1e-15)
    assert res.error_energy == pytest.approx(1.5)
    assert res.gain == pytest.approx(np.sqrt(1.5))
    assert res.stable
    assert res.diagnostics == ()


def test_matches_independent_toeplitz_solve(noise):
    from app.lpc.autocorr import autocorrelation

    order = 12
    r = autocorrelation(noise[:512], order)
    res = levinson_durbin(r, order)
    ref = solve_toeplitz_reference(r, order)
    np.testing.assert_allclose(res.lpc, ref, rtol=0, atol=1e-10)
    # residual energy identity: E = r[0] + sum a_i r_i
    e_direct = r[0] + float(np.dot(res.lpc[1:], r[1:]))
    assert res.error_energy == pytest.approx(e_direct, rel=1e-10)


def test_zero_energy_frame_has_defined_output():
    res = levinson_durbin(np.zeros(6), 5)
    assert res.zero_energy
    np.testing.assert_array_equal(res.lpc, [1.0, 0, 0, 0, 0, 0])
    assert res.gain == 0.0
    assert res.error_energy == 0.0
    assert res.stable  # trivially stable: A(z) = 1
    assert DIAG_ZERO_ENERGY in res.diagnostics


def test_unstable_reflection_coefficient_is_diagnosed():
    # |r1| > r0 violates positive-definiteness -> |k1| > 1
    res = levinson_durbin(np.array([1.0, 2.0, 0.5, 0.1]), 3)
    assert not res.stable
    assert res.max_abs_reflection >= 1.0
    assert DIAG_UNSTABLE_REFLECTION in res.diagnostics
    # error energy goes non-positive -> singular diagnostic follows
    assert DIAG_SINGULAR_AUTOCORR in res.diagnostics


def test_order_too_high_for_signal_content_is_diagnosed():
    """An exactly rank-2 autocorrelation (a pure sinusoid's r[k]=cos(wk))
    solved at order 40 must surface instability and singularity
    diagnostics, not silent garbage."""
    w = 0.7
    r = np.cos(w * np.arange(41))  # Toeplitz of this is exactly rank 2
    res = levinson_durbin(r, 40)
    assert not res.stable
    assert DIAG_UNSTABLE_REFLECTION in res.diagnostics
    assert DIAG_SINGULAR_AUTOCORR in res.diagnostics
    assert res.error_energy == 0.0
    # coefficients after the breakdown point are zeroed, not NaN
    assert np.all(np.isfinite(res.lpc))


def test_high_order_sine_deviates_from_toeplitz_reference(sine_signal):
    """Order 40 on a rank-2-ish windowed sinusoid: the recursion and the
    independent Toeplitz solve must be reported as diverging by the
    verification cross-check (ill-conditioning surfaced, not hidden)."""
    from app.lpc.autocorr import apply_window, autocorrelation
    from app.verification import cross_check_toeplitz

    order = 40
    r = autocorrelation(apply_window(sine_signal["samples"][:256], "hann"), order)
    res = levinson_durbin(r, order)
    agrees, dev, _ = cross_check_toeplitz(r, order, res.lpc)
    assert not agrees
    assert dev > 1e-8


def test_rejects_short_autocorrelation_vector():
    with pytest.raises(ValueError, match="need r"):
        levinson_durbin(np.array([1.0, 0.5]), 4)


def test_sine_order2_recovers_closed_form(sine_signal, expected):
    """Order-2 LPC of a sustained sinusoid: [1, -2cos(w), 1] (closed form,
    stored in expected.json — not generated by the code under test)."""
    from app.lpc.autocorr import apply_window, autocorrelation

    ref = np.array(expected["sine"]["order2_lpc_closed_form"])
    tol = expected["sine"]["closed_form_tolerance"]
    frame = apply_window(sine_signal["samples"][:512], "hann")
    res = levinson_durbin(autocorrelation(frame, 2), 2)
    np.testing.assert_allclose(res.lpc, ref, rtol=0, atol=tol)
    assert res.stable
