/**
 * Test harness shared by suites. Expected JSON-RPC payloads in the tests are
 * hand-written literals — they are NEVER generated by the kernel — so the
 * tests are genuine oracles, not self-consistent tautologies.
 */
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach } from 'vitest';
import { DiagnosticLogger } from '../../src/diagnostics/logger.js';
import { Kernel } from '../../src/kernel/kernel.js';
import { buildMethods } from '../../src/kernel/methods/index.js';
import { TaskRegistry } from '../../src/kernel/task-registry.js';
import { MemoryDomainStore } from '../../src/state/memory-domain-store.js';
import { MemoryStateStore } from '../../src/state/memory-store.js';
import type { StateStore } from '../../src/state/store.js';
import type { DomainStore } from '../../src/state/domain-store.js';

export interface MemoryHarness {
  kernel: Kernel;
  store: StateStore;
  domain: DomainStore;
  tasks: TaskRegistry;
  logger: DiagnosticLogger;
  /** Collected console log lines (so tests can assert redaction sink output). */
  logLines: string[];
  invoke(body: string, init?: { signal?: AbortSignal }): ReturnType<Kernel['handle']>;
}

export function memoryHarness(opts: { maxTaskDelayMs?: number; logLevel?: 'silent' | 'info' | 'debug' } = {}): MemoryHarness {
  const store = new MemoryStateStore();
  store.init();
  const domain = new MemoryDomainStore();
  domain.init();
  const tasks = new TaskRegistry();
  const logLines: string[] = [];
  const logger = new DiagnosticLogger(
    store,
    opts.logLevel ?? 'silent',
    (line) => logLines.push(line),
  );
  const methods = buildMethods({
    domain,
    store,
    tasks,
    maxTaskDelayMs: opts.maxTaskDelayMs ?? 5_000,
  });
  const kernel = new Kernel({ store, methods, tasks, logger });
  const controller = new AbortController();
  return {
    kernel,
    store,
    domain,
    tasks,
    logger,
    logLines,
    invoke: (body, init) =>
      kernel.handle(body, {
        connectionId: 'conn-test',
        signal: init?.signal ?? controller.signal,
      }),
  };
}

const tempDirs: string[] = [];

export function tempDbPath(): string {
  const dir = mkdtempSync(join(tmpdir(), 'jsonrpc-test-'));
  const path = join(dir, 'test.sqlite');
  tempDirs.push(dir);
  return path;
}

afterEach(() => {
  while (tempDirs.length) {
    const dir = tempDirs.pop();
    if (dir) rmSync(dir, { recursive: true, force: true });
  }
});

/** A promise + controls used to simulate a client that drops the connection. */
export function abortable(): { signal: AbortSignal; abort: (reason?: string) => void } {
  const controller = new AbortController();
  return {
    signal: controller.signal,
    abort: (reason) => controller.abort(new Error(reason ?? 'connection lost')),
  };
}

export async function flush(ms = 2): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, ms));
}
