package blockwise_test

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"coapblockwise/internal/blockwise"
	"coapblockwise/internal/wire"
)

// recipeByte mirrors scripts/gen_fixtures.py independently. The authoritative
// hashes live in manifest.json (generated by Python); Go only regenerates the
// bytes and must match those hashes — it never certifies its own fixtures.
func recipeByte(i int) byte {
	return byte((i*73)&0xFF) ^ byte((i/97)&0xFF)
}

func recipeBody(n int) []byte {
	b := make([]byte, n)
	for i := range b {
		b[i] = recipeByte(i)
	}
	return b
}

type fixtureManifest struct {
	Files map[string]struct {
		Length int    `json:"length"`
		SHA256 string `json:"sha256"`
	} `json:"files"`
}

func loadManifest(t *testing.T) fixtureManifest {
	t.Helper()
	path := filepath.Join("..", "..", "test", "testdata", "fixtures",
		"manifest.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read manifest (run python3 scripts/gen_fixtures.py): %v", err)
	}
	var m fixtureManifest
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatalf("parse manifest: %v", err)
	}
	return m
}

func feed(t *testing.T, a *blockwise.Assembler, body []byte, size int,
	nums []int, etag []byte,
) {
	t.Helper()
	szx := wire.SZXFor(size)
	if 1<<uint(szx+4) != size {
		t.Fatalf("test size %d is not a legal block size", size)
	}
	count := (len(body) + size - 1) / size
	for _, n := range nums {
		if n < 0 || n >= count {
			t.Fatalf("test asked for block %d outside 0..%d", n, count-1)
		}
		start := n * size
		end := start + size
		if end > len(body) {
			end = len(body)
		}
		more := n < count-1
		if _, err := a.AddBlock(n, more, szx, body[start:end], etag); err != nil {
			t.Fatalf("AddBlock(%d): %v", n, err)
		}
	}
}

func perm(n int, order ...int) []int { return order }

func TestInOrderAssemblyMatchesFixture(t *testing.T) {
	manifest := loadManifest(t)
	for _, tc := range []struct {
		file string
		size int
	}{
		{"payload_300.bin", 128},
		{"payload_2500.bin", 256},
		{"payload_5000.bin", 1024},
	} {
		t.Run(tc.file, func(t *testing.T) {
			meta := manifest.Files[tc.file]
			body := recipeBody(meta.Length)
			count := (meta.Length + tc.size - 1) / tc.size
			order := make([]int, count)
			for i := range order {
				order[i] = i
			}
			a := blockwise.NewAssembler()
			feed(t, a, body, tc.size, order, []byte("v1"))
			if !a.IsComplete() {
				t.Fatalf("not complete after feeding all %d blocks", count)
			}
			got, err := a.Bytes()
			if err != nil {
				t.Fatalf("Bytes: %v", err)
			}
			sum := sha256.Sum256(got)
			if hex.EncodeToString(sum[:]) != meta.SHA256 {
				t.Fatalf("assembled sha256 %x != fixture manifest %s",
					sum[:8], meta.SHA256)
			}
		})
	}
}

func TestOutOfOrderAssembly(t *testing.T) {
	body := recipeBody(500) // 128*3=384, then 116; blocks 0,1,2,3
	a := blockwise.NewAssembler()
	order := perm(4, 2, 0, 3, 1)

	// Block 2 first: buffered behind a gap; not advanced.
	feed(t, a, body, 128, order[:1], []byte("v1"))
	if a.NextExpected() != 0 {
		t.Fatalf("next expected = %d, want 0 while block 0 missing",
			a.NextExpected())
	}
	if a.IsComplete() {
		t.Fatal("cannot be complete with a hole at block 0")
	}
	if _, err := a.Bytes(); err == nil {
		t.Fatal("Bytes must fail while a gap exists (KindIncomplete)")
	}

	feed(t, a, body, 128, order[1:], []byte("v1"))
	if !a.IsComplete() {
		t.Fatal("expected completion after all blocks delivered")
	}
	got, err := a.Bytes()
	if err != nil {
		t.Fatalf("Bytes: %v", err)
	}
	if len(got) != 500 {
		t.Fatalf("length = %d, want 500", len(got))
	}
	want := sha256.Sum256(body)
	if sha256.Sum256(got) != want {
		t.Fatal("out-of-order reassembly differs from source body")
	}
}

func TestGapNumsReported(t *testing.T) {
	body := recipeBody(400) // blocks 0..3 at 128
	a := blockwise.NewAssembler()
	feed(t, a, body, 128, []int{0, 3}, []byte("v"))
	gaps := a.GapNums()
	if len(gaps) != 2 || gaps[0] != 1 || gaps[1] != 2 {
		t.Fatalf("gaps = %v, want [1 2]", gaps)
	}
}

func TestDuplicateBlockNotCommittedTwice(t *testing.T) {
	body := recipeBody(300) // blocks 0..2 at 128
	a := blockwise.NewAssembler()

	chunk := body[0:128]
	r1, err := a.AddBlock(0, true, wire.SZXFor(128), chunk, []byte("v"))
	if err != nil {
		t.Fatalf("first AddBlock: %v", err)
	}
	if r1.Status != blockwise.StatusAdvanced {
		t.Fatalf("first block status = %v, want advanced", r1.Status)
	}
	// Retransmitted identical block: duplicate, not a second commit.
	r2, err := a.AddBlock(0, true, wire.SZXFor(128), append([]byte(nil), chunk...),
		[]byte("v"))
	if err != nil {
		t.Fatalf("identical duplicate should be accepted idempotently: %v", err)
	}
	if r2.Status != blockwise.StatusDuplicate {
		t.Fatalf("retransmit status = %v, want duplicate", r2.Status)
	}
	if a.NextExpected() != 1 {
		t.Fatalf("next expected = %d, duplicate must not advance state",
			a.NextExpected())
	}
	// Finish the transfer and confirm the duplicated block's bytes appear once.
	feed(t, a, body, 128, []int{1, 2}, []byte("v"))
	got, _ := a.Bytes()
	if sha256.Sum256(got) != sha256.Sum256(body) {
		t.Fatal("duplicated block corrupted the assembled body")
	}
}

func TestDuplicateBlockWithDifferentBytesRejected(t *testing.T) {
	body := recipeBody(300)
	a := blockwise.NewAssembler()
	if _, err := a.AddBlock(0, true, wire.SZXFor(128), body[0:128], []byte("v")); err != nil {
		t.Fatal(err)
	}
	tampered := append([]byte(nil), body[0:128]...)
	tampered[0] ^= 0xFF
	_, err := a.AddBlock(0, true, wire.SZXFor(128), tampered, []byte("v"))
	be, ok := blockwise.AsError(err)
	if !ok || be.Kind != blockwise.KindOverlap {
		t.Fatalf("err = %v, want overlap (same num, different bytes)", err)
	}
}

func TestBlockSizeChangeRejected(t *testing.T) {
	body := recipeBody(500)
	a := blockwise.NewAssembler()
	feed(t, a, body, 128, []int{0}, []byte("v"))
	// Peer renegotiates to 256 mid-transfer.
	if _, err := a.AddBlock(1, true, wire.SZXFor(256), make([]byte, 256),
		[]byte("v")); err == nil {
		t.Fatal("expected size-changed rejection")
	} else if be, ok := blockwise.AsError(err); !ok ||
		be.Kind != blockwise.KindSizeChanged {
		t.Fatalf("err = %v, want size-changed", err)
	}
}

func TestETagChangeRejectsSplice(t *testing.T) {
	body := recipeBody(300)
	a := blockwise.NewAssembler()
	feed(t, a, body, 128, []int{0, 1}, []byte("etag-A"))
	// Representation updated server-side while block 2 was in flight.
	_, err := a.AddBlock(2, false, wire.SZXFor(128), body[256:300],
		[]byte("etag-B"))
	be, ok := blockwise.AsError(err)
	if !ok || be.Kind != blockwise.KindETagChanged {
		t.Fatalf("err = %v, want etag-changed (refuse to splice versions)", err)
	}
	if a.IsComplete() {
		t.Fatal("assembler must not mark cross-version transfer complete")
	}
}

func TestShortMiddleBlockRejected(t *testing.T) {
	a := blockwise.NewAssembler()
	// Block 0 with more=1 but only 10 bytes in a 128-size slot.
	_, err := a.AddBlock(0, true, wire.SZXFor(128), make([]byte, 10), nil)
	if be, ok := blockwise.AsError(err); !ok ||
		be.Kind != blockwise.KindBadBlockSize {
		t.Fatalf("err = %v, want bad-block-size for short middle block", err)
	}
}

func TestTwoTerminalBlocksRejected(t *testing.T) {
	body := recipeBody(300)
	a := blockwise.NewAssembler()
	feed(t, a, body, 128, []int{0, 1}, nil)
	if _, err := a.AddBlock(2, false, wire.SZXFor(128), body[256:280], nil); err != nil {
		t.Fatalf("first terminal: %v", err)
	}
	// Another terminal at a different number.
	_, err := a.AddBlock(5, false, wire.SZXFor(128), body[0:20], nil)
	if be, ok := blockwise.AsError(err); !ok ||
		be.Kind != blockwise.KindBadMoreFlag {
		t.Fatalf("err = %v, want bad-more-flag", err)
	}
}

func TestBlockPayloadExceedsSizeRejected(t *testing.T) {
	a := blockwise.NewAssembler()
	_, err := a.AddBlock(0, true, wire.SZXFor(16), make([]byte, 17), nil)
	if be, ok := blockwise.AsError(err); !ok ||
		be.Kind != blockwise.KindBadBlockSize {
		t.Fatalf("err = %v, want bad-block-size", err)
	}
}

func TestFailureKindStringsAreStable(t *testing.T) {
	cases := map[blockwise.FailureKind]string{
		blockwise.KindGap:        "gap",
		blockwise.KindETagChanged: "etag-changed",
		blockwise.KindSizeChanged: "size-changed",
		blockwise.KindOverlap:    "overlap",
	}
	for k, want := range cases {
		if k.String() != want {
			t.Errorf("kind %d string = %q, want %q", k, k.String(), want)
		}
	}
}

func ExampleAssembler_outOfOrder() {
	body := recipeBody(300)
	a := blockwise.NewAssembler()
	// Deliberately send block 2 before block 0.
	feedExample(a, body, 128, []int{2})
	fmt.Println("next-expected:", a.NextExpected(), "complete:", a.IsComplete())
	feedExample(a, body, 128, []int{0, 1})
	got, _ := a.Bytes()
	fmt.Println("complete:", a.IsComplete(), "bytes:", len(got))
	// Output:
	// next-expected: 0 complete: false
	// complete: true bytes: 300
}

func feedExample(a *blockwise.Assembler, body []byte, size int, nums []int) {
	for _, n := range nums {
		start := n * size
		end := start + size
		if end > len(body) {
			end = len(body)
		}
		count := (len(body) + size - 1) / size
		_, _ = a.AddBlock(n, n < count-1, wire.SZXFor(size), body[start:end], nil)
	}
}
