package rectkernel;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Test;
import rectkernel.error.ErrorCategory;
import rectkernel.evidence.Overlap;
import rectkernel.evidence.RunLog;
import rectkernel.model.Domain;
import rectkernel.model.Problem;
import rectkernel.model.RectSpec;
import rectkernel.search.Placement;
import rectkernel.search.Solution;
import rectkernel.search.SolveOptions;
import rectkernel.search.SolveResult;
import rectkernel.search.SolveStatus;
import rectkernel.search.Solver;

/** Solver tests with hand-computed reference answers (not generated by the kernel). */
class SolverTest {

    private static RectSpec m(String id, long w, long h, Domain d) {
        return new RectSpec(id, w, h, false, d);
    }

    private static RectSpec o(String id, long w, long h, Domain d) {
        return new RectSpec(id, w, h, true, d);
    }

    private static Set<String> canonicalSet(SolveResult r) {
        return r.solutions().stream().map(Solution::canonical).collect(Collectors.toSet());
    }

    @Test
    void twoUnitRectsOnTwoCellsHaveExactlyTwoLayouts() {
        // Hand-computed: A and B swap the two cells -> exactly 2 layouts.
        Problem p = Problem.of(2, 1, List.of(
                m("A", 1, 1, new Domain(0, 1, 0, 0)),
                m("B", 1, 1, new Domain(0, 1, 0, 0))), "S-two");
        SolveResult r = new Solver(SolveOptions.all(100), RunLog.inMemory(), "S-two").solve(p);
        assertEquals(SolveStatus.SAT, r.status());
        assertEquals(Set.of("A=P(0,0),B=P(1,0)", "A=P(1,0),B=P(0,0)"), canonicalSet(r));
    }

    @Test
    void optionalRectIsAbsorbedWhenGridIsFull() {
        // Hand-computed: A fills the grid; optional B has no legal cell ->
        // exactly 1 solution, with B absent.
        Problem p = Problem.of(2, 2, List.of(
                m("A", 2, 2, Domain.singleton(0, 0)),
                o("B", 1, 1, new Domain(0, 1, 0, 1))), "S-absorb");
        SolveResult r = new Solver(SolveOptions.all(100), RunLog.inMemory(), "S-absorb").solve(p);
        assertEquals(SolveStatus.SAT, r.status());
        assertEquals(Set.of("A=P(0,0),B=A"), canonicalSet(r));
    }

    @Test
    void mandatoryRectInFullGridIsUnsat() {
        // Same geometry with B mandatory -> UNSAT, category STATE_CONFLICT.
        Problem p = Problem.of(2, 2, List.of(
                m("A", 2, 2, Domain.singleton(0, 0)),
                m("B", 1, 1, new Domain(0, 1, 0, 1))), "S-unsat");
        SolveResult r = new Solver(SolveOptions.all(100), RunLog.inMemory(), "S-unsat").solve(p);
        assertEquals(SolveStatus.UNSAT, r.status());
        assertEquals(ErrorCategory.STATE_CONFLICT, r.category());
        assertTrue(r.solutions().isEmpty());
    }

    @Test
    void zeroAreaRectContributesLayoutsButNeverConflicts() {
        // Hand-computed: B is 0x1 on a 1x1 grid -> x in {0,1}, both legal even
        // though A fills the only cell. Exactly 2 layouts.
        Problem p = Problem.of(1, 1, List.of(
                m("A", 1, 1, Domain.singleton(0, 0)),
                m("B", 0, 1, new Domain(0, 1, 0, 0))), "S-zero");
        SolveResult r = new Solver(SolveOptions.all(100), RunLog.inMemory(), "S-zero").solve(p);
        assertEquals(SolveStatus.SAT, r.status());
        assertEquals(Set.of("A=P(0,0),B=P(0,0)", "A=P(0,0),B=P(1,0)"), canonicalSet(r));
    }

    @Test
    void searchBacktracksFromPresentBranchToAbsentBranch() {
        // O optional fixed at (0,0); A and B mandatory 1x1 on a 2-cell row.
        // O=PRESENT leaves one cell for two mandatory rects -> conflict ->
        // the solver must backtrack to O=ABSENT and place A,B on the two cells.
        RunLog log = RunLog.inMemory();
        Problem p = Problem.of(2, 1, List.of(
                o("O", 1, 1, Domain.singleton(0, 0)),
                m("A", 1, 1, new Domain(0, 1, 0, 0)),
                m("B", 1, 1, new Domain(0, 1, 0, 0))), "S-backtrack");
        SolveResult r = new Solver(SolveOptions.all(100), log, "S-backtrack").solve(p);
        assertEquals(SolveStatus.SAT, r.status());
        assertEquals(Set.of("O=A,A=P(0,0),B=P(1,0)", "O=A,A=P(1,0),B=P(0,0)"), canonicalSet(r));
        assertEquals(1, r.backtracks(), "exactly the O=PRESENT branch must fail");
        assertTrue(log.events().stream().anyMatch(
                e -> e.kind().equals("branch") && e.detail().contains("O") && e.detail().contains("PRESENT")));
        assertTrue(log.events().stream().anyMatch(
                e -> e.kind().equals("backtrack") && e.detail().contains("reason=")),
                "backtrack must be logged with a reason");
    }

    @Test
    void unsatOnlyAfterDeeperSearchBacktracking() {
        // Two 1x2 bars fill whole columns of the 2x2 grid; C (1x1) never fits.
        // Root propagation sees no anchors, so the failure only appears after
        // branching: exactly 2 failed branches.
        RunLog log = RunLog.inMemory();
        Problem p = Problem.of(2, 2, List.of(
                m("A", 1, 2, new Domain(0, 1, 0, 0)),
                m("B", 1, 2, new Domain(0, 1, 0, 0)),
                m("C", 1, 1, new Domain(0, 1, 0, 1))), "S-deep-unsat");
        SolveResult r = new Solver(SolveOptions.all(100), log, "S-deep-unsat").solve(p);
        assertEquals(SolveStatus.UNSAT, r.status());
        assertEquals(ErrorCategory.STATE_CONFLICT, r.category());
        assertEquals(2, r.backtracks(), "both placements of A must fail deeper in the tree");
        assertTrue(log.events().stream().filter(e -> e.kind().equals("backtrack")).count() >= 2);
    }

    @Test
    void nodeLimitYieldsResourceExhaustedNotWrongAnswer() {
        Problem p = Problem.of(4, 4, List.of(
                m("A", 1, 1, new Domain(0, 3, 0, 3)),
                m("B", 1, 1, new Domain(0, 3, 0, 3)),
                m("C", 1, 1, new Domain(0, 3, 0, 3))), "S-limit");
        RunLog log = RunLog.inMemory();
        SolveResult r = new Solver(new SolveOptions(3, 10_000, false, 1), log, "S-limit").solve(p);
        assertEquals(SolveStatus.LIMIT, r.status());
        assertEquals(ErrorCategory.RESOURCE_EXHAUSTED, r.category());
        assertTrue(log.hasKind("limit"), "limit event must be logged");
    }

    @Test
    void firstSolutionIsValidPerIndependentGeometry() {
        // Validate the solver's answer with the independent Overlap checker,
        // not with the solver's own propagation logic.
        Problem p = Problem.of(3, 2, List.of(
                m("A", 1, 1, new Domain(0, 2, 0, 1)),
                m("B", 2, 1, new Domain(0, 1, 0, 1)),
                o("C", 1, 1, new Domain(0, 2, 0, 1))), "S-valid");
        SolveResult r = new Solver(SolveOptions.first(), RunLog.inMemory(), "S-valid").solve(p);
        assertEquals(SolveStatus.SAT, r.status());
        assertEquals(1, r.solutions().size());
        Solution sol = r.solutions().get(0);
        for (Placement a : sol.placements()) {
            if (!a.present()) {
                continue;
            }
            RectSpec spec = p.rects().stream().filter(s -> s.id().equals(a.id())).findFirst().orElseThrow();
            assertTrue(a.x() >= spec.initialDomain().xmin() && a.x() <= spec.initialDomain().xmax()
                    && a.y() >= spec.initialDomain().ymin() && a.y() <= spec.initialDomain().ymax(),
                    "placement inside declared domain");
            for (Placement b : sol.placements()) {
                if (!b.present() || b.id().equals(a.id())) {
                    continue;
                }
                RectSpec sb = p.rects().stream().filter(s -> s.id().equals(b.id())).findFirst().orElseThrow();
                assertTrue(!Overlap.overlaps(a.x(), a.y(), spec.w(), spec.h(),
                                b.x(), b.y(), sb.w(), sb.h()),
                        "no present pair overlaps: " + a.id() + " vs " + b.id());
            }
        }
    }
}
